#!/usr/bin/env python3
"""UI seam guard — keep pages off raw @mantine/core for wrapped primitives.

We standardise Button and Badge through `@/components/ui` so tone/colour
decisions live in one place (the seam) and the underlying kit can be swapped
without touching call sites. New page code must import these from the seam.

This is a *ratchet*: the files importing the raw Mantine component today are
recorded in scripts/ui_seam_baseline.txt and grandfathered. The check fails
only when a page NOT in the baseline pulls a wrapped primitive from
"@mantine/core". As baselined files are converted to @/components/ui, the
guard reports them as stale so they get dropped from the baseline — the count
only goes down.

  python3 scripts/check_ui_seam.py            # check (wired into make check-ui-seam)
  python3 scripts/check_ui_seam.py --update   # regenerate the baseline (use sparingly)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Primitives that MUST come from @/components/ui in page code.
WRAPPED = ("Button", "Badge")

ROOT = Path(__file__).resolve().parent.parent
PAGES_DIR = ROOT / "apps" / "web" / "src" / "pages"
BASELINE_FILE = Path(__file__).resolve().parent / "ui_seam_baseline.txt"

# Capture every `... from "@mantine/core"` import block (possibly multi-line).
IMPORT_RE = re.compile(r"import\s*\{(?P<body>[^}]*)\}\s*from\s*[\"']@mantine/core[\"']", re.S)


def wrapped_imports(text: str) -> set[str]:
    """Return the set of WRAPPED names imported from @mantine/core in this file."""
    found: set[str] = set()
    for m in IMPORT_RE.finditer(text):
        body = m.group("body")
        for name in WRAPPED:
            if re.search(rf"\b{name}\b", body):
                found.add(name)
    return found


def current_leakers() -> dict[str, set[str]]:
    """Map of {relative page path -> wrapped names it imports raw}."""
    out: dict[str, set[str]] = {}
    for path in sorted(PAGES_DIR.rglob("*.tsx")):
        names = wrapped_imports(path.read_text(encoding="utf-8"))
        if names:
            out[path.relative_to(PAGES_DIR).as_posix()] = names
    return out


def load_baseline() -> set[str]:
    if not BASELINE_FILE.exists():
        return set()
    return {
        line.strip()
        for line in BASELINE_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }


def write_baseline(paths: set[str]) -> None:
    header = (
        "# UI seam baseline — pages still importing Button/Badge from @mantine/core.\n"
        "# Generated by scripts/check_ui_seam.py --update. Shrink this; never grow it by\n"
        "# hand. Convert a file to @/components/ui, then re-run --update to drop it.\n"
    )
    BASELINE_FILE.write_text(header + "\n".join(sorted(paths)) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    if not PAGES_DIR.is_dir():
        print(f"check-ui-seam: pages dir not found: {PAGES_DIR}", file=sys.stderr)
        return 2

    leakers = current_leakers()

    if "--update" in argv:
        write_baseline(set(leakers))
        print(f"check-ui-seam: baseline written with {len(leakers)} file(s) -> {BASELINE_FILE.name}")
        return 0

    baseline = load_baseline()
    violations = {rel: names for rel, names in leakers.items() if rel not in baseline}

    if violations:
        print("UI seam violation — import these from '@/components/ui', not '@mantine/core':\n")
        for rel, names in sorted(violations.items()):
            print(f"  pages/{rel}: {', '.join(sorted(names))}")
        print(
            "\nUse <Button tone=...> / <Badge tone=...> from @/components/ui. New pages must "
            "use the seam. If raw Mantine is genuinely required, justify it in review and run "
            "`python3 scripts/check_ui_seam.py --update`."
        )
        return 1

    stale = baseline - set(leakers)
    if stale:
        print(f"check-ui-seam: OK, 0 new violations. {len(stale)} baselined file(s) now clean —")
        print("run `python3 scripts/check_ui_seam.py --update` to drop them:")
        for rel in sorted(stale):
            print(f"  - {rel}")
        return 0

    print(f"check-ui-seam: OK. {len(baseline)} grandfathered file(s), 0 new violations.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
