#!/usr/bin/env python3
"""UI seam guard — keep pages off raw @mantine/core for wrapped primitives.

We standardise certain primitives through `@/components/ui` so styling/tone
decisions live in one place (the seam) and the underlying kit can be swapped
without touching call sites. New page code must import these from the seam:

  @mantine/core      ->  @/components/ui
  -------------------    ------------------
  Button             ->  Button   (tone=...)
  Badge              ->  Badge    (tone=...)
  ActionIcon         ->  IconButton
  Table              ->  Table

This is a *per-name ratchet*: scripts/ui_seam_baseline.txt records, per page,
which raw primitives it is grandfathered for. The check fails when a page
imports a wrapped primitive it is NOT grandfathered for — so Button/Badge
(fully adopted, zero grandfathered) are a hard-zero gate, while ActionIcon and
Table ratchet down as they get converted. The count only goes down.

  python3 scripts/check_ui_seam.py            # check (wired into make check-ui-seam)
  python3 scripts/check_ui_seam.py --update   # regenerate the baseline (use sparingly)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Raw @mantine/core name -> the @/components/ui primitive that replaces it.
SEAM = {
    "Button": "Button",
    "Badge": "Badge",
    "ActionIcon": "IconButton",
    "Table": "Table",
}

ROOT = Path(__file__).resolve().parent.parent
PAGES_DIR = ROOT / "apps" / "web" / "src" / "pages"
BASELINE_FILE = Path(__file__).resolve().parent / "ui_seam_baseline.txt"

# Capture every `... from "@mantine/core"` import block (possibly multi-line).
IMPORT_RE = re.compile(r"import\s*\{(?P<body>[^}]*)\}\s*from\s*[\"']@mantine/core[\"']", re.S)


def wrapped_imports(text: str) -> set[str]:
    """Return the set of SEAM-wrapped names imported raw from @mantine/core."""
    found: set[str] = set()
    for m in IMPORT_RE.finditer(text):
        body = m.group("body")
        for name in SEAM:
            if re.search(rf"\b{name}\b", body):
                found.add(name)
    return found


def current_leakers() -> dict[str, set[str]]:
    """Map of {relative page path -> raw wrapped names it imports}."""
    out: dict[str, set[str]] = {}
    for path in sorted(PAGES_DIR.rglob("*.tsx")):
        names = wrapped_imports(path.read_text(encoding="utf-8"))
        if names:
            out[path.relative_to(PAGES_DIR).as_posix()] = names
    return out


def load_baseline() -> dict[str, set[str]]:
    """Parse `relpath: Name1,Name2` lines into {relpath -> grandfathered names}."""
    if not BASELINE_FILE.exists():
        return {}
    out: dict[str, set[str]] = {}
    for line in BASELINE_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        rel, names = line.split(":", 1)
        out[rel.strip()] = {n.strip() for n in names.split(",") if n.strip()}
    return out


def write_baseline(leakers: dict[str, set[str]]) -> None:
    header = (
        "# UI seam baseline — per page, the raw @mantine/core primitives it is\n"
        "# grandfathered for. EMPTY: Button/Badge/ActionIcon/Table are all fully\n"
        "# adopted (hard-zero) — any new raw import of one fails the guard.\n"
        "# Generated by scripts/check_ui_seam.py --update. Shrink this; never grow\n"
        "# it by hand. Convert a file to @/components/ui, then re-run --update.\n"
    )
    lines = [f"{rel}: {', '.join(sorted(names))}" for rel, names in sorted(leakers.items())]
    BASELINE_FILE.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    if not PAGES_DIR.is_dir():
        print(f"check-ui-seam: pages dir not found: {PAGES_DIR}", file=sys.stderr)
        return 2

    leakers = current_leakers()

    if "--update" in argv:
        write_baseline(leakers)
        total = sum(len(names) for names in leakers.values())
        print(f"check-ui-seam: baseline written — {len(leakers)} file(s), {total} grandfathered import(s)")
        return 0

    baseline = load_baseline()
    violations: dict[str, set[str]] = {}
    for rel, names in leakers.items():
        new = names - baseline.get(rel, set())
        if new:
            violations[rel] = new

    if violations:
        print("UI seam violation — import these from '@/components/ui', not '@mantine/core':\n")
        for rel, names in sorted(violations.items()):
            mapped = ", ".join(f"{n} -> {SEAM[n]}" for n in sorted(names))
            print(f"  pages/{rel}: {mapped}")
        print(
            "\nNew page code must use the seam (Button/Badge tone=..., IconButton, ui Table). "
            "If raw Mantine is genuinely required, justify it in review and run "
            "`python3 scripts/check_ui_seam.py --update`."
        )
        return 1

    # Report grandfathered names that no longer leak (baseline can shrink).
    stale: list[str] = []
    for rel, names in baseline.items():
        gone = names - leakers.get(rel, set())
        if gone:
            stale.append(f"{rel}: {', '.join(sorted(gone))}")

    grandfathered = sum(len(names) for names in baseline.values())
    if stale:
        print(f"check-ui-seam: OK, 0 new violations. {len(stale)} file(s) now cleaner —")
        print("run `python3 scripts/check_ui_seam.py --update` to update the baseline:")
        for entry in sorted(stale):
            print(f"  - {entry}")
        return 0

    print(f"check-ui-seam: OK. {grandfathered} grandfathered import(s), 0 new violations.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
