#!/usr/bin/env python3
"""Generate the redactable-field catalogue for the admin UI, from the Rust.

    python3 scripts/generate_field_catalogue.py           # write
    python3 scripts/generate_field_catalogue.py --check    # fail if stale

The fields that can be redacted are decided in Rust: each is a
`const X_FIELD: &str = "module.thing"` that some handler looks up in the
resolved access map. A field the admin UI offers but no handler reads is a
switch that does nothing; a field a handler reads but the UI never offers can
never be turned on.

Hand-maintaining a TypeScript copy guarantees both failures eventually, so the
list is generated and `--check` runs in CI. When a developer adds a redactable
field in Rust, the check fails until the catalogue is regenerated — which is
the point.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CRATES = os.path.join(ROOT, "crates")
OUT = os.path.join(ROOT, "packages/types/src/field-access-catalogue.ts")

FIELD_CONST = re.compile(r'const\s+[A-Z_0-9]+_FIELD\s*:\s*&str\s*=\s*"([a-z_][a-z_.]*)"')

# How a module prefix reads to an administrator. Anything unlisted falls back
# to the prefix itself, so a new module appears rather than disappearing.
MODULE_LABELS = {
    "patients": "Patient identity",
    "opd": "OPD consultation",
    "ipd": "Inpatient",
    "emergency": "Medico-legal (MLC)",
    "pharmacy": "Pharmacy",
    "camp": "Camp registration",
    "billing": "Billing",
}

# Fields where redaction is a regulatory question rather than a preference.
# Surfaced in the UI so an administrator loosening one knows what they are
# loosening.
SENSITIVE_NOTES = {
    "emergency.mlc.pocso_report": "POCSO — statutory confidentiality",
    "emergency.mlc.fir_number": "police record",
    "emergency.mlc.cause_of_death": "medico-legal",
    "pharmacy.ndps.witnessed_by": "NDPS witness record",
    "pharmacy.ndps.user_ids": "NDPS register",
    "patients.abha_id": "ABDM health identifier",
    "patients.uhid": "hospital identifier — hiding it breaks patient lookup",
    "patients.mlc_number": "medico-legal",
    "patients.identifiers.id_number": "government ID",
    "camp.registrations.id_proof_number": "government ID",
}


def discover() -> list[str]:
    found: set[str] = set()
    for dirpath, dirs, files in os.walk(CRATES):
        dirs[:] = [d for d in dirs if d not in {"target", "vendor"}]
        for name in files:
            if not name.endswith(".rs"):
                continue
            try:
                with open(os.path.join(dirpath, name), encoding="utf-8",
                          errors="replace") as handle:
                    found.update(FIELD_CONST.findall(handle.read()))
            except OSError:
                continue
    return sorted(found)


def render(fields: list[str]) -> str:
    groups: dict[str, list[str]] = {}
    for field in fields:
        groups.setdefault(field.split(".")[0], []).append(field)

    lines = [
        "/**",
        " * Fields that can be redacted per role.",
        " *",
        " * GENERATED by scripts/generate_field_catalogue.py — do not edit.",
        " *",
        " * Each entry corresponds to a `const *_FIELD` in the Rust sources that a",
        " * handler looks up in the resolved field-access map. Offering a field here",
        " * that no handler reads would put a switch in the admin UI that changes",
        " * nothing; omitting one a handler reads would make it unconfigurable. The",
        " * generator keeps both from happening, and `--check` runs in CI.",
        " */",
        "",
        "// `FieldAccessLevel` is defined once in ./common and re-used here.",
        "// Redeclaring it would give the package two exports of the same name and",
        "// let the two drift apart, which for an access-control type is the kind",
        "// of drift nobody notices until a level stops being honoured.",
        'import type { FieldAccessLevel } from "./common";',
        "",
        "export type { FieldAccessLevel };",
        "",
        "export interface RedactableField {",
        "  /** The key the backend matches on. */",
        "  key: string;",
        "  /** The part after the module prefix, for display. */",
        "  label: string;",
        "  /** Present when redaction here is a regulatory matter, not a preference. */",
        "  note?: string;",
        "}",
        "",
        "export interface RedactableFieldGroup {",
        "  module: string;",
        "  label: string;",
        "  fields: RedactableField[];",
        "}",
        "",
        f"/** {len(fields)} fields across {len(groups)} modules. */",
        "export const REDACTABLE_FIELDS: RedactableFieldGroup[] = [",
    ]

    for module in sorted(groups):
        label = MODULE_LABELS.get(module, module.replace("_", " "))
        lines.append("  {")
        lines.append(f'    module: "{module}",')
        lines.append(f'    label: "{label}",')
        lines.append("    fields: [")
        for field in groups[module]:
            # Drop the module prefix; the group heading already carries it.
            display = field[len(module) + 1 :].replace("_", " ").replace(".", " · ")
            note = SENSITIVE_NOTES.get(field)
            if note:
                lines.append(
                    f'      {{ key: "{field}", label: "{display}", note: "{note}" }},'
                )
            else:
                lines.append(f'      {{ key: "{field}", label: "{display}" }},')
        lines.append("    ],")
        lines.append("  },")

    lines.append("];")
    lines.append("")
    lines.append("/** Every key, flat — for validating what the server returns. */")
    lines.append(
        "export const REDACTABLE_FIELD_KEYS: readonly string[] = "
        "REDACTABLE_FIELDS.flatMap((g) => g.fields.map((f) => f.key));"
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    fields = discover()
    if not fields:
        raise SystemExit("found no *_FIELD constants — has the naming convention changed?")
    rendered = render(fields)

    if args.check:
        existing = ""
        if os.path.exists(OUT):
            with open(OUT, encoding="utf-8") as handle:
                existing = handle.read()
        if existing != rendered:
            print(f"{OUT} is out of date — run scripts/generate_field_catalogue.py")
            return 1
        print(f"field catalogue current: {len(fields)} fields")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"wrote {len(fields)} redactable fields to {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
