#!/usr/bin/env python3
"""Generate the Carbon design tokens for the native apps from the one source.

`packages/design-system/src/theme/tokens.ts` is pure data: palettes as ten-step
hex arrays, the six emergency-code colours, and the spacing/radius/type scales.
The web reads it directly; SwiftUI and Compose cannot, so this emits

    apps/ios/Packages/MedBrainsUI/Sources/MedBrainsUI/Generated/Carbon.swift
    apps/android/ui/src/main/kotlin/com/medbrains/ui/Carbon.kt

Commandment 2 of the device-surface rules — never a raw hex, never a per-surface
palette fork — becomes mechanical: native code names `Carbon.blue[5]`, never a
literal. Re-run after any change to tokens.ts; both outputs are committed so a
reviewer sees the diff. Usage: python3 scripts/generate_native_tokens.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "packages/design-system/src/theme/tokens.ts"
SWIFT_OUT = ROOT / "apps/ios/Packages/MedBrainsUI/Sources/MedBrainsUI/Generated/Carbon.swift"
KOTLIN_OUT = ROOT / "apps/android/ui/src/main/kotlin/com/medbrains/ui/Carbon.kt"

RE_PALETTE = re.compile(r"export const (\w+) = \[\s*((?:\s*\"#[0-9a-fA-F]{6}\",?\s*(?://[^\n]*)?)+)\s*\] as const", re.S)
RE_HEX = re.compile(r"\"#([0-9a-fA-F]{6})\"")
RE_OBJECT = re.compile(r"export const (\w+) = \{(.*?)\} as const", re.S)
RE_ENTRY = re.compile(r"^\s*(\w+):\s*(\"#[0-9a-fA-F]{6}\"|-?\d+(?:\.\d+)?)\s*,?", re.M)
NUMERIC_SCALES = ("space", "radius", "fontSize", "lineHeight", "fontWeight", "duration")


def parse():
    text = TOKENS.read_text()
    palettes = {m.group(1): RE_HEX.findall(m.group(2)) for m in RE_PALETTE.finditer(text)}
    objects = {}
    for m in RE_OBJECT.finditer(text):
        entries = [(k, v.strip('"')) for k, v in RE_ENTRY.findall(m.group(2))]
        if entries:
            objects[m.group(1)] = entries
    return palettes, objects


def swift(palettes, objects) -> str:
    lines = [
        "// GENERATED by scripts/generate_native_tokens.py from packages/design-system/src/theme/tokens.ts — DO NOT EDIT.",
        "import SwiftUI",
        "",
        "/// Carbon design tokens. Name a token; never write a hex.",
        "public enum Carbon {",
        "    public static func hex(_ value: UInt32) -> Color {",
        "        Color(red: Double((value >> 16) & 0xFF) / 255, green: Double((value >> 8) & 0xFF) / 255, blue: Double(value & 0xFF) / 255)",
        "    }",
        "",
    ]
    for name, steps in palettes.items():
        lines.append(f"    /// {len(steps)}-step palette; index 0 is the lightest.")
        lines.append(f"    public static let {name}: [Color] = [" + ", ".join(f"hex(0x{s.upper()})" for s in steps) + "]")
    lines.append("")
    if "emergencyCodes" in objects:
        lines.append("    /// Emergency codes — patient-safety constants, identical on every deployment.")
        lines.append("    public enum EmergencyCode {")
        for k, v in objects["emergencyCodes"]:
            lines.append(f"        public static let {k} = Carbon.hex(0x{v.lstrip('#').upper()})")
        lines.append("    }")
    for scale in NUMERIC_SCALES:
        if scale in objects:
            lines.append(f"    public enum {scale[0].upper() + scale[1:]} {{")
            for k, v in objects[scale]:
                key = k if k[0].isalpha() else f"_{k}"
                lines.append(f"        public static let {key}: CGFloat = {v}")
            lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def kotlin(palettes, objects) -> str:
    lines = [
        "// GENERATED by scripts/generate_native_tokens.py from packages/design-system/src/theme/tokens.ts — DO NOT EDIT.",
        "package com.medbrains.ui",
        "",
        "import androidx.compose.ui.graphics.Color",
        "",
        "/** Carbon design tokens. Name a token; never write a hex. */",
        "object Carbon {",
    ]
    for name, steps in palettes.items():
        lines.append(f"    /** {len(steps)}-step palette; index 0 is the lightest. */")
        lines.append(f"    val {name}: List<Color> = listOf(" + ", ".join(f"Color(0xFF{s.upper()})" for s in steps) + ")")
    lines.append("")
    if "emergencyCodes" in objects:
        lines.append("    /** Emergency codes — patient-safety constants, identical on every deployment. */")
        lines.append("    object EmergencyCode {")
        for k, v in objects["emergencyCodes"]:
            lines.append(f"        val {k} = Color(0xFF{v.lstrip('#').upper()})")
        lines.append("    }")
    for scale in NUMERIC_SCALES:
        if scale in objects:
            lines.append(f"    object {scale[0].upper() + scale[1:]} {{")
            for k, v in objects[scale]:
                key = k if k[0].isalpha() else f"_{k}"
                lines.append(f"        const val {key}: Float = {v}f")
            lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    palettes, objects = parse()
    if not palettes:
        raise SystemExit("no palettes parsed from tokens.ts")
    for out, text in ((SWIFT_OUT, swift(palettes, objects)), (KOTLIN_OUT, kotlin(palettes, objects))):
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
    print(f"{len(palettes)} palettes, {len(objects)} scales → {SWIFT_OUT.relative_to(ROOT)}, {KOTLIN_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
