#!/usr/bin/env python3
"""Generate one marker type per permission constant, for `Authorized<P>`.

    python3 scripts/generate_permission_markers.py           # write
    python3 scripts/generate_permission_markers.py --check    # fail if stale

`Authorized<AdminUsersList>` needs the permission code in the type system, and
Rust has no const generics over `&'static str`. A marker type per permission is
the way to carry it, and 893 hand-written markers would rot the first time
somebody added a permission.

So they are generated from the same `permissions.rs` that the audit and the
OpenAPI description already read. `--check` runs in CI: add a permission in
Rust and this fails until it is regenerated, which is the point.

The marker name is the module path in CamelCase — `admin::users::LIST` becomes
`AdminUsersList` — so the type reads like the code it stands for.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "crates/medbrains-core/src/permissions.rs")
OUT = os.path.join(ROOT, "crates/medbrains-core/src/permission_markers.rs")


def constants() -> list[tuple[str, str]]:
    """`(rust path, dotted code)` for every permission constant, in file order."""
    with open(SOURCE, encoding="utf-8") as handle:
        lines = handle.read().split("\n")

    stack: list[str] = []
    depth_of: list[int] = []
    depth = 0
    found: list[tuple[str, str]] = []
    module = re.compile(r"pub\s+mod\s+([a-z_0-9]+)")
    constant = re.compile(r'pub\s+const\s+([A-Z_0-9]+)\s*:\s*&str\s*=\s*"([^"]+)"')

    for line in lines:
        if match := module.search(line):
            stack.append(match.group(1))
            depth_of.append(depth)
        if match := constant.search(line):
            found.append(("::".join(stack + [match.group(1)]), match.group(2)))
        depth += line.count("{") - line.count("}")
        while depth_of and depth <= depth_of[-1]:
            stack.pop()
            depth_of.pop()
    return found


def marker_name(path: str) -> str:
    """`admin::users::LIST` -> `AdminUsersList`."""
    return "".join(part.title().replace("_", "") for part in path.split("::"))


def render(found: list[tuple[str, str]]) -> str:
    seen: dict[str, str] = {}
    lines = [
        "//! One marker type per permission, for `Authorized<P>`.",
        "//!",
        "//! GENERATED by scripts/generate_permission_markers.py — do not edit.",
        "//!",
        "//! Rust has no const generics over `&'static str`, so a permission is",
        "//! carried into the type system as a zero-sized type implementing",
        "//! `Permission`. Writing 893 of these by hand would go stale the first time",
        "//! somebody added a permission; `--check` in CI keeps them honest.",
        "",
        "use crate::permissions;",
        "",
        "/// A permission code, lifted into the type system.",
        "///",
        "/// Defined here rather than in `medbrains-server-core` so that this crate,",
        "/// which owns the permission constants, has no dependency on the web layer.",
        "pub trait Permission {",
        "    /// The dotted code, e.g. `\"admin.users.list\"`.",
        "    const CODE: &'static str;",
        "}",
        "",
    ]

    for path, code in found:
        name = marker_name(path)
        if name in seen:
            # Two constants collapsing to one marker name would silently give
            # one of them the other's permission.
            raise SystemExit(
                f"marker name collision: {name} from both {seen[name]} and {path}"
            )
        seen[name] = path
        lines.append(f"/// `{code}`")
        lines.append(f"pub struct {name};")
        lines.append(f"impl Permission for {name} {{")
        lines.append(f"    const CODE: &'static str = permissions::{path};")
        lines.append("}")
        lines.append("")

    lines.append(f"/// {len(found)} markers, one per permission constant.")
    lines.append(f"pub const MARKER_COUNT: usize = {len(found)};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    found = constants()
    if not found:
        raise SystemExit("found no permission constants — has permissions.rs moved?")
    rendered = render(found)

    if args.check:
        existing = ""
        if os.path.exists(OUT):
            with open(OUT, encoding="utf-8") as handle:
                existing = handle.read()
        if existing != rendered:
            print(f"{OUT} is out of date — run scripts/generate_permission_markers.py")
            return 1
        print(f"permission markers current: {len(found)}")
        return 0

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print(f"wrote {len(found)} markers to {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
