//! Infection control leaf crate (HAI surveillance, isolation, AMS). Mounted via router().

use axum::{Router, routing::{get,patch,post}};
use medbrains_server_core::state::AppState;

pub mod infection_control;

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/api/infection-control/surveillance",
            get(infection_control::list_surveillance).post(infection_control::create_surveillance),
        )
        .route(
            "/api/infection-control/device-days",
            get(infection_control::list_device_days).post(infection_control::record_device_days),
        )
        .route(
            "/api/infection-control/indwelling-devices",
            get(infection_control::list_indwelling_devices)
                .post(infection_control::create_indwelling_device),
        )
        .route(
            "/api/infection-control/indwelling-devices/{id}/review",
            post(infection_control::review_indwelling_device),
        )
        .route(
            "/api/infection-control/indwelling-devices/{id}/remove",
            post(infection_control::remove_indwelling_device),
        )
        .route(
            "/api/infection-control/stewardship",
            get(infection_control::list_stewardship).post(infection_control::create_stewardship),
        )
        .route(
            "/api/infection-control/stewardship/{id}",
            patch(infection_control::review_stewardship),
        )
        .route(
            "/api/infection-control/stewardship/{id}/timeout-review",
            post(infection_control::timeout_review_stewardship),
        )
        .route(
            "/api/infection-control/consumption",
            get(infection_control::list_consumption).post(infection_control::record_consumption),
        )
        .route(
            "/api/infection-control/biowaste",
            get(infection_control::list_biowaste).post(infection_control::create_biowaste),
        )
        .route(
            "/api/infection-control/needle-stick",
            get(infection_control::list_needle_stick).post(infection_control::create_needle_stick),
        )
        .route(
            "/api/infection-control/hygiene-audits",
            get(infection_control::list_hygiene_audits).post(infection_control::create_hygiene_audit),
        )
        .route(
            "/api/infection-control/cultures",
            get(infection_control::list_cultures).post(infection_control::create_culture),
        )
        .route(
            "/api/infection-control/outbreaks",
            get(infection_control::list_outbreaks).post(infection_control::create_outbreak),
        )
        .route(
            "/api/infection-control/outbreaks/{id}",
            patch(infection_control::update_outbreak),
        )
        .route(
            "/api/infection-control/outbreaks/{id}/contacts",
            get(infection_control::list_outbreak_contacts).post(infection_control::add_outbreak_contact),
        )
        // ── Infection Control Analytics & Reporting ──────
        .route(
            "/api/infection-control/analytics/hai-rates",
            get(infection_control::hai_rates),
        )
        .route(
            "/api/infection-control/analytics/device-utilization",
            get(infection_control::device_utilization),
        )
        .route(
            "/api/infection-control/analytics/antimicrobial-consumption",
            get(infection_control::antimicrobial_consumption),
        )
        .route(
            "/api/infection-control/analytics/surgical-prophylaxis",
            get(infection_control::surgical_prophylaxis),
        )
        .route(
            "/api/infection-control/reports/culture-sensitivity",
            get(infection_control::culture_sensitivity_report),
        )
        .route(
            "/api/infection-control/analytics/mdro",
            get(infection_control::mdro_tracking),
        )
        .route(
            "/api/infection-control/exposures",
            post(infection_control::create_exposure),
        )
        .route(
            "/api/infection-control/meetings",
            get(infection_control::list_ic_meetings).post(infection_control::create_ic_meeting),
        )
        .route(
            "/api/infection-control/reports/monthly",
            get(infection_control::monthly_surveillance_report),
        )
        .route(
            "/api/infection-control/outbreaks/{id}/rca",
            post(infection_control::create_outbreak_rca),
        )
}
