//! Built-in role definitions — single source of truth.
//!
//! Adding / changing a role: edit this file. `seed::seed_built_in_roles`
//! reads from `BUILT_IN_ROLES` and writes the `roles` table; the
//! manifest API serves them to the frontend.

use crate::permissions;

#[derive(Debug)]
pub struct BuiltInRole {
    pub code: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub permissions: &'static [&'static str],
}
pub const BUILT_IN_ROLES: &[BuiltInRole] = &[
    BuiltInRole {
        code: "super_admin",
        name: "Super Admin",
        description: "Full system access — bypasses all permission checks",
        permissions: &[], // bypass role, no explicit permissions needed
    },
    BuiltInRole {
        code: "hospital_admin",
        name: "Hospital Admin",
        description: "Full hospital access — bypasses all permission checks",
        permissions: &[], // bypass role, no explicit permissions needed
    },
    BuiltInRole {
        code: "doctor",
        name: "Doctor",
        description: "Clinical staff — patient care, OPD, orders, admissions",
        permissions: &[
            // Recall lists are built from diagnoses, so a clinician defines
            // them; marketing runs them without seeing why anyone qualified.
            permissions::marketing::cohorts::CLINICAL_DEFINE,
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::doctor::dashboard::VIEW_OWN,
            permissions::doctor::profile::VIEW_OWN,
            permissions::doctor::profile::UPDATE_OWN,
            permissions::doctor::signature::SIGN,
            permissions::doctor::signature::VERIFY,
            permissions::doctor::signoffs::VIEW_OWN,
            permissions::doctor::signoffs::VERBAL_REGISTER,
            permissions::audit::START,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::patients::CREATE,
            permissions::patients::UPDATE,
            permissions::patient_packages::VIEW,
            permissions::patient_packages::CONSUME,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::opd::TOKEN_MANAGE,
            permissions::opd::visit::CREATE,
            permissions::opd::visit::UPDATE,
            permissions::opd::vitals::LIST,
            permissions::opd::vitals::CREATE,
            permissions::opd::diagnoses::LIST,
            permissions::opd::diagnoses::CREATE,
            permissions::opd::diagnoses::UPDATE,
            permissions::opd::diagnoses::DELETE,
            permissions::opd::procedures::LIST,
            permissions::opd::procedures::CREATE,
            permissions::opd::procedures::CANCEL,
            permissions::opd::referrals::LIST,
            permissions::opd::referrals::CREATE,
            permissions::opd::certificates::LIST,
            permissions::opd::certificates::CREATE,
            permissions::opd::certificates::PRINT,
            permissions::opd::certificates::REPRINT,
            permissions::opd::certificates::VOID,
            permissions::opd::reminders::LIST,
            permissions::opd::reminders::CREATE,
            permissions::opd::reminders::UPDATE,
            permissions::opd::feedback::LIST,
            permissions::opd::feedback::CREATE,
            permissions::opd::consents::LIST,
            permissions::opd::consents::CREATE,
            permissions::opd::consents::SIGN,
            permissions::opd::consents::PRINT,
            permissions::opd::consents::REPRINT,
            permissions::opd::consents::REVOKE,
            // Emergency clinical work
            permissions::emergency::visits::LIST,
            permissions::emergency::visits::UPDATE,
            permissions::emergency::triage::LIST,
            permissions::emergency::triage::CREATE,
            permissions::emergency::resuscitation::LIST,
            permissions::emergency::resuscitation::CREATE,
            permissions::emergency::codes::LIST,
            permissions::emergency::codes::CREATE,
            permissions::emergency::codes::UPDATE,
            permissions::emergency::mlc::LIST,
            permissions::emergency::mlc::CREATE,
            permissions::emergency::mlc::UPDATE,
            permissions::emergency::mlc::PRINT,
            permissions::emergency::mlc::REPRINT,
            permissions::emergency::mlc_documents::SBAR_CREATE,
            permissions::emergency::mlc_documents::AGE_ESTIMATION_CREATE,
            permissions::emergency::mlc_documents::POCSO_CREATE,
            permissions::emergency::mlc_documents::COURT_SUMMONS_CREATE,
            permissions::emergency::mass_casualty::LIST,
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::orders::CREATE,
            permissions::lab::reports::VIEW,
            permissions::lab::results::UPDATE,
            permissions::lab::dispatch::LIST,
            permissions::lab::specialized::LIST,
            permissions::lab::specialized::CREATE,
            permissions::lab::b2b::LIST,
            permissions::pharmacy::prescriptions::LIST,
            permissions::pharmacy::prescriptions::VIEW,
            permissions::pharmacy::ndps::LIST,
            permissions::pharmacy::analytics::VIEW,
            permissions::pharmacy::validation::BYPASS,
            permissions::pharmacy::rx_queue::LIST,
            permissions::pharmacy::safety::VIEW,
            permissions::ipd::admissions::LIST,
            permissions::ipd::admissions::VIEW,
            permissions::ipd::admissions::CREATE,
            permissions::ipd::admissions::UPDATE,
            permissions::ipd::admissions::PRINT,
            permissions::ipd::admissions::REPRINT,
            permissions::ipd::attenders::MANAGE,
            permissions::ipd::wristband::PRINT,
            permissions::ipd::wristband::REPRINT,
            permissions::ipd::discharge::CREATE,
            permissions::ipd::discharge_summary::CREATE,
            permissions::ipd::bed_dashboard::VIEW,
            permissions::ipd::reports::VIEW,
            permissions::ipd::progress_notes::LIST,
            permissions::ipd::progress_notes::CREATE,
            permissions::ipd::clinical_docs::LIST,
            permissions::ipd::clinical_docs::CREATE,
            permissions::ipd::transfers::CREATE,
            permissions::ipd::death_records::MANAGE,
            permissions::ipd::birth_records::MANAGE,
            permissions::ipd::discharge_tat::VIEW,
            permissions::ipd::discharge_tat::UPDATE,
            permissions::ipd::discharge_tat::DOCTOR_UPDATE,
            permissions::ipd::discharge_tat::COMPLETE,
            permissions::ipd::tariffs::LIST,
            permissions::ot::consumables::MANAGE,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::CREATE,
            // Consent
            permissions::consent::VERIFY,
            permissions::consent::REVOKE,
            permissions::consent::templates::LIST,
            permissions::consent::signatures::LIST,
            // Specialty Clinical
            permissions::specialty::cath_lab::procedures::LIST,
            permissions::specialty::cath_lab::procedures::CREATE,
            permissions::specialty::cath_lab::devices::LIST,
            permissions::specialty::cath_lab::stemi::LIST,
            permissions::specialty::cath_lab::monitoring::LIST,
            permissions::specialty::cath_lab::monitoring::CREATE,
            permissions::specialty::endoscopy::procedures::LIST,
            permissions::specialty::endoscopy::procedures::CREATE,
            permissions::specialty::endoscopy::scopes::LIST,
            permissions::specialty::psychiatry::patients::LIST,
            permissions::specialty::psychiatry::patients::CREATE,
            permissions::specialty::psychiatry::patients::UPDATE,
            permissions::specialty::psychiatry::assessments::LIST,
            permissions::specialty::psychiatry::assessments::CREATE,
            permissions::specialty::psychiatry::ect::LIST,
            permissions::specialty::psychiatry::ect::CREATE,
            permissions::specialty::psychiatry::restraint::LIST,
            permissions::specialty::pmr::plans::LIST,
            permissions::specialty::pmr::plans::CREATE,
            permissions::specialty::pmr::sessions::LIST,
            permissions::specialty::pmr::sessions::CREATE,
            permissions::specialty::pmr::audiology::LIST,
            permissions::specialty::pmr::audiology::CREATE,
            permissions::specialty::palliative::dnr::LIST,
            permissions::specialty::palliative::pain::LIST,
            permissions::specialty::palliative::pain::CREATE,
            permissions::specialty::palliative::mortuary::LIST,
            permissions::specialty::palliative::nucmed::LIST,
            permissions::specialty::palliative::nucmed::CREATE,
            permissions::specialty::maternity::registrations::LIST,
            permissions::specialty::maternity::registrations::CREATE,
            permissions::specialty::maternity::anc::LIST,
            permissions::specialty::maternity::anc::CREATE,
            permissions::specialty::maternity::labor::LIST,
            permissions::specialty::maternity::labor::CREATE,
            permissions::specialty::maternity::newborn::LIST,
            permissions::specialty::maternity::newborn::CREATE,
            permissions::specialty::maternity::postnatal::LIST,
            permissions::specialty::maternity::postnatal::CREATE,
            // Clinical trials had no grantable permission at all — the codes
            // were bare strings defined nowhere, so `require_permission`
            // refused every non-bypass caller and the module worked for
            // super_admin and hospital_admin only. Investigators are
            // clinicians, so the doctor role is where the capability belongs.
            //
            // UNBLIND is deliberately NOT granted here. Breaking a
            // randomisation blind is a controlled act with its own
            // justification and audit trail, and who may perform it is a
            // governance decision for this hospital, not a default.
            permissions::specialty::clinical_trials::LIST,
            permissions::specialty::clinical_trials::CREATE,
            permissions::specialty::clinical_trials::SCREEN,
            permissions::specialty::other::templates::LIST,
            permissions::specialty::other::records::LIST,
            permissions::specialty::other::records::CREATE,
            permissions::specialty::other::dialysis::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            permissions::documents::audit::LIST,
            permissions::mrd::case_sheets::VIEW,
            permissions::mrd::case_sheets::GENERATE,
            permissions::mrd::case_sheets::PRINT,
            // Order Sets
            permissions::order_sets::templates::LIST,
            permissions::order_sets::templates::VIEW,
            permissions::order_sets::templates::CREATE,
            permissions::order_sets::templates::UPDATE,
            permissions::order_sets::templates::APPROVE,
            permissions::order_sets::activation::CREATE,
            permissions::order_sets::activation::VIEW,
            permissions::order_sets::analytics::VIEW,
            // Insurance
            permissions::insurance::verification::LIST,
            permissions::insurance::prior_auth::LIST,
            permissions::insurance::prior_auth::CREATE,
            permissions::insurance::prior_auth::SUBMIT,
            permissions::insurance::appeals::LIST,
            permissions::insurance::dashboard::VIEW,
            // Care View
            permissions::care_view::VIEW,
            permissions::care_view::DISCHARGE_TRACKER,
            permissions::care_view::scores::LIST,
            permissions::care_view::scores::RECORD,
            // Chronic Care
            permissions::chronic::programs::LIST,
            permissions::chronic::enrollments::LIST,
            permissions::chronic::enrollments::CREATE,
            permissions::chronic::enrollments::UPDATE,
            permissions::chronic::timeline::VIEW,
            permissions::chronic::timeline::CREATE,
            permissions::chronic::outcomes::VIEW,
            permissions::chronic::outcomes::CREATE,
            // Regulatory
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::adr::CREATE,
            permissions::regulatory::pcpndt::LIST,
            permissions::regulatory::pcpndt::CREATE,
            // Retrospective
            permissions::retrospective::CREATE,
            permissions::retrospective::AUDIT,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            permissions::abdm::abha::VIEW,
            // Intensive care. No built-in role named a single `icu.*` code, so
            // every ICU endpoint answered 403 to the staff who use it — an ICU
            // nurse could not record a ventilator setting. Granted on the
            // operator's decision (2026-08-18).
            permissions::icu::devices::LIST,
            permissions::icu::devices::MANAGE,
            permissions::icu::flowsheets::LIST,
            permissions::icu::flowsheets::CREATE,
            permissions::icu::neonatal::LIST,
            permissions::icu::neonatal::CREATE,
            permissions::icu::nutrition::LIST,
            permissions::icu::nutrition::CREATE,
            permissions::icu::scores::LIST,
            permissions::icu::scores::CREATE,
            permissions::icu::ventilator::LIST,
            permissions::icu::ventilator::CREATE,
            // Bedside: read-only for doctors. Managing sessions, answering
            // requests and curating education video are nursing work.
            permissions::bedside::VIEW,
            permissions::bedside::sessions::LIST,
            permissions::bedside::feedback::LIST,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::order_basket::DRAFT,
            permissions::order_basket::SIGN,
            permissions::emergency::mass_casualty::CLOSE,
            permissions::emergency::mass_casualty::CREATE,
            permissions::emergency::mass_casualty::UPDATE,
            permissions::ipd::discharge_summary::FINALIZE,
            permissions::opd::schedule::LIST,
            permissions::opd::schedule::MANAGE,
            permissions::ot::anesthesia::CREATE,
            permissions::ot::anesthesia::LIST,
            permissions::ot::case_records::CREATE,
            permissions::ot::case_records::LIST,
            permissions::ot::postop::CREATE,
            permissions::ot::postop::LIST,
            permissions::ot::preferences::LIST,
            permissions::ot::preferences::MANAGE,
            permissions::ot::reports::VIEW,
            permissions::ot::safety_checklist::CREATE,
            permissions::patients::notes::EDIT,
            permissions::patients::notes::VIEW,
            permissions::radiology::orders::CANCEL,
            permissions::radiology::orders::CREATE,
            permissions::radiology::reports::CREATE,
            permissions::radiology::reports::VERIFY,
            permissions::specialty::cath_lab::devices::MANAGE,
            permissions::specialty::cath_lab::stemi::MANAGE,
            permissions::specialty::dental::chart::CREATE,
            permissions::specialty::dental::chart::LIST,
            permissions::specialty::dental::exams::CREATE,
            permissions::specialty::dental::exams::LIST,
            permissions::specialty::dental::exams::UPDATE,
            permissions::specialty::endoscopy::reprocessing::LIST,
            permissions::specialty::endoscopy::reprocessing::MANAGE,
            permissions::specialty::endoscopy::scopes::MANAGE,
            permissions::specialty::ophthalmology::exams::CREATE,
            permissions::specialty::ophthalmology::exams::LIST,
            permissions::specialty::ophthalmology::exams::UPDATE,
            permissions::specialty::other::dialysis::MANAGE,
            permissions::specialty::other::oncology::CREATE,
            permissions::specialty::other::oncology::LIST,
            permissions::specialty::other::templates::MANAGE,
            permissions::specialty::palliative::dnr::MANAGE,
            permissions::specialty::palliative::mortuary::MANAGE,
            permissions::specialty::palliative::nucmed::MANAGE,
            permissions::specialty::pmr::psychometric::LIST,
            permissions::specialty::pmr::psychometric::MANAGE,
            permissions::specialty::psychiatry::restraint::MANAGE,
        ],
    },
    BuiltInRole {
        code: "nurse",
        name: "Nurse",
        description: "Nursing staff — patient view, OPD queue, bed management",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::opd::diagnoses::LIST,
            // Emergency nursing work
            permissions::emergency::visits::LIST,
            permissions::emergency::triage::LIST,
            permissions::emergency::triage::CREATE,
            permissions::emergency::resuscitation::LIST,
            permissions::emergency::resuscitation::CREATE,
            permissions::emergency::codes::LIST,
            permissions::emergency::codes::CREATE,
            permissions::emergency::mass_casualty::LIST,
            permissions::lab::phlebotomy::LIST,
            // Cross-module read for safe nursing care:
            // MAR cross-check, lab/imaging review, vitals from labs.
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::reports::VIEW,
            permissions::pharmacy::prescriptions::LIST,
            permissions::pharmacy::prescriptions::VIEW,
            permissions::radiology::orders::LIST,
            permissions::radiology::orders::VIEW,
            permissions::ipd::admissions::LIST,
            permissions::ipd::admissions::VIEW,
            permissions::ipd::wristband::PRINT,
            permissions::ipd::wristband::REPRINT,
            permissions::ipd::attenders::MANAGE,
            permissions::ipd::beds::MANAGE,
            permissions::ipd::bed_dashboard::VIEW,
            permissions::ipd::wards::MANAGE,
            permissions::ipd::tariffs::LIST,
            permissions::ipd::progress_notes::LIST,
            permissions::ipd::progress_notes::CREATE,
            permissions::ipd::assessments::LIST,
            permissions::ipd::assessments::CREATE,
            permissions::ipd::mar::LIST,
            permissions::ipd::mar::CREATE,
            permissions::ipd::mar::UPDATE,
            permissions::ipd::io_chart::LIST,
            permissions::ipd::io_chart::CREATE,
            permissions::ipd::nursing_assessment::LIST,
            permissions::ipd::nursing_assessment::CREATE,
            // Long-term care ran on the two codes above, and the nurse was the
            // only built-in role holding them. Granting the whole LTC family
            // here keeps effective access exactly as it was.
            //
            // Worth a clinical decision separately: no doctor role can
            // complete an MDS assessment or sign a home-care referral today,
            // and `case_manager` — whose job these referrals are — cannot see
            // them either. Both follow from the borrowed permission, not from
            // anyone deciding it.
            permissions::specialty::ltc::mds::LIST,
            permissions::specialty::ltc::mds::CREATE,
            permissions::specialty::ltc::mds::COMPLETE,
            permissions::specialty::ltc::medications::LIST,
            permissions::specialty::ltc::medications::CREATE,
            permissions::specialty::ltc::medications::UPDATE,
            permissions::specialty::ltc::rehab::LIST,
            permissions::specialty::ltc::rehab::CREATE,
            permissions::specialty::ltc::family::LIST,
            permissions::specialty::ltc::family::CREATE,
            permissions::specialty::ltc::family::UPDATE,
            permissions::specialty::ltc::readmission::LIST,
            permissions::specialty::ltc::readmission::CREATE,
            permissions::specialty::ltc::home_care::LIST,
            permissions::specialty::ltc::home_care::CREATE,
            permissions::specialty::ltc::home_care::UPDATE,
            permissions::specialty::ltc::snf::LIST,
            permissions::specialty::ltc::snf::CREATE,
            permissions::specialty::ltc::snf::UPDATE,
            permissions::ipd::care_plans::LIST,
            permissions::ipd::care_plans::CREATE,
            permissions::ipd::handover::LIST,
            permissions::ipd::handover::CREATE,
            permissions::ipd::discharge_checklist::LIST,
            permissions::ipd::discharge_checklist::UPDATE,
            permissions::ipd::clinical_docs::LIST,
            permissions::ipd::clinical_docs::CREATE,
            permissions::ipd::reservations::MANAGE,
            permissions::ipd::transfers::CREATE,
            permissions::ipd::discharge_tat::VIEW,
            permissions::ipd::discharge_tat::UPDATE,
            permissions::ipd::discharge_tat::NURSING_UPDATE,
            permissions::ipd::discharge_tat::COMPLETE,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::CREATE,
            // Specialty Clinical (list access)
            permissions::specialty::cath_lab::procedures::LIST,
            permissions::specialty::cath_lab::monitoring::LIST,
            permissions::specialty::endoscopy::procedures::LIST,
            permissions::specialty::psychiatry::patients::LIST,
            permissions::specialty::psychiatry::assessments::LIST,
            permissions::specialty::psychiatry::restraint::LIST,
            permissions::specialty::pmr::plans::LIST,
            permissions::specialty::pmr::sessions::LIST,
            permissions::specialty::palliative::dnr::LIST,
            permissions::specialty::palliative::pain::LIST,
            permissions::specialty::maternity::registrations::LIST,
            permissions::specialty::maternity::anc::LIST,
            permissions::specialty::maternity::labor::LIST,
            permissions::specialty::maternity::newborn::LIST,
            permissions::specialty::maternity::postnatal::LIST,
            permissions::specialty::other::records::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // Order Sets (activation only)
            permissions::order_sets::activation::CREATE,
            permissions::order_sets::activation::VIEW,
            // Care View
            permissions::care_view::VIEW,
            permissions::care_view::MY_TASKS,
            permissions::care_view::HANDOVER,
            permissions::care_view::DISCHARGE_TRACKER,
            permissions::care_view::MANAGE_TASKS,
            // Nursing does most of the scoring: Aldrete in recovery, MEOWS on
            // the obstetric ward, NEWS2 on every round.
            permissions::care_view::scores::LIST,
            permissions::care_view::scores::RECORD,
            // Chronic Care
            permissions::chronic::enrollments::LIST,
            permissions::chronic::timeline::VIEW,
            permissions::chronic::adherence::LIST,
            permissions::chronic::adherence::CREATE,
            permissions::chronic::outcomes::VIEW,
            // Regulatory
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::adr::CREATE,
            // Retrospective
            permissions::retrospective::CREATE,
            permissions::audit::START,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            // Nurse activities
            permissions::nurse::dashboard::VIEW,
            permissions::nurse::profile::VIEW,
            permissions::nurse::shift::VIEW,
            permissions::nurse::mar::VIEW,
            permissions::nurse::mar::ADMINISTER,
            permissions::nurse::mar::HOLD,
            permissions::nurse::mar::REFUSE,
            permissions::nurse::prescriptions::DRAFT,
            permissions::doctor::signoffs::VERBAL_REGISTER,
            permissions::nurse::vitals::VIEW,
            permissions::nurse::vitals::RECORD,
            permissions::nurse::intake_output::VIEW,
            permissions::nurse::intake_output::RECORD,
            permissions::nurse::restraint::VIEW,
            permissions::nurse::restraint::RECORD,
            permissions::nurse::transfusion::VIEW,
            permissions::nurse::transfusion::ADMINISTER,
            permissions::nurse::pain::VIEW,
            permissions::nurse::pain::RECORD,
            permissions::nurse::wound::VIEW,
            permissions::nurse::wound::RECORD,
            permissions::nurse::fall_risk::VIEW,
            permissions::nurse::fall_risk::RECORD,
            permissions::nurse::handoff::VIEW,
            permissions::nurse::handoff::RECORD,
            permissions::nurse::code_blue::VIEW,
            permissions::nurse::code_blue::RECORD,
            permissions::nurse::equipment::VIEW,
            permissions::nurse::equipment::RECORD,
            permissions::mrd::forms::VIEW,
            permissions::mrd::forms::MANAGE,
            // Intensive care. No built-in role named a single `icu.*` code, so
            // every ICU endpoint answered 403 to the staff who use it — an ICU
            // nurse could not record a ventilator setting. Granted on the
            // operator's decision (2026-08-18).
            permissions::icu::devices::LIST,
            permissions::icu::devices::MANAGE,
            permissions::icu::flowsheets::LIST,
            permissions::icu::flowsheets::CREATE,
            permissions::icu::neonatal::LIST,
            permissions::icu::neonatal::CREATE,
            permissions::icu::nutrition::LIST,
            permissions::icu::nutrition::CREATE,
            permissions::icu::scores::LIST,
            permissions::icu::scores::CREATE,
            permissions::icu::ventilator::LIST,
            permissions::icu::ventilator::CREATE,
            // The bedside tablet. Same story as ICU: guarded everywhere,
            // granted nowhere, so the whole portal was administrator-only.
            // That is also why its read-any-admission defect went unnoticed.
            permissions::bedside::VIEW,
            permissions::bedside::REQUEST,
            permissions::bedside::sessions::LIST,
            permissions::bedside::sessions::MANAGE,
            permissions::bedside::calls::BOARD,
            permissions::bedside::feedback::LIST,
            permissions::bedside::feedback::CREATE,
            permissions::bedside::videos::LIST,
            permissions::bedside::videos::MANAGE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::emergency::mass_casualty::CLOSE,
            permissions::emergency::mass_casualty::CREATE,
            permissions::emergency::mass_casualty::UPDATE,
            permissions::nurse::handoff_entries::RECORD,
            permissions::nurse::handoff_entries::VIEW,
            permissions::nurse::shift_notes::EDIT,
            permissions::nurse::shift_notes::VIEW,
            permissions::patients::notes::EDIT,
            permissions::patients::notes::VIEW,
            permissions::specialty::cath_lab::devices::MANAGE,
            permissions::specialty::cath_lab::stemi::MANAGE,
            permissions::specialty::dental::chart::CREATE,
            permissions::specialty::dental::chart::LIST,
            permissions::specialty::dental::exams::CREATE,
            permissions::specialty::dental::exams::LIST,
            permissions::specialty::dental::exams::UPDATE,
            permissions::specialty::endoscopy::reprocessing::LIST,
            permissions::specialty::endoscopy::reprocessing::MANAGE,
            permissions::specialty::endoscopy::scopes::MANAGE,
            permissions::specialty::ophthalmology::exams::CREATE,
            permissions::specialty::ophthalmology::exams::LIST,
            permissions::specialty::ophthalmology::exams::UPDATE,
            permissions::specialty::other::dialysis::MANAGE,
            permissions::specialty::other::oncology::CREATE,
            permissions::specialty::other::oncology::LIST,
            permissions::specialty::other::templates::MANAGE,
            permissions::specialty::palliative::mortuary::MANAGE,
            permissions::specialty::palliative::nucmed::MANAGE,
            permissions::specialty::pmr::psychometric::LIST,
            permissions::specialty::pmr::psychometric::MANAGE,
        ],
    },
    BuiltInRole {
        code: "receptionist",
        name: "Receptionist",
        description: "Front desk — registration, OPD visits, billing",
        permissions: &[
            // Marketing / enquiry desk — the tele-calling and front-desk seat.
            // Enquiry only: these codes never reach the clinical record.
            permissions::marketing::contacts::LIST,
            permissions::marketing::contacts::VIEW,
            permissions::marketing::contacts::CREATE,
            permissions::marketing::contacts::UPDATE,
            permissions::marketing::pipeline::VIEW,
            permissions::marketing::pipeline::MOVE,
            permissions::marketing::interactions::LOG,
            // The desk is who a patient actually tells. Recording a refusal
            // must not wait for a campaign manager to be at their desk.
            permissions::marketing::consent::VIEW,
            permissions::marketing::consent::CAPTURE,
            permissions::marketing::consent::WITHDRAW,
            permissions::marketing::SUPPRESSION_MANAGE,
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::patients::CREATE,
            permissions::patients::UPDATE,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::opd::visit::CREATE,
            permissions::opd::TOKEN_MANAGE,
            permissions::opd::appointment::LIST,
            permissions::opd::appointment::CREATE,
            permissions::opd::appointment::UPDATE,
            permissions::opd::appointment::CANCEL,
            permissions::emergency::visits::LIST,
            permissions::emergency::visits::CREATE,
            permissions::billing::invoices::LIST,
            permissions::billing::invoices::VIEW,
            permissions::billing::invoices::CREATE,
            permissions::billing::invoices::UPDATE,
            permissions::billing::invoices::CANCEL,
            permissions::billing::payments::CREATE,
            permissions::billing::receipts::PRINT,
            permissions::patient_packages::VIEW,
            permissions::patient_packages::SUBSCRIBE,
            permissions::admin::doctor_packages::LIST,
            // Front Office
            permissions::front_office::visitors::LIST,
            permissions::front_office::visitors::CREATE,
            permissions::front_office::visitors::MANAGE,
            permissions::front_office::passes::LIST,
            permissions::front_office::passes::MANAGE,
            permissions::front_office::queue::LIST,
            permissions::front_office::queue::MANAGE,
            permissions::front_office::enquiry::LIST,
            permissions::front_office::enquiry::CREATE,
            permissions::front_office::enquiry::MANAGE,
            // Insurance
            permissions::insurance::verification::LIST,
            permissions::insurance::verification::CREATE,
            permissions::insurance::prior_auth::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            // Health packages are sold at the front desk; the codes existed
            // only as bare strings, so nobody could be granted them.
            permissions::specialty::health_packages::LIST,
            // ABDM health IDs are created at the registration desk. These codes
            // were consts inside the route file, so nobody could hold them.
            permissions::abdm::abha::VIEW,
            permissions::abdm::abha::MANAGE,
        ],
    },
    BuiltInRole {
        code: "lab_technician",
        name: "Lab Technician",
        description: "Lab staff — orders, results, QC, phlebotomy, outsourced",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::patients::VIEW,
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::orders::CREATE,
            permissions::lab::results::CREATE,
            permissions::lab::results::UPDATE,
            permissions::lab::results::AMEND,
            permissions::lab::qc::LIST,
            permissions::lab::qc::CREATE,
            permissions::lab::qc::MANAGE,
            // The laboratory owns its own catalogue. Everyone who can order a
            // test used to be able to edit it, because the catalogue handlers
            // were gated on lab.orders.create.
            permissions::lab::catalog::MANAGE,
            permissions::lab::phlebotomy::LIST,
            permissions::lab::phlebotomy::MANAGE,
            permissions::lab::outsourced::LIST,
            permissions::lab::outsourced::MANAGE,
            permissions::lab::reports::VIEW,
            // Phase 3
            permissions::lab::samples::LIST,
            permissions::lab::samples::MANAGE,
            permissions::lab::dispatch::LIST,
            permissions::lab::specialized::LIST,
            permissions::lab::b2b::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::lab::dispatch::MANAGE,
        ],
    },
    BuiltInRole {
        code: "pharmacist",
        name: "Pharmacist",
        description: "Pharmacy staff — prescriptions, dispensing, stock",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::patients::VIEW,
            permissions::pharmacy::prescriptions::LIST,
            permissions::pharmacy::prescriptions::VIEW,
            permissions::pharmacy::dispensing::CREATE,
            permissions::pharmacy::dispensing::PARTIAL,
            permissions::pharmacy::dispensing::CANCEL,
            permissions::pharmacy::dispensing::VOID,
            permissions::pharmacy::stock::MANAGE,
            permissions::pharmacy::ndps::LIST,
            permissions::pharmacy::ndps::MANAGE,
            permissions::pharmacy::stores::LIST,
            permissions::pharmacy::stores::MANAGE,
            permissions::pharmacy::stores::indents::CREATE,
            permissions::pharmacy::stores::indents::APPROVE,
            permissions::pharmacy::stores::indents::ISSUE,
            permissions::pharmacy::stores::indents::RECEIVE,
            permissions::pharmacy::fulfilment::PICK,
            permissions::pharmacy::fulfilment::PACK,
            permissions::pharmacy::fulfilment::VERIFY,
            permissions::pharmacy::fulfilment::DISPATCH,
            permissions::pharmacy::fulfilment::RELEASE,
            permissions::pharmacy::analytics::VIEW,
            permissions::pharmacy::returns::LIST,
            permissions::pharmacy::returns::REQUEST,
            permissions::pharmacy::returns::APPROVE,
            permissions::pharmacy::returns::RESTOCK,
            permissions::pharmacy::returns::DESTROY,
            permissions::pharmacy::returns::REJECT,
            permissions::pharmacy::formulary::APPROVE,
            permissions::pharmacy::stewardship::APPROVE,
            permissions::pharmacy::validation::BYPASS,
            // Pharmacy Phase 3
            permissions::pharmacy::rx_queue::LIST,
            permissions::pharmacy::rx_queue::REVIEW,
            permissions::pharmacy::pos::CREATE,
            permissions::pharmacy::pos::VIEW,
            permissions::pharmacy::pos::CANCEL,
            permissions::pharmacy::pos::RETURN,
            permissions::pharmacy::pricing::MANAGE,
            permissions::pharmacy::safety::VIEW,
            permissions::pharmacy::safety::OVERRIDE,
            permissions::pharmacy::reconciliation::MANAGE,
            permissions::ipd::discharge_tat::VIEW,
            permissions::ipd::discharge_tat::UPDATE,
            permissions::ipd::discharge_tat::PHARMACY_UPDATE,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::STOCK_MANAGE,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // Regulatory
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::adr::CREATE,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            // Pharmacy improvements
            permissions::pharmacy_improvements::repeats::VIEW,
            permissions::pharmacy_improvements::repeats::DISPENSE,
            permissions::pharmacy_improvements::substitution::VIEW,
            permissions::pharmacy_improvements::substitution::RECORD,
            permissions::pharmacy_improvements::counseling::VIEW,
            permissions::pharmacy_improvements::counseling::RECORD,
            permissions::pharmacy_improvements::coverage::VIEW,
            permissions::pharmacy_improvements::coverage::CHECK,
            // Pharmacy finance
            permissions::pharmacy_finance::cash_drawer::VIEW,
            permissions::pharmacy_finance::cash_drawer::OPEN,
            permissions::pharmacy_finance::cash_drawer::CLOSE,
            permissions::pharmacy_finance::petty_cash::VIEW,
            permissions::pharmacy_finance::petty_cash::RECORD,
            permissions::pharmacy_finance::free_dispensing::VIEW,
            permissions::pharmacy_finance::supplier_payments::VIEW,
            permissions::pharmacy_finance::finance_reports::VIEW,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::pharmacy_finance::cashier_audit::VIEW,
            permissions::pharmacy_finance::supplier_payments::MANAGE,
        ],
    },
    BuiltInRole {
        code: "billing_clerk",
        name: "Billing Clerk",
        description: "Billing staff — invoices, payments, advances, corporate, reports",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::billing::invoices::LIST,
            permissions::billing::invoices::VIEW,
            permissions::billing::invoices::CREATE,
            permissions::billing::invoices::UPDATE,
            permissions::billing::invoices::CANCEL,
            permissions::billing::catalog::MANAGE,
            permissions::billing::payments::CREATE,
            permissions::billing::payments::VOID,
            permissions::billing::receipts::PRINT,
            permissions::billing::receipts::REPRINT,
            permissions::billing::advances::LIST,
            permissions::billing::advances::CREATE,
            permissions::billing::advances::ADJUST,
            permissions::billing::advances::REFUND,
            permissions::billing::corporate::LIST,
            permissions::billing::corporate::CREATE,
            permissions::billing::corporate::UPDATE,
            permissions::billing::corporate::ENROLL,
            permissions::billing::corporate::UNENROLL,
            permissions::billing::reports::VIEW,
            permissions::billing::day_close::CREATE,
            permissions::billing::day_close::VERIFY,
            permissions::billing::write_off::CREATE,
            permissions::billing::audit::VIEW,
            permissions::patient_packages::VIEW,
            permissions::patient_packages::SUBSCRIBE,
            permissions::patient_packages::REFUND,
            permissions::admin::doctor_packages::LIST,
            // Phase 3 — credit, accounting, tax, recon, ERP
            permissions::billing::credit::LIST,
            permissions::billing::credit::MANAGE,
            permissions::billing::credit::APPLY,
            permissions::billing::journal::LIST,
            permissions::billing::journal::CREATE,
            permissions::billing::journal::POST,
            permissions::billing::bank_recon::LIST,
            permissions::billing::bank_recon::MANAGE,
            permissions::billing::tds::LIST,
            permissions::billing::tds::MANAGE,
            permissions::billing::gst_returns::LIST,
            permissions::billing::gst_returns::MANAGE,
            permissions::billing::erp::EXPORT,
            permissions::camp::billing::LIST,
            permissions::camp::billing::CREATE,
            permissions::emergency::visits::LIST,
            permissions::ipd::tariffs::LIST,
            permissions::ipd::discharge_tat::VIEW,
            permissions::ipd::discharge_tat::UPDATE,
            permissions::ipd::discharge_tat::BILLING_UPDATE,
            // Insurance — full access
            permissions::insurance::verification::LIST,
            permissions::insurance::verification::CREATE,
            permissions::insurance::prior_auth::LIST,
            permissions::insurance::prior_auth::CREATE,
            permissions::insurance::prior_auth::UPDATE,
            permissions::insurance::prior_auth::SUBMIT,
            permissions::insurance::appeals::LIST,
            permissions::insurance::appeals::CREATE,
            permissions::insurance::rules::LIST,
            permissions::insurance::rules::MANAGE,
            permissions::insurance::dashboard::VIEW,
            // Lab B2B & Dispatch
            permissions::lab::b2b::LIST,
            permissions::lab::b2b::MANAGE,
            permissions::lab::dispatch::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            // Health packages are priced and billed here.
            permissions::specialty::health_packages::LIST,
            permissions::specialty::health_packages::MANAGE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::billing::concessions::CREATE,
            permissions::billing::concessions::LIST,
            permissions::pharmacy_finance::cashier_audit::VIEW,
            permissions::pharmacy_finance::supplier_payments::MANAGE,
        ],
    },
    BuiltInRole {
        code: "housekeeping_staff",
        name: "Housekeeping Staff",
        description: "Housekeeping — cleaning tasks, room turnaround, linen management",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::housekeeping::cleaning::LIST,
            permissions::housekeeping::cleaning::CREATE,
            permissions::housekeeping::turnaround::LIST,
            permissions::housekeeping::turnaround::MANAGE,
            permissions::housekeeping::linen::LIST,
            permissions::housekeeping::linen::CREATE,
            permissions::housekeeping::laundry::LIST,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
        ],
    },
    BuiltInRole {
        code: "facilities_manager",
        name: "Facilities Manager",
        description: "Facilities management — dashboard, bed management, indent approval, integrations",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::ipd::beds::MANAGE,
            permissions::ipd::wards::MANAGE,
            permissions::ipd::tariffs::LIST,
            permissions::ipd::tariffs::MANAGE,
            permissions::ipd::bed_dashboard::VIEW,
            permissions::ipd::reports::VIEW,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::CREATE,
            permissions::indent::APPROVE,
            permissions::indent::STOCK_MANAGE,
            permissions::integration::LIST,
            permissions::integration::VIEW,
            // Housekeeping
            permissions::housekeeping::cleaning::LIST,
            permissions::housekeeping::cleaning::CREATE,
            permissions::housekeeping::cleaning::MANAGE,
            permissions::housekeeping::turnaround::LIST,
            permissions::housekeeping::turnaround::MANAGE,
            permissions::housekeeping::pest_control::LIST,
            permissions::housekeeping::pest_control::MANAGE,
            permissions::housekeeping::linen::LIST,
            permissions::housekeeping::linen::CREATE,
            permissions::housekeeping::linen::MANAGE,
            permissions::housekeeping::laundry::LIST,
            permissions::housekeeping::laundry::MANAGE,
            // HR
            permissions::hr::employees::LIST,
            permissions::hr::employees::CREATE,
            permissions::hr::employees::UPDATE,
            permissions::hr::credentials::LIST,
            permissions::hr::credentials::MANAGE,
            permissions::hr::attendance::LIST,
            permissions::hr::attendance::MANAGE,
            permissions::hr::leave::LIST,
            permissions::hr::leave::CREATE,
            permissions::hr::leave::APPROVE,
            permissions::hr::roster::LIST,
            permissions::hr::roster::MANAGE,
            permissions::hr::on_call::LIST,
            permissions::hr::on_call::MANAGE,
            permissions::hr::training::LIST,
            permissions::hr::training::MANAGE,
            permissions::hr::appraisal::MANAGE,
            // BME / CMMS
            permissions::bme::equipment::LIST,
            permissions::bme::equipment::CREATE,
            permissions::bme::equipment::UPDATE,
            permissions::bme::pm::LIST,
            permissions::bme::pm::MANAGE,
            permissions::bme::calibration::LIST,
            permissions::bme::calibration::MANAGE,
            permissions::bme::contracts::LIST,
            permissions::bme::contracts::MANAGE,
            permissions::bme::breakdowns::LIST,
            permissions::bme::breakdowns::CREATE,
            permissions::bme::breakdowns::MANAGE,
            permissions::bme::evaluations::MANAGE,
            // Facilities Management
            permissions::facilities::gas::LIST,
            permissions::facilities::gas::MANAGE,
            permissions::facilities::fire::LIST,
            permissions::facilities::fire::MANAGE,
            permissions::facilities::water::LIST,
            permissions::facilities::water::MANAGE,
            permissions::facilities::energy::LIST,
            permissions::facilities::energy::MANAGE,
            permissions::facilities::work_orders::LIST,
            permissions::facilities::work_orders::CREATE,
            permissions::facilities::work_orders::MANAGE,
            permissions::facilities::compliance::LIST,
            permissions::facilities::compliance::MANAGE,
            permissions::facilities::stats::VIEW,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::templates::CREATE,
            permissions::documents::templates::UPDATE,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            permissions::documents::VOID,
            permissions::documents::audit::LIST,
            permissions::documents::review::LIST,
            permissions::documents::review::MANAGE,
            // Regulatory
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::checklists::LIST,
            permissions::regulatory::checklists::CREATE,
            permissions::regulatory::checklists::UPDATE,
            permissions::regulatory::calendar::MANAGE,
            // LMS (full admin — manages training)
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::courses::VIEW,
            permissions::lms::courses::CREATE,
            permissions::lms::courses::UPDATE,
            permissions::lms::enrollments::LIST,
            permissions::lms::enrollments::CREATE,
            permissions::lms::enrollments::UPDATE,
            permissions::lms::quizzes::LIST,
            permissions::lms::quizzes::CREATE,
            permissions::lms::paths::LIST,
            permissions::lms::paths::CREATE,
            permissions::lms::paths::UPDATE,
            permissions::lms::certificates::LIST,
            permissions::lms::certificates::CREATE,
            permissions::lms::compliance::VIEW,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::assets::ISSUE,
            permissions::assets::LIST,
            permissions::assets::MANAGE,
            permissions::assets::RESERVE,
            permissions::assets::RETURN,
        ],
    },
    BuiltInRole {
        code: "audit_officer",
        name: "Audit Officer",
        description: "Audit & compliance — read-only access across modules",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::audit::VIEW,
            permissions::audit::EXPORT,
            permissions::audit::ACCESS_VIEW,
            permissions::audit::REVIEW,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::emergency::visits::LIST,
            permissions::emergency::mlc::LIST,
            permissions::emergency::mlc::PRINT,
            permissions::emergency::mlc::REPRINT,
            permissions::emergency::mlc_police_intimations::LIST,
            permissions::emergency::mlc_police_intimations::CREATE,
            permissions::emergency::mlc_police_intimations::CONFIRM,
            permissions::emergency::mlc_police_intimations::PRINT,
            permissions::emergency::mlc_police_intimations::REPRINT,
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::reports::VIEW,
            permissions::lab::qc::LIST,
            permissions::pharmacy::prescriptions::LIST,
            permissions::pharmacy::prescriptions::VIEW,
            permissions::billing::invoices::LIST,
            permissions::billing::invoices::VIEW,
            permissions::ipd::admissions::LIST,
            permissions::ipd::admissions::VIEW,
            // MRD (read-only for audit)
            permissions::mrd::records::LIST,
            permissions::mrd::births::LIST,
            permissions::mrd::deaths::LIST,
            permissions::mrd::case_sheets::VIEW,
            // Camp (read-only for audit)
            permissions::camp::LIST,
            // Consent (read-only for audit)
            permissions::consent::templates::LIST,
            permissions::consent::audit::LIST,
            // Security (read-only for audit)
            permissions::security::access::LIST,
            permissions::security::cctv::LIST,
            permissions::security::incidents::LIST,
            permissions::security::patient_safety::LIST,
            permissions::security::debriefs::LIST,
            // Documents (read-only for audit)
            permissions::documents::templates::LIST,
            permissions::documents::audit::LIST,
            permissions::documents::review::LIST,
            // Regulatory (all read permissions for audit)
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::checklists::LIST,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::materiovigilance::LIST,
            permissions::regulatory::pcpndt::LIST,
            permissions::regulatory::calendar::MANAGE,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            permissions::lms::compliance::VIEW,
        ],
    },
    BuiltInRole {
        code: "quality_officer",
        name: "Quality Officer",
        description: "Quality & compliance — full regulatory access",
        permissions: &[
            // NMC advertising and the Drugs and Magic Remedies Act are
            // compliance questions, which is this role's remit.
            permissions::marketing::outreach::APPROVE,
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::doctor::signoffs::VERBAL_REGISTER,
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::reports::VIEW,
            permissions::quality::indicators::LIST,
            permissions::quality::indicators::MANAGE,
            permissions::quality::documents::LIST,
            permissions::quality::documents::MANAGE,
            permissions::quality::incidents::LIST,
            permissions::quality::incidents::CREATE,
            permissions::quality::incidents::UPDATE,
            permissions::quality::capa::LIST,
            permissions::quality::capa::MANAGE,
            permissions::quality::committees::LIST,
            permissions::quality::committees::MANAGE,
            permissions::quality::accreditation::LIST,
            permissions::quality::accreditation::MANAGE,
            permissions::quality::audits::LIST,
            permissions::quality::audits::CREATE,
            // Order Sets (analytics)
            permissions::order_sets::templates::LIST,
            permissions::order_sets::templates::VIEW,
            permissions::order_sets::analytics::VIEW,
            // Regulatory — all 12 permissions
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::checklists::LIST,
            permissions::regulatory::checklists::CREATE,
            permissions::regulatory::checklists::UPDATE,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::adr::CREATE,
            permissions::regulatory::adr::UPDATE,
            permissions::regulatory::materiovigilance::LIST,
            permissions::regulatory::materiovigilance::CREATE,
            permissions::regulatory::pcpndt::LIST,
            permissions::regulatory::pcpndt::CREATE,
            permissions::regulatory::calendar::MANAGE,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            permissions::lms::compliance::VIEW,
            // Trial oversight: view only. Registering a trial and breaking a
            // blind both stay elsewhere.
            permissions::specialty::clinical_trials::LIST,
        ],
    },
    BuiltInRole {
        code: "occ_health_officer",
        name: "Occupational Health Officer",
        description: "Employee health screenings, drug testing, vaccinations, injury reports",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::occ_health::screenings::LIST,
            permissions::occ_health::screenings::CREATE,
            permissions::occ_health::screenings::UPDATE,
            permissions::occ_health::drug_screens::LIST,
            permissions::occ_health::drug_screens::MANAGE,
            permissions::occ_health::vaccinations::LIST,
            permissions::occ_health::vaccinations::MANAGE,
            permissions::occ_health::injuries::LIST,
            permissions::occ_health::injuries::CREATE,
            permissions::occ_health::injuries::MANAGE,
        ],
    },
    BuiltInRole {
        code: "utilization_reviewer",
        name: "Utilization Reviewer",
        description: "Admission reviews, LOS monitoring, payer communications",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::ur::reviews::LIST,
            permissions::ur::reviews::CREATE,
            permissions::ur::reviews::UPDATE,
            permissions::ur::communications::LIST,
            permissions::ur::communications::CREATE,
            permissions::ur::conversions::LIST,
            permissions::ur::conversions::CREATE,
        ],
    },
    BuiltInRole {
        code: "case_manager",
        name: "Case Manager",
        description: "Discharge planning, barrier tracking, referrals, analytics",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::case_mgmt::assignments::LIST,
            permissions::case_mgmt::assignments::CREATE,
            permissions::case_mgmt::assignments::UPDATE,
            permissions::case_mgmt::barriers::LIST,
            permissions::case_mgmt::barriers::MANAGE,
            permissions::case_mgmt::referrals::LIST,
            permissions::case_mgmt::referrals::MANAGE,
            permissions::case_mgmt::analytics::VIEW,
        ],
    },
    BuiltInRole {
        code: "scheduling_admin",
        name: "Scheduling Admin",
        description: "No-show predictions, waitlist management, overbooking rules",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::scheduling::predictions::LIST,
            permissions::scheduling::predictions::CREATE,
            permissions::scheduling::waitlist::LIST,
            permissions::scheduling::waitlist::MANAGE,
            permissions::scheduling::overbooking::LIST,
            permissions::scheduling::overbooking::MANAGE,
            permissions::scheduling::analytics::VIEW,
            permissions::scheduling::AUTO_FILL_MANAGE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::opd::schedule::LIST,
            permissions::opd::schedule::MANAGE,
        ],
    },
    BuiltInRole {
        code: "mrd_officer",
        name: "MRD Officer",
        description: "Medical records — file room, births, deaths, retrieval",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::mrd::records::LIST,
            permissions::mrd::records::CREATE,
            permissions::mrd::records::MANAGE,
            permissions::mrd::births::LIST,
            permissions::mrd::births::CREATE,
            permissions::mrd::deaths::LIST,
            permissions::mrd::deaths::CREATE,
            permissions::mrd::case_sheets::VIEW,
            permissions::mrd::case_sheets::GENERATE,
            permissions::mrd::case_sheets::PRINT,
            permissions::mrd::case_sheets::FILE,
            permissions::mrd::case_sheets::REPRINT,
            permissions::mrd::storage::MANAGE,
            permissions::mrd::forms::VIEW,
            permissions::mrd::forms::MANAGE,
            // File-room work needs patient demographics + encounter lookup.
            // Read-only; MRD doesn't create or edit clinical records.
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::ipd::admissions::LIST,
            permissions::ipd::admissions::VIEW,
        ],
    },
    BuiltInRole {
        code: "canteen_staff",
        name: "Canteen Staff",
        description: "Patient meal orders, kitchen output, tray dispatch",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::diet::orders::LIST,
            permissions::diet::orders::CREATE,
            permissions::diet::kitchen::LIST,
            permissions::diet::kitchen::MANAGE,
            permissions::diet::inventory::LIST,
        ],
    },
    BuiltInRole {
        code: "dietitian",
        name: "Dietitian",
        description: "Diet templates, nutrition plans, kitchen inventory",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::diet::orders::LIST,
            permissions::diet::orders::CREATE,
            permissions::diet::templates::LIST,
            permissions::diet::templates::MANAGE,
            permissions::diet::kitchen::LIST,
            permissions::diet::inventory::LIST,
            permissions::diet::inventory::MANAGE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::diet::audits::CREATE,
            permissions::diet::audits::LIST,
        ],
    },
    BuiltInRole {
        code: "security_guard",
        name: "Security Guard",
        description: "Visitor passes, incident reports, CCTV, access logs",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::security::access::LIST,
            permissions::security::cctv::LIST,
            permissions::security::incidents::LIST,
            permissions::security::incidents::CREATE,
            permissions::security::patient_safety::LIST,
            permissions::front_office::visitors::LIST,
            permissions::front_office::passes::LIST,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::security::access::MANAGE,
            permissions::security::cctv::MANAGE,
            permissions::security::debriefs::CREATE,
            permissions::security::incidents::UPDATE,
            permissions::security::patient_safety::MANAGE,
        ],
    },
    BuiltInRole {
        code: "biomed_engineer",
        name: "Biomedical Engineer",
        description: "Medical equipment, preventive maintenance, calibration, AMC contracts",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::bme::equipment::LIST,
            permissions::bme::equipment::CREATE,
            permissions::bme::equipment::UPDATE,
            permissions::bme::pm::LIST,
            permissions::bme::pm::MANAGE,
            permissions::bme::calibration::LIST,
            permissions::bme::calibration::MANAGE,
            permissions::bme::contracts::LIST,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::assets::ISSUE,
            permissions::assets::LIST,
            permissions::assets::MANAGE,
            permissions::assets::RESERVE,
            permissions::assets::RETURN,
            permissions::devices::agents::LIST,
            permissions::devices::catalog::LIST,
            permissions::devices::CREATE,
            permissions::devices::INGEST,
            permissions::devices::LIST,
            permissions::devices::messages::VIEW,
            permissions::devices::pairing::PAIRED_LIST,
            permissions::devices::pairing::PAIRED_REVOKE,
            permissions::devices::pairing::ROSTER_READ,
            permissions::devices::pairing::TOKEN_CREATE,
            permissions::devices::TEST,
            permissions::devices::UPDATE,
            permissions::devices::VIEW,
        ],
    },
    BuiltInRole {
        code: "ambulance_driver",
        name: "Ambulance Driver",
        description: "Trip dispatch, fleet status, driver roster",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::ambulance::fleet::LIST,
            permissions::ambulance::drivers::LIST,
            permissions::ambulance::trips::LIST,
            permissions::ambulance::trips::CREATE,
            permissions::ambulance::trips::UPDATE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::ambulance::drivers::MANAGE,
            permissions::ambulance::fleet::CREATE,
            permissions::ambulance::fleet::UPDATE,
            permissions::ambulance::maintenance::LIST,
            permissions::ambulance::maintenance::MANAGE,
        ],
    },
    BuiltInRole {
        code: "radiology_tech",
        name: "Radiology Technician",
        description: "Modality acquisition, study upload, technologist worklist",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::radiology::orders::LIST,
            permissions::radiology::orders::VIEW,
            permissions::radiology::modalities::MANAGE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::radiology::orders::CANCEL,
            permissions::radiology::orders::CREATE,
            permissions::radiology::reports::CREATE,
            permissions::radiology::reports::VERIFY,
        ],
    },
    BuiltInRole {
        code: "cssd_technician",
        name: "CSSD Technician",
        description: "Sterilization cycles, instrument sets, issuance to OT",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::cssd::instruments::LIST,
            permissions::cssd::instruments::MANAGE,
            permissions::cssd::sets::LIST,
            permissions::cssd::sets::MANAGE,
            permissions::cssd::sterilization::LIST,
            permissions::cssd::sterilization::CREATE,
            permissions::cssd::issuance::LIST,
            permissions::cssd::issuance::CREATE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::cssd::equipment::LIST,
            permissions::cssd::equipment::MANAGE,
        ],
    },
    BuiltInRole {
        code: "blood_bank_tech",
        name: "Blood Bank Technician",
        description: "Donor screening, inventory, crossmatch, transfusion records",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::blood_bank::donors::LIST,
            permissions::blood_bank::donors::CREATE,
            permissions::blood_bank::inventory::LIST,
            permissions::blood_bank::inventory::MANAGE,
            permissions::blood_bank::crossmatch::LIST,
            permissions::blood_bank::crossmatch::CREATE,
            permissions::blood_bank::transfusion::LIST,
            permissions::blood_bank::transfusion::CREATE,
        ],
    },
    BuiltInRole {
        code: "marketing_executive",
        name: "Marketing Executive",
        description: "Campaigns, enquiry sources and funnel reporting — no clinical access",
        permissions: &[
            permissions::dashboard::VIEW,
            // Campaign attribution needs the enquiry list to be meaningful:
            // "which campaign produced revenue" is unanswerable from campaign
            // rows alone. It stops at the enquiry — no patients.* code here.
            permissions::marketing::contacts::LIST,
            permissions::marketing::pipeline::VIEW,
            permissions::marketing::campaigns::VIEW,
            permissions::marketing::campaigns::MANAGE,
            permissions::marketing::cohorts::VIEW,
            permissions::marketing::cohorts::MANAGE,
            permissions::marketing::outreach::SEND,
            permissions::marketing::outreach::DISPATCH,
            // Seeing who a run reached is not the same as seeing a cohort's
            // membership, and a clinical run's recipients stay behind a
            // per-record check on top of this code.
            permissions::marketing::messages::VIEW,
            // View, and not capture or withdraw: the people who run campaigns
            // may see that somebody is unreachable, and may not make them
            // reachable. SUPPRESSION_MANAGE is deliberately absent for the
            // same reason.
            permissions::marketing::consent::VIEW,
            // NOT cohorts::CLINICAL_DEFINE — building a recall list from
            // diagnoses is a clinical act, and NOT outreach::APPROVE — the
            // author of a campaign does not sign it off.
            permissions::marketing::REPORTS_VIEW,
        ],
    },
    BuiltInRole {
        code: "front_office_staff",
        name: "Front Office Staff",
        description: "Visitor management, gate pass, queue board, enquiry desk",
        permissions: &[
            // Marketing / enquiry desk — the tele-calling and front-desk seat.
            // Enquiry only: these codes never reach the clinical record.
            permissions::marketing::contacts::LIST,
            permissions::marketing::contacts::VIEW,
            permissions::marketing::contacts::CREATE,
            permissions::marketing::contacts::UPDATE,
            permissions::marketing::pipeline::VIEW,
            permissions::marketing::pipeline::MOVE,
            permissions::marketing::interactions::LOG,
            // The desk is who a patient actually tells. Recording a refusal
            // must not wait for a campaign manager to be at their desk.
            permissions::marketing::consent::VIEW,
            permissions::marketing::consent::CAPTURE,
            permissions::marketing::consent::WITHDRAW,
            permissions::marketing::SUPPRESSION_MANAGE,
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::front_office::visitors::LIST,
            permissions::front_office::visitors::CREATE,
            permissions::front_office::visitors::MANAGE,
            permissions::front_office::passes::LIST,
            permissions::front_office::passes::MANAGE,
            permissions::front_office::queue::LIST,
            permissions::front_office::queue::MANAGE,
            permissions::front_office::enquiry::LIST,
            permissions::abdm::abha::VIEW,
            permissions::abdm::abha::MANAGE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::communications::alerts::CREATE,
            permissions::communications::alerts::LIST,
            permissions::communications::alerts::MANAGE,
            permissions::communications::clinical::ACKNOWLEDGE,
            permissions::communications::clinical::CREATE,
            permissions::communications::clinical::LIST,
            permissions::communications::complaints::CREATE,
            permissions::communications::complaints::LIST,
            permissions::communications::complaints::MANAGE,
            permissions::communications::config::MANAGE,
            permissions::communications::dlt::LIST,
            permissions::communications::dlt::MANAGE,
            permissions::communications::feedback::CREATE,
            permissions::communications::feedback::LIST,
            permissions::communications::messages::CREATE,
            permissions::communications::messages::LIST,
        ],
    },
    BuiltInRole {
        code: "infection_control_officer",
        name: "Infection Control Officer",
        description: "HAI surveillance, antibiotic stewardship, biowaste, hand hygiene",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::infection_control::surveillance::LIST,
            permissions::infection_control::surveillance::CREATE,
            permissions::infection_control::stewardship::LIST,
            permissions::infection_control::stewardship::CREATE,
            permissions::infection_control::biowaste::LIST,
            permissions::infection_control::biowaste::CREATE,
            permissions::infection_control::hygiene::LIST,
            permissions::infection_control::hygiene::CREATE,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::infection_control::outbreak::CREATE,
            permissions::infection_control::outbreak::LIST,
            permissions::infection_control::outbreak::UPDATE,
        ],
    },
    BuiltInRole {
        code: "procurement_officer",
        name: "Procurement Officer",
        description: "Vendor onboarding, purchase orders, GRN, supplier payments",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::procurement::vendors::LIST,
            permissions::procurement::vendors::CREATE,
            permissions::procurement::vendors::UPDATE,
            permissions::procurement::purchase_orders::LIST,
            permissions::procurement::purchase_orders::CREATE,
            permissions::procurement::purchase_orders::APPROVE,
            permissions::procurement::grn::LIST,
            permissions::procurement::grn::CREATE,
            permissions::procurement::payments::LIST,
            permissions::procurement::payments::MANAGE,
            permissions::procurement::PERFORMANCE_VIEW,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::procurement::rate_contracts::LIST,
            permissions::procurement::rate_contracts::MANAGE,
            permissions::procurement::stores::MANAGE,
        ],
    },
    BuiltInRole {
        code: "store_keeper",
        name: "Store Keeper",
        description: "Indents, stock movements, dead stock, consumables",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::CREATE,
            permissions::indent::STOCK_MANAGE,
            permissions::indent::CONSUMABLES_LIST,
            permissions::indent::CONSUMABLES_MANAGE,
            permissions::procurement::purchase_orders::LIST,
            permissions::procurement::grn::LIST,
            permissions::procurement::grn::CREATE,
            permissions::procurement::stores::LIST,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::indent::ANALYTICS_VIEW,
            permissions::indent::CONDEMNATION_LIST,
            permissions::indent::CONDEMNATION_MANAGE,
            permissions::indent::IMPLANTS_LIST,
            permissions::indent::IMPLANTS_MANAGE,
            permissions::inventory::DISPOSE,
            permissions::inventory::VIEW,
            permissions::storage::policies::LIST,
            permissions::storage::policies::MANAGE,
            permissions::storage::RESTORE,
            permissions::storage::SWEEP_TRIGGER,
            permissions::storage::transitions::LIST,
            permissions::storage::usage::VIEW,
        ],
    },
    BuiltInRole {
        code: "hr_officer",
        name: "HR Officer",
        description: "Employee master, attendance, leave, credentials, payroll inputs",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::hr::employees::LIST,
            permissions::hr::employees::CREATE,
            permissions::hr::employees::UPDATE,
            permissions::hr::credentials::LIST,
            permissions::hr::credentials::MANAGE,
            permissions::hr::attendance::LIST,
            permissions::hr::attendance::MANAGE,
            permissions::hr::leave::LIST,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::hr::payroll::runs::CREATE,
            permissions::hr::payroll::runs::LIST,
            permissions::hr::payroll::structures::LIST,
            permissions::hr::payroll::structures::MANAGE,
        ],
    },
    BuiltInRole {
        code: "camp_coordinator",
        name: "Camp Coordinator",
        description: "Outreach camp planning, registrations, screenings, lab linkage",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::camp::LIST,
            permissions::camp::CREATE,
            permissions::camp::UPDATE,
            permissions::camp::registrations::LIST,
            permissions::camp::registrations::CREATE,
            permissions::camp::registrations::UPDATE,
            permissions::camp::screenings::LIST,
            permissions::camp::screenings::MANAGE,
            permissions::camp::referrals::CREATE,
            permissions::camp::referrals::UPDATE,
            permissions::camp::referrals::STATUS,
            permissions::camp::lab::LIST,
            permissions::camp::lab::MANAGE,
            permissions::camp::billing::LIST,
            permissions::camp::billing::CREATE,
            permissions::camp::followups::LIST,
            permissions::camp::followups::SCHEDULE,
            permissions::camp::followups::OUTCOME,
            permissions::camp::followups::CONVERT,
        ],
    },
    BuiltInRole {
        code: "insurance_officer",
        name: "Insurance Officer",
        description: "Eligibility, prior auth, claim submission, appeals",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::insurance::verification::LIST,
            permissions::insurance::verification::CREATE,
            permissions::insurance::prior_auth::LIST,
            permissions::insurance::prior_auth::CREATE,
            permissions::insurance::prior_auth::UPDATE,
            permissions::insurance::prior_auth::SUBMIT,
            permissions::insurance::appeals::LIST,
            permissions::insurance::appeals::CREATE,
            permissions::insurance::dashboard::VIEW,
        ],
    },
    BuiltInRole {
        code: "display_device",
        name: "Wall Display",
        description: "A screen, not a person — reads queue and status boards and nothing else",
        permissions: &[
            // Deliberately the whole list. A display has no dashboard, no
            // settings read, no patient list: it shows a board and is bolted to
            // a wall where anyone walking past can see it. Every code added
            // here is visible to a corridor.
            permissions::display::board::READ,
        ],
    },
    BuiltInRole {
        code: "ot_staff",
        name: "OT Staff",
        description: "Operation theatre booking, room status, pre-op checks, safety checklist",
        permissions: &[
            permissions::admin::settings::READ,
            permissions::dashboard::VIEW,
            permissions::ot::bookings::LIST,
            permissions::ot::bookings::CREATE,
            permissions::ot::bookings::UPDATE,
            permissions::ot::rooms::LIST,
            permissions::ot::rooms::MANAGE,
            permissions::ot::preop::LIST,
            permissions::ot::preop::CREATE,
            permissions::ot::safety_checklist::LIST,
            // Guarded by handlers that exist, granted to no role until now — the same gap as ICU.
            // Granted on the operator's decision, 2026-08-18.
            permissions::ot::anesthesia::CREATE,
            permissions::ot::anesthesia::LIST,
            permissions::ot::case_records::CREATE,
            permissions::ot::case_records::LIST,
            permissions::ot::postop::CREATE,
            permissions::ot::postop::LIST,
            permissions::ot::preferences::LIST,
            permissions::ot::preferences::MANAGE,
            permissions::ot::reports::VIEW,
            permissions::ot::safety_checklist::CREATE,
        ],
    },
];
