//! Built-in role definitions — single source of truth.
//!
//! Adding / changing a role: edit this file. `seed::seed_built_in_roles`
//! reads from `BUILT_IN_ROLES` and writes the `roles` table; the
//! manifest API serves them to the frontend.

use crate::permissions;

pub struct BuiltInRole {
    pub code: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub permissions: &'static [&'static str],
}
pub const BUILT_IN_ROLES: &[BuiltInRole] = &[
    BuiltInRole {
        code: "super_admin",
        name: "Super Admin",
        description: "Full system access — bypasses all permission checks",
        permissions: &[], // bypass role, no explicit permissions needed
    },
    BuiltInRole {
        code: "hospital_admin",
        name: "Hospital Admin",
        description: "Full hospital access — bypasses all permission checks",
        permissions: &[], // bypass role, no explicit permissions needed
    },
    BuiltInRole {
        code: "doctor",
        name: "Doctor",
        description: "Clinical staff — patient care, OPD, orders, admissions",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::patients::CREATE,
            permissions::patients::UPDATE,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::opd::visit::CREATE,
            permissions::opd::visit::UPDATE,
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::orders::CREATE,
            permissions::lab::reports::VIEW,
            permissions::lab::dispatch::LIST,
            permissions::lab::specialized::LIST,
            permissions::lab::specialized::CREATE,
            permissions::lab::b2b::LIST,
            permissions::pharmacy::prescriptions::LIST,
            permissions::pharmacy::prescriptions::VIEW,
            permissions::pharmacy::ndps::LIST,
            permissions::pharmacy::analytics::VIEW,
            permissions::pharmacy::validation::BYPASS,
            permissions::pharmacy::rx_queue::LIST,
            permissions::pharmacy::safety::VIEW,
            permissions::ipd::admissions::LIST,
            permissions::ipd::admissions::VIEW,
            permissions::ipd::admissions::CREATE,
            permissions::ipd::discharge::CREATE,
            permissions::ipd::discharge_summary::CREATE,
            permissions::ipd::bed_dashboard::VIEW,
            permissions::ipd::reports::VIEW,
            permissions::ipd::clinical_docs::LIST,
            permissions::ipd::clinical_docs::CREATE,
            permissions::ipd::transfers::CREATE,
            permissions::ipd::death_records::MANAGE,
            permissions::ipd::birth_records::MANAGE,
            permissions::ipd::discharge_tat::VIEW,
            permissions::ot::consumables::MANAGE,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::CREATE,
            // Consent
            permissions::consent::VERIFY,
            permissions::consent::REVOKE,
            permissions::consent::templates::LIST,
            permissions::consent::signatures::LIST,
            // Specialty Clinical
            permissions::specialty::cath_lab::procedures::LIST,
            permissions::specialty::cath_lab::procedures::CREATE,
            permissions::specialty::cath_lab::devices::LIST,
            permissions::specialty::cath_lab::stemi::LIST,
            permissions::specialty::cath_lab::monitoring::LIST,
            permissions::specialty::cath_lab::monitoring::CREATE,
            permissions::specialty::endoscopy::procedures::LIST,
            permissions::specialty::endoscopy::procedures::CREATE,
            permissions::specialty::endoscopy::scopes::LIST,
            permissions::specialty::psychiatry::patients::LIST,
            permissions::specialty::psychiatry::patients::CREATE,
            permissions::specialty::psychiatry::patients::UPDATE,
            permissions::specialty::psychiatry::assessments::LIST,
            permissions::specialty::psychiatry::assessments::CREATE,
            permissions::specialty::psychiatry::ect::LIST,
            permissions::specialty::psychiatry::ect::CREATE,
            permissions::specialty::psychiatry::restraint::LIST,
            permissions::specialty::pmr::plans::LIST,
            permissions::specialty::pmr::plans::CREATE,
            permissions::specialty::pmr::sessions::LIST,
            permissions::specialty::pmr::sessions::CREATE,
            permissions::specialty::pmr::audiology::LIST,
            permissions::specialty::pmr::audiology::CREATE,
            permissions::specialty::palliative::dnr::LIST,
            permissions::specialty::palliative::pain::LIST,
            permissions::specialty::palliative::pain::CREATE,
            permissions::specialty::palliative::mortuary::LIST,
            permissions::specialty::palliative::nucmed::LIST,
            permissions::specialty::palliative::nucmed::CREATE,
            permissions::specialty::maternity::registrations::LIST,
            permissions::specialty::maternity::registrations::CREATE,
            permissions::specialty::maternity::anc::LIST,
            permissions::specialty::maternity::anc::CREATE,
            permissions::specialty::maternity::labor::LIST,
            permissions::specialty::maternity::labor::CREATE,
            permissions::specialty::maternity::newborn::LIST,
            permissions::specialty::maternity::newborn::CREATE,
            permissions::specialty::other::templates::LIST,
            permissions::specialty::other::records::LIST,
            permissions::specialty::other::records::CREATE,
            permissions::specialty::other::dialysis::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            permissions::documents::audit::LIST,
            // Order Sets
            permissions::order_sets::templates::LIST,
            permissions::order_sets::templates::VIEW,
            permissions::order_sets::templates::CREATE,
            permissions::order_sets::templates::UPDATE,
            permissions::order_sets::templates::APPROVE,
            permissions::order_sets::activation::CREATE,
            permissions::order_sets::activation::VIEW,
            permissions::order_sets::analytics::VIEW,
            // Insurance
            permissions::insurance::verification::LIST,
            permissions::insurance::prior_auth::LIST,
            permissions::insurance::prior_auth::CREATE,
            permissions::insurance::prior_auth::SUBMIT,
            permissions::insurance::appeals::LIST,
            permissions::insurance::dashboard::VIEW,
            // Care View
            permissions::care_view::VIEW,
            permissions::care_view::DISCHARGE_TRACKER,
            // Chronic Care
            permissions::chronic::programs::LIST,
            permissions::chronic::enrollments::LIST,
            permissions::chronic::enrollments::CREATE,
            permissions::chronic::enrollments::UPDATE,
            permissions::chronic::timeline::VIEW,
            permissions::chronic::timeline::CREATE,
            permissions::chronic::outcomes::VIEW,
            permissions::chronic::outcomes::CREATE,
            // Regulatory
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::adr::CREATE,
            permissions::regulatory::pcpndt::LIST,
            permissions::regulatory::pcpndt::CREATE,
            // Retrospective
            permissions::retrospective::CREATE,
            permissions::retrospective::AUDIT,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
        ],
    },
    BuiltInRole {
        code: "nurse",
        name: "Nurse",
        description: "Nursing staff — patient view, OPD queue, bed management",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::lab::phlebotomy::LIST,
            // Cross-module read for safe nursing care:
            // MAR cross-check, lab/imaging review, vitals from labs.
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::reports::VIEW,
            permissions::pharmacy::prescriptions::LIST,
            permissions::pharmacy::prescriptions::VIEW,
            permissions::radiology::orders::LIST,
            permissions::radiology::orders::VIEW,
            permissions::ipd::admissions::LIST,
            permissions::ipd::admissions::VIEW,
            permissions::ipd::beds::MANAGE,
            permissions::ipd::bed_dashboard::VIEW,
            permissions::ipd::wards::MANAGE,
            permissions::ipd::clinical_docs::LIST,
            permissions::ipd::clinical_docs::CREATE,
            permissions::ipd::reservations::MANAGE,
            permissions::ipd::transfers::CREATE,
            permissions::ipd::discharge_tat::VIEW,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::CREATE,
            // Specialty Clinical (list access)
            permissions::specialty::cath_lab::procedures::LIST,
            permissions::specialty::cath_lab::monitoring::LIST,
            permissions::specialty::endoscopy::procedures::LIST,
            permissions::specialty::psychiatry::patients::LIST,
            permissions::specialty::psychiatry::assessments::LIST,
            permissions::specialty::psychiatry::restraint::LIST,
            permissions::specialty::pmr::plans::LIST,
            permissions::specialty::pmr::sessions::LIST,
            permissions::specialty::palliative::dnr::LIST,
            permissions::specialty::palliative::pain::LIST,
            permissions::specialty::maternity::registrations::LIST,
            permissions::specialty::maternity::anc::LIST,
            permissions::specialty::maternity::labor::LIST,
            permissions::specialty::maternity::newborn::LIST,
            permissions::specialty::other::records::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // Order Sets (activation only)
            permissions::order_sets::activation::CREATE,
            permissions::order_sets::activation::VIEW,
            // Care View
            permissions::care_view::VIEW,
            permissions::care_view::MY_TASKS,
            permissions::care_view::HANDOVER,
            permissions::care_view::DISCHARGE_TRACKER,
            permissions::care_view::MANAGE_TASKS,
            // Chronic Care
            permissions::chronic::enrollments::LIST,
            permissions::chronic::timeline::VIEW,
            permissions::chronic::adherence::LIST,
            permissions::chronic::adherence::CREATE,
            permissions::chronic::outcomes::VIEW,
            // Regulatory
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::adr::CREATE,
            // Retrospective
            permissions::retrospective::CREATE,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            // Nurse activities
            permissions::nurse::dashboard::VIEW,
            permissions::nurse::profile::VIEW,
            permissions::nurse::shift::VIEW,
            permissions::nurse::mar::VIEW,
            permissions::nurse::mar::ADMINISTER,
            permissions::nurse::mar::HOLD,
            permissions::nurse::mar::REFUSE,
            permissions::nurse::vitals::VIEW,
            permissions::nurse::vitals::RECORD,
            permissions::nurse::intake_output::VIEW,
            permissions::nurse::intake_output::RECORD,
            permissions::nurse::restraint::VIEW,
            permissions::nurse::restraint::RECORD,
            permissions::nurse::pain::VIEW,
            permissions::nurse::pain::RECORD,
            permissions::nurse::wound::VIEW,
            permissions::nurse::wound::RECORD,
            permissions::nurse::fall_risk::VIEW,
            permissions::nurse::fall_risk::RECORD,
            permissions::nurse::handoff::VIEW,
            permissions::nurse::handoff::RECORD,
            permissions::nurse::code_blue::VIEW,
            permissions::nurse::code_blue::RECORD,
            permissions::nurse::equipment::VIEW,
            permissions::nurse::equipment::RECORD,
        ],
    },
    BuiltInRole {
        code: "receptionist",
        name: "Receptionist",
        description: "Front desk — registration, OPD visits, billing",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::patients::CREATE,
            permissions::patients::UPDATE,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::opd::visit::CREATE,
            permissions::opd::TOKEN_MANAGE,
            permissions::billing::invoices::LIST,
            permissions::billing::invoices::VIEW,
            permissions::billing::invoices::CREATE,
            permissions::billing::payments::CREATE,
            // Front Office
            permissions::front_office::visitors::LIST,
            permissions::front_office::visitors::CREATE,
            permissions::front_office::visitors::MANAGE,
            permissions::front_office::passes::LIST,
            permissions::front_office::passes::MANAGE,
            permissions::front_office::queue::LIST,
            permissions::front_office::enquiry::LIST,
            permissions::front_office::enquiry::CREATE,
            permissions::front_office::enquiry::MANAGE,
            // Insurance
            permissions::insurance::verification::LIST,
            permissions::insurance::verification::CREATE,
            permissions::insurance::prior_auth::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
        ],
    },
    BuiltInRole {
        code: "lab_technician",
        name: "Lab Technician",
        description: "Lab staff — orders, results, QC, phlebotomy, outsourced",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::patients::VIEW,
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::orders::CREATE,
            permissions::lab::results::CREATE,
            permissions::lab::results::UPDATE,
            permissions::lab::results::AMEND,
            permissions::lab::qc::LIST,
            permissions::lab::qc::CREATE,
            permissions::lab::qc::MANAGE,
            permissions::lab::phlebotomy::LIST,
            permissions::lab::phlebotomy::MANAGE,
            permissions::lab::outsourced::LIST,
            permissions::lab::outsourced::MANAGE,
            permissions::lab::reports::VIEW,
            // Phase 3
            permissions::lab::samples::LIST,
            permissions::lab::samples::MANAGE,
            permissions::lab::dispatch::LIST,
            permissions::lab::specialized::LIST,
            permissions::lab::b2b::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
        ],
    },
    BuiltInRole {
        code: "pharmacist",
        name: "Pharmacist",
        description: "Pharmacy staff — prescriptions, dispensing, stock",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::patients::VIEW,
            permissions::pharmacy::prescriptions::LIST,
            permissions::pharmacy::prescriptions::VIEW,
            permissions::pharmacy::dispensing::CREATE,
            permissions::pharmacy::stock::MANAGE,
            permissions::pharmacy::ndps::LIST,
            permissions::pharmacy::ndps::MANAGE,
            permissions::pharmacy::stores::LIST,
            permissions::pharmacy::stores::MANAGE,
            permissions::pharmacy::analytics::VIEW,
            permissions::pharmacy::returns::LIST,
            permissions::pharmacy::returns::MANAGE,
            permissions::pharmacy::formulary::APPROVE,
            permissions::pharmacy::stewardship::APPROVE,
            permissions::pharmacy::validation::BYPASS,
            // Pharmacy Phase 3
            permissions::pharmacy::rx_queue::LIST,
            permissions::pharmacy::rx_queue::REVIEW,
            permissions::pharmacy::pos::CREATE,
            permissions::pharmacy::pos::VIEW,
            permissions::pharmacy::pricing::MANAGE,
            permissions::pharmacy::safety::VIEW,
            permissions::pharmacy::safety::OVERRIDE,
            permissions::pharmacy::reconciliation::MANAGE,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::STOCK_MANAGE,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // Regulatory
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::adr::CREATE,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            // Pharmacy improvements
            permissions::pharmacy_improvements::repeats::VIEW,
            permissions::pharmacy_improvements::repeats::DISPENSE,
            permissions::pharmacy_improvements::substitution::VIEW,
            permissions::pharmacy_improvements::substitution::RECORD,
            permissions::pharmacy_improvements::counseling::VIEW,
            permissions::pharmacy_improvements::counseling::RECORD,
            permissions::pharmacy_improvements::coverage::VIEW,
            permissions::pharmacy_improvements::coverage::CHECK,
            // Pharmacy finance
            permissions::pharmacy_finance::cash_drawer::VIEW,
            permissions::pharmacy_finance::cash_drawer::OPEN,
            permissions::pharmacy_finance::cash_drawer::CLOSE,
            permissions::pharmacy_finance::petty_cash::VIEW,
            permissions::pharmacy_finance::petty_cash::RECORD,
            permissions::pharmacy_finance::free_dispensing::VIEW,
            permissions::pharmacy_finance::supplier_payments::VIEW,
            permissions::pharmacy_finance::finance_reports::VIEW,
        ],
    },
    BuiltInRole {
        code: "billing_clerk",
        name: "Billing Clerk",
        description: "Billing staff — invoices, payments, advances, corporate, reports",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::billing::invoices::LIST,
            permissions::billing::invoices::VIEW,
            permissions::billing::invoices::CREATE,
            permissions::billing::payments::CREATE,
            permissions::billing::payments::VOID,
            permissions::billing::advances::LIST,
            permissions::billing::advances::CREATE,
            permissions::billing::advances::ADJUST,
            permissions::billing::advances::REFUND,
            permissions::billing::corporate::LIST,
            permissions::billing::corporate::CREATE,
            permissions::billing::corporate::UPDATE,
            permissions::billing::reports::VIEW,
            permissions::billing::day_close::CREATE,
            permissions::billing::day_close::VERIFY,
            permissions::billing::write_off::CREATE,
            permissions::billing::audit::VIEW,
            // Phase 3 — credit, accounting, tax, recon, ERP
            permissions::billing::credit::LIST,
            permissions::billing::credit::MANAGE,
            permissions::billing::journal::LIST,
            permissions::billing::journal::CREATE,
            permissions::billing::journal::POST,
            permissions::billing::bank_recon::LIST,
            permissions::billing::bank_recon::MANAGE,
            permissions::billing::tds::LIST,
            permissions::billing::tds::MANAGE,
            permissions::billing::gst_returns::LIST,
            permissions::billing::gst_returns::MANAGE,
            permissions::billing::erp::EXPORT,
            permissions::ipd::discharge_tat::VIEW,
            // Insurance — full access
            permissions::insurance::verification::LIST,
            permissions::insurance::verification::CREATE,
            permissions::insurance::prior_auth::LIST,
            permissions::insurance::prior_auth::CREATE,
            permissions::insurance::prior_auth::UPDATE,
            permissions::insurance::prior_auth::SUBMIT,
            permissions::insurance::appeals::LIST,
            permissions::insurance::appeals::CREATE,
            permissions::insurance::rules::LIST,
            permissions::insurance::rules::MANAGE,
            permissions::insurance::dashboard::VIEW,
            // Lab B2B & Dispatch
            permissions::lab::b2b::LIST,
            permissions::lab::b2b::MANAGE,
            permissions::lab::dispatch::LIST,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
        ],
    },
    BuiltInRole {
        code: "housekeeping_staff",
        name: "Housekeeping Staff",
        description: "Housekeeping — cleaning tasks, room turnaround, linen management",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::housekeeping::cleaning::LIST,
            permissions::housekeeping::cleaning::CREATE,
            permissions::housekeeping::turnaround::LIST,
            permissions::housekeeping::turnaround::MANAGE,
            permissions::housekeeping::linen::LIST,
            permissions::housekeeping::linen::CREATE,
            permissions::housekeeping::laundry::LIST,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
        ],
    },
    BuiltInRole {
        code: "facilities_manager",
        name: "Facilities Manager",
        description: "Facilities management — dashboard, bed management, indent approval, integrations",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::ipd::beds::MANAGE,
            permissions::ipd::wards::MANAGE,
            permissions::ipd::bed_dashboard::VIEW,
            permissions::ipd::reports::VIEW,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::CREATE,
            permissions::indent::APPROVE,
            permissions::indent::STOCK_MANAGE,
            permissions::integration::LIST,
            permissions::integration::VIEW,
            // Housekeeping
            permissions::housekeeping::cleaning::LIST,
            permissions::housekeeping::cleaning::CREATE,
            permissions::housekeeping::cleaning::MANAGE,
            permissions::housekeeping::turnaround::LIST,
            permissions::housekeeping::turnaround::MANAGE,
            permissions::housekeeping::pest_control::LIST,
            permissions::housekeeping::pest_control::MANAGE,
            permissions::housekeeping::linen::LIST,
            permissions::housekeeping::linen::CREATE,
            permissions::housekeeping::linen::MANAGE,
            permissions::housekeeping::laundry::LIST,
            permissions::housekeeping::laundry::MANAGE,
            // HR
            permissions::hr::employees::LIST,
            permissions::hr::employees::CREATE,
            permissions::hr::employees::UPDATE,
            permissions::hr::credentials::LIST,
            permissions::hr::credentials::MANAGE,
            permissions::hr::attendance::LIST,
            permissions::hr::attendance::MANAGE,
            permissions::hr::leave::LIST,
            permissions::hr::leave::CREATE,
            permissions::hr::leave::APPROVE,
            permissions::hr::roster::LIST,
            permissions::hr::roster::MANAGE,
            permissions::hr::on_call::LIST,
            permissions::hr::on_call::MANAGE,
            permissions::hr::training::LIST,
            permissions::hr::training::MANAGE,
            permissions::hr::appraisal::MANAGE,
            // BME / CMMS
            permissions::bme::equipment::LIST,
            permissions::bme::equipment::CREATE,
            permissions::bme::equipment::UPDATE,
            permissions::bme::pm::LIST,
            permissions::bme::pm::MANAGE,
            permissions::bme::calibration::LIST,
            permissions::bme::calibration::MANAGE,
            permissions::bme::contracts::LIST,
            permissions::bme::contracts::MANAGE,
            permissions::bme::breakdowns::LIST,
            permissions::bme::breakdowns::CREATE,
            permissions::bme::breakdowns::MANAGE,
            permissions::bme::evaluations::MANAGE,
            // Facilities Management
            permissions::facilities::gas::LIST,
            permissions::facilities::gas::MANAGE,
            permissions::facilities::fire::LIST,
            permissions::facilities::fire::MANAGE,
            permissions::facilities::water::LIST,
            permissions::facilities::water::MANAGE,
            permissions::facilities::energy::LIST,
            permissions::facilities::energy::MANAGE,
            permissions::facilities::work_orders::LIST,
            permissions::facilities::work_orders::CREATE,
            permissions::facilities::work_orders::MANAGE,
            permissions::facilities::compliance::LIST,
            permissions::facilities::compliance::MANAGE,
            permissions::facilities::stats::VIEW,
            // Documents
            permissions::documents::templates::LIST,
            permissions::documents::templates::CREATE,
            permissions::documents::templates::UPDATE,
            permissions::documents::GENERATE,
            permissions::documents::REPRINT,
            permissions::documents::VOID,
            permissions::documents::audit::LIST,
            permissions::documents::review::LIST,
            permissions::documents::review::MANAGE,
            // Regulatory
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::checklists::LIST,
            permissions::regulatory::checklists::CREATE,
            permissions::regulatory::checklists::UPDATE,
            permissions::regulatory::calendar::MANAGE,
            // LMS (full admin — manages training)
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::courses::VIEW,
            permissions::lms::courses::CREATE,
            permissions::lms::courses::UPDATE,
            permissions::lms::enrollments::LIST,
            permissions::lms::enrollments::CREATE,
            permissions::lms::enrollments::UPDATE,
            permissions::lms::quizzes::LIST,
            permissions::lms::quizzes::CREATE,
            permissions::lms::paths::LIST,
            permissions::lms::paths::CREATE,
            permissions::lms::paths::UPDATE,
            permissions::lms::certificates::LIST,
            permissions::lms::certificates::CREATE,
            permissions::lms::compliance::VIEW,
        ],
    },
    BuiltInRole {
        code: "audit_officer",
        name: "Audit Officer",
        description: "Audit & compliance — read-only access across modules",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::lab::orders::LIST,
            permissions::lab::orders::VIEW,
            permissions::lab::reports::VIEW,
            permissions::lab::qc::LIST,
            permissions::pharmacy::prescriptions::LIST,
            permissions::pharmacy::prescriptions::VIEW,
            permissions::billing::invoices::LIST,
            permissions::billing::invoices::VIEW,
            permissions::ipd::admissions::LIST,
            permissions::ipd::admissions::VIEW,
            // MRD (read-only for audit)
            permissions::mrd::records::LIST,
            permissions::mrd::births::LIST,
            permissions::mrd::deaths::LIST,
            // Camp (read-only for audit)
            permissions::camp::LIST,
            // Consent (read-only for audit)
            permissions::consent::templates::LIST,
            permissions::consent::audit::LIST,
            // Security (read-only for audit)
            permissions::security::access::LIST,
            permissions::security::cctv::LIST,
            permissions::security::incidents::LIST,
            permissions::security::patient_safety::LIST,
            permissions::security::debriefs::LIST,
            // Documents (read-only for audit)
            permissions::documents::templates::LIST,
            permissions::documents::audit::LIST,
            permissions::documents::review::LIST,
            // Regulatory (all read permissions for audit)
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::checklists::LIST,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::materiovigilance::LIST,
            permissions::regulatory::pcpndt::LIST,
            permissions::regulatory::calendar::MANAGE,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            permissions::lms::compliance::VIEW,
        ],
    },
    BuiltInRole {
        code: "quality_officer",
        name: "Quality Officer",
        description: "Quality & compliance — full regulatory access",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::quality::indicators::LIST,
            permissions::quality::indicators::MANAGE,
            permissions::quality::documents::LIST,
            permissions::quality::documents::MANAGE,
            permissions::quality::incidents::LIST,
            permissions::quality::incidents::CREATE,
            permissions::quality::incidents::UPDATE,
            permissions::quality::capa::LIST,
            permissions::quality::capa::MANAGE,
            permissions::quality::committees::LIST,
            permissions::quality::committees::MANAGE,
            permissions::quality::accreditation::LIST,
            permissions::quality::accreditation::MANAGE,
            permissions::quality::audits::LIST,
            permissions::quality::audits::CREATE,
            // Order Sets (analytics)
            permissions::order_sets::templates::LIST,
            permissions::order_sets::templates::VIEW,
            permissions::order_sets::analytics::VIEW,
            // Regulatory — all 12 permissions
            permissions::regulatory::dashboard::VIEW,
            permissions::regulatory::checklists::LIST,
            permissions::regulatory::checklists::CREATE,
            permissions::regulatory::checklists::UPDATE,
            permissions::regulatory::adr::LIST,
            permissions::regulatory::adr::CREATE,
            permissions::regulatory::adr::UPDATE,
            permissions::regulatory::materiovigilance::LIST,
            permissions::regulatory::materiovigilance::CREATE,
            permissions::regulatory::pcpndt::LIST,
            permissions::regulatory::pcpndt::CREATE,
            permissions::regulatory::calendar::MANAGE,
            // LMS
            permissions::lms::my_learning::VIEW,
            permissions::lms::quizzes::ATTEMPT,
            permissions::lms::courses::LIST,
            permissions::lms::certificates::LIST,
            permissions::lms::compliance::VIEW,
        ],
    },
    BuiltInRole {
        code: "occ_health_officer",
        name: "Occupational Health Officer",
        description: "Employee health screenings, drug testing, vaccinations, injury reports",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::occ_health::screenings::LIST,
            permissions::occ_health::screenings::CREATE,
            permissions::occ_health::screenings::UPDATE,
            permissions::occ_health::drug_screens::LIST,
            permissions::occ_health::drug_screens::MANAGE,
            permissions::occ_health::vaccinations::LIST,
            permissions::occ_health::vaccinations::MANAGE,
            permissions::occ_health::injuries::LIST,
            permissions::occ_health::injuries::CREATE,
            permissions::occ_health::injuries::MANAGE,
        ],
    },
    BuiltInRole {
        code: "utilization_reviewer",
        name: "Utilization Reviewer",
        description: "Admission reviews, LOS monitoring, payer communications",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::ur::reviews::LIST,
            permissions::ur::reviews::CREATE,
            permissions::ur::reviews::UPDATE,
            permissions::ur::communications::LIST,
            permissions::ur::communications::CREATE,
            permissions::ur::conversions::LIST,
            permissions::ur::conversions::CREATE,
        ],
    },
    BuiltInRole {
        code: "case_manager",
        name: "Case Manager",
        description: "Discharge planning, barrier tracking, referrals, analytics",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::case_mgmt::assignments::LIST,
            permissions::case_mgmt::assignments::CREATE,
            permissions::case_mgmt::assignments::UPDATE,
            permissions::case_mgmt::barriers::LIST,
            permissions::case_mgmt::barriers::MANAGE,
            permissions::case_mgmt::referrals::LIST,
            permissions::case_mgmt::referrals::MANAGE,
            permissions::case_mgmt::analytics::VIEW,
        ],
    },
    BuiltInRole {
        code: "scheduling_admin",
        name: "Scheduling Admin",
        description: "No-show predictions, waitlist management, overbooking rules",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::scheduling::predictions::LIST,
            permissions::scheduling::predictions::CREATE,
            permissions::scheduling::waitlist::LIST,
            permissions::scheduling::waitlist::MANAGE,
            permissions::scheduling::overbooking::LIST,
            permissions::scheduling::overbooking::MANAGE,
            permissions::scheduling::analytics::VIEW,
            permissions::scheduling::AUTO_FILL_MANAGE,
        ],
    },
    BuiltInRole {
        code: "mrd_officer",
        name: "MRD Officer",
        description: "Medical records — file room, births, deaths, retrieval",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::mrd::records::LIST,
            permissions::mrd::records::CREATE,
            permissions::mrd::records::MANAGE,
            permissions::mrd::births::LIST,
            permissions::mrd::births::CREATE,
            permissions::mrd::deaths::LIST,
            permissions::mrd::deaths::CREATE,
            // File-room work needs patient demographics + encounter lookup.
            // Read-only; MRD doesn't create or edit clinical records.
            permissions::patients::LIST,
            permissions::patients::VIEW,
            permissions::opd::queue::LIST,
            permissions::opd::queue::VIEW,
            permissions::ipd::admissions::LIST,
            permissions::ipd::admissions::VIEW,
        ],
    },
    BuiltInRole {
        code: "canteen_staff",
        name: "Canteen Staff",
        description: "Patient meal orders, kitchen output, tray dispatch",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::diet::orders::LIST,
            permissions::diet::orders::CREATE,
            permissions::diet::kitchen::LIST,
            permissions::diet::kitchen::MANAGE,
            permissions::diet::inventory::LIST,
        ],
    },
    BuiltInRole {
        code: "dietitian",
        name: "Dietitian",
        description: "Diet templates, nutrition plans, kitchen inventory",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::diet::orders::LIST,
            permissions::diet::orders::CREATE,
            permissions::diet::templates::LIST,
            permissions::diet::templates::MANAGE,
            permissions::diet::kitchen::LIST,
            permissions::diet::inventory::LIST,
            permissions::diet::inventory::MANAGE,
        ],
    },
    BuiltInRole {
        code: "security_guard",
        name: "Security Guard",
        description: "Visitor passes, incident reports, CCTV, access logs",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::security::access::LIST,
            permissions::security::cctv::LIST,
            permissions::security::incidents::LIST,
            permissions::security::incidents::CREATE,
            permissions::security::patient_safety::LIST,
            permissions::front_office::visitors::LIST,
            permissions::front_office::passes::LIST,
        ],
    },
    BuiltInRole {
        code: "biomed_engineer",
        name: "Biomedical Engineer",
        description: "Medical equipment, preventive maintenance, calibration, AMC contracts",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::bme::equipment::LIST,
            permissions::bme::equipment::CREATE,
            permissions::bme::equipment::UPDATE,
            permissions::bme::pm::LIST,
            permissions::bme::pm::MANAGE,
            permissions::bme::calibration::LIST,
            permissions::bme::calibration::MANAGE,
            permissions::bme::contracts::LIST,
        ],
    },
    BuiltInRole {
        code: "ambulance_driver",
        name: "Ambulance Driver",
        description: "Trip dispatch, fleet status, driver roster",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::ambulance::fleet::LIST,
            permissions::ambulance::drivers::LIST,
            permissions::ambulance::trips::LIST,
            permissions::ambulance::trips::CREATE,
            permissions::ambulance::trips::UPDATE,
        ],
    },
    BuiltInRole {
        code: "radiology_tech",
        name: "Radiology Technician",
        description: "Modality acquisition, study upload, technologist worklist",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::radiology::orders::LIST,
            permissions::radiology::orders::VIEW,
            permissions::radiology::modalities::MANAGE,
        ],
    },
    BuiltInRole {
        code: "cssd_technician",
        name: "CSSD Technician",
        description: "Sterilization cycles, instrument sets, issuance to OT",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::cssd::instruments::LIST,
            permissions::cssd::instruments::MANAGE,
            permissions::cssd::sets::LIST,
            permissions::cssd::sets::MANAGE,
            permissions::cssd::sterilization::LIST,
            permissions::cssd::sterilization::CREATE,
            permissions::cssd::issuance::LIST,
            permissions::cssd::issuance::CREATE,
        ],
    },
    BuiltInRole {
        code: "blood_bank_tech",
        name: "Blood Bank Technician",
        description: "Donor screening, inventory, crossmatch, transfusion records",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::blood_bank::donors::LIST,
            permissions::blood_bank::donors::CREATE,
            permissions::blood_bank::inventory::LIST,
            permissions::blood_bank::inventory::MANAGE,
            permissions::blood_bank::crossmatch::LIST,
            permissions::blood_bank::crossmatch::CREATE,
            permissions::blood_bank::transfusion::LIST,
            permissions::blood_bank::transfusion::CREATE,
        ],
    },
    BuiltInRole {
        code: "front_office_staff",
        name: "Front Office Staff",
        description: "Visitor management, gate pass, queue board, enquiry desk",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::front_office::visitors::LIST,
            permissions::front_office::visitors::CREATE,
            permissions::front_office::visitors::MANAGE,
            permissions::front_office::passes::LIST,
            permissions::front_office::passes::MANAGE,
            permissions::front_office::queue::LIST,
            permissions::front_office::enquiry::LIST,
        ],
    },
    BuiltInRole {
        code: "infection_control_officer",
        name: "Infection Control Officer",
        description: "HAI surveillance, antibiotic stewardship, biowaste, hand hygiene",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::infection_control::surveillance::LIST,
            permissions::infection_control::surveillance::CREATE,
            permissions::infection_control::stewardship::LIST,
            permissions::infection_control::stewardship::CREATE,
            permissions::infection_control::biowaste::LIST,
            permissions::infection_control::biowaste::CREATE,
            permissions::infection_control::hygiene::LIST,
            permissions::infection_control::hygiene::CREATE,
        ],
    },
    BuiltInRole {
        code: "procurement_officer",
        name: "Procurement Officer",
        description: "Vendor onboarding, purchase orders, GRN, supplier payments",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::procurement::vendors::LIST,
            permissions::procurement::vendors::CREATE,
            permissions::procurement::vendors::UPDATE,
            permissions::procurement::purchase_orders::LIST,
            permissions::procurement::purchase_orders::CREATE,
            permissions::procurement::grn::LIST,
            permissions::procurement::grn::CREATE,
        ],
    },
    BuiltInRole {
        code: "store_keeper",
        name: "Store Keeper",
        description: "Indents, stock movements, dead stock, consumables",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::indent::LIST,
            permissions::indent::VIEW,
            permissions::indent::CREATE,
            permissions::indent::STOCK_MANAGE,
            permissions::indent::CONSUMABLES_LIST,
            permissions::indent::CONSUMABLES_MANAGE,
        ],
    },
    BuiltInRole {
        code: "hr_officer",
        name: "HR Officer",
        description: "Employee master, attendance, leave, credentials, payroll inputs",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::hr::employees::LIST,
            permissions::hr::employees::CREATE,
            permissions::hr::employees::UPDATE,
            permissions::hr::credentials::LIST,
            permissions::hr::credentials::MANAGE,
            permissions::hr::attendance::LIST,
            permissions::hr::attendance::MANAGE,
            permissions::hr::leave::LIST,
        ],
    },
    BuiltInRole {
        code: "camp_coordinator",
        name: "Camp Coordinator",
        description: "Outreach camp planning, registrations, screenings, lab linkage",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::camp::LIST,
            permissions::camp::CREATE,
            permissions::camp::UPDATE,
            permissions::camp::registrations::LIST,
            permissions::camp::registrations::CREATE,
            permissions::camp::screenings::LIST,
            permissions::camp::screenings::MANAGE,
            permissions::camp::lab::LIST,
        ],
    },
    BuiltInRole {
        code: "insurance_officer",
        name: "Insurance Officer",
        description: "Eligibility, prior auth, claim submission, appeals",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::insurance::verification::LIST,
            permissions::insurance::verification::CREATE,
            permissions::insurance::prior_auth::LIST,
            permissions::insurance::prior_auth::CREATE,
            permissions::insurance::prior_auth::UPDATE,
            permissions::insurance::prior_auth::SUBMIT,
            permissions::insurance::appeals::LIST,
            permissions::insurance::appeals::CREATE,
        ],
    },
    BuiltInRole {
        code: "ot_staff",
        name: "OT Staff",
        description: "Operation theatre booking, room status, pre-op checks, safety checklist",
        permissions: &[
            permissions::dashboard::VIEW,
            permissions::ot::bookings::LIST,
            permissions::ot::bookings::CREATE,
            permissions::ot::bookings::UPDATE,
            permissions::ot::rooms::LIST,
            permissions::ot::rooms::MANAGE,
            permissions::ot::preop::LIST,
            permissions::ot::preop::CREATE,
            permissions::ot::safety_checklist::LIST,
        ],
    },
];
