//! Screen registry — every navigable page mapped to its required permission.
//!
//! Adding / changing a screen: edit this file. The frontend nav config
//! at `apps/web/src/config/navigation.ts` is generated from `SCREENS`
//! via the codegen script (see `scripts/generate-access-bundle.mjs`).
//! Manual edits to navigation.ts will be overwritten.

#[derive(Debug, Clone)]
pub struct ScreenDef {
    /// Unique stable code (e.g. "patients.list", "admin.users").
    pub code: &'static str,
    /// Human-readable label (i18n key for the frontend).
    pub label: &'static str,
    /// Frontend route path, e.g. "/patients".
    pub route: &'static str,
    /// Module the screen belongs to, e.g. "patients", "lab", "admin".
    pub module: &'static str,
    /// Permission code the user must hold to navigate to this screen.
    /// `None` = always-visible (e.g. `/dashboard` for any authenticated user).
    pub required_permission: Option<&'static str>,
    /// Icon identifier used by the sidebar nav. Maps to a Tabler-icon
    /// name on the frontend.
    pub icon: &'static str,
}

pub const SCREENS: &[ScreenDef] = &[
    ScreenDef {
        code: "dashboard",
        label: "Dashboard",
        route: "/dashboard",
        module: "dashboard",
        required_permission: Some("dashboard.view"),
        icon: "IconDashboard",
    },
    ScreenDef {
        code: "patients",
        label: "Patients",
        route: "/patients",
        module: "patients",
        required_permission: Some("patients.list"),
        icon: "IconUsers",
    },
    ScreenDef {
        code: "opd",
        label: "OPD",
        route: "/opd",
        module: "opd",
        required_permission: Some("opd.queue.list"),
        icon: "IconStethoscope",
    },
    ScreenDef {
        code: "ipd",
        label: "IPD",
        route: "/ipd",
        module: "ipd",
        required_permission: Some("ipd.admissions.list"),
        icon: "IconBed",
    },
    ScreenDef {
        code: "icu",
        label: "ICU",
        route: "/icu",
        module: "icu",
        required_permission: Some("icu.list"),
        icon: "IconHeartbeat",
    },
    ScreenDef {
        code: "emergency",
        label: "Emergency",
        route: "/emergency",
        module: "emergency",
        required_permission: Some("emergency.visits.list"),
        icon: "IconAmbulance",
    },
    ScreenDef {
        code: "lab",
        label: "Lab",
        route: "/lab",
        module: "lab",
        required_permission: Some("lab.orders.list"),
        icon: "IconTestPipe",
    },
    ScreenDef {
        code: "radiology",
        label: "Radiology",
        route: "/radiology",
        module: "radiology",
        required_permission: Some("radiology.orders.list"),
        icon: "IconScan",
    },
    ScreenDef {
        code: "blood-bank",
        label: "Blood Bank",
        route: "/blood-bank",
        module: "blood_bank",
        required_permission: Some("blood_bank.list"),
        icon: "IconDroplet",
    },
    ScreenDef {
        code: "pharmacy",
        label: "Pharmacy",
        route: "/pharmacy",
        module: "pharmacy",
        required_permission: Some("pharmacy.orders.list"),
        icon: "IconPill",
    },
    ScreenDef {
        code: "billing",
        label: "Billing",
        route: "/billing",
        module: "billing",
        required_permission: Some("billing.invoices.list"),
        icon: "IconFileInvoice",
    },
    ScreenDef {
        code: "indent",
        label: "Indent / Stores",
        route: "/indent",
        module: "indent",
        required_permission: Some("indent.list"),
        icon: "IconBoxSeam",
    },
    ScreenDef {
        code: "procurement",
        label: "Procurement",
        route: "/procurement",
        module: "procurement",
        required_permission: Some("procurement.list"),
        icon: "IconTruck",
    },
    ScreenDef {
        code: "diet-kitchen",
        label: "Diet & Kitchen",
        route: "/diet-kitchen",
        module: "diet",
        required_permission: Some("diet.list"),
        icon: "IconSalad",
    },
    ScreenDef {
        code: "cssd",
        label: "CSSD",
        route: "/cssd",
        module: "cssd",
        required_permission: Some("cssd.list"),
        icon: "IconStack2",
    },
    ScreenDef {
        code: "quality",
        label: "Quality",
        route: "/quality",
        module: "quality",
        required_permission: Some("quality.list"),
        icon: "IconCertificate",
    },
    ScreenDef {
        code: "infection-control",
        label: "Infection Control",
        route: "/infection-control",
        module: "infection_control",
        required_permission: Some("infection_control.list"),
        icon: "IconVirus",
    },
    ScreenDef {
        code: "regulatory",
        label: "Regulatory",
        route: "/regulatory",
        module: "regulatory",
        required_permission: Some("regulatory.list"),
        icon: "IconShield",
    },
    ScreenDef {
        code: "front-office",
        label: "Front Office",
        route: "/front-office",
        module: "front_office",
        required_permission: Some("front_office.list"),
        icon: "IconBuildingCommunity",
    },
    ScreenDef {
        code: "facilities",
        label: "Facilities",
        route: "/facilities",
        module: "facilities",
        required_permission: Some("facilities.list"),
        icon: "IconBuildingBank",
    },
    ScreenDef {
        code: "hr",
        label: "HR",
        route: "/hr",
        module: "hr",
        required_permission: Some("hr.list"),
        icon: "IconUserCog",
    },
    ScreenDef {
        code: "consent",
        label: "Consent",
        route: "/consent",
        module: "consent",
        required_permission: Some("consent.list"),
        icon: "IconWriting",
    },
    ScreenDef {
        code: "camp",
        label: "Camps",
        route: "/camp",
        module: "camp",
        required_permission: Some("camp.list"),
        icon: "IconCampfire",
    },
    ScreenDef {
        code: "lms",
        label: "LMS",
        route: "/lms",
        module: "lms",
        required_permission: Some("lms.list"),
        icon: "IconBook",
    },
    ScreenDef {
        code: "admin-users",
        label: "Users",
        route: "/admin/users",
        module: "admin",
        required_permission: Some("admin.users.list"),
        icon: "IconUsers",
    },
    ScreenDef {
        code: "admin-roles",
        label: "Roles",
        route: "/admin/roles",
        module: "admin",
        required_permission: Some("admin.roles.list"),
        icon: "IconLockAccess",
    },
    ScreenDef {
        code: "admin-groups",
        label: "Groups",
        route: "/admin/groups",
        module: "admin",
        required_permission: Some("admin.groups.list"),
        icon: "IconUsersGroup",
    },
    ScreenDef {
        code: "admin-integration",
        label: "Integration Hub",
        route: "/admin/integration-hub",
        module: "admin",
        required_permission: Some("integration.list"),
        icon: "IconPlug",
    },
    ScreenDef {
        code: "admin-doctors",
        label: "Doctors",
        route: "/admin/doctors",
        module: "admin",
        required_permission: Some("admin.users.list"),
        icon: "IconStethoscope",
    },
    ScreenDef {
        code: "admin-devices",
        label: "Devices",
        route: "/admin/devices",
        module: "admin",
        required_permission: Some("admin.devices.list"),
        icon: "IconDevices",
    },
    ScreenDef {
        code: "admin-settings",
        label: "Settings",
        route: "/admin/settings",
        module: "admin",
        required_permission: None,
        icon: "IconSettings",
    },
];
