-- RLS-Posture: mixed (per-table, as dumped)
-- Tenant-Column: tenant_id
-- New-Tables: all
-- Drops: none
-- Consolidated baseline schema.
--
-- This replaces 262 incremental migrations (80,641 lines) that had accumulated
-- 4,195 ALTER TABLE statements and 605 ADD COLUMNs — 84 of those files did
-- nothing but alter what earlier ones had built. Reading the schema meant
-- replaying three hundred files in your head, and a version mismatch in the
-- middle of that chain took the whole backend down (VersionMismatch(143)).
--
-- Generated by pg_dump from a database built by applying all 262 in order, so
-- it is the schema that was actually running rather than a hand-rewrite of it.
-- The equivalence was verified by diffing a database built from this file
-- against one built from the 262 — see scripts/verify_baseline.sh.
--
-- The originals are kept under migrations/archive/ rather than deleted: they
-- are the only record of *why* several columns exist.
--
-- psql meta-commands are stripped. PostgreSQL 18's pg_dump emits \restrict,
-- which psql understands and sqlx — sending SQL straight to the server — does
-- not.

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET transaction_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SELECT pg_catalog.set_config('search_path', '', false);

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';

CREATE TYPE public.accreditation_body AS ENUM (
    'nabh',
    'nmc',
    'nabl',
    'jci',
    'abdm',
    'naac',
    'other'
);

CREATE TYPE public.address_type AS ENUM (
    'current',
    'permanent',
    'correspondence',
    'workplace',
    'temporary'
);

CREATE TYPE public.adherence_event_type AS ENUM (
    'dose_taken',
    'dose_missed',
    'dose_late',
    'refill_on_time',
    'refill_late',
    'refill_missed',
    'appointment_attended',
    'appointment_missed',
    'appointment_rescheduled'
);

CREATE TYPE public.admission_source AS ENUM (
    'er',
    'opd',
    'direct',
    'referral',
    'transfer_in'
);

CREATE TYPE public.admission_status AS ENUM (
    'admitted',
    'transferred',
    'discharged',
    'absconded',
    'deceased'
);

CREATE TYPE public.advance_purpose AS ENUM (
    'admission',
    'prepaid',
    'general',
    'procedure'
);

CREATE TYPE public.advance_status AS ENUM (
    'active',
    'partially_used',
    'fully_used',
    'refunded'
);

CREATE TYPE public.adverse_event_severity AS ENUM (
    'mild',
    'moderate',
    'severe',
    'fatal'
);

CREATE TYPE public.adverse_event_status AS ENUM (
    'draft',
    'submitted',
    'under_review',
    'closed',
    'withdrawn'
);

CREATE TYPE public.allergy_severity AS ENUM (
    'mild',
    'moderate',
    'severe',
    'life_threatening'
);

CREATE TYPE public.allergy_type AS ENUM (
    'drug',
    'food',
    'environmental',
    'latex',
    'contrast_dye',
    'biological',
    'other'
);

CREATE TYPE public.ambulance_maintenance_status AS ENUM (
    'scheduled',
    'in_progress',
    'completed',
    'overdue',
    'cancelled'
);

CREATE TYPE public.ambulance_status AS ENUM (
    'available',
    'on_trip',
    'maintenance',
    'off_duty',
    'decommissioned'
);

CREATE TYPE public.ambulance_trip_priority AS ENUM (
    'critical',
    'urgent',
    'routine'
);

CREATE TYPE public.ambulance_trip_status AS ENUM (
    'requested',
    'dispatched',
    'en_route_pickup',
    'at_pickup',
    'en_route_drop',
    'at_drop',
    'completed',
    'cancelled'
);

CREATE TYPE public.ambulance_trip_type AS ENUM (
    'emergency',
    'scheduled',
    'inter_facility',
    'discharge'
);

CREATE TYPE public.ambulance_type AS ENUM (
    'bls',
    'als',
    'patient_transport',
    'mortuary',
    'neonatal'
);

CREATE TYPE public.anc_risk_category AS ENUM (
    'low',
    'moderate',
    'high',
    'very_high'
);

CREATE TYPE public.anesthesia_type AS ENUM (
    'general',
    'spinal',
    'epidural',
    'regional_block',
    'local',
    'sedation',
    'combined'
);

CREATE TYPE public.antibiotic_action AS ENUM (
    'initiate',
    'escalate',
    'de_escalate',
    'stop'
);

CREATE TYPE public.antibiotic_request_status AS ENUM (
    'pending',
    'approved',
    'denied',
    'expired'
);

CREATE TYPE public.appeal_status AS ENUM (
    'draft',
    'submitted',
    'in_review',
    'upheld',
    'overturned',
    'withdrawn'
);

CREATE TYPE public.appointment_status AS ENUM (
    'scheduled',
    'confirmed',
    'checked_in',
    'in_consultation',
    'completed',
    'cancelled',
    'no_show'
);

CREATE TYPE public.appointment_type AS ENUM (
    'new_visit',
    'follow_up',
    'consultation',
    'procedure',
    'walk_in'
);

CREATE TYPE public.approval_decision_kind AS ENUM (
    'approve',
    'reject',
    'abstain'
);

CREATE TYPE public.approval_request_status AS ENUM (
    'draft',
    'pending',
    'approved',
    'rejected',
    'cancelled',
    'expired',
    'revoked'
);

CREATE TYPE public.approval_step_status AS ENUM (
    'waiting',
    'active',
    'approved',
    'rejected',
    'skipped'
);

CREATE TYPE public.asa_classification AS ENUM (
    'asa_1',
    'asa_2',
    'asa_3',
    'asa_4',
    'asa_5',
    'asa_6'
);

CREATE TYPE public.audit_action AS ENUM (
    'invoice_created',
    'invoice_issued',
    'invoice_cancelled',
    'payment_recorded',
    'payment_voided',
    'refund_created',
    'discount_applied',
    'discount_removed',
    'advance_collected',
    'advance_adjusted',
    'advance_refunded',
    'credit_note_created',
    'credit_note_applied',
    'claim_created',
    'claim_updated',
    'day_closed',
    'write_off_created',
    'write_off_approved',
    'invoice_cloned',
    'journal_entry_posted',
    'tds_deducted',
    'bank_reconciled',
    'gstr_filed',
    'threshold_alert',
    'erp_exported'
);

CREATE TYPE public.bb_billing_status AS ENUM (
    'pending',
    'invoiced',
    'paid',
    'waived'
);

CREATE TYPE public.bb_cold_chain_alert_level AS ENUM (
    'normal',
    'warning',
    'critical'
);

CREATE TYPE public.bb_lookback_status AS ENUM (
    'detected',
    'investigating',
    'notified',
    'closed'
);

CREATE TYPE public.bb_return_status AS ENUM (
    'requested',
    'inspecting',
    'accepted',
    'rejected'
);

CREATE TYPE public.bed_reservation_status AS ENUM (
    'active',
    'confirmed',
    'cancelled',
    'expired',
    'fulfilled'
);

CREATE TYPE public.bed_status AS ENUM (
    'vacant_clean',
    'vacant_dirty',
    'reserved',
    'occupied',
    'occupied_transfer_pending',
    'maintenance',
    'blocked'
);

CREATE TYPE public.bedside_request_status AS ENUM (
    'pending',
    'acknowledged',
    'in_progress',
    'completed',
    'cancelled'
);

CREATE TYPE public.bedside_request_type AS ENUM (
    'nurse_call',
    'pain_management',
    'bathroom_assist',
    'water_food',
    'blanket_pillow',
    'position_change',
    'other'
);

CREATE TYPE public.blood_bag_status AS ENUM (
    'collected',
    'processing',
    'tested',
    'available',
    'reserved',
    'crossmatched',
    'issued',
    'transfused',
    'returned',
    'expired',
    'discarded'
);

CREATE TYPE public.blood_component_type AS ENUM (
    'whole_blood',
    'prbc',
    'ffp',
    'platelets',
    'cryoprecipitate',
    'granulocytes'
);

CREATE TYPE public.blood_group AS ENUM (
    'a_positive',
    'a_negative',
    'b_positive',
    'b_negative',
    'ab_positive',
    'ab_negative',
    'o_positive',
    'o_negative',
    'unknown'
);

CREATE TYPE public.bme_breakdown_priority AS ENUM (
    'critical',
    'high',
    'medium',
    'low'
);

CREATE TYPE public.bme_breakdown_status AS ENUM (
    'reported',
    'acknowledged',
    'in_progress',
    'parts_awaited',
    'resolved',
    'closed'
);

CREATE TYPE public.bme_calibration_status AS ENUM (
    'calibrated',
    'due',
    'overdue',
    'out_of_tolerance',
    'exempted'
);

CREATE TYPE public.bme_contract_type AS ENUM (
    'amc',
    'cmc',
    'warranty',
    'camc'
);

CREATE TYPE public.bme_equipment_status AS ENUM (
    'active',
    'under_maintenance',
    'out_of_service',
    'condemned',
    'disposed'
);

CREATE TYPE public.bme_pm_frequency AS ENUM (
    'monthly',
    'quarterly',
    'semi_annual',
    'annual'
);

CREATE TYPE public.bme_risk_category AS ENUM (
    'critical',
    'high',
    'medium',
    'low'
);

CREATE TYPE public.bme_work_order_status AS ENUM (
    'open',
    'assigned',
    'in_progress',
    'completed',
    'cancelled'
);

CREATE TYPE public.bme_work_order_type AS ENUM (
    'preventive',
    'corrective',
    'calibration',
    'installation',
    'inspection'
);

CREATE TYPE public.body_status AS ENUM (
    'received',
    'cold_storage',
    'inquest_pending',
    'pm_scheduled',
    'pm_completed',
    'released',
    'unclaimed',
    'disposed'
);

CREATE TYPE public.camp_followup_status AS ENUM (
    'scheduled',
    'completed',
    'missed',
    'cancelled'
);

CREATE TYPE public.camp_registration_status AS ENUM (
    'registered',
    'screened',
    'referred',
    'converted',
    'no_show'
);

CREATE TYPE public.camp_status AS ENUM (
    'planned',
    'approved',
    'setup',
    'active',
    'completed',
    'cancelled'
);

CREATE TYPE public.camp_type AS ENUM (
    'general_health',
    'blood_donation',
    'vaccination',
    'eye_screening',
    'dental',
    'awareness',
    'specialized'
);

CREATE TYPE public.capa_status AS ENUM (
    'open',
    'in_progress',
    'completed',
    'verified',
    'overdue'
);

CREATE TYPE public.care_plan_status AS ENUM (
    'active',
    'resolved',
    'discontinued'
);

CREATE TYPE public.case_mgmt_status AS ENUM (
    'assigned',
    'active',
    'pending_discharge',
    'discharged',
    'closed'
);

CREATE TYPE public.cath_device_type AS ENUM (
    'stent',
    'balloon',
    'guidewire',
    'catheter',
    'closure_device',
    'pacemaker',
    'icd',
    'lead',
    'other'
);

CREATE TYPE public.cath_procedure_type AS ENUM (
    'diagnostic_cath',
    'pci',
    'pacemaker',
    'icd',
    'eps',
    'ablation',
    'valve_intervention',
    'structural',
    'peripheral'
);

CREATE TYPE public.charge_source AS ENUM (
    'opd',
    'ipd',
    'lab',
    'pharmacy',
    'procedure',
    'manual',
    'radiology',
    'ot',
    'emergency',
    'diet',
    'cssd',
    'ambulance',
    'consumable'
);

CREATE TYPE public.checklist_phase AS ENUM (
    'sign_in',
    'time_out',
    'sign_out'
);

CREATE TYPE public.chronic_program_type AS ENUM (
    'tb_dots',
    'hiv_art',
    'diabetes',
    'hypertension',
    'ckd',
    'copd',
    'asthma',
    'cancer_chemo',
    'mental_health',
    'epilepsy',
    'thyroid',
    'rheumatic',
    'other'
);

CREATE TYPE public.cleaning_area_type AS ENUM (
    'icu',
    'ward',
    'ot',
    'er',
    'lab',
    'pharmacy',
    'corridor',
    'lobby',
    'washroom',
    'kitchen',
    'general'
);

CREATE TYPE public.cleaning_task_status AS ENUM (
    'pending',
    'assigned',
    'in_progress',
    'completed',
    'verified',
    'rejected'
);

CREATE TYPE public.clinical_assessment_type AS ENUM (
    'morse_fall_scale',
    'braden_scale',
    'gcs',
    'pain_vas',
    'pain_nrs',
    'pain_flacc',
    'barthel_adl',
    'norton_scale',
    'waterlow_score',
    'rass',
    'cam',
    'news2',
    'mews',
    'custom'
);

CREATE TYPE public.cms_content_type AS ENUM (
    'article',
    'quick_post',
    'opinion',
    'case_study',
    'news',
    'event',
    'announcement'
);

CREATE TYPE public.cms_post_status AS ENUM (
    'draft',
    'pending_review',
    'pending_medical_review',
    'approved',
    'published',
    'scheduled',
    'archived'
);

CREATE TYPE public.comm_alert_status AS ENUM (
    'triggered',
    'acknowledged',
    'escalated',
    'resolved',
    'expired'
);

CREATE TYPE public.comm_channel AS ENUM (
    'sms',
    'whatsapp',
    'email',
    'push',
    'ivr',
    'portal'
);

CREATE TYPE public.comm_clinical_priority AS ENUM (
    'routine',
    'urgent',
    'critical',
    'stat'
);

CREATE TYPE public.comm_complaint_source AS ENUM (
    'walk_in',
    'phone',
    'email',
    'portal',
    'kiosk',
    'social_media',
    'google_review'
);

CREATE TYPE public.comm_complaint_status AS ENUM (
    'open',
    'assigned',
    'in_progress',
    'pending_review',
    'resolved',
    'closed',
    'reopened'
);

CREATE TYPE public.comm_feedback_type AS ENUM (
    'bedside',
    'post_discharge',
    'nps',
    'department',
    'kiosk'
);

CREATE TYPE public.comm_message_status AS ENUM (
    'queued',
    'sent',
    'delivered',
    'failed',
    'read'
);

CREATE TYPE public.comm_template_type AS ENUM (
    'appointment_reminder',
    'lab_result',
    'discharge_summary',
    'billing',
    'medication_reminder',
    'follow_up',
    'generic',
    'marketing'
);

CREATE TYPE public.committee_frequency AS ENUM (
    'weekly',
    'biweekly',
    'monthly',
    'quarterly',
    'biannual',
    'annual',
    'as_needed'
);

CREATE TYPE public.compliance_checklist_status AS ENUM (
    'not_started',
    'in_progress',
    'compliant',
    'non_compliant',
    'not_applicable'
);

CREATE TYPE public.compliance_status AS ENUM (
    'compliant',
    'partially_compliant',
    'non_compliant',
    'not_applicable'
);

CREATE TYPE public.concession_status AS ENUM (
    'pending',
    'approved',
    'rejected',
    'auto_applied'
);

CREATE TYPE public.condemnation_status AS ENUM (
    'initiated',
    'committee_review',
    'approved',
    'condemned',
    'rejected'
);

CREATE TYPE public.consent_audit_action AS ENUM (
    'created',
    'granted',
    'denied',
    'signed',
    'refused',
    'withdrawn',
    'revoked',
    'expired',
    'renewed',
    'amended'
);

CREATE TYPE public.consent_capture_mode AS ENUM (
    'paper_signed',
    'digital_signature',
    'biometric',
    'otp_verified',
    'verbal_recorded'
);

CREATE TYPE public.consent_status AS ENUM (
    'granted',
    'denied',
    'withdrawn',
    'pending'
);

CREATE TYPE public.consent_template_category AS ENUM (
    'general',
    'surgical',
    'anesthesia',
    'blood_transfusion',
    'investigation',
    'data_sharing',
    'research',
    'photography',
    'teaching',
    'refusal',
    'advance_directive',
    'organ_donation',
    'communication',
    'custom'
);

CREATE TYPE public.consent_type AS ENUM (
    'general_treatment',
    'data_sharing',
    'abdm_linking',
    'research_participation',
    'sms_communication',
    'email_communication',
    'photography',
    'advance_directive',
    'organ_donation',
    'hie_participation'
);

CREATE TYPE public.consumable_issue_status AS ENUM (
    'issued',
    'returned',
    'billed'
);

CREATE TYPE public.credential_status AS ENUM (
    'active',
    'expired',
    'suspended',
    'revoked',
    'pending_renewal'
);

CREATE TYPE public.credential_type AS ENUM (
    'medical_council',
    'nursing_council',
    'pharmacy_council',
    'dental_council',
    'other_council',
    'bls',
    'acls',
    'pals',
    'nals',
    'fire_safety',
    'radiation_safety',
    'nabh_orientation'
);

CREATE TYPE public.credit_patient_status AS ENUM (
    'active',
    'overdue',
    'suspended',
    'closed'
);

CREATE TYPE public.crossmatch_status AS ENUM (
    'requested',
    'testing',
    'compatible',
    'incompatible',
    'issued',
    'cancelled'
);

CREATE TYPE public.currency_code AS ENUM (
    'INR',
    'USD',
    'EUR',
    'GBP',
    'AED',
    'SAR',
    'SGD',
    'BDT',
    'NPR',
    'LKR'
);

CREATE TYPE public.day_close_status AS ENUM (
    'open',
    'verified',
    'discrepancy'
);

CREATE TYPE public.death_cert_form_type AS ENUM (
    'form_4',
    'form_4a'
);

CREATE TYPE public.delivery_type AS ENUM (
    'normal_vaginal',
    'assisted_vaginal',
    'lscs_elective',
    'lscs_emergency',
    'breech'
);

CREATE TYPE public.department_type AS ENUM (
    'clinical',
    'pre_clinical',
    'para_clinical',
    'administrative',
    'support',
    'academic'
);

CREATE TYPE public.device_instance_status AS ENUM (
    'pending_setup',
    'configuring',
    'testing',
    'active',
    'degraded',
    'disconnected',
    'maintenance',
    'decommissioned'
);

CREATE TYPE public.device_message_status AS ENUM (
    'received',
    'parsed',
    'mapped',
    'validated',
    'delivered',
    'failed',
    'rejected',
    'dead_letter'
);

CREATE TYPE public.device_type AS ENUM (
    'central_line',
    'urinary_catheter',
    'ventilator',
    'arterial_line',
    'peripheral_iv',
    'nasogastric_tube',
    'chest_tube',
    'tracheostomy'
);

CREATE TYPE public.diet_order_status AS ENUM (
    'active',
    'modified',
    'completed',
    'cancelled'
);

CREATE TYPE public.diet_type AS ENUM (
    'regular',
    'diabetic',
    'renal',
    'cardiac',
    'liquid',
    'soft',
    'high_protein',
    'low_sodium',
    'npo',
    'custom'
);

CREATE TYPE public.discharge_barrier_type AS ENUM (
    'insurance_auth',
    'placement',
    'equipment',
    'family',
    'transport',
    'financial',
    'clinical',
    'documentation',
    'other'
);

CREATE TYPE public.discharge_summary_status AS ENUM (
    'draft',
    'finalized'
);

CREATE TYPE public.discharge_type AS ENUM (
    'normal',
    'lama',
    'dama',
    'absconded',
    'referred',
    'deceased',
    'death'
);

CREATE TYPE public.dnr_status AS ENUM (
    'active',
    'expired',
    'revoked'
);

CREATE TYPE public.document_output_status AS ENUM (
    'draft',
    'generated',
    'printed',
    'downloaded',
    'voided',
    'superseded'
);

CREATE TYPE public.document_status AS ENUM (
    'draft',
    'under_review',
    'approved',
    'released',
    'revised',
    'obsolete'
);

CREATE TYPE public.document_template_category AS ENUM (
    'prescription',
    'consultation_summary',
    'discharge_summary',
    'death_certificate',
    'consent_form',
    'lab_report',
    'radiology_report',
    'opd_bill',
    'ipd_bill',
    'receipt',
    'case_sheet_cover',
    'progress_note',
    'nursing_assessment',
    'mar_chart',
    'vitals_chart',
    'surgical_checklist',
    'anesthesia_record',
    'operation_note',
    'employee_id_card',
    'purchase_order',
    'patient_card',
    'wristband',
    'queue_token',
    'bmw_manifest',
    'pcpndt_form_f',
    'mlc_certificate',
    'referral_letter',
    'medical_certificate',
    'fitness_certificate',
    'blood_requisition',
    'diet_chart',
    'investigation_report',
    'transfer_summary',
    'admission_form',
    'against_medical_advice',
    'medico_legal_report',
    'birth_certificate',
    'duty_roster',
    'indent_form',
    'grn_form',
    'custom',
    'visitor_pass',
    'estimate',
    'credit_note',
    'gst_invoice',
    'insurance_form',
    'tds_certificate',
    'package_bill',
    'culture_report',
    'histopathology_report',
    'crossmatch_report',
    'component_issue',
    'patient_education',
    'appointment_slip',
    'interim_bill',
    'pg_logbook',
    'intern_logbook',
    'assessment',
    'certificate',
    'research_form',
    'hostel_form'
);

CREATE TYPE public.donation_type AS ENUM (
    'whole_blood',
    'apheresis_platelets',
    'apheresis_plasma'
);

CREATE TYPE public.drug_screen_status AS ENUM (
    'ordered',
    'collected',
    'sent_to_lab',
    'mro_review',
    'positive',
    'negative',
    'inconclusive',
    'cancelled'
);

CREATE TYPE public.ect_laterality AS ENUM (
    'bilateral',
    'right_unilateral',
    'left_unilateral'
);

CREATE TYPE public.employee_status AS ENUM (
    'active',
    'on_leave',
    'suspended',
    'resigned',
    'terminated',
    'retired',
    'absconding'
);

CREATE TYPE public.employment_type AS ENUM (
    'permanent',
    'contract',
    'visiting',
    'intern',
    'resident',
    'fellow',
    'volunteer',
    'outsourced'
);

CREATE TYPE public.encounter_status AS ENUM (
    'open',
    'in_progress',
    'completed',
    'cancelled'
);

CREATE TYPE public.encounter_type AS ENUM (
    'opd',
    'ipd',
    'emergency'
);

CREATE TYPE public.enrollment_status AS ENUM (
    'active',
    'completed',
    'discontinued',
    'transferred',
    'lost_to_followup',
    'deceased'
);

CREATE TYPE public.er_visit_status AS ENUM (
    'registered',
    'triaged',
    'in_treatment',
    'observation',
    'admitted',
    'discharged',
    'transferred',
    'lama',
    'deceased'
);

CREATE TYPE public.erp_export_status AS ENUM (
    'pending',
    'exported',
    'failed',
    'acknowledged'
);

CREATE TYPE public.facility_status AS ENUM (
    'active',
    'inactive',
    'under_construction',
    'closed'
);

CREATE TYPE public.facility_type AS ENUM (
    'main_hospital',
    'medical_college',
    'dental_college',
    'nursing_college',
    'pharmacy_college',
    'ayush_hospital',
    'research_center',
    'blood_bank',
    'dialysis_center',
    'trauma_center',
    'burn_center',
    'rehabilitation_center',
    'palliative_care',
    'psychiatric_hospital',
    'eye_hospital',
    'maternity_hospital',
    'pediatric_hospital',
    'cancer_center',
    'cardiac_center',
    'neuro_center',
    'ortho_center',
    'day_care_center',
    'diagnostic_center',
    'telemedicine_hub',
    'community_health_center',
    'primary_health_center',
    'sub_center',
    'urban_health_center',
    'mobile_health_unit',
    'other'
);

CREATE TYPE public.field_data_type AS ENUM (
    'text',
    'email',
    'phone',
    'date',
    'datetime',
    'time',
    'select',
    'multiselect',
    'checkbox',
    'radio',
    'textarea',
    'number',
    'decimal',
    'file',
    'hidden',
    'computed',
    'boolean',
    'uuid_fk',
    'json'
);

CREATE TYPE public.financial_class AS ENUM (
    'self_pay',
    'insurance',
    'government_scheme',
    'corporate',
    'charity',
    'research'
);

CREATE TYPE public.fms_drill_type AS ENUM (
    'fire',
    'code_red',
    'evacuation',
    'chemical_spill',
    'bomb_threat'
);

CREATE TYPE public.fms_energy_source_type AS ENUM (
    'grid',
    'dg_set',
    'ups',
    'solar',
    'inverter'
);

CREATE TYPE public.fms_fire_equipment_type AS ENUM (
    'extinguisher_abc',
    'extinguisher_co2',
    'extinguisher_water',
    'hydrant',
    'hose_reel',
    'smoke_detector',
    'heat_detector',
    'sprinkler',
    'fire_alarm_panel',
    'emergency_light'
);

CREATE TYPE public.fms_gas_source_type AS ENUM (
    'psa_plant',
    'lmo_tank',
    'cylinder_manifold',
    'pipeline'
);

CREATE TYPE public.fms_gas_type AS ENUM (
    'oxygen',
    'nitrous_oxide',
    'nitrogen',
    'medical_air',
    'vacuum',
    'co2',
    'heliox'
);

CREATE TYPE public.fms_water_source_type AS ENUM (
    'municipal',
    'borewell',
    'tanker',
    'ro_plant',
    'stp_recycled'
);

CREATE TYPE public.fms_water_test_type AS ENUM (
    'bacteriological',
    'chemical',
    'endotoxin',
    'conductivity'
);

CREATE TYPE public.fms_work_order_status AS ENUM (
    'open',
    'assigned',
    'in_progress',
    'on_hold',
    'completed',
    'cancelled'
);

CREATE TYPE public.form_status AS ENUM (
    'draft',
    'active',
    'deprecated'
);

CREATE TYPE public.gender AS ENUM (
    'male',
    'female',
    'other',
    'unknown'
);

CREATE TYPE public.grn_status AS ENUM (
    'draft',
    'inspecting',
    'accepted',
    'partially_accepted',
    'rejected',
    'completed'
);

CREATE TYPE public.gst_type AS ENUM (
    'cgst_sgst',
    'igst',
    'exempt'
);

CREATE TYPE public.gstr_filing_status AS ENUM (
    'draft',
    'validated',
    'filed',
    'accepted',
    'error'
);

CREATE TYPE public.hai_type AS ENUM (
    'clabsi',
    'cauti',
    'vap',
    'ssi',
    'cdiff',
    'mrsa',
    'other'
);

CREATE TYPE public.hearing_test_type AS ENUM (
    'pta',
    'bera',
    'oae',
    'tympanometry',
    'speech_audiometry'
);

CREATE TYPE public.hemodynamic_site AS ENUM (
    'aorta',
    'lv',
    'rv',
    'ra',
    'la',
    'pa',
    'pcwp',
    'svg',
    'lm',
    'lad',
    'lcx',
    'rca',
    'other'
);

CREATE TYPE public.hld_result AS ENUM (
    'pass',
    'fail',
    'pending'
);

CREATE TYPE public.hospital_type AS ENUM (
    'medical_college',
    'multi_specialty',
    'district_hospital',
    'community_health',
    'primary_health',
    'standalone_clinic',
    'eye_hospital',
    'dental_college'
);

CREATE TYPE public.hygiene_moment AS ENUM (
    'before_patient',
    'before_aseptic',
    'after_body_fluid',
    'after_patient',
    'after_surroundings'
);

CREATE TYPE public.iam_access_request_status AS ENUM (
    'pending',
    'approved',
    'rejected',
    'revoked',
    'expired'
);

CREATE TYPE public.icu_score_type AS ENUM (
    'apache_ii',
    'apache_iv',
    'sofa',
    'gcs',
    'prism',
    'snappe',
    'rass',
    'cam_icu'
);

CREATE TYPE public.identifier_type AS ENUM (
    'aadhaar',
    'pan',
    'voter_id',
    'driving_license',
    'passport',
    'ration_card',
    'ssn',
    'nhs_number',
    'medicare_number',
    'national_id',
    'birth_certificate',
    'employee_id',
    'disability_certificate',
    'abha',
    'abha_address',
    'emirates_id',
    'iqama',
    'uhid_external'
);

CREATE TYPE public.incident_severity AS ENUM (
    'near_miss',
    'minor',
    'moderate',
    'major',
    'sentinel'
);

CREATE TYPE public.incident_status AS ENUM (
    'reported',
    'acknowledged',
    'investigating',
    'rca_complete',
    'capa_assigned',
    'capa_in_progress',
    'closed',
    'reopened'
);

CREATE TYPE public.indicator_frequency AS ENUM (
    'daily',
    'weekly',
    'monthly',
    'quarterly',
    'annually'
);

CREATE TYPE public.indicator_type AS ENUM (
    'chemical',
    'biological'
);

CREATE TYPE public.infection_status AS ENUM (
    'suspected',
    'confirmed',
    'ruled_out'
);

CREATE TYPE public.instrument_status AS ENUM (
    'available',
    'in_use',
    'decontaminating',
    'sterilizing',
    'sterile',
    'damaged',
    'condemned'
);

CREATE TYPE public.insurance_scheme_type AS ENUM (
    'private',
    'cghs',
    'echs',
    'pmjay',
    'esis',
    'state_scheme'
);

CREATE TYPE public.intake_type AS ENUM (
    'oral',
    'iv_fluid',
    'iv_medication',
    'blood_product',
    'enteral_feed',
    'parenteral',
    'irrigation',
    'other'
);

CREATE TYPE public.invoice_status AS ENUM (
    'draft',
    'issued',
    'partially_paid',
    'paid',
    'cancelled',
    'refunded'
);

CREATE TYPE public.ip_type AS ENUM (
    'general',
    'semi_private',
    'private',
    'deluxe',
    'suite',
    'icu',
    'nicu',
    'picu',
    'hdu',
    'isolation',
    'nursery'
);

CREATE TYPE public.ipd_clinical_doc_type AS ENUM (
    'wound_care',
    'central_line',
    'catheter',
    'drain',
    'restraint',
    'transfusion',
    'clinical_pathway',
    'other',
    'elopement_risk',
    'dialysis',
    'endoscopy',
    'chemotherapy',
    'blood_transfusion_checklist'
);

CREATE TYPE public.journal_entry_status AS ENUM (
    'draft',
    'posted',
    'reversed'
);

CREATE TYPE public.journal_entry_type AS ENUM (
    'manual',
    'auto_invoice',
    'auto_payment',
    'auto_refund',
    'auto_write_off',
    'auto_advance'
);

CREATE TYPE public.lab_collection_center_type AS ENUM (
    'hospital',
    'satellite',
    'partner',
    'camp'
);

CREATE TYPE public.lab_dispatch_method AS ENUM (
    'counter',
    'email',
    'sms',
    'whatsapp',
    'portal',
    'courier'
);

CREATE TYPE public.lab_eqas_evaluation AS ENUM (
    'acceptable',
    'marginal',
    'unacceptable',
    'pending'
);

CREATE TYPE public.lab_home_collection_status AS ENUM (
    'scheduled',
    'assigned',
    'in_transit',
    'arrived',
    'collected',
    'returned_to_lab',
    'cancelled'
);

CREATE TYPE public.lab_order_status AS ENUM (
    'ordered',
    'sample_collected',
    'processing',
    'completed',
    'verified',
    'cancelled'
);

CREATE TYPE public.lab_outsource_status AS ENUM (
    'pending_send',
    'sent',
    'result_received',
    'cancelled'
);

CREATE TYPE public.lab_payout_status AS ENUM (
    'pending',
    'approved',
    'paid',
    'cancelled'
);

CREATE TYPE public.lab_phlebotomy_status AS ENUM (
    'waiting',
    'in_progress',
    'completed',
    'skipped'
);

CREATE TYPE public.lab_priority AS ENUM (
    'routine',
    'urgent',
    'stat'
);

CREATE TYPE public.lab_qc_status AS ENUM (
    'accepted',
    'rejected',
    'warning'
);

CREATE TYPE public.lab_report_status AS ENUM (
    'preliminary',
    'final',
    'amended'
);

CREATE TYPE public.lab_result_flag AS ENUM (
    'normal',
    'low',
    'high',
    'critical_low',
    'critical_high',
    'abnormal'
);

CREATE TYPE public.lab_sample_archive_status AS ENUM (
    'stored',
    'retrieved',
    'discarded',
    'expired'
);

CREATE TYPE public.lab_westgard_rule AS ENUM (
    '1_2s',
    '1_3s',
    '2_2s',
    'r_4s',
    '4_1s',
    '10x'
);

CREATE TYPE public.labor_stage AS ENUM (
    'first_latent',
    'first_active',
    'second',
    'third',
    'completed'
);

CREATE TYPE public.leave_status AS ENUM (
    'draft',
    'pending_hod',
    'pending_admin',
    'approved',
    'rejected',
    'cancelled'
);

CREATE TYPE public.leave_type AS ENUM (
    'casual',
    'earned',
    'medical',
    'maternity',
    'paternity',
    'compensatory',
    'study',
    'special',
    'loss_of_pay'
);

CREATE TYPE public.linen_contamination_type AS ENUM (
    'regular',
    'contaminated',
    'isolation'
);

CREATE TYPE public.linen_status AS ENUM (
    'clean',
    'in_use',
    'soiled',
    'washing',
    'condemned'
);

CREATE TYPE public.lms_content_type AS ENUM (
    'text',
    'video',
    'document',
    'slides',
    'scorm',
    'external_link'
);

CREATE TYPE public.lms_enrollment_status AS ENUM (
    'assigned',
    'in_progress',
    'completed',
    'expired',
    'cancelled'
);

CREATE TYPE public.lms_question_type AS ENUM (
    'single_choice',
    'multiple_choice',
    'true_false',
    'fill_blank'
);

CREATE TYPE public.load_status AS ENUM (
    'loading',
    'running',
    'completed',
    'failed'
);

CREATE TYPE public.location_level AS ENUM (
    'campus',
    'building',
    'floor',
    'wing',
    'zone',
    'room',
    'bed',
    'station'
);

CREATE TYPE public.mar_status AS ENUM (
    'scheduled',
    'given',
    'held',
    'refused',
    'missed',
    'self_administered'
);

CREATE TYPE public.marital_status AS ENUM (
    'single',
    'married',
    'divorced',
    'widowed',
    'separated',
    'domestic_partner',
    'unknown'
);

CREATE TYPE public.mass_casualty_status AS ENUM (
    'activated',
    'ongoing',
    'scaling_down',
    'deactivated'
);

CREATE TYPE public.meal_prep_status AS ENUM (
    'pending',
    'preparing',
    'ready',
    'dispatched',
    'delivered'
);

CREATE TYPE public.meal_type AS ENUM (
    'breakfast',
    'morning_snack',
    'lunch',
    'afternoon_snack',
    'dinner',
    'bedtime_snack'
);

CREATE TYPE public.medication_event_type AS ENUM (
    'started',
    'dose_changed',
    'switched',
    'discontinued',
    'resumed',
    'held'
);

CREATE TYPE public.mlc_status AS ENUM (
    'registered',
    'under_investigation',
    'opinion_given',
    'court_pending',
    'closed'
);

CREATE TYPE public.module_status AS ENUM (
    'available',
    'enabled',
    'disabled',
    'coming_soon'
);

CREATE TYPE public.mrd_movement_status AS ENUM (
    'issued',
    'returned',
    'overdue'
);

CREATE TYPE public.mrd_record_status AS ENUM (
    'active',
    'archived',
    'destroyed',
    'missing'
);

CREATE TYPE public.mrd_register_type AS ENUM (
    'birth',
    'death'
);

CREATE TYPE public.ndps_register_action AS ENUM (
    'receipt',
    'dispensed',
    'destroyed',
    'transferred',
    'adjustment'
);

CREATE TYPE public.nursing_shift AS ENUM (
    'morning',
    'afternoon',
    'night'
);

CREATE TYPE public.nursing_task_category AS ENUM (
    'vital_check',
    'wound_care',
    'catheter_care',
    'repositioning',
    'mouth_care',
    'hygiene',
    'mobilization',
    'teaching',
    'drain_care',
    'tracheostomy_care',
    'medication',
    'other'
);

CREATE TYPE public.nursing_task_priority AS ENUM (
    'routine',
    'urgent',
    'stat'
);

CREATE TYPE public.nutrition_route AS ENUM (
    'enteral',
    'parenteral',
    'oral',
    'npo'
);

CREATE TYPE public.order_set_context AS ENUM (
    'general',
    'admission',
    'pre_operative',
    'diagnosis_specific',
    'department_specific'
);

CREATE TYPE public.order_set_item_type AS ENUM (
    'lab',
    'medication',
    'nursing',
    'diet'
);

CREATE TYPE public.ot_booking_status AS ENUM (
    'requested',
    'confirmed',
    'in_progress',
    'completed',
    'cancelled',
    'postponed'
);

CREATE TYPE public.ot_case_priority AS ENUM (
    'elective',
    'urgent',
    'emergency'
);

CREATE TYPE public.ot_consumable_category AS ENUM (
    'surgical_instrument',
    'implant',
    'disposable',
    'suture',
    'drug',
    'blood_product',
    'other'
);

CREATE TYPE public.ot_room_status AS ENUM (
    'available',
    'in_use',
    'cleaning',
    'maintenance',
    'reserved'
);

CREATE TYPE public.outbreak_status AS ENUM (
    'suspected',
    'confirmed',
    'contained',
    'closed'
);

CREATE TYPE public.output_type AS ENUM (
    'urine',
    'drain',
    'nasogastric',
    'vomit',
    'stool',
    'blood_loss',
    'wound_drainage',
    'chest_tube',
    'other'
);

CREATE TYPE public.pa_urgency AS ENUM (
    'standard',
    'urgent',
    'retrospective'
);

CREATE TYPE public.patient_category AS ENUM (
    'general',
    'private',
    'insurance',
    'pmjay',
    'cghs',
    'staff',
    'vip',
    'mlc',
    'esi',
    'corporate',
    'free',
    'charity',
    'research_subject',
    'staff_dependent'
);

CREATE TYPE public.payment_mode AS ENUM (
    'cash',
    'card',
    'upi',
    'bank_transfer',
    'cheque',
    'insurance',
    'credit'
);

CREATE TYPE public.pcpndt_form_status AS ENUM (
    'draft',
    'submitted',
    'registered',
    'expired'
);

CREATE TYPE public.pharmacy_dispensing_type AS ENUM (
    'prescription',
    'otc',
    'discharge',
    'package',
    'emergency'
);

CREATE TYPE public.pharmacy_payment_mode AS ENUM (
    'cash',
    'card',
    'upi',
    'insurance',
    'credit',
    'mixed'
);

CREATE TYPE public.pharmacy_return_status AS ENUM (
    'requested',
    'approved',
    'returned_to_stock',
    'destroyed',
    'rejected'
);

CREATE TYPE public.pharmacy_rx_status AS ENUM (
    'pending_review',
    'approved',
    'rejected',
    'on_hold',
    'dispensing',
    'dispensed',
    'partially_dispensed',
    'cancelled'
);

CREATE TYPE public.po_status AS ENUM (
    'draft',
    'submitted',
    'approved',
    'sent_to_vendor',
    'partially_received',
    'fully_received',
    'closed',
    'cancelled'
);

CREATE TYPE public.postop_recovery_status AS ENUM (
    'in_recovery',
    'stable',
    'shifted_to_ward',
    'shifted_to_icu',
    'discharged'
);

CREATE TYPE public.preop_clearance_status AS ENUM (
    'pending',
    'cleared',
    'not_cleared',
    'conditional'
);

CREATE TYPE public.print_format AS ENUM (
    'a4_portrait',
    'a4_landscape',
    'a5_portrait',
    'a5_landscape',
    'thermal_80mm',
    'thermal_58mm',
    'label_50x25mm',
    'wristband',
    'custom'
);

CREATE TYPE public.print_job_status AS ENUM (
    'queued',
    'printing',
    'completed',
    'failed',
    'cancelled'
);

CREATE TYPE public.prior_auth_status AS ENUM (
    'draft',
    'pending_info',
    'submitted',
    'in_review',
    'approved',
    'partially_approved',
    'denied',
    'expired',
    'cancelled'
);

CREATE TYPE public.progress_note_type AS ENUM (
    'doctor_round',
    'nursing_note',
    'specialist_opinion',
    'dietitian_note',
    'physiotherapy_note',
    'social_worker_note',
    'discharge_note'
);

CREATE TYPE public.psych_admission_category AS ENUM (
    'independent',
    'supported',
    'minor_supported',
    'emergency'
);

CREATE TYPE public.queue_priority AS ENUM (
    'normal',
    'elderly',
    'disabled',
    'pregnant',
    'emergency_referral',
    'vip'
);

CREATE TYPE public.queue_status AS ENUM (
    'waiting',
    'called',
    'in_consultation',
    'completed',
    'no_show',
    'cancelled'
);

CREATE TYPE public.radiology_order_status AS ENUM (
    'ordered',
    'scheduled',
    'in_progress',
    'completed',
    'reported',
    'verified',
    'cancelled'
);

CREATE TYPE public.radiology_priority AS ENUM (
    'routine',
    'urgent',
    'stat'
);

CREATE TYPE public.radiology_report_status AS ENUM (
    'draft',
    'preliminary',
    'final',
    'amended'
);

CREATE TYPE public.radiopharmaceutical_type AS ENUM (
    'diagnostic',
    'therapeutic'
);

CREATE TYPE public.rate_contract_status AS ENUM (
    'draft',
    'active',
    'expired',
    'terminated'
);

CREATE TYPE public.recon_status AS ENUM (
    'unmatched',
    'matched',
    'discrepancy',
    'excluded'
);

CREATE TYPE public.registration_source AS ENUM (
    'walk_in',
    'phone',
    'online_portal',
    'mobile_app',
    'kiosk',
    'referral',
    'ambulance',
    'camp',
    'telemedicine'
);

CREATE TYPE public.registration_type AS ENUM (
    'new',
    'revisit',
    'transfer_in',
    'referral',
    'emergency',
    'camp',
    'telemedicine',
    'pre_registration'
);

CREATE TYPE public.regulatory_level AS ENUM (
    'international',
    'national',
    'state',
    'education'
);

CREATE TYPE public.rehab_discipline AS ENUM (
    'physiotherapy',
    'occupational_therapy',
    'speech_therapy',
    'psychology',
    'prosthetics_orthotics'
);

CREATE TYPE public.requirement_level AS ENUM (
    'optional',
    'recommended',
    'conditional',
    'mandatory'
);

CREATE TYPE public.restraint_check_status AS ENUM (
    'circulation_ok',
    'skin_intact',
    'repositioned',
    'released',
    'escalated'
);

CREATE TYPE public.restraint_type AS ENUM (
    'physical',
    'chemical',
    'seclusion'
);

CREATE TYPE public.retrospective_entry_status AS ENUM (
    'pending',
    'approved',
    'rejected'
);

CREATE TYPE public.rtw_clearance_status AS ENUM (
    'pending_evaluation',
    'cleared_full',
    'cleared_with_restrictions',
    'not_cleared',
    'follow_up_required'
);

CREATE TYPE public.scope_status AS ENUM (
    'available',
    'in_use',
    'reprocessing',
    'quarantine',
    'decommissioned'
);

CREATE TYPE public.screen_type AS ENUM (
    'form',
    'list',
    'detail',
    'composite',
    'wizard',
    'dashboard',
    'calendar',
    'kanban'
);

CREATE TYPE public.sec_access_method AS ENUM (
    'card',
    'biometric',
    'pin',
    'manual'
);

CREATE TYPE public.sec_incident_severity AS ENUM (
    'low',
    'medium',
    'high',
    'critical'
);

CREATE TYPE public.sec_incident_status AS ENUM (
    'reported',
    'investigating',
    'resolved',
    'closed'
);

CREATE TYPE public.sec_patient_tag_type AS ENUM (
    'infant_rfid',
    'wander_guard',
    'elopement_risk'
);

CREATE TYPE public.sec_tag_alert_status AS ENUM (
    'active',
    'alert_triggered',
    'resolved',
    'deactivated'
);

CREATE TYPE public.sec_zone_level AS ENUM (
    'public',
    'general',
    'restricted',
    'high_security',
    'critical'
);

CREATE TYPE public.service_type AS ENUM (
    'consultation',
    'procedure',
    'investigation',
    'surgery',
    'therapy',
    'nursing',
    'support',
    'administrative'
);

CREATE TYPE public.shift_type AS ENUM (
    'morning',
    'afternoon',
    'evening',
    'night',
    'general',
    'split',
    'on_call',
    'custom'
);

CREATE TYPE public.sidecar_trigger AS ENUM (
    'screen_load',
    'screen_exit',
    'form_submit',
    'form_validate',
    'form_save_draft',
    'field_change',
    'row_select',
    'row_action',
    'interval',
    'step_enter',
    'step_leave'
);

CREATE TYPE public.signature_type AS ENUM (
    'pen_on_paper',
    'digital_pen',
    'aadhaar_esign',
    'biometric_thumb',
    'otp',
    'video_consent',
    'verbal_witness'
);

CREATE TYPE public.stemi_pathway_status AS ENUM (
    'door',
    'ecg',
    'cath_lab_activation',
    'arterial_access',
    'balloon_inflation',
    'completed'
);

CREATE TYPE public.sterilization_method AS ENUM (
    'steam',
    'eto',
    'plasma',
    'dry_heat',
    'flash'
);

CREATE TYPE public.stock_transfer_status AS ENUM (
    'requested',
    'approved',
    'dispatched',
    'in_transit',
    'received',
    'cancelled'
);

CREATE TYPE public.storage_tier AS ENUM (
    'hot',
    'cold',
    'archive',
    'deleted'
);

CREATE TYPE public.supplier_payment_status AS ENUM (
    'pending',
    'partially_paid',
    'paid',
    'overdue',
    'disputed'
);

CREATE TYPE public.tax_applicability AS ENUM (
    'taxable',
    'exempt',
    'zero_rated'
);

CREATE TYPE public.tds_status AS ENUM (
    'deducted',
    'deposited',
    'certificate_issued'
);

CREATE TYPE public.training_status AS ENUM (
    'scheduled',
    'in_progress',
    'completed',
    'cancelled',
    'failed'
);

CREATE TYPE public.transfer_status AS ENUM (
    'requested',
    'approved',
    'in_transit',
    'received',
    'cancelled',
    'rejected'
);

CREATE TYPE public.transfer_type AS ENUM (
    'inter_ward',
    'inter_department',
    'inter_hospital'
);

CREATE TYPE public.transfusion_reaction_severity AS ENUM (
    'mild',
    'moderate',
    'severe',
    'fatal'
);

CREATE TYPE public.transport_mode AS ENUM (
    'wheelchair',
    'stretcher',
    'walking',
    'porter',
    'ambulance'
);

CREATE TYPE public.transport_status AS ENUM (
    'requested',
    'assigned',
    'in_transit',
    'completed',
    'cancelled'
);

CREATE TYPE public.triage_level AS ENUM (
    'immediate',
    'emergent',
    'urgent',
    'less_urgent',
    'non_urgent',
    'expectant',
    'unassigned'
);

CREATE TYPE public.ur_decision AS ENUM (
    'approved',
    'denied',
    'pending_info',
    'modified',
    'escalated'
);

CREATE TYPE public.ur_review_type AS ENUM (
    'pre_admission',
    'admission',
    'continued_stay',
    'retrospective'
);

CREATE TYPE public.user_role AS ENUM (
    'super_admin',
    'hospital_admin',
    'doctor',
    'nurse',
    'receptionist',
    'lab_technician',
    'pharmacist',
    'billing_clerk',
    'housekeeping_staff',
    'facilities_manager',
    'audit_officer',
    'quality_officer',
    'occ_health_officer',
    'utilization_reviewer',
    'case_manager',
    'scheduling_admin',
    'mrd_officer',
    'canteen_staff',
    'dietitian',
    'security_guard',
    'biomed_engineer',
    'ambulance_driver',
    'radiology_tech',
    'cssd_technician',
    'blood_bank_tech',
    'front_office_staff',
    'infection_control_officer',
    'procurement_officer',
    'store_keeper',
    'hr_officer',
    'camp_coordinator',
    'insurance_officer',
    'ot_staff'
);

CREATE TYPE public.ved_class AS ENUM (
    'vital',
    'essential',
    'desirable'
);

CREATE TYPE public.vendor_status AS ENUM (
    'active',
    'inactive',
    'blacklisted',
    'pending_approval'
);

CREATE TYPE public.ventilator_mode AS ENUM (
    'cmv',
    'acv',
    'simv',
    'psv',
    'cpap',
    'bipap',
    'hfov',
    'aprv',
    'niv',
    'other'
);

CREATE TYPE public.verification_status AS ENUM (
    'pending',
    'active',
    'inactive',
    'unknown',
    'error'
);

CREATE TYPE public.visitor_category AS ENUM (
    'general',
    'legal_counsel',
    'religious',
    'vip',
    'media',
    'vendor',
    'emergency'
);

CREATE TYPE public.visitor_pass_status AS ENUM (
    'active',
    'expired',
    'revoked'
);

CREATE TYPE public.waste_category AS ENUM (
    'yellow',
    'red',
    'white_translucent',
    'blue',
    'cytotoxic',
    'chemical',
    'radioactive'
);

CREATE TYPE public.watermark_type AS ENUM (
    'none',
    'draft',
    'confidential',
    'copy',
    'duplicate',
    'uncontrolled',
    'sample',
    'cancelled'
);

CREATE TYPE public.widget_type AS ENUM (
    'stat_card',
    'data_table',
    'list',
    'chart',
    'quick_actions',
    'module_embed',
    'form_embed',
    'system_health',
    'custom_html'
);

CREATE TYPE public.workflow_status AS ENUM (
    'pending',
    'in_progress',
    'paused',
    'completed',
    'cancelled',
    'error'
);

CREATE TYPE public.write_off_status AS ENUM (
    'pending',
    'approved',
    'rejected'
);

-- Name: apply_department_rls(regclass, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.apply_department_rls(tbl regclass, dept_col text) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    short_name TEXT := regexp_replace(tbl::text, '^.*\.', '');
    policy_name TEXT := 'dept_scope_' || short_name;
BEGIN
    -- Department policy is additive to tenant isolation; both must pass.
    -- Postgres applies all permissive policies as OR within action, so we
    -- must declare this RESTRICTIVE so it AND-combines with tenant policy.
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', tbl);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', policy_name, tbl);

    EXECUTE format(
        'CREATE POLICY %I ON %s '
        || 'AS RESTRICTIVE '
        || 'USING (check_department_access(%I)) '
        || 'WITH CHECK (check_department_access(%I))',
        policy_name, tbl, dept_col, dept_col
    );
END $$;

CREATE FUNCTION public.apply_tenant_rls(tbl regclass) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    short_name TEXT := regexp_replace(tbl::text, '^.*\.', '');
    policy_name TEXT := 'tenant_isolation_' || short_name;
BEGIN
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', tbl);

    -- Drop existing policy with same name to make this idempotent
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', policy_name, tbl);

    EXECUTE format(
        'CREATE POLICY %I ON %s '
        || 'USING (tenant_id::text = current_setting(''app.tenant_id'', true)) '
        || 'WITH CHECK (tenant_id::text = current_setting(''app.tenant_id'', true))',
        policy_name, tbl
    );
END $$;

CREATE FUNCTION public.apply_tenant_rls_with_global(tbl regclass) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    short_name TEXT := regexp_replace(tbl::text, '^.*\.', '');
    policy_name TEXT := 'tenant_isolation_' || short_name;
BEGIN
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', tbl);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %s', policy_name, tbl);

    EXECUTE format(
        'CREATE POLICY %I ON %s '
        || 'USING (tenant_id IS NULL OR tenant_id::text = current_setting(''app.tenant_id'', true)) '
        || 'WITH CHECK (tenant_id IS NULL OR tenant_id::text = current_setting(''app.tenant_id'', true))',
        policy_name, tbl
    );
END $$;

CREATE FUNCTION public.audit_log_hash_chain() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    last_hash TEXT;
    canonical TEXT;
BEGIN
    -- pg_advisory_xact_lock prevents concurrent inserts for the same
    -- tenant from racing on prev_hash lookup. Cross-tenant chains are
    -- independent so we lock by tenant_id only.
    PERFORM pg_advisory_xact_lock(hashtext('audit_chain'), hashtext(NEW.tenant_id::text));

    SELECT hash INTO last_hash
    FROM audit_log
    WHERE tenant_id = NEW.tenant_id
    ORDER BY created_at DESC, id DESC
    LIMIT 1;

    NEW.prev_hash := COALESCE(last_hash, '');

    -- Build canonical payload — keys sorted, no whitespace.
    canonical := jsonb_build_object(
        'tenant_id',  NEW.tenant_id::text,
        'user_id',    COALESCE(NEW.user_id::text, ''),
        'action',     NEW.action,
        'entity_type', NEW.entity_type,
        'entity_id',  COALESCE(NEW.entity_id::text, ''),
        'old_values', COALESCE(NEW.old_values::text, ''),
        'new_values', COALESCE(NEW.new_values::text, ''),
        'ip_address', COALESCE(NEW.ip_address, ''),
        'created_at', NEW.created_at::text,
        'prev_hash',  NEW.prev_hash
    )::text;

    NEW.hash_input_canonical := canonical;
    NEW.hash := encode(digest(canonical, 'sha256'), 'hex');

    RETURN NEW;
END;
$$;

CREATE FUNCTION public.audit_trigger_func() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_tenant_id     UUID;
    v_user_id       UUID;
    v_ip_address    TEXT;
    v_user_agent    TEXT;
    v_session_id    UUID;
    v_correlation   UUID;
    v_old_values    JSONB;
    v_new_values    JSONB;
    v_entity_id     UUID;
    v_skip          BOOLEAN := false;
BEGIN
    -- Read context from session GUCs (set by application middleware)
    BEGIN
        v_tenant_id := NULLIF(current_setting('app.tenant_id', true), '')::UUID;
    EXCEPTION WHEN OTHERS THEN v_tenant_id := NULL;
    END;
    BEGIN
        v_user_id := NULLIF(current_setting('app.user_id', true), '')::UUID;
    EXCEPTION WHEN OTHERS THEN v_user_id := NULL;
    END;
    BEGIN
        v_ip_address := NULLIF(current_setting('app.ip_address', true), '');
    EXCEPTION WHEN OTHERS THEN v_ip_address := NULL;
    END;
    BEGIN
        v_user_agent := NULLIF(current_setting('app.user_agent', true), '');
    EXCEPTION WHEN OTHERS THEN v_user_agent := NULL;
    END;
    BEGIN
        v_session_id := NULLIF(current_setting('app.session_id', true), '')::UUID;
    EXCEPTION WHEN OTHERS THEN v_session_id := NULL;
    END;
    BEGIN
        v_correlation := NULLIF(current_setting('app.correlation_id', true), '')::UUID;
    EXCEPTION WHEN OTHERS THEN v_correlation := NULL;
    END;

    -- Without tenant context we cannot audit; bail out silently rather
    -- than failing the underlying write.
    IF v_tenant_id IS NULL THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    IF (TG_OP = 'INSERT') THEN
        v_entity_id := (row_to_json(NEW)->>'id')::UUID;
        v_new_values := to_jsonb(NEW);
    ELSIF (TG_OP = 'UPDATE') THEN
        v_entity_id := (row_to_json(NEW)->>'id')::UUID;
        v_old_values := to_jsonb(OLD);
        v_new_values := to_jsonb(NEW);
        -- Skip no-op updates that only changed updated_at
        IF v_old_values - 'updated_at' = v_new_values - 'updated_at' THEN
            v_skip := true;
        END IF;
    ELSIF (TG_OP = 'DELETE') THEN
        v_entity_id := (row_to_json(OLD)->>'id')::UUID;
        v_old_values := to_jsonb(OLD);
    END IF;

    -- HTTP middleware dedup: if we have a correlation_id and an audit row
    -- already exists for this correlation+entity within the last 5s, skip
    IF NOT v_skip AND v_correlation IS NOT NULL THEN
        IF EXISTS (
            SELECT 1 FROM audit_log
            WHERE correlation_id = v_correlation
              AND entity_id IS NOT DISTINCT FROM v_entity_id
              AND entity_type = TG_TABLE_NAME
              AND created_at > now() - INTERVAL '5 seconds'
        ) THEN
            v_skip := true;
        END IF;
    END IF;

    IF NOT v_skip THEN
        INSERT INTO audit_log (
            tenant_id, user_id, action, entity_type, entity_id,
            old_values, new_values, ip_address, user_agent,
            session_id, correlation_id, hash
        ) VALUES (
            v_tenant_id, v_user_id, TG_OP, TG_TABLE_NAME, v_entity_id,
            v_old_values, v_new_values, v_ip_address, v_user_agent,
            v_session_id, v_correlation, NULL
        );
    END IF;

    RETURN COALESCE(NEW, OLD);
END $$;

CREATE FUNCTION public.bump_perm_version_on_group_change() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
BEGIN
    IF NEW.permissions IS DISTINCT FROM OLD.permissions THEN
        UPDATE users SET perm_version = perm_version + 1
        WHERE id IN (SELECT user_id FROM access_group_members WHERE group_id = NEW.id);
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.bump_perm_version_on_membership() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        UPDATE users SET perm_version = perm_version + 1 WHERE id = OLD.user_id;
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        -- Only when the row's effective membership changed (soft-delete/restore or
        -- expiry) — not on unrelated column touches.
        IF NEW.deleted_at IS DISTINCT FROM OLD.deleted_at
            OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
            UPDATE users SET perm_version = perm_version + 1 WHERE id = NEW.user_id;
        END IF;
        RETURN NEW;
    END IF;
    UPDATE users SET perm_version = perm_version + 1 WHERE id = NEW.user_id;
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.bump_perm_version_on_role_change() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
BEGIN
    IF NEW.permissions IS DISTINCT FROM OLD.permissions THEN
        UPDATE users SET perm_version = perm_version + 1
        WHERE tenant_id = NEW.tenant_id AND role::text = NEW.code;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.check_department_access(dept_id uuid) RETURNS boolean
    LANGUAGE plpgsql STABLE
    AS $$
DECLARE
    dept_ids_raw TEXT;
    dept_ids UUID[];
BEGIN
    dept_ids_raw := current_setting('app.user_department_ids', true);
    IF dept_ids_raw IS NULL OR dept_ids_raw = '' OR dept_ids_raw = '{}' THEN
        RETURN TRUE;  -- no restriction
    END IF;
    dept_ids := dept_ids_raw::UUID[];
    RETURN dept_id = ANY(dept_ids) OR dept_id IS NULL;
END;
$$;

CREATE FUNCTION public.ensure_partitions() RETURNS void
    LANGUAGE plpgsql
    AS $_$
DECLARE
    cfg          record;
    is_parent    boolean;
    step         interval;
    name_fmt     text;
    base         date;
    p_start      date;
    p_end        date;
    child        text;
    i            integer;
    cutoff       date;
    child_rec    record;
    child_period date;
BEGIN
    FOR cfg IN SELECT * FROM partition_config LOOP
        -- Only operate on genuine partitioned parents (relkind 'p').
        SELECT (c.relkind = 'p') INTO is_parent
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = cfg.table_name AND n.nspname = 'public';
        IF is_parent IS NOT TRUE THEN
            CONTINUE;
        END IF;

        IF cfg.partition_interval = 'year' THEN
            step := interval '1 year';
            name_fmt := 'YYYY';
            base := date_trunc('year', now())::date;
        ELSE
            step := interval '1 month';
            name_fmt := 'YYYYMM';
            base := date_trunc('month', now())::date;
        END IF;

        -- DEFAULT safety net so an insert never fails for an un-created range.
        child := format('%s_default', cfg.table_name);
        EXECUTE format('CREATE TABLE IF NOT EXISTS %I PARTITION OF %I DEFAULT',
                       child, cfg.table_name);

        -- Current + premake future partitions.
        FOR i IN 0 .. cfg.premake LOOP
            p_start := base + (step * i);
            p_end   := p_start + step;
            child   := format('%s_p%s', cfg.table_name, to_char(p_start, name_fmt));
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                child, cfg.table_name, p_start::text, p_end::text);
        END LOOP;

        -- Retention: retire partitions whose range ends before the cutoff.
        IF cfg.retention_months IS NOT NULL THEN
            cutoff := date_trunc('month', now())::date
                      - make_interval(months => cfg.retention_months);
            FOR child_rec IN
                SELECT c.relname
                FROM pg_inherits inh
                JOIN pg_class c ON c.oid = inh.inhrelid
                JOIN pg_class p ON p.oid = inh.inhparent
                JOIN pg_namespace n ON n.oid = p.relnamespace
                WHERE p.relname = cfg.table_name
                  AND n.nspname = 'public'
                  AND c.relname ~ ('^' || cfg.table_name || '_p[0-9]+$')
            LOOP
                BEGIN
                    IF cfg.partition_interval = 'year' THEN
                        child_period := to_date(right(child_rec.relname, 4), 'YYYY');
                    ELSE
                        child_period := to_date(right(child_rec.relname, 6), 'YYYYMM');
                    END IF;
                EXCEPTION WHEN others THEN
                    CONTINUE;  -- name didn't parse as a period; leave it alone
                END;

                IF (child_period + step) <= cutoff THEN
                    IF cfg.retention_action = 'drop' THEN
                        EXECUTE format('DROP TABLE IF EXISTS %I', child_rec.relname);
                    ELSE
                        EXECUTE format('ALTER TABLE %I DETACH PARTITION %I',
                                       cfg.table_name, child_rec.relname);
                    END IF;
                END IF;
            END LOOP;
        END IF;
    END LOOP;
END;
$_$;

-- Name: FUNCTION ensure_partitions(); Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON FUNCTION public.ensure_partitions() IS 'Pre-creates current + premake future partitions and retires old ones for every table in partition_config. Called daily by the maintenance worker.';

-- Name: next_queue_token_seq(uuid, uuid, date); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.next_queue_token_seq(p_tenant_id uuid, p_department_id uuid, p_date date DEFAULT CURRENT_DATE) RETURNS integer
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_seq INT;
BEGIN
    SELECT COALESCE(MAX(token_seq), 0) + 1 INTO v_seq
    FROM queue_tokens
    WHERE tenant_id = p_tenant_id
      AND department_id = p_department_id
      AND token_date = p_date;
    RETURN v_seq;
END;
$$;

CREATE FUNCTION public.notify_notification_created() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Keep the payload well under Postgres's ~8000-byte NOTIFY limit: the body
    -- is truncated (the full row is always available via the REST feed).
    PERFORM pg_notify(
        'notification_created',
        json_build_object(
            'id', NEW.id,
            'tenant_id', NEW.tenant_id,
            'user_id', NEW.user_id,
            'kind', NEW.kind,
            'title', left(NEW.title, 2000),
            'body', left(NEW.body, 4000),
            'category', NEW.category,
            'entity_type', NEW.entity_type,
            'entity_id', NEW.entity_id,
            'action_url', NEW.action_url
        )::text
    );
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.prevent_camp_physical_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF current_setting('app.allow_physical_delete', true) = 'true' THEN
        RETURN OLD;
    END IF;

    RAISE EXCEPTION 'physical delete is disabled for public.%; set deleted_at/deleted_by/delete_reason instead', TG_TABLE_NAME
        USING ERRCODE = 'check_violation';
END;
$$;

CREATE FUNCTION public.soft_delete_guardrail() RETURNS trigger
    LANGUAGE plpgsql
    AS $_$
DECLARE
    user_uuid uuid;
    set_clause text;
BEGIN
    IF current_setting('app.allow_physical_delete', true) = 'true' THEN
        RETURN OLD;
    END IF;

    user_uuid := NULLIF(current_setting('app.user_id', true), '')::uuid;
    set_clause :=
        'deleted_at = COALESCE(deleted_at, now()), ' ||
        'deleted_by = COALESCE(deleted_by, $1), ' ||
        'delete_reason = COALESCE(delete_reason, $2)';

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = TG_TABLE_SCHEMA
          AND table_name = TG_TABLE_NAME
          AND column_name = 'updated_at'
    ) THEN
        set_clause := set_clause || ', updated_at = now()';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = TG_TABLE_SCHEMA
          AND table_name = TG_TABLE_NAME
          AND column_name = 'is_active'
    ) THEN
        set_clause := set_clause || ', is_active = false';
    END IF;

    EXECUTE format(
        'UPDATE %I.%I SET %s WHERE ctid = $3 AND deleted_at IS NULL',
        TG_TABLE_SCHEMA,
        TG_TABLE_NAME,
        set_clause
    )
    USING user_uuid, 'Soft deleted by database guardrail', OLD.ctid;

    RETURN NULL;
END;
$_$;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE FUNCTION public.update_integration_pipelines_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.update_screen_masters_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.update_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.users_track_deactivation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF OLD.is_active = TRUE AND NEW.is_active = FALSE THEN
        NEW.deactivated_at = COALESCE(NEW.deactivated_at, now());
    ELSIF OLD.is_active = FALSE AND NEW.is_active = TRUE THEN
        NEW.deactivated_at = NULL;
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION public.validate_tenant_db_topology() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.topology IN ('patroni', 'aurora_with_patroni_reads') THEN
        IF NEW.patroni_writer_url IS NULL OR NEW.patroni_reader_url IS NULL THEN
            RAISE EXCEPTION 'topology=%, patroni_writer_url AND patroni_reader_url required',
                            NEW.topology;
        END IF;
    END IF;
    RETURN NEW;
END $$;

-- PostgreSQL database dump complete
--



-- ── reference data ──────────────────────────────────────────────────────
-- Seeded by 9 of the original migrations. A schema-only dump drops these,
-- and a fresh install without them has no countries, states or categories.

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET transaction_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SELECT pg_catalog.set_config('search_path', '', false);

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

-- PostgreSQL database dump complete
--
