-- Seed the device adapter catalog (Device Knowledge Base) with ~28 common
-- Indian-hospital medical devices and their real protocol defaults, so device
-- onboarding has something to look up. Global reference data; idempotent on
-- adapter_code. Protocols: ASTM E1381 (most lab analyzers over RS-232 9600 8N1),
-- HL7 v2 (patient monitors / newer analyzers over TCP MLLP).

INSERT INTO public.device_adapter_catalog
    (adapter_code, manufacturer, manufacturer_code, model, model_code,
     device_category, data_direction, protocol, transport,
     default_port, default_baud_rate, default_ae_title, known_quirks,
     is_verified, adapter_version)
VALUES
-- ── Roche Diagnostics ──
('roche_cobas_c311', 'Roche', 'roche', 'cobas c311', 'cobas_c311',
  'lab_chemistry', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '["8N1 framing", "Sends ENQ before each ASTM frame"]', true, '1.0.0'),
('roche_cobas_c501', 'Roche', 'roche', 'cobas c501', 'cobas_c501',
  'lab_chemistry', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
('roche_cobas_e411', 'Roche', 'roche', 'cobas e411', 'cobas_e411',
  'lab_immunoassay', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
('roche_cobas_h232', 'Roche', 'roche', 'cobas h232', 'cobas_h232',
  'lab_immunoassay', 'producer', 'hl7_v2', 'tcp', 5100, NULL, NULL,
  '[]', true, '1.0.0'),
-- ── Sysmex ──
('sysmex_xn1000', 'Sysmex', 'sysmex', 'XN-1000', 'xn_1000',
  'lab_hematology', 'producer', 'astm_e1381', 'tcp', 12000, NULL, NULL,
  '["Uses ASTM over TCP, not serial"]', true, '1.0.0'),
('sysmex_xn550', 'Sysmex', 'sysmex', 'XN-550', 'xn_550',
  'lab_hematology', 'producer', 'astm_e1381', 'tcp', 12000, NULL, NULL,
  '[]', true, '1.0.0'),
('sysmex_xp100', 'Sysmex', 'sysmex', 'XP-100', 'xp_100',
  'lab_hematology', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
('sysmex_kx21', 'Sysmex', 'sysmex', 'KX-21', 'kx_21',
  'lab_hematology', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '["Older RS-232 only model still common in India"]', true, '1.0.0'),
-- ── Beckman Coulter ──
('beckman_au480', 'Beckman Coulter', 'beckman', 'AU480', 'au480',
  'lab_chemistry', 'producer', 'astm_e1381', 'tcp', 5000, NULL, NULL,
  '[]', true, '1.0.0'),
('beckman_dxh800', 'Beckman Coulter', 'beckman', 'DxH 800', 'dxh_800',
  'lab_hematology', 'producer', 'astm_e1381', 'tcp', 5000, NULL, NULL,
  '[]', true, '1.0.0'),
('beckman_access2', 'Beckman Coulter', 'beckman', 'Access 2', 'access_2',
  'lab_immunoassay', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
-- ── Mindray ──
('mindray_bs240', 'Mindray', 'mindray', 'BS-240', 'bs_240',
  'lab_chemistry', 'producer', 'hl7_v2', 'tcp', 5100, NULL, NULL,
  '[]', true, '1.0.0'),
('mindray_bc5150', 'Mindray', 'mindray', 'BC-5150', 'bc_5150',
  'lab_hematology', 'producer', 'hl7_v2', 'tcp', 5100, NULL, NULL,
  '[]', true, '1.0.0'),
('mindray_bc3000', 'Mindray', 'mindray', 'BC-3000 Plus', 'bc_3000_plus',
  'lab_hematology', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
('mindray_benevision_n1', 'Mindray', 'mindray', 'BeneVision N1', 'benevision_n1',
  'patient_monitor', 'producer', 'hl7_v2', 'tcp', 2575, NULL, NULL,
  '[]', true, '1.0.0'),
-- ── Abbott ──
('abbott_architect_c4000', 'Abbott', 'abbott', 'Architect c4000', 'architect_c4000',
  'lab_chemistry', 'producer', 'astm_e1381', 'tcp', 5000, NULL, NULL,
  '[]', true, '1.0.0'),
('abbott_celldyn_ruby', 'Abbott', 'abbott', 'CELL-DYN Ruby', 'celldyn_ruby',
  'lab_hematology', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
-- ── Siemens Healthineers ──
('siemens_atellica_ch', 'Siemens', 'siemens', 'Atellica CH 930', 'atellica_ch930',
  'lab_chemistry', 'producer', 'hl7_v2', 'tcp', 5101, NULL, NULL,
  '[]', true, '1.0.0'),
('siemens_dimension_exl', 'Siemens', 'siemens', 'Dimension EXL 200', 'dimension_exl200',
  'lab_chemistry', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
-- ── Transasia / Erba Mannheim (India-common) ──
('erba_em200', 'Transasia Erba', 'erba', 'EM 200', 'em_200',
  'lab_chemistry', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '["Very common in Indian mid-size labs"]', true, '1.0.0'),
('erba_xl200', 'Transasia Erba', 'erba', 'XL-200', 'xl_200',
  'lab_chemistry', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
('erba_elite5', 'Transasia Erba', 'erba', 'Elite 5', 'elite_5',
  'lab_hematology', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
-- ── Horiba ──
('horiba_yumizen_h500', 'Horiba', 'horiba', 'Yumizen H500', 'yumizen_h500',
  'lab_hematology', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
('horiba_pentra_c400', 'Horiba', 'horiba', 'Pentra C400', 'pentra_c400',
  'lab_chemistry', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
-- ── Coagulation / Blood gas ──
('werfen_acl_elite_pro', 'Werfen', 'werfen', 'ACL Elite Pro', 'acl_elite_pro',
  'lab_coagulation', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
('stago_sta_compact', 'Stago', 'stago', 'STA Compact Max', 'sta_compact_max',
  'lab_coagulation', 'producer', 'astm_e1381', 'serial', NULL, 9600, NULL,
  '[]', true, '1.0.0'),
('radiometer_abl90', 'Radiometer', 'radiometer', 'ABL90 FLEX', 'abl90_flex',
  'lab_blood_gas', 'producer', 'hl7_v2', 'tcp', 6000, NULL, NULL,
  '[]', true, '1.0.0'),
-- ── Patient monitors / ECG ──
('philips_intellivue_mx450', 'Philips', 'philips', 'IntelliVue MX450', 'intellivue_mx450',
  'patient_monitor', 'producer', 'hl7_v2', 'tcp', 2575, NULL, NULL,
  '["HL7 MLLP framing (0x0B/0x1C0x0D)"]', true, '1.0.0'),
('ge_carescape_b650', 'GE Healthcare', 'ge', 'CARESCAPE B650', 'carescape_b650',
  'patient_monitor', 'producer', 'hl7_v2', 'tcp', 2575, NULL, NULL,
  '[]', true, '1.0.0'),
('nihon_kohden_lifescope', 'Nihon Kohden', 'nihon_kohden', 'Life Scope G9', 'lifescope_g9',
  'patient_monitor', 'producer', 'hl7_v2', 'tcp', 2575, NULL, NULL,
  '[]', true, '1.0.0'),
('ge_mac2000', 'GE Healthcare', 'ge', 'MAC 2000 ECG', 'mac_2000',
  'ecg_machine', 'producer', 'hl7_v2', 'tcp', 9100, NULL, NULL,
  '[]', true, '1.0.0')
ON CONFLICT (adapter_code) DO NOTHING;
