-- Migration 090: Seed 32 print templates into document_templates
-- Idempotent: ON CONFLICT DO NOTHING
-- NOTE: Enum values added in migration 089 (must be committed separately)

-- ══════════════════════════════════════════════════════════
--  SEED 32 PRINT TEMPLATES
--  Skipped if no tenants exist yet (seed runs after migrations)
-- ══════════════════════════════════════════════════════════

-- Only seed templates if a tenant already exists (otherwise seed.rs handles it)
DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM tenants LIMIT 1) THEN
    RAISE NOTICE 'No tenants yet — skipping template seeding (seed.rs will handle it)';
    RETURN;
END IF;

INSERT INTO document_templates (
    tenant_id, code, name, category, module_code, description, version,
    is_active, is_default, print_format, header_layout, body_layout, footer_layout,
    show_logo, show_hospital_name, show_hospital_address, show_hospital_phone,
    show_qr_code, default_watermark, signature_blocks, required_context
) VALUES
((SELECT id FROM tenants LIMIT 1), 'BILL_ESTIMATE', 'Estimate', 'estimate', 'billing',
 'Cost estimate for planned treatment or procedure', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{estimate_number}}", "label": "Estimate No"}, {"field": "{{estimate_date}}", "label": "Date"}, {"field": "{{valid_until}}", "label": "Valid Until"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender"]}, {"rows": [{"field": "{{procedure_name}}", "label": "Procedure/Treatment"}, {"field": "{{doctor_name}}", "label": "Consultant"}, {"field": "{{expected_los}} days", "label": "Expected LOS"}, {"field": "{{room_category}}", "label": "Room Category"}], "type": "key_value"}, {"type": "table", "title": "Estimated Charges", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Description"}, {"field": "{{amount}}", "header": "Amount"}]}, {"rows": [{"bold": true, "field": "{{estimated_total}}", "label": "Estimated Total"}], "type": "summary"}, {"type": "text", "field": "Actual charges may vary. This is an indicative estimate only.", "label": "Note"}]}',
 '{"rows": [{"text": "This estimate is valid for {{validity_days}} days from issue date."}]}',
 true, true, true, true,
 false, 'draft',
 '[{"role": "billing_exec", "label": "Prepared By"}]',
 '{estimate_number,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'BILL_FINAL', 'Final Bill', 'ipd_bill', 'billing',
 'Final consolidated discharge bill', 1, true, false, 'a4_portrait',
 '{"rows": [{"field": "{{invoice_number}}", "label": "Final Bill No"}, {"field": "{{invoice_date}}", "label": "Date"}, {"field": "{{ip_number}}", "label": "IP No"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "ip_number", "age", "gender", "phone"]}, {"rows": [{"field": "{{admission_date}}", "label": "Admission"}, {"field": "{{discharge_date}}", "label": "Discharge"}, {"field": "{{length_of_stay}} days", "label": "LOS"}, {"field": "{{doctor_name}}", "label": "Consultant"}, {"field": "{{diagnosis}}", "label": "Diagnosis"}], "type": "key_value"}, {"type": "table", "title": "Detailed Charges", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{category}}", "header": "Category"}, {"field": "{{description}}", "header": "Description"}, {"field": "{{quantity}}", "header": "Qty"}, {"field": "{{unit_price}}", "header": "Rate"}, {"field": "{{total_price}}", "header": "Amount"}]}, {"rows": [{"field": "{{gross_total}}", "label": "Gross Total"}, {"field": "{{discount}}", "label": "Discount"}, {"field": "{{tax_amount}}", "label": "Tax (GST)"}, {"bold": true, "field": "{{total_amount}}", "label": "Total"}, {"field": "{{advance_paid}}", "label": "Advance Paid"}, {"field": "{{tpa_amount}}", "label": "Insurance/TPA"}, {"bold": true, "field": "{{net_payable}}", "label": "Net Payable"}], "type": "summary"}, {"rows": [{"field": "{{amount_in_words}}", "label": "Amount in Words"}], "type": "key_value"}]}',
 '{"rows": [{"field": "{{cashier_name}}", "label": "Received By"}, {"text": "This is a computer-generated document. No signature required."}]}',
 true, true, true, true,
 true, 'none',
 '[{"role": "cashier", "label": "Billing Executive"}, {"role": "patient", "label": "Patient/Attendant"}]',
 '{invoice_number,patient_id,admission_id}'),
((SELECT id FROM tenants LIMIT 1), 'BILL_INTERIM', 'Interim Bill', 'interim_bill', 'billing',
 'Interim bill for ongoing IPD stay', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{invoice_number}}", "label": "Interim Bill No"}, {"field": "{{invoice_date}}", "label": "Date"}, {"field": "{{ip_number}}", "label": "IP No"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "ip_number", "ward_bed"]}, {"rows": [{"field": "{{admission_date}}", "label": "Admission Date"}, {"field": "{{period_from}} to {{period_to}}", "label": "Bill Period"}, {"field": "{{doctor_name}}", "label": "Consultant"}], "type": "key_value"}, {"type": "table", "title": "Charges to Date", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Description"}, {"field": "{{quantity}}", "header": "Qty"}, {"field": "{{unit_price}}", "header": "Rate"}, {"field": "{{total_price}}", "header": "Amount"}]}, {"rows": [{"field": "{{subtotal}}", "label": "Total to Date"}, {"field": "{{advance_paid}}", "label": "Advance Paid"}, {"bold": true, "field": "{{balance_due}}", "label": "Balance Due"}], "type": "summary"}]}',
 '{"rows": [{"text": "This is an interim bill. Final bill will be generated at discharge."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "cashier", "label": "Prepared By"}]',
 '{invoice_number,patient_id,admission_id}'),
((SELECT id FROM tenants LIMIT 1), 'BILL_IPD', 'IPD Bill', 'ipd_bill', 'billing',
 'Inpatient discharge billing invoice', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{invoice_number}}", "label": "Bill No"}, {"field": "{{invoice_date}}", "label": "Date"}, {"field": "{{ip_number}}", "label": "IP No"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "phone", "ip_number"]}, {"rows": [{"field": "{{admission_date}}", "label": "Admission Date"}, {"field": "{{discharge_date}}", "label": "Discharge Date"}, {"field": "{{ward_bed}}", "label": "Ward/Bed"}, {"field": "{{doctor_name}}", "label": "Consultant"}, {"field": "{{diagnosis}}", "label": "Diagnosis"}], "type": "key_value"}, {"type": "table", "title": "Room Charges", "columns": [{"field": "{{room_type}}", "header": "Room Type"}, {"field": "{{days}}", "header": "Days"}, {"field": "{{rate}}", "header": "Rate/Day"}, {"field": "{{amount}}", "header": "Amount"}]}, {"type": "table", "title": "Service Charges", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Description"}, {"field": "{{quantity}}", "header": "Qty"}, {"field": "{{unit_price}}", "header": "Rate"}, {"field": "{{total_price}}", "header": "Amount"}]}, {"rows": [{"field": "{{subtotal}}", "label": "Subtotal"}, {"field": "{{advance_paid}}", "label": "Advance Paid"}, {"field": "{{discount}}", "label": "Discount"}, {"field": "{{tax_amount}}", "label": "Tax"}, {"bold": true, "field": "{{net_payable}}", "label": "Net Payable"}], "type": "summary"}, {"rows": [{"field": "{{amount_in_words}}", "label": "Amount in Words"}], "type": "key_value"}]}',
 '{"rows": [{"field": "{{cashier_name}}", "label": "Received By"}, {"text": "This is a computer-generated document."}]}',
 true, true, true, true,
 true, 'none',
 '[{"role": "cashier", "label": "Received By"}, {"role": "patient", "label": "Patient/Attendant"}]',
 '{invoice_number,patient_id,admission_id}'),
((SELECT id FROM tenants LIMIT 1), 'BILL_OPD', 'OPD Bill', 'opd_bill', 'billing',
 'Standard outpatient billing invoice', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{invoice_number}}", "label": "Invoice No"}, {"field": "{{invoice_date}}", "label": "Date"}, {"field": "{{payment_mode}}", "label": "Payment Mode"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "phone"]}, {"rows": [{"field": "{{doctor_name}}", "label": "Doctor"}, {"field": "{{department}}", "label": "Department"}], "type": "key_value"}, {"type": "table", "title": "Charges", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Description"}, {"field": "{{quantity}}", "header": "Qty"}, {"field": "{{unit_price}}", "header": "Rate"}, {"field": "{{total_price}}", "header": "Amount"}]}, {"rows": [{"field": "{{subtotal}}", "label": "Subtotal"}, {"field": "{{discount}}", "label": "Discount"}, {"field": "{{tax_amount}}", "label": "Tax"}, {"bold": true, "field": "{{total_amount}}", "label": "Total"}], "type": "summary"}, {"rows": [{"field": "{{amount_in_words}}", "label": "Amount in Words"}], "type": "key_value"}]}',
 '{"rows": [{"field": "{{cashier_name}}", "label": "Received By"}, {"text": "This is a computer-generated document."}]}',
 true, true, true, true,
 true, 'none',
 '[{"role": "cashier", "label": "Received By"}, {"role": "patient", "label": "Patient/Attendant"}]',
 '{invoice_number,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'BILL_PACKAGE', 'Package Bill', 'package_bill', 'billing',
 'Bill for packaged treatment/procedure', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{invoice_number}}", "label": "Bill No"}, {"field": "{{invoice_date}}", "label": "Date"}, {"field": "{{package_name}}", "label": "Package"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "ip_number", "age", "gender"]}, {"rows": [{"field": "{{package_name}}", "label": "Package Name"}, {"field": "{{package_code}}", "label": "Package Code"}, {"field": "{{doctor_name}}", "label": "Consultant"}, {"field": "{{admission_date}}", "label": "Admission"}, {"field": "{{discharge_date}}", "label": "Discharge"}], "type": "key_value"}, {"type": "table", "title": "Package Inclusions", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Item"}, {"field": "{{included}}", "header": "Included"}]}, {"type": "table", "title": "Additional Charges (Non-Package)", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Description"}, {"field": "{{amount}}", "header": "Amount"}]}, {"rows": [{"field": "{{package_amount}}", "label": "Package Amount"}, {"field": "{{additional_charges}}", "label": "Additional Charges"}, {"bold": true, "field": "{{total_amount}}", "label": "Total"}], "type": "summary"}, {"rows": [{"field": "{{amount_in_words}}", "label": "Amount in Words"}], "type": "key_value"}]}',
 '{"rows": [{"field": "{{cashier_name}}", "label": "Received By"}]}',
 true, true, true, true,
 true, 'none',
 '[{"role": "cashier", "label": "Received By"}, {"role": "patient", "label": "Patient/Attendant"}]',
 '{invoice_number,patient_id,package_id}'),
((SELECT id FROM tenants LIMIT 1), 'CREDIT_NOTE', 'Credit Note', 'credit_note', 'billing',
 'Credit note against original invoice', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{credit_note_number}}", "label": "Credit Note No"}, {"field": "{{date}}", "label": "Date"}, {"field": "{{original_invoice}}", "label": "Against Invoice"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid"]}, {"rows": [{"field": "{{original_invoice}}", "label": "Original Invoice"}, {"field": "{{original_date}}", "label": "Original Date"}, {"field": "{{reason}}", "label": "Reason"}], "type": "key_value"}, {"type": "table", "title": "Adjusted Items", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Description"}, {"field": "{{original_amount}}", "header": "Original Amt"}, {"field": "{{credit_amount}}", "header": "Credit Amt"}]}, {"rows": [{"bold": true, "field": "{{total_credit}}", "label": "Total Credit"}], "type": "summary"}]}',
 '{"rows": [{"field": "{{authorized_by}}", "label": "Authorized By"}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "billing_manager", "label": "Authorized By"}]',
 '{credit_note_number,original_invoice}'),
((SELECT id FROM tenants LIMIT 1), 'GST_INVOICE', 'GST Invoice', 'gst_invoice', 'billing',
 'GST-compliant tax invoice', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{invoice_number}}", "label": "Invoice No"}, {"field": "{{invoice_date}}", "label": "Date"}, {"field": "{{place_of_supply}}", "label": "Place of Supply"}]}',
 '{"sections": [{"rows": [{"field": "{{hospital_gstin}}", "label": "Hospital GSTIN"}, {"field": "{{sac_code}}", "label": "SAC Code"}, {"field": "{{state}}", "label": "State"}], "type": "key_value"}, {"type": "patient_info", "fields": ["patient_name", "uhid", "phone"]}, {"rows": [{"field": "{{patient_gstin}}", "label": "Patient GSTIN", "optional": true}], "type": "key_value"}, {"type": "table", "title": "Taxable Items", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Description"}, {"field": "{{sac_code}}", "header": "SAC"}, {"field": "{{quantity}}", "header": "Qty"}, {"field": "{{unit_price}}", "header": "Rate"}, {"field": "{{taxable_value}}", "header": "Taxable Value"}, {"field": "{{cgst}}", "header": "CGST"}, {"field": "{{sgst}}", "header": "SGST"}, {"field": "{{igst}}", "header": "IGST"}, {"field": "{{total}}", "header": "Total"}]}, {"rows": [{"field": "{{taxable_total}}", "label": "Taxable Amount"}, {"field": "{{cgst_total}}", "label": "CGST"}, {"field": "{{sgst_total}}", "label": "SGST"}, {"field": "{{igst_total}}", "label": "IGST"}, {"field": "{{round_off}}", "label": "Round Off"}, {"bold": true, "field": "{{grand_total}}", "label": "Grand Total"}], "type": "summary"}, {"rows": [{"field": "{{amount_in_words}}", "label": "Amount in Words"}, {"field": "{{hsn_summary}}", "label": "HSN/SAC Summary"}], "type": "key_value"}]}',
 '{"rows": [{"text": "This is a computer-generated GST invoice and does not require a physical signature."}, {"field": "", "label": "E&OE"}]}',
 true, true, true, true,
 true, 'none',
 '[{"role": "authorized_signatory", "label": "For {{hospital_name}}"}]',
 '{invoice_number,hospital_gstin}'),
((SELECT id FROM tenants LIMIT 1), 'INSURANCE_CASHLESS', 'Cashless Claim Form', 'insurance_form', 'billing',
 'Final cashless claim settlement form for TPA', 1, true, false, 'a4_portrait',
 '{"rows": [{"field": "{{claim_number}}", "label": "Claim No"}, {"field": "{{preauth_number}}", "label": "Pre-Auth No"}, {"field": "{{date}}", "label": "Date"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "ip_number", "age", "gender"]}, {"rows": [{"field": "{{insurance_company}}", "label": "Insurance Co"}, {"field": "{{tpa_name}}", "label": "TPA"}, {"field": "{{policy_number}}", "label": "Policy No"}, {"field": "{{preauth_amount}}", "label": "Pre-Auth Amount"}], "type": "key_value"}, {"rows": [{"field": "{{admission_date}}", "label": "Admission Date"}, {"field": "{{discharge_date}}", "label": "Discharge Date"}, {"field": "{{diagnosis}}", "label": "Final Diagnosis"}, {"field": "{{procedure}}", "label": "Procedure Done"}], "type": "key_value"}, {"type": "table", "title": "Final Bill Breakup", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{category}}", "header": "Category"}, {"field": "{{amount}}", "header": "Amount"}]}, {"rows": [{"field": "{{total_bill}}", "label": "Total Bill"}, {"field": "{{approved_amount}}", "label": "Approved Amount"}, {"bold": true, "field": "{{patient_share}}", "label": "Patient Share"}], "type": "summary"}]}',
 '{"rows": [{"field": "{{doctor_name}}", "label": "Treating Doctor"}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "doctor", "label": "Treating Doctor"}, {"role": "insurance_desk", "label": "Insurance Coordinator"}, {"role": "patient", "label": "Patient/Attendant"}]',
 '{claim_number,patient_id,admission_id}'),
((SELECT id FROM tenants LIMIT 1), 'INSURANCE_PREAUTH', 'Insurance Pre-Auth Form', 'insurance_form', 'billing',
 'Pre-authorization request for insurance/TPA', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{preauth_number}}", "label": "Pre-Auth No"}, {"field": "{{date}}", "label": "Date"}, {"field": "{{urgency}}", "label": "Priority"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "phone"]}, {"rows": [{"field": "{{insurance_company}}", "label": "Insurance Company"}, {"field": "{{policy_number}}", "label": "Policy No"}, {"field": "{{tpa_name}}", "label": "TPA Name"}, {"field": "{{member_id}}", "label": "Member ID"}, {"field": "{{sum_insured}}", "label": "Sum Insured"}], "type": "key_value"}, {"rows": [{"field": "{{diagnosis}}", "label": "Provisional Diagnosis"}, {"field": "{{icd_code}}", "label": "ICD Code"}, {"field": "{{procedure}}", "label": "Planned Procedure"}, {"field": "{{expected_los}}", "label": "Expected LOS"}, {"field": "{{room_category}}", "label": "Room Category"}], "type": "key_value"}, {"type": "table", "title": "Estimated Cost Breakup", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{description}}", "header": "Item"}, {"field": "{{amount}}", "header": "Amount"}]}, {"rows": [{"bold": true, "field": "{{total_estimate}}", "label": "Total Estimated Cost"}, {"bold": true, "field": "{{requested_amount}}", "label": "Pre-Auth Amount Requested"}], "type": "summary"}]}',
 '{"rows": [{"field": "{{doctor_name}}", "label": "Treating Doctor"}, {"field": "{{doctor_reg_no}}", "label": "Registration No"}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "doctor", "label": "Treating Doctor"}, {"role": "insurance_desk", "label": "Insurance Coordinator"}]',
 '{preauth_number,patient_id,insurance_id}'),
((SELECT id FROM tenants LIMIT 1), 'RECEIPT_ADVANCE', 'Advance Receipt', 'receipt', 'billing',
 'Receipt for advance payment', 1, true, true, 'a5_portrait',
 '{"rows": [{"field": "{{receipt_number}}", "label": "Receipt No"}, {"field": "{{receipt_date}}", "label": "Date"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "ip_number"]}, {"rows": [{"bold": true, "field": "{{amount}}", "label": "Amount Received"}, {"field": "{{payment_mode}}", "label": "Payment Mode"}, {"field": "{{payment_reference}}", "label": "Reference"}, {"field": "{{amount_in_words}}", "label": "Amount in Words"}, {"field": "{{purpose}}", "label": "Against"}, {"field": "{{previous_advance}}", "label": "Previous Advance"}, {"field": "{{total_advance}}", "label": "Total Advance"}], "type": "key_value"}]}',
 '{"rows": [{"field": "{{cashier_name}}", "label": "Received By"}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "cashier", "label": "Received By"}]',
 '{receipt_number,patient_id,amount}'),
((SELECT id FROM tenants LIMIT 1), 'RECEIPT_REFUND', 'Refund Receipt', 'receipt', 'billing',
 'Receipt for refund issued to patient', 1, true, false, 'a5_portrait',
 '{"rows": [{"field": "{{refund_number}}", "label": "Refund No"}, {"field": "{{refund_date}}", "label": "Date"}, {"field": "{{original_receipt}}", "label": "Original Receipt"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid"]}, {"rows": [{"bold": true, "field": "{{amount}}", "label": "Refund Amount"}, {"field": "{{reason}}", "label": "Reason"}, {"field": "{{refund_mode}}", "label": "Mode"}, {"field": "{{payment_reference}}", "label": "Reference"}, {"field": "{{amount_in_words}}", "label": "Amount in Words"}], "type": "key_value"}]}',
 '{"rows": [{"field": "{{authorized_by}}", "label": "Authorized By"}, {"field": "{{cashier_name}}", "label": "Paid By"}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "cashier", "label": "Paid By"}, {"role": "authorizer", "label": "Authorized By"}, {"role": "patient", "label": "Received By (Patient)"}]',
 '{refund_number,patient_id,amount}'),
((SELECT id FROM tenants LIMIT 1), 'TDS_CERTIFICATE', 'TDS Certificate', 'tds_certificate', 'billing',
 'TDS deduction certificate for consultants', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{certificate_number}}", "label": "Certificate No"}, {"field": "{{financial_year}}", "label": "Financial Year"}, {"field": "{{quarter}}", "label": "Quarter"}]}',
 '{"sections": [{"rows": [{"field": "{{hospital_name}}", "label": "Deductor Name"}, {"field": "{{tan_number}}", "label": "TAN"}, {"field": "{{deductor_pan}}", "label": "PAN"}], "type": "key_value"}, {"rows": [{"field": "{{deductee_name}}", "label": "Deductee Name"}, {"field": "{{deductee_pan}}", "label": "PAN"}, {"field": "{{tds_section}}", "label": "Section"}], "type": "key_value"}, {"type": "table", "title": "TDS Details", "columns": [{"field": "{{quarter}}", "header": "Quarter"}, {"field": "{{gross_amount}}", "header": "Gross Payment"}, {"field": "{{tds_rate}}", "header": "TDS Rate"}, {"field": "{{tds_amount}}", "header": "TDS Amount"}]}, {"rows": [{"field": "{{total_payment}}", "label": "Total Payment"}, {"bold": true, "field": "{{total_tds}}", "label": "Total TDS Deducted"}], "type": "summary"}]}',
 '{"rows": [{"text": "Certified that TDS has been deposited to the credit of the Central Government."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "authorized_signatory", "label": "Authorized Signatory"}]',
 '{certificate_number,deductee_pan,financial_year}'),
((SELECT id FROM tenants LIMIT 1), 'BB_COMPONENT_ISSUE', 'Component Issue Slip', 'component_issue', 'blood_bank',
 'Blood component issue slip for transfusion', 1, true, true, 'a5_portrait',
 '{"rows": [{"field": "{{issue_number}}", "label": "Issue No"}, {"field": "{{issue_datetime}}", "label": "Date/Time"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "ward_bed", "blood_group"]}, {"rows": [{"field": "{{component_type}}", "label": "Component"}, {"field": "{{bag_number}}", "label": "Bag No"}, {"field": "{{volume_ml}} ml", "label": "Volume"}, {"field": "{{collection_date}}", "label": "Collected On"}, {"field": "{{expiry_date}}", "label": "Expiry"}, {"field": "{{crossmatch_result}}", "label": "Cross-Match"}], "type": "key_value"}, {"bold": true, "type": "text", "field": "{{instructions}}", "label": "Special Instructions"}]}',
 '{"rows": [{"text": "Check: Patient ID band → Bag label → Blood group. Two-person verification required."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "blood_bank", "label": "Issued By"}, {"role": "nurse", "label": "Received By (Ward)"}]',
 '{issue_number,patient_id,bag_number}'),
((SELECT id FROM tenants LIMIT 1), 'BB_CROSSMATCH', 'Blood Bank Cross-Match Report', 'crossmatch_report', 'blood_bank',
 'Cross-match compatibility report', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{report_number}}", "label": "Report No"}, {"field": "{{report_date}}", "label": "Date"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "ward_bed"]}, {"rows": [{"field": "{{patient_blood_group}}", "label": "Blood Group"}, {"field": "{{patient_rh}}", "label": "Rh Type"}, {"field": "{{antibody_screen}}", "label": "Antibody Screen"}], "type": "key_value"}, {"type": "table", "title": "Cross-Match Results", "columns": [{"field": "{{bag_number}}", "header": "Bag No"}, {"field": "{{component}}", "header": "Component"}, {"field": "{{donor_blood_group}}", "header": "Blood Group"}, {"field": "{{crossmatch_result}}", "header": "Cross-Match"}, {"field": "{{expiry_date}}", "header": "Expiry"}]}, {"type": "text", "field": "{{remarks}}", "label": "Remarks"}]}',
 '{"rows": [{"text": "Transfuse within 72 hours of cross-match. Verify patient identity before transfusion."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "technician", "label": "Blood Bank Technician"}, {"role": "medical_officer", "label": "Blood Bank Medical Officer", "registration": true}]',
 '{report_number,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'VISITOR_PASS', 'Visitor Pass', 'visitor_pass', 'front_office',
 'Visitor identification pass for hospital entry', 1, true, true, 'a5_portrait',
 '{"rows": [{"field": "{{pass_number}}", "label": "Pass No"}, {"field": "{{date}}", "label": "Date"}]}',
 '{"sections": [{"type": "text", "align": "center", "field": "VISITOR PASS", "style": "jumbo"}, {"rows": [{"field": "{{visitor_name}}", "label": "Visitor Name"}, {"field": "{{id_type}}: {{id_number}}", "label": "ID Proof"}, {"field": "{{phone}}", "label": "Phone"}, {"field": "{{patient_name}} ({{uhid}})", "label": "Visiting"}, {"field": "{{ward_bed}}", "label": "Ward/Room"}, {"field": "{{relationship}}", "label": "Relation"}], "type": "key_value"}, {"rows": [{"field": "{{valid_from}}", "label": "Valid From"}, {"field": "{{valid_until}}", "label": "Valid Until"}, {"field": "{{allowed_area}}", "label": "Allowed Area"}], "type": "key_value"}, {"type": "barcode", "field": "{{pass_number}}", "format": "qr"}]}',
 '{"rows": [{"text": "This pass must be worn visibly at all times. Return at exit gate."}]}',
 true, true, false, true,
 false, 'none',
 NULL,
 '{visitor_id,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'DEATH_CERTIFICATE', 'Death Certificate Form 4/4A', 'death_certificate', 'ipd',
 'Death certificate as per Registration of Births and Deaths Act', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{certificate_number}}", "label": "Certificate No"}, {"field": "{{date}}", "label": "Date"}]}',
 '{"sections": [{"rows": [{"bold": true, "field": "{{patient_name}}", "label": "Name of Deceased"}, {"field": "{{uhid}}", "label": "UHID"}, {"field": "{{age}}", "label": "Age"}, {"field": "{{gender}}", "label": "Gender"}, {"field": "{{father_husband_name}}", "label": "Father/Husband Name"}, {"field": "{{address}}", "label": "Address"}], "type": "key_value"}, {"rows": [{"field": "{{date_of_death}}", "label": "Date of Death"}, {"field": "{{time_of_death}}", "label": "Time of Death"}, {"field": "{{place_of_death}}", "label": "Place of Death"}, {"field": "{{cause_immediate}}", "label": "Cause of Death (Immediate)"}, {"field": "{{cause_antecedent}}", "label": "Antecedent Cause"}, {"field": "{{cause_other}}", "label": "Other Conditions"}, {"field": "{{manner_of_death}}", "label": "Manner of Death"}, {"field": "{{is_mlc}}", "label": "MLC"}, {"field": "{{pregnancy_related}}", "label": "Pregnancy Related"}], "type": "key_value"}, {"rows": [{"field": "{{icd_code}}", "label": "ICD-10 Code"}, {"field": "{{hospital_stay}}", "label": "Duration of Hospital Stay"}], "type": "key_value"}]}',
 '{"rows": [{"text": "Issued under Section 10/10A of Registration of Births and Deaths Act, 1969."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "doctor", "label": "Medical Officer (Certifying)", "registration": true}, {"role": "witness", "label": "Witness"}]',
 '{patient_id,death_record_id}'),
((SELECT id FROM tenants LIMIT 1), 'RX_IPD_CHART', 'IPD Treatment Chart', 'prescription', 'ipd',
 'Inpatient medication administration record (MAR)', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{ip_number}}", "label": "IP No"}, {"field": "{{chart_date}}", "label": "Date"}, {"field": "{{ward_bed}}", "label": "Ward/Bed"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "blood_group", "allergies", "weight_kg"]}, {"rows": [{"field": "{{doctor_name}}", "label": "Consultant"}, {"field": "{{diagnosis}}", "label": "Diagnosis"}, {"field": "{{diet_order}}", "label": "Diet"}], "type": "key_value"}, {"type": "table", "title": "Medications", "columns": [{"field": "{{drug_name}}", "header": "Drug"}, {"field": "{{dose}}", "header": "Dose"}, {"field": "{{route}}", "header": "Route"}, {"field": "{{frequency}}", "header": "Freq"}, {"field": "{{slot_06}}", "header": "06:00"}, {"field": "{{slot_10}}", "header": "10:00"}, {"field": "{{slot_14}}", "header": "14:00"}, {"field": "{{slot_18}}", "header": "18:00"}, {"field": "{{slot_22}}", "header": "22:00"}]}, {"type": "table", "title": "IV Fluids", "columns": [{"field": "{{fluid_name}}", "header": "Fluid"}, {"field": "{{volume}}", "header": "Volume"}, {"field": "{{rate}}", "header": "Rate"}, {"field": "{{start_time}}", "header": "Start"}, {"field": "{{end_time}}", "header": "End"}]}, {"type": "table", "title": "PRN Medications", "columns": [{"field": "{{drug_name}}", "header": "Drug"}, {"field": "{{dose}}", "header": "Dose"}, {"field": "{{indication}}", "header": "Indication"}, {"field": "{{given_at}}", "header": "Given At"}, {"field": "{{nurse_initials}}", "header": "By"}]}]}',
 '{"rows": [{"text": "5 Rights: Right Patient, Drug, Dose, Route, Time"}]}',
 true, true, false, true,
 false, 'none',
 '[{"role": "doctor", "label": "Prescribing Doctor"}, {"role": "nurse", "label": "Administering Nurse"}]',
 '{admission_id,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'TRANSFER_SUMMARY', 'Transfer Summary', 'transfer_summary', 'ipd',
 'Inter-hospital or inter-ward transfer summary', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{transfer_number}}", "label": "Transfer No"}, {"field": "{{transfer_date}}", "label": "Date"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "blood_group", "allergies"]}, {"rows": [{"field": "{{from_location}}", "label": "From"}, {"field": "{{to_location}}", "label": "To"}, {"field": "{{transfer_reason}}", "label": "Reason"}, {"field": "{{condition}}", "label": "Condition at Transfer"}], "type": "key_value"}, {"rows": [{"field": "{{diagnosis}}", "label": "Diagnosis"}, {"field": "{{key_findings}}", "label": "Key Findings"}, {"field": "{{treatment_given}}", "label": "Treatment Given"}, {"field": "{{pending_investigations}}", "label": "Pending Investigations"}], "type": "key_value"}, {"type": "table", "title": "Current Medications", "columns": [{"field": "{{drug_name}}", "header": "Drug"}, {"field": "{{dose}}", "header": "Dose"}, {"field": "{{route}}", "header": "Route"}, {"field": "{{frequency}}", "header": "Frequency"}]}, {"rows": [{"field": "{{instructions}}", "label": "Special Instructions"}, {"field": "{{monitoring}}", "label": "Monitoring Required"}], "type": "key_value"}]}',
 '{"rows": [{"text": "Ensure continuity of care. Handover bedside."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "sending_doctor", "label": "Sending Doctor"}, {"role": "receiving_doctor", "label": "Receiving Doctor"}, {"role": "nurse", "label": "Transfer Nurse"}]',
 '{patient_id,admission_id}'),
((SELECT id FROM tenants LIMIT 1), 'WRISTBAND_IPD', 'IPD Wristband', 'wristband', 'ipd',
 'Patient identification wristband for inpatients', 1, true, true, 'wristband',
 NULL,
 '{"sections": [{"type": "text", "field": "{{patient_name}}", "style": "bold"}, {"rows": [{"field": "{{uhid}}", "label": "UHID"}, {"field": "{{ip_number}}", "label": "IP No"}, {"field": "{{dob}}", "label": "DOB"}, {"field": "{{blood_group}}", "label": "Blood Grp"}, {"field": "{{allergies}}", "label": "Allergies"}], "type": "key_value"}, {"type": "barcode", "field": "{{uhid}}", "format": "code128"}]}',
 NULL,
 false, false, false, false,
 false, 'none',
 NULL,
 '{patient_id,admission_id}'),
((SELECT id FROM tenants LIMIT 1), 'WRISTBAND_NICU', 'NICU Wristband', 'wristband', 'ipd',
 'Neonatal ICU wristband with mother reference', 1, true, false, 'wristband',
 NULL,
 '{"sections": [{"type": "text", "field": "Baby of {{mother_name}}", "style": "bold"}, {"rows": [{"field": "{{baby_uhid}}", "label": "UHID"}, {"field": "{{mother_uhid}}", "label": "Mother UHID"}, {"field": "{{dob}}", "label": "DOB"}, {"field": "{{birth_time}}", "label": "Time"}, {"field": "{{gender}}", "label": "Gender"}, {"field": "{{birth_weight}} g", "label": "Weight"}, {"field": "{{blood_group}}", "label": "Blood Grp"}], "type": "key_value"}, {"type": "barcode", "field": "{{baby_uhid}}", "format": "code128"}]}',
 NULL,
 false, false, false, false,
 false, 'none',
 NULL,
 '{patient_id,mother_patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'LAB_CULTURE', 'Culture Sensitivity Report', 'culture_report', 'lab',
 'Microbiology culture and antibiotic sensitivity report', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{lab_number}}", "label": "Lab No"}, {"field": "{{report_date}}", "label": "Date"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "ward_bed"]}, {"rows": [{"field": "{{sample_type}}", "label": "Sample Type"}, {"field": "{{collection_time}}", "label": "Collected"}, {"field": "{{method}}", "label": "Culture Method"}], "type": "key_value"}, {"rows": [{"field": "{{organism}}", "label": "Organism Isolated"}, {"field": "{{colony_count}}", "label": "Colony Count"}, {"field": "{{gram_stain}}", "label": "Gram Stain"}], "type": "key_value"}, {"type": "table", "title": "Antibiotic Sensitivity", "columns": [{"field": "{{antibiotic}}", "header": "Antibiotic"}, {"field": "{{mic}}", "header": "MIC"}, {"field": "{{sensitivity}}", "header": "Interpretation"}]}, {"type": "text", "field": "{{comments}}", "label": "Comments"}]}',
 '{"rows": [{"text": "S=Sensitive, I=Intermediate, R=Resistant. AWaRe classification shown where applicable."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "microbiologist", "label": "Microbiologist", "registration": true}]',
 '{lab_order_id,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'LAB_CUMULATIVE', 'Cumulative Lab Report', 'lab_report', 'lab',
 'Cumulative report showing test trends over time', 1, true, false, 'a4_portrait',
 '{"rows": [{"field": "{{report_date}}", "label": "Report Date"}, {"field": "{{period_from}} to {{period_to}}", "label": "Period"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender"]}, {"type": "table", "title": "Cumulative Results", "columns": [{"field": "{{test_name}}", "header": "Test"}, {"field": "{{unit}}", "header": "Unit"}, {"field": "{{reference_range}}", "header": "Ref Range"}, {"field": "{{result_1}}", "header": "{{date_1}}"}, {"field": "{{result_2}}", "header": "{{date_2}}"}, {"field": "{{result_3}}", "header": "{{date_3}}"}, {"field": "{{result_4}}", "header": "{{date_4}}"}, {"field": "{{trend_arrow}}", "header": "Trend"}]}, {"type": "text", "field": "{{clinical_summary}}", "label": "Summary"}]}',
 '{"rows": [{"field": "{{pathologist_name}}", "label": "Pathologist"}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "pathologist", "label": "Pathologist", "registration": true}]',
 '{patient_id,test_ids}'),
((SELECT id FROM tenants LIMIT 1), 'LAB_HISTOPATH', 'Histopathology Report', 'histopathology_report', 'lab',
 'Surgical pathology / histopathology report', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{hpe_number}}", "label": "HPE No"}, {"field": "{{report_date}}", "label": "Date"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "referred_by"]}, {"rows": [{"field": "{{specimen_type}}", "label": "Specimen"}, {"field": "{{received_date}}", "label": "Received"}, {"field": "{{clinical_history}}", "label": "Clinical History"}, {"field": "{{gross_description}}", "label": "Gross Description"}], "type": "key_value"}, {"type": "text", "field": "{{microscopy}}", "label": "Microscopic Examination"}, {"rows": [{"bold": true, "field": "{{diagnosis}}", "label": "Diagnosis"}, {"field": "{{icd_o_code}}", "label": "ICD-O Morphology"}, {"field": "{{tnm_stage}}", "label": "TNM Stage"}, {"field": "{{margins}}", "label": "Margins"}, {"field": "{{grade}}", "label": "Grade"}], "type": "key_value"}, {"type": "text", "field": "{{comments}}", "label": "Comments"}]}',
 '{"rows": [{"text": "This report is based on the material submitted for examination."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "pathologist", "label": "Histopathologist", "registration": true}]',
 '{hpe_number,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'LAB_REPORT', 'Lab Report', 'lab_report', 'lab',
 'Standard laboratory investigation report', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{lab_number}}", "label": "Lab No"}, {"field": "{{report_date}}", "label": "Date"}, {"type": "image", "field": "{{nabl_logo}}", "label": "NABL Accredited"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "referred_by"]}, {"rows": [{"field": "{{sample_type}}", "label": "Sample Type"}, {"field": "{{collection_time}}", "label": "Collected"}, {"field": "{{received_time}}", "label": "Received"}, {"field": "{{reported_time}}", "label": "Reported"}], "type": "key_value"}, {"type": "table", "title": "Investigation Results", "columns": [{"field": "{{test_name}}", "header": "Test"}, {"field": "{{result}}", "header": "Result"}, {"field": "{{unit}}", "header": "Unit"}, {"field": "{{reference_range}}", "header": "Bio Ref Range"}, {"field": "{{flag}}", "header": "Flag"}]}, {"type": "text", "field": "{{interpretation}}", "label": "Interpretation"}, {"type": "text", "field": "{{comments}}", "label": "Comments"}]}',
 '{"rows": [{"text": "NABL Accredited Lab — Cert No: {{nabl_certificate}}"}, {"text": "Results relate only to the sample tested."}]}',
 true, true, true, true,
 true, 'none',
 '[{"role": "technician", "label": "Medical Lab Technician"}, {"role": "pathologist", "label": "Pathologist", "registration": true}]',
 '{lab_order_id,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'LAB_REQUISITION', 'Investigation Requisition Form', 'investigation_report', 'lab',
 'Lab test requisition / order form', 1, true, true, 'a5_portrait',
 '{"rows": [{"field": "{{requisition_number}}", "label": "Req No"}, {"field": "{{date}}", "label": "Date"}, {"field": "{{priority}}", "label": "Priority"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "ward_bed"]}, {"rows": [{"field": "{{doctor_name}}", "label": "Ordering Doctor"}, {"field": "{{diagnosis}}", "label": "Diagnosis"}, {"field": "{{clinical_notes}}", "label": "Clinical Notes"}], "type": "key_value"}, {"type": "table", "title": "Tests Requested", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{test_name}}", "header": "Test Name"}, {"field": "{{sample_type}}", "header": "Sample Type"}, {"field": "{{instructions}}", "header": "Special Instructions"}]}, {"rows": [{"field": "{{fasting_required}}", "label": "Fasting"}, {"field": "{{lmp}}", "label": "LMP", "optional": true}], "type": "key_value"}]}',
 '{"rows": [{"text": "Ensure correct patient identification. Label samples at bedside."}]}',
 true, true, false, true,
 false, 'none',
 '[{"role": "doctor", "label": "Ordering Physician"}]',
 '{requisition_number,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'APPOINTMENT_SLIP', 'Appointment Slip', 'appointment_slip', 'opd',
 'Appointment confirmation slip for OPD', 1, true, true, 'thermal_80mm',
 NULL,
 '{"sections": [{"type": "text", "align": "center", "field": "{{hospital_name}}", "style": "bold"}, {"type": "divider"}, {"rows": [{"field": "{{patient_name}}", "label": "Patient"}, {"field": "{{uhid}}", "label": "UHID"}, {"field": "{{doctor_name}}", "label": "Doctor"}, {"field": "{{department}}", "label": "Dept"}, {"field": "{{appointment_date}}", "label": "Date"}, {"field": "{{appointment_time}}", "label": "Time"}, {"field": "{{token_number}}", "label": "Token"}], "type": "key_value"}, {"type": "barcode", "field": "{{appointment_id}}", "format": "qr"}, {"type": "text", "align": "center", "field": "Please arrive 15 mins before appointment time.", "style": "small"}]}',
 NULL,
 true, false, false, true,
 true, 'none',
 NULL,
 '{appointment_id,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'PATIENT_EDUCATION', 'Patient Education Sheet', 'patient_education', 'opd',
 'Disease/procedure-specific patient education handout', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{date}}", "label": "Date"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid"]}, {"bold": true, "type": "text", "field": "{{condition_name}}", "label": "Condition"}, {"type": "text", "field": "{{description}}", "label": "What is it?"}, {"type": "text", "field": "{{dos}}", "label": "Do''s"}, {"type": "text", "field": "{{donts}}", "label": "Don''ts"}, {"type": "text", "field": "{{diet_advice}}", "label": "Diet Advice"}, {"type": "text", "field": "{{medication_advice}}", "label": "Medications"}, {"bold": true, "type": "text", "field": "{{warning_signs}}", "label": "Warning Signs — Visit ER if:"}, {"type": "text", "field": "{{follow_up}}", "label": "Follow-up"}, {"type": "text", "field": "{{emergency_contact}}", "label": "Emergency Contact"}]}',
 '{"rows": [{"text": "This is general health information. Follow your doctor''s specific advice."}]}',
 true, true, false, true,
 false, 'none',
 '[{"role": "doctor", "label": "Educated By"}]',
 '{patient_id,condition_code}'),
((SELECT id FROM tenants LIMIT 1), 'QUEUE_TOKEN', 'Queue Token', 'queue_token', 'opd',
 'Queue token for OPD counter display', 1, true, true, 'thermal_80mm',
 NULL,
 '{"sections": [{"type": "text", "align": "center", "field": "{{hospital_name}}", "style": "bold"}, {"type": "divider"}, {"type": "text", "align": "center", "field": "TOKEN", "style": "small"}, {"type": "text", "align": "center", "field": "{{token_number}}", "style": "jumbo"}, {"type": "divider"}, {"rows": [{"field": "{{department}}", "label": "Dept"}, {"field": "{{counter}}", "label": "Counter"}, {"field": "{{date}}", "label": "Date"}, {"field": "{{time}}", "label": "Time"}], "type": "key_value"}, {"type": "text", "align": "center", "field": "Please wait for your number to be called.", "style": "small"}]}',
 NULL,
 false, false, false, false,
 false, 'none',
 NULL,
 '{department,token_number}'),
((SELECT id FROM tenants LIMIT 1), 'RX_OPD', 'OPD Prescription', 'prescription', 'opd',
 'Outpatient prescription with Rx symbol', 1, true, true, 'a5_portrait',
 '{"rows": [{"field": "{{visit_date}}", "label": "Date"}, {"field": "{{visit_number}}", "label": "Visit No"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "date"]}, {"rows": [{"field": "{{doctor_name}}", "label": "Doctor"}, {"field": "{{department}}", "label": "Department"}, {"field": "{{diagnosis}}", "label": "Diagnosis"}], "type": "key_value"}, {"type": "table", "title": "℞ Medications", "columns": [{"field": "{{sno}}", "header": "#"}, {"field": "{{drug_name}}", "header": "Drug Name"}, {"field": "{{dose}}", "header": "Dose"}, {"field": "{{route}}", "header": "Route"}, {"field": "{{frequency}}", "header": "Frequency"}, {"field": "{{duration}}", "header": "Duration"}, {"field": "{{instructions}}", "header": "Instructions"}]}, {"type": "text", "field": "{{advice}}", "label": "Advice"}, {"type": "text", "field": "{{follow_up}}", "label": "Follow-up"}]}',
 '{"rows": [{"text": "Not valid for medico-legal purposes."}]}',
 true, true, true, true,
 false, 'none',
 '[{"role": "doctor", "label": "Consulting Doctor", "registration": true}]',
 '{visit_id,patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'PATIENT_CARD', 'Patient Registration Card', 'patient_card', 'patients',
 'Patient ID card with barcode for registration desk', 1, true, true, 'label_50x25mm',
 NULL,
 '{"sections": [{"size": "small", "type": "text", "field": "{{hospital_name}}", "style": "bold"}, {"rows": [{"field": "{{patient_name}}", "label": "Name"}, {"field": "{{uhid}}", "label": "UHID"}, {"field": "{{dob}}", "label": "DOB"}, {"field": "{{gender}}", "label": "Gender"}, {"field": "{{blood_group}}", "label": "Blood Grp"}, {"field": "{{phone}}", "label": "Phone"}], "type": "key_value"}, {"type": "barcode", "field": "{{uhid}}", "format": "code128"}]}',
 NULL,
 true, true, false, false,
 false, 'none',
 NULL,
 '{patient_id}'),
((SELECT id FROM tenants LIMIT 1), 'RAD_REPORT', 'Radiology Report', 'radiology_report', 'radiology',
 'Radiology / imaging investigation report', 1, true, true, 'a4_portrait',
 '{"rows": [{"field": "{{rad_number}}", "label": "Rad No"}, {"field": "{{report_date}}", "label": "Date"}, {"field": "{{modality}}", "label": "Modality"}]}',
 '{"sections": [{"type": "patient_info", "fields": ["patient_name", "uhid", "age", "gender", "referred_by"]}, {"rows": [{"field": "{{exam_name}}", "label": "Examination"}, {"field": "{{modality}}", "label": "Modality"}, {"field": "{{contrast_used}}", "label": "Contrast"}, {"field": "{{indication}}", "label": "Clinical Indication"}], "type": "key_value"}, {"type": "text", "field": "{{findings}}", "label": "Findings"}, {"bold": true, "type": "text", "field": "{{impression}}", "label": "Impression"}, {"type": "text", "field": "{{recommendation}}", "label": "Recommendation"}]}',
 '{"rows": [{"text": "Correlation with clinical findings is recommended."}]}',
 true, true, true, true,
 true, 'none',
 '[{"role": "radiologist", "label": "Radiologist", "registration": true}]',
 '{rad_order_id,patient_id}')
ON CONFLICT (tenant_id, code) DO NOTHING;

END $$;
