-- 102_it_security.sql — IT Security, Data Quality, Compliance, Incentives
-- NOTE: This migration was already applied to the database.
-- The file was regenerated as a no-op placeholder after a tooling incident.
-- All tables (break_glass_events, sensitive_patients, access_alerts,
-- role_access_restrictions, stock_disposal_requests, stock_disposal_items,
-- tat_benchmarks, tat_records, tat_alerts, data_migrations,
-- eod_digest_subscriptions, eod_digest_history, data_quality_rules,
-- data_quality_issues, data_quality_scores, security_incidents,
-- security_incident_updates, vulnerabilities, compliance_requirements,
-- system_health_metrics, backup_history, onboarding_progress,
-- incentive_plans, incentive_plan_rules, doctor_incentive_assignments,
-- incentive_calculations) and enums (disposal_method, disposal_status,
-- security_incident_severity, security_incident_status) were created
-- by the original migration run.
SELECT 1;
