//! Telehealth + clinical decision support + doctor activity leaf crate:
//! telemedicine, CDS alerts, doctor profile/dashboard. Mounted via router().

use axum::{Router, routing::{delete,get,post,put}};
use medbrains_server_core::state::AppState;

pub mod cds;
pub mod doctor_dashboard;
pub mod doctor_profile;
pub mod telemedicine;

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/api/cds/drug-safety-check",
            post(cds::check_drug_safety),
        )
        .route(
            "/api/cds/drug-interactions",
            get(cds::list_drug_interactions).post(cds::create_drug_interaction),
        )
        .route(
            "/api/cds/drug-interactions/{id}",
            delete(cds::delete_drug_interaction),
        )
        .route(
            "/api/cds/critical-value-rules",
            get(cds::list_critical_value_rules).post(cds::create_critical_value_rule),
        )
        .route(
            "/api/cds/critical-value-rules/{id}",
            delete(cds::delete_critical_value_rule),
        )
        .route(
            "/api/cds/protocols",
            get(cds::list_protocols).post(cds::create_protocol),
        )
        .route(
            "/api/cds/protocols/{id}",
            delete(cds::delete_protocol),
        )
        .route(
            "/api/cds/restricted-drug-approvals",
            get(cds::list_restricted_drug_approvals).post(cds::create_restricted_drug_approval),
        )
        .route(
            "/api/cds/restricted-drug-approvals/{id}",
            put(cds::update_restricted_drug_approval),
        )
        .route(
            "/api/cds/pre-auth-requests",
            get(cds::list_pre_auth_requests).post(cds::create_pre_auth_request),
        )
        .route(
            "/api/cds/pre-auth-requests/{id}",
            put(cds::update_pre_auth_request),
        )
        .route(
            "/api/cds/pg-logbook",
            get(cds::list_pg_logbook).post(cds::create_pg_logbook_entry),
        )
        .route(
            "/api/cds/pg-logbook/{id}/verify",
            put(cds::verify_pg_logbook_entry),
        )
        .route(
            "/api/cds/co-signatures",
            get(cds::list_co_signatures).post(cds::create_co_signature),
        )
        .route(
            "/api/cds/co-signatures/{id}",
            put(cds::update_co_signature),
        )
        .route(
            "/api/telemedicine/consultations",
            get(telemedicine::list_tele_consultations)
                .post(telemedicine::create_tele_consultation),
        )
        .route(
            "/api/telemedicine/waiting-room",
            get(telemedicine::waiting_room),
        )
        .route(
            "/api/telemedicine/config",
            get(telemedicine::get_tele_config).put(telemedicine::update_tele_config),
        )
        .route(
            "/api/telemedicine/consultations/{id}/recording",
            put(telemedicine::update_recording),
        )
        .route(
            "/api/telemedicine/consultations/{id}/follow-up",
            post(telemedicine::schedule_follow_up),
        )
        .route(
            "/api/telemedicine/consultations/{id}/chat",
            get(telemedicine::list_chat).post(telemedicine::post_chat),
        )
        .route(
            "/api/telemedicine/consultations/{id}/triage",
            get(telemedicine::get_triage).post(telemedicine::submit_triage),
        )
        .route(
            "/api/telemedicine/triage-research/summary",
            get(telemedicine::triage_research_summary),
        )
        .route(
            "/api/telemedicine/triage-research/dataset",
            get(telemedicine::triage_research_dataset),
        )
        .route(
            "/api/telemedicine/consultations/{id}",
            get(telemedicine::get_tele_consultation),
        )
        .route(
            "/api/telemedicine/consultations/{id}/join",
            get(telemedicine::get_join_info),
        )
        .route(
            "/api/telemedicine/consultations/{id}/status",
            put(telemedicine::update_tele_status),
        )
        .route(
            "/api/admin/doctors",
            get(doctor_profile::list_doctors).post(doctor_profile::create_doctor),
        )
        .route(
            "/api/admin/doctors/{id}",
            get(doctor_profile::get_doctor).put(doctor_profile::update_doctor),
        )
        .route(
            "/api/doctors/me/profile",
            get(doctor_profile::get_my_profile).put(doctor_profile::update_my_profile),
        )
        .route(
            "/api/doctors/me/dashboard",
            get(doctor_dashboard::my_day),
        )
        .route(
            "/api/doctors/me/pending-signoffs",
            get(doctor_dashboard::list_my_pending_signoffs),
        )
}
