use sqlx::PgPool;

/// `(code, name, generic_name, category, unit, base_price, tax_percent,
///   drug_schedule, is_controlled, inn_name, atc_code, aware_category)`
#[allow(clippy::type_complexity)]
const DRUGS: &[(
    &str,
    &str,
    &str,
    &str,
    &str,
    &str,
    &str,
    &str,
    &str,
    &str,
    &str,
    &str,
)] = &[
    // ── Analgesics & Antipyretics ───────────────────────────────
    (
        "PCM500",
        "Paracetamol 500mg",
        "Paracetamol",
        "Analgesics",
        "tab",
        "2.00",
        "12.00",
        "OTC",
        "false",
        "Paracetamol",
        "N02BE01",
        "",
    ),
    (
        "PCM650",
        "Paracetamol 650mg",
        "Paracetamol",
        "Analgesics",
        "tab",
        "3.00",
        "12.00",
        "OTC",
        "false",
        "Paracetamol",
        "N02BE01",
        "",
    ),
    (
        "IBU400",
        "Ibuprofen 400mg",
        "Ibuprofen",
        "Analgesics",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Ibuprofen",
        "M01AE01",
        "",
    ),
    (
        "DICLO50",
        "Diclofenac 50mg",
        "Diclofenac Sodium",
        "Analgesics",
        "tab",
        "4.00",
        "12.00",
        "H",
        "false",
        "Diclofenac",
        "M01AB05",
        "",
    ),
    (
        "ACECLO",
        "Aceclofenac 100mg + Paracetamol 325mg",
        "Aceclofenac",
        "Analgesics",
        "tab",
        "6.00",
        "12.00",
        "H",
        "false",
        "Aceclofenac",
        "M01AB16",
        "",
    ),
    (
        "TRAM50",
        "Tramadol 50mg",
        "Tramadol HCl",
        "Analgesics",
        "cap",
        "8.00",
        "12.00",
        "H1",
        "true",
        "Tramadol",
        "N02AX02",
        "",
    ),
    // ── Antibiotics ─────────────────────────────────────────────
    (
        "AMOX500",
        "Amoxicillin 500mg",
        "Amoxicillin",
        "Antibiotics",
        "cap",
        "8.00",
        "12.00",
        "H",
        "false",
        "Amoxicillin",
        "J01CA04",
        "access",
    ),
    (
        "AMOX_CLAV",
        "Amoxicillin + Clavulanate 625mg",
        "Amoxicillin-Clavulanic Acid",
        "Antibiotics",
        "tab",
        "15.00",
        "12.00",
        "H",
        "false",
        "Amoxicillin and enzyme inhibitor",
        "J01CR02",
        "access",
    ),
    (
        "AZI500",
        "Azithromycin 500mg",
        "Azithromycin",
        "Antibiotics",
        "tab",
        "20.00",
        "12.00",
        "H",
        "false",
        "Azithromycin",
        "J01FA10",
        "watch",
    ),
    (
        "CIPRO500",
        "Ciprofloxacin 500mg",
        "Ciprofloxacin",
        "Antibiotics",
        "tab",
        "10.00",
        "12.00",
        "H",
        "false",
        "Ciprofloxacin",
        "J01MA02",
        "watch",
    ),
    (
        "LEVO500",
        "Levofloxacin 500mg",
        "Levofloxacin",
        "Antibiotics",
        "tab",
        "12.00",
        "12.00",
        "H",
        "false",
        "Levofloxacin",
        "J01MA12",
        "watch",
    ),
    (
        "CEPH500",
        "Cephalexin 500mg",
        "Cephalexin",
        "Antibiotics",
        "cap",
        "12.00",
        "12.00",
        "H",
        "false",
        "Cefalexin",
        "J01DB01",
        "access",
    ),
    (
        "CEFTRI1G",
        "Ceftriaxone 1g Injection",
        "Ceftriaxone",
        "Antibiotics",
        "vial",
        "80.00",
        "12.00",
        "H",
        "false",
        "Ceftriaxone",
        "J01DD04",
        "watch",
    ),
    (
        "METRO400",
        "Metronidazole 400mg",
        "Metronidazole",
        "Antibiotics",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Metronidazole",
        "J01XD01",
        "access",
    ),
    (
        "DOXY100",
        "Doxycycline 100mg",
        "Doxycycline",
        "Antibiotics",
        "cap",
        "8.00",
        "12.00",
        "H",
        "false",
        "Doxycycline",
        "J01AA02",
        "access",
    ),
    (
        "CEFIX200",
        "Cefixime 200mg",
        "Cefixime",
        "Antibiotics",
        "tab",
        "15.00",
        "12.00",
        "H",
        "false",
        "Cefixime",
        "J01DD08",
        "watch",
    ),
    (
        "MERO1G",
        "Meropenem 1g Injection",
        "Meropenem",
        "Antibiotics",
        "vial",
        "500.00",
        "12.00",
        "H1",
        "false",
        "Meropenem",
        "J01DH02",
        "reserve",
    ),
    (
        "PIPE_TAZ",
        "Piperacillin + Tazobactam 4.5g",
        "Piperacillin-Tazobactam",
        "Antibiotics",
        "vial",
        "350.00",
        "12.00",
        "H1",
        "false",
        "Piperacillin and enzyme inhibitor",
        "J01CR05",
        "watch",
    ),
    (
        "VANCO1G",
        "Vancomycin 1g Injection",
        "Vancomycin",
        "Antibiotics",
        "vial",
        "300.00",
        "12.00",
        "H1",
        "false",
        "Vancomycin",
        "J01XA01",
        "reserve",
    ),
    (
        "LINEZOLID",
        "Linezolid 600mg",
        "Linezolid",
        "Antibiotics",
        "tab",
        "40.00",
        "12.00",
        "H1",
        "false",
        "Linezolid",
        "J01XX08",
        "reserve",
    ),
    // ── Antidiabetics ───────────────────────────────────────────
    (
        "MET500",
        "Metformin 500mg",
        "Metformin HCl",
        "Antidiabetics",
        "tab",
        "3.00",
        "5.00",
        "H",
        "false",
        "Metformin",
        "A10BA02",
        "",
    ),
    (
        "MET1000",
        "Metformin 1000mg SR",
        "Metformin HCl",
        "Antidiabetics",
        "tab",
        "6.00",
        "5.00",
        "H",
        "false",
        "Metformin",
        "A10BA02",
        "",
    ),
    (
        "GLIM1",
        "Glimepiride 1mg",
        "Glimepiride",
        "Antidiabetics",
        "tab",
        "4.00",
        "5.00",
        "H",
        "false",
        "Glimepiride",
        "A10BB12",
        "",
    ),
    (
        "GLIM2",
        "Glimepiride 2mg",
        "Glimepiride",
        "Antidiabetics",
        "tab",
        "6.00",
        "5.00",
        "H",
        "false",
        "Glimepiride",
        "A10BB12",
        "",
    ),
    (
        "SITA50",
        "Sitagliptin 50mg",
        "Sitagliptin",
        "Antidiabetics",
        "tab",
        "15.00",
        "5.00",
        "H",
        "false",
        "Sitagliptin",
        "A10BH01",
        "",
    ),
    (
        "INS_REG",
        "Insulin Regular (Human) 40IU/mL",
        "Insulin Human Regular",
        "Antidiabetics",
        "vial",
        "120.00",
        "5.00",
        "H",
        "false",
        "Insulin (human)",
        "A10AB01",
        "",
    ),
    (
        "INS_NPH",
        "Insulin NPH 40IU/mL",
        "Insulin Isophane",
        "Antidiabetics",
        "vial",
        "120.00",
        "5.00",
        "H",
        "false",
        "Insulin (human)",
        "A10AC01",
        "",
    ),
    (
        "INS_GLAR",
        "Insulin Glargine 100IU/mL Pen",
        "Insulin Glargine",
        "Antidiabetics",
        "pen",
        "800.00",
        "5.00",
        "H",
        "false",
        "Insulin glargine",
        "A10AE04",
        "",
    ),
    // ── Cardiovascular ──────────────────────────────────────────
    (
        "AMLO5",
        "Amlodipine 5mg",
        "Amlodipine",
        "Cardiovascular",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Amlodipine",
        "C08CA01",
        "",
    ),
    (
        "AMLO10",
        "Amlodipine 10mg",
        "Amlodipine",
        "Cardiovascular",
        "tab",
        "8.00",
        "12.00",
        "H",
        "false",
        "Amlodipine",
        "C08CA01",
        "",
    ),
    (
        "ATEN50",
        "Atenolol 50mg",
        "Atenolol",
        "Cardiovascular",
        "tab",
        "4.00",
        "12.00",
        "H",
        "false",
        "Atenolol",
        "C07AB03",
        "",
    ),
    (
        "METRO50",
        "Metoprolol 50mg",
        "Metoprolol Succinate",
        "Cardiovascular",
        "tab",
        "6.00",
        "12.00",
        "H",
        "false",
        "Metoprolol",
        "C07AB02",
        "",
    ),
    (
        "LOSAR50",
        "Losartan 50mg",
        "Losartan Potassium",
        "Cardiovascular",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Losartan",
        "C09CA01",
        "",
    ),
    (
        "TELMI40",
        "Telmisartan 40mg",
        "Telmisartan",
        "Cardiovascular",
        "tab",
        "6.00",
        "12.00",
        "H",
        "false",
        "Telmisartan",
        "C09CA07",
        "",
    ),
    (
        "ENAL5",
        "Enalapril 5mg",
        "Enalapril Maleate",
        "Cardiovascular",
        "tab",
        "4.00",
        "12.00",
        "H",
        "false",
        "Enalapril",
        "C09AA02",
        "",
    ),
    (
        "HYDRO12",
        "Hydrochlorothiazide 12.5mg",
        "Hydrochlorothiazide",
        "Cardiovascular",
        "tab",
        "3.00",
        "12.00",
        "H",
        "false",
        "Hydrochlorothiazide",
        "C03AA03",
        "",
    ),
    (
        "FUROS40",
        "Furosemide 40mg",
        "Furosemide",
        "Cardiovascular",
        "tab",
        "3.00",
        "12.00",
        "H",
        "false",
        "Furosemide",
        "C03CA01",
        "",
    ),
    (
        "ASPIRIN75",
        "Aspirin 75mg (Ecosprin)",
        "Aspirin",
        "Cardiovascular",
        "tab",
        "2.00",
        "12.00",
        "OTC",
        "false",
        "Acetylsalicylic acid",
        "B01AC06",
        "",
    ),
    (
        "CLOP75",
        "Clopidogrel 75mg",
        "Clopidogrel",
        "Cardiovascular",
        "tab",
        "8.00",
        "12.00",
        "H",
        "false",
        "Clopidogrel",
        "B01AC04",
        "",
    ),
    (
        "ATORV10",
        "Atorvastatin 10mg",
        "Atorvastatin",
        "Cardiovascular",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Atorvastatin",
        "C10AA05",
        "",
    ),
    (
        "ATORV20",
        "Atorvastatin 20mg",
        "Atorvastatin",
        "Cardiovascular",
        "tab",
        "8.00",
        "12.00",
        "H",
        "false",
        "Atorvastatin",
        "C10AA05",
        "",
    ),
    (
        "WARFARIN5",
        "Warfarin 5mg",
        "Warfarin Sodium",
        "Cardiovascular",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Warfarin",
        "B01AA03",
        "",
    ),
    (
        "DIGOXIN",
        "Digoxin 0.25mg",
        "Digoxin",
        "Cardiovascular",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Digoxin",
        "C01AA05",
        "",
    ),
    // ── Gastrointestinal ────────────────────────────────────────
    (
        "PAN40",
        "Pantoprazole 40mg",
        "Pantoprazole",
        "Gastrointestinal",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Pantoprazole",
        "A02BC02",
        "",
    ),
    (
        "RABE20",
        "Rabeprazole 20mg",
        "Rabeprazole",
        "Gastrointestinal",
        "tab",
        "6.00",
        "12.00",
        "H",
        "false",
        "Rabeprazole",
        "A02BC04",
        "",
    ),
    (
        "OND4",
        "Ondansetron 4mg",
        "Ondansetron",
        "Gastrointestinal",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Ondansetron",
        "A04AA01",
        "",
    ),
    (
        "DOM10",
        "Domperidone 10mg",
        "Domperidone",
        "Gastrointestinal",
        "tab",
        "3.00",
        "12.00",
        "H",
        "false",
        "Domperidone",
        "A03FA03",
        "",
    ),
    (
        "ORS",
        "ORS Sachet",
        "Oral Rehydration Salts",
        "Gastrointestinal",
        "sachet",
        "10.00",
        "5.00",
        "OTC",
        "false",
        "Oral rehydration salts",
        "A07CA",
        "",
    ),
    (
        "SUCRA1G",
        "Sucralfate 1g Suspension",
        "Sucralfate",
        "Gastrointestinal",
        "bottle",
        "60.00",
        "12.00",
        "H",
        "false",
        "Sucralfate",
        "A02BX02",
        "",
    ),
    (
        "LACTULOSE",
        "Lactulose Solution 100mL",
        "Lactulose",
        "Gastrointestinal",
        "bottle",
        "80.00",
        "12.00",
        "OTC",
        "false",
        "Lactulose",
        "A06AD11",
        "",
    ),
    // ── Respiratory ─────────────────────────────────────────────
    (
        "SALB_INH",
        "Salbutamol Inhaler 100mcg",
        "Salbutamol",
        "Respiratory",
        "inhaler",
        "120.00",
        "12.00",
        "H",
        "false",
        "Salbutamol",
        "R03AC02",
        "",
    ),
    (
        "BUD_INH",
        "Budesonide Inhaler 200mcg",
        "Budesonide",
        "Respiratory",
        "inhaler",
        "250.00",
        "12.00",
        "H",
        "false",
        "Budesonide",
        "R03BA02",
        "",
    ),
    (
        "MONTEL10",
        "Montelukast 10mg",
        "Montelukast",
        "Respiratory",
        "tab",
        "8.00",
        "12.00",
        "H",
        "false",
        "Montelukast",
        "R03DC03",
        "",
    ),
    (
        "CETRIZ10",
        "Cetirizine 10mg",
        "Cetirizine",
        "Respiratory",
        "tab",
        "3.00",
        "12.00",
        "OTC",
        "false",
        "Cetirizine",
        "R06AE07",
        "",
    ),
    (
        "LEVOCET5",
        "Levocetirizine 5mg",
        "Levocetirizine",
        "Respiratory",
        "tab",
        "4.00",
        "12.00",
        "OTC",
        "false",
        "Levocetirizine",
        "R06AE09",
        "",
    ),
    (
        "AMB_SYR",
        "Ambroxol Syrup 100mL",
        "Ambroxol HCl",
        "Respiratory",
        "bottle",
        "50.00",
        "12.00",
        "OTC",
        "false",
        "Ambroxol",
        "R05CB06",
        "",
    ),
    (
        "DERIPHYLLIN",
        "Deriphylline Retard 150mg",
        "Etophylline + Theophylline",
        "Respiratory",
        "tab",
        "6.00",
        "12.00",
        "H",
        "false",
        "Etofylline",
        "R03DA",
        "",
    ),
    // ── Corticosteroids ─────────────────────────────────────────
    (
        "PRED5",
        "Prednisolone 5mg",
        "Prednisolone",
        "Corticosteroids",
        "tab",
        "3.00",
        "12.00",
        "H",
        "false",
        "Prednisolone",
        "H02AB06",
        "",
    ),
    (
        "PRED10",
        "Prednisolone 10mg",
        "Prednisolone",
        "Corticosteroids",
        "tab",
        "5.00",
        "12.00",
        "H",
        "false",
        "Prednisolone",
        "H02AB06",
        "",
    ),
    (
        "DEXA4",
        "Dexamethasone 4mg Injection",
        "Dexamethasone",
        "Corticosteroids",
        "amp",
        "15.00",
        "12.00",
        "H",
        "false",
        "Dexamethasone",
        "H02AB02",
        "",
    ),
    (
        "HYDROCORT100",
        "Hydrocortisone 100mg Injection",
        "Hydrocortisone",
        "Corticosteroids",
        "vial",
        "30.00",
        "12.00",
        "H",
        "false",
        "Hydrocortisone",
        "H02AB09",
        "",
    ),
    // ── Vitamins & Supplements ──────────────────────────────────
    (
        "BCOMP",
        "B-Complex Tablets",
        "Vitamin B Complex",
        "Vitamins",
        "tab",
        "2.00",
        "12.00",
        "OTC",
        "false",
        "Vitamin B complex",
        "A11EA",
        "",
    ),
    (
        "VITC500",
        "Vitamin C 500mg",
        "Ascorbic Acid",
        "Vitamins",
        "tab",
        "3.00",
        "12.00",
        "OTC",
        "false",
        "Ascorbic acid",
        "A11GA01",
        "",
    ),
    (
        "VITD3_60K",
        "Vitamin D3 60,000 IU Sachet",
        "Cholecalciferol",
        "Vitamins",
        "sachet",
        "30.00",
        "5.00",
        "OTC",
        "false",
        "Colecalciferol",
        "A11CC05",
        "",
    ),
    (
        "CALCI500",
        "Calcium + Vitamin D3 500mg",
        "Calcium Carbonate + D3",
        "Vitamins",
        "tab",
        "5.00",
        "12.00",
        "OTC",
        "false",
        "Calcium combinations",
        "A12AX",
        "",
    ),
    (
        "IRON_FOL",
        "Iron + Folic Acid",
        "Ferrous Sulphate + Folic Acid",
        "Vitamins",
        "tab",
        "3.00",
        "5.00",
        "OTC",
        "false",
        "Iron combinations",
        "B03AD",
        "",
    ),
    (
        "FOLIC5",
        "Folic Acid 5mg",
        "Folic Acid",
        "Vitamins",
        "tab",
        "2.00",
        "5.00",
        "OTC",
        "false",
        "Folic acid",
        "B03BB01",
        "",
    ),
    // ── IV Fluids & Injections ──────────────────────────────────
    (
        "NS500",
        "Normal Saline (NS) 500mL",
        "Sodium Chloride 0.9%",
        "IV Fluids",
        "bottle",
        "40.00",
        "5.00",
        "H",
        "false",
        "Sodium chloride",
        "B05BB01",
        "",
    ),
    (
        "NS1000",
        "Normal Saline (NS) 1000mL",
        "Sodium Chloride 0.9%",
        "IV Fluids",
        "bottle",
        "50.00",
        "5.00",
        "H",
        "false",
        "Sodium chloride",
        "B05BB01",
        "",
    ),
    (
        "RL500",
        "Ringer Lactate 500mL",
        "Ringer Lactate",
        "IV Fluids",
        "bottle",
        "40.00",
        "5.00",
        "H",
        "false",
        "Electrolytes",
        "B05BB01",
        "",
    ),
    (
        "DNS500",
        "Dextrose Normal Saline 500mL",
        "Dextrose 5% + NS",
        "IV Fluids",
        "bottle",
        "45.00",
        "5.00",
        "H",
        "false",
        "Glucose and sodium chloride",
        "B05BB02",
        "",
    ),
    (
        "D5W500",
        "Dextrose 5% Water 500mL",
        "Dextrose 5%",
        "IV Fluids",
        "bottle",
        "40.00",
        "5.00",
        "H",
        "false",
        "Glucose",
        "B05BA03",
        "",
    ),
    (
        "MANNITOL",
        "Mannitol 20% 350mL",
        "Mannitol",
        "IV Fluids",
        "bottle",
        "80.00",
        "5.00",
        "H",
        "false",
        "Mannitol",
        "B05BC01",
        "",
    ),
    // ── Emergency Drugs ─────────────────────────────────────────
    (
        "ADR1",
        "Adrenaline 1mg/mL",
        "Epinephrine",
        "Emergency",
        "amp",
        "15.00",
        "5.00",
        "H",
        "false",
        "Epinephrine",
        "C01CA24",
        "",
    ),
    (
        "ATR06",
        "Atropine 0.6mg/mL",
        "Atropine Sulphate",
        "Emergency",
        "amp",
        "10.00",
        "5.00",
        "H",
        "false",
        "Atropine",
        "A03BA01",
        "",
    ),
    (
        "DOPAMINE",
        "Dopamine 200mg/5mL",
        "Dopamine HCl",
        "Emergency",
        "amp",
        "30.00",
        "5.00",
        "H",
        "false",
        "Dopamine",
        "C01CA04",
        "",
    ),
    (
        "DOBUTAMINE",
        "Dobutamine 250mg/20mL",
        "Dobutamine",
        "Emergency",
        "vial",
        "80.00",
        "5.00",
        "H",
        "false",
        "Dobutamine",
        "C01CA07",
        "",
    ),
    (
        "NORADR",
        "Noradrenaline 2mg/mL",
        "Norepinephrine",
        "Emergency",
        "amp",
        "50.00",
        "5.00",
        "H",
        "false",
        "Norepinephrine",
        "C01CA03",
        "",
    ),
    (
        "MIDAZ5",
        "Midazolam 5mg/mL",
        "Midazolam",
        "Emergency",
        "amp",
        "25.00",
        "5.00",
        "H1",
        "true",
        "Midazolam",
        "N05CD08",
        "",
    ),
    // ── Topical ─────────────────────────────────────────────────
    (
        "POVI_OINT",
        "Povidone Iodine 5% Ointment 15g",
        "Povidone Iodine",
        "Topical",
        "tube",
        "25.00",
        "12.00",
        "OTC",
        "false",
        "Povidone-iodine",
        "D08AG02",
        "",
    ),
    (
        "FUSIDIC",
        "Fusidic Acid 2% Cream 15g",
        "Fusidic Acid",
        "Topical",
        "tube",
        "60.00",
        "12.00",
        "H",
        "false",
        "Fusidic acid",
        "D06AX01",
        "",
    ),
    (
        "SILV_SULF",
        "Silver Sulfadiazine 1% Cream 50g",
        "Silver Sulfadiazine",
        "Topical",
        "tube",
        "40.00",
        "12.00",
        "H",
        "false",
        "Silver sulfadiazine",
        "D06BA01",
        "",
    ),
    // ── Antiepileptics & Psychiatric ────────────────────────────
    (
        "LEVET500",
        "Levetiracetam 500mg",
        "Levetiracetam",
        "Antiepileptics",
        "tab",
        "15.00",
        "12.00",
        "H",
        "false",
        "Levetiracetam",
        "N03AX14",
        "",
    ),
    (
        "PHENYT100",
        "Phenytoin 100mg",
        "Phenytoin Sodium",
        "Antiepileptics",
        "tab",
        "4.00",
        "12.00",
        "H",
        "false",
        "Phenytoin",
        "N03AB02",
        "",
    ),
    (
        "VALP200",
        "Sodium Valproate 200mg",
        "Sodium Valproate",
        "Antiepileptics",
        "tab",
        "6.00",
        "12.00",
        "H",
        "false",
        "Valproic acid",
        "N03AG01",
        "",
    ),
    (
        "ESCIT10",
        "Escitalopram 10mg",
        "Escitalopram",
        "Psychiatric",
        "tab",
        "8.00",
        "12.00",
        "H",
        "false",
        "Escitalopram",
        "N06AB10",
        "",
    ),
    (
        "SERT50",
        "Sertraline 50mg",
        "Sertraline",
        "Psychiatric",
        "tab",
        "7.00",
        "12.00",
        "H",
        "false",
        "Sertraline",
        "N06AB06",
        "",
    ),
    (
        "OLANZ5",
        "Olanzapine 5mg",
        "Olanzapine",
        "Psychiatric",
        "tab",
        "8.00",
        "12.00",
        "H",
        "false",
        "Olanzapine",
        "N05AH03",
        "",
    ),
    // ── Anticoagulants & Others ─────────────────────────────────
    (
        "ENOX40",
        "Enoxaparin 40mg Injection",
        "Enoxaparin Sodium",
        "Anticoagulants",
        "prefill",
        "250.00",
        "5.00",
        "H",
        "false",
        "Enoxaparin",
        "B01AB05",
        "",
    ),
    (
        "ENOX60",
        "Enoxaparin 60mg Injection",
        "Enoxaparin Sodium",
        "Anticoagulants",
        "prefill",
        "350.00",
        "5.00",
        "H",
        "false",
        "Enoxaparin",
        "B01AB05",
        "",
    ),
    (
        "HEPARIN",
        "Heparin 5000IU/mL",
        "Heparin Sodium",
        "Anticoagulants",
        "vial",
        "100.00",
        "5.00",
        "H",
        "false",
        "Heparin",
        "B01AB01",
        "",
    ),
];

/// Seed pharmacy drug catalog with regulatory classification data for the DEFAULT tenant.
/// Idempotent — upserts regulatory fields on re-run.
pub(super) async fn seed_pharmacy_catalog(
    pool: &PgPool,
    tenant_id: uuid::Uuid,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut tx = pool.begin().await?;

    sqlx::query("SELECT set_config('app.tenant_id', $1::text, true)")
        .bind(tenant_id.to_string())
        .execute(&mut *tx)
        .await?;

    for &(
        code,
        name,
        generic_name,
        category,
        unit,
        base_price,
        tax_percent,
        drug_schedule,
        is_controlled,
        inn_name,
        atc_code,
        aware_category,
    ) in DRUGS
    {
        let schedule: Option<&str> = if drug_schedule.is_empty() {
            None
        } else {
            Some(drug_schedule)
        };
        let controlled: bool = is_controlled == "true";
        let inn: Option<&str> = if inn_name.is_empty() {
            None
        } else {
            Some(inn_name)
        };
        let atc: Option<&str> = if atc_code.is_empty() {
            None
        } else {
            Some(atc_code)
        };
        let aware: Option<&str> = if aware_category.is_empty() {
            None
        } else {
            Some(aware_category)
        };

        sqlx::query(
            "INSERT INTO pharmacy_catalog \
             (tenant_id, code, name, generic_name, category, unit, base_price, tax_percent, \
              drug_schedule, is_controlled, inn_name, atc_code, aware_category) \
             VALUES ($1, $2, $3, $4, $5, $6, $7::numeric, $8::numeric, \
                     $9, $10, $11, $12, $13) \
             ON CONFLICT (tenant_id, code) DO UPDATE SET \
             drug_schedule = COALESCE(EXCLUDED.drug_schedule, pharmacy_catalog.drug_schedule), \
             is_controlled = EXCLUDED.is_controlled, \
             inn_name = COALESCE(EXCLUDED.inn_name, pharmacy_catalog.inn_name), \
             atc_code = COALESCE(EXCLUDED.atc_code, pharmacy_catalog.atc_code), \
             aware_category = COALESCE(EXCLUDED.aware_category, pharmacy_catalog.aware_category)",
        )
        .bind(tenant_id)
        .bind(code)
        .bind(name)
        .bind(generic_name)
        .bind(category)
        .bind(unit)
        .bind(base_price)
        .bind(tax_percent)
        .bind(schedule)
        .bind(controlled)
        .bind(inn)
        .bind(atc)
        .bind(aware)
        .execute(&mut *tx)
        .await?;
    }

    tx.commit().await?;
    tracing::info!("Seeded {} pharmacy drugs with regulatory data", DRUGS.len());
    Ok(())
}
