use sqlx::PgPool;

/// `(code, name, category, sub_category, unit, base_price, reorder_level)`
const ITEMS: &[(&str, &str, &str, &str, &str, &str, i32)] = &[
    // ── Surgical Supplies ─────────────────────────────────────
    (
        "STR-SG-001",
        "Disposable Surgical Gloves (S)",
        "Surgical",
        "Gloves",
        "pair",
        "8.00",
        500,
    ),
    (
        "STR-SG-002",
        "Disposable Surgical Gloves (M)",
        "Surgical",
        "Gloves",
        "pair",
        "8.00",
        500,
    ),
    (
        "STR-SG-003",
        "Disposable Surgical Gloves (L)",
        "Surgical",
        "Gloves",
        "pair",
        "8.00",
        500,
    ),
    (
        "STR-SG-004",
        "Sterile Surgical Drape",
        "Surgical",
        "Drapes",
        "piece",
        "45.00",
        200,
    ),
    (
        "STR-SG-005",
        "Surgical Blade #10",
        "Surgical",
        "Blades",
        "piece",
        "12.00",
        300,
    ),
    (
        "STR-SG-006",
        "Surgical Blade #15",
        "Surgical",
        "Blades",
        "piece",
        "12.00",
        300,
    ),
    (
        "STR-SG-007",
        "Suture Silk 2-0",
        "Surgical",
        "Sutures",
        "piece",
        "35.00",
        200,
    ),
    (
        "STR-SG-008",
        "Suture Vicryl 3-0",
        "Surgical",
        "Sutures",
        "piece",
        "120.00",
        100,
    ),
    (
        "STR-SG-009",
        "Surgical Gown (Disposable)",
        "Surgical",
        "Gowns",
        "piece",
        "65.00",
        200,
    ),
    (
        "STR-SG-010",
        "Surgical Cap (Disposable)",
        "Surgical",
        "Caps",
        "piece",
        "5.00",
        1000,
    ),
    // ── PPE / Protective ──────────────────────────────────────
    (
        "STR-PP-001",
        "N95 Respirator Mask",
        "PPE",
        "Masks",
        "piece",
        "25.00",
        500,
    ),
    (
        "STR-PP-002",
        "3-Ply Surgical Mask",
        "PPE",
        "Masks",
        "piece",
        "3.00",
        2000,
    ),
    (
        "STR-PP-003",
        "Face Shield",
        "PPE",
        "Shields",
        "piece",
        "35.00",
        200,
    ),
    (
        "STR-PP-004",
        "Nitrile Exam Gloves (S)",
        "PPE",
        "Gloves",
        "pair",
        "6.00",
        1000,
    ),
    (
        "STR-PP-005",
        "Nitrile Exam Gloves (M)",
        "PPE",
        "Gloves",
        "pair",
        "6.00",
        1000,
    ),
    (
        "STR-PP-006",
        "Nitrile Exam Gloves (L)",
        "PPE",
        "Gloves",
        "pair",
        "6.00",
        1000,
    ),
    (
        "STR-PP-007",
        "Disposable Shoe Cover",
        "PPE",
        "Covers",
        "pair",
        "4.00",
        1000,
    ),
    (
        "STR-PP-008",
        "Isolation Gown",
        "PPE",
        "Gowns",
        "piece",
        "85.00",
        200,
    ),
    // ── IV & Infusion ─────────────────────────────────────────
    (
        "STR-IV-001",
        "IV Cannula 20G",
        "IV/Infusion",
        "Cannulae",
        "piece",
        "18.00",
        500,
    ),
    (
        "STR-IV-002",
        "IV Cannula 22G",
        "IV/Infusion",
        "Cannulae",
        "piece",
        "18.00",
        500,
    ),
    (
        "STR-IV-003",
        "IV Cannula 24G",
        "IV/Infusion",
        "Cannulae",
        "piece",
        "18.00",
        300,
    ),
    (
        "STR-IV-004",
        "IV Set (Standard)",
        "IV/Infusion",
        "Sets",
        "piece",
        "22.00",
        500,
    ),
    (
        "STR-IV-005",
        "IV Set (Blood)",
        "IV/Infusion",
        "Sets",
        "piece",
        "35.00",
        200,
    ),
    (
        "STR-IV-006",
        "3-Way Stopcock",
        "IV/Infusion",
        "Accessories",
        "piece",
        "28.00",
        300,
    ),
    (
        "STR-IV-007",
        "Extension Tube",
        "IV/Infusion",
        "Accessories",
        "piece",
        "15.00",
        300,
    ),
    (
        "STR-IV-008",
        "Scalp Vein Set (Butterfly) 23G",
        "IV/Infusion",
        "Needles",
        "piece",
        "10.00",
        300,
    ),
    // ── Catheters & Drainage ──────────────────────────────────
    (
        "STR-CT-001",
        "Foley Catheter 14Fr",
        "Catheters",
        "Urinary",
        "piece",
        "45.00",
        100,
    ),
    (
        "STR-CT-002",
        "Foley Catheter 16Fr",
        "Catheters",
        "Urinary",
        "piece",
        "45.00",
        100,
    ),
    (
        "STR-CT-003",
        "Urine Collection Bag",
        "Catheters",
        "Bags",
        "piece",
        "30.00",
        200,
    ),
    (
        "STR-CT-004",
        "Ryle's Tube 16Fr",
        "Catheters",
        "Nasogastric",
        "piece",
        "25.00",
        100,
    ),
    (
        "STR-CT-005",
        "Suction Catheter 12Fr",
        "Catheters",
        "Suction",
        "piece",
        "15.00",
        200,
    ),
    (
        "STR-CT-006",
        "Intercostal Drainage Set",
        "Catheters",
        "Drainage",
        "piece",
        "250.00",
        50,
    ),
    (
        "STR-CT-007",
        "Central Line Catheter Kit",
        "Catheters",
        "Central",
        "piece",
        "450.00",
        30,
    ),
    // ── Wound Care ────────────────────────────────────────────
    (
        "STR-WC-001",
        "Cotton Gauze Roll (15cm)",
        "Wound Care",
        "Gauze",
        "roll",
        "12.00",
        500,
    ),
    (
        "STR-WC-002",
        "Sterile Gauze Pad (10x10cm)",
        "Wound Care",
        "Pads",
        "pack",
        "8.00",
        500,
    ),
    (
        "STR-WC-003",
        "Adhesive Bandage (Strips)",
        "Wound Care",
        "Bandages",
        "pack",
        "15.00",
        300,
    ),
    (
        "STR-WC-004",
        "Crepe Bandage (10cm)",
        "Wound Care",
        "Bandages",
        "roll",
        "20.00",
        300,
    ),
    (
        "STR-WC-005",
        "Micropore Tape (2.5cm)",
        "Wound Care",
        "Tapes",
        "roll",
        "35.00",
        200,
    ),
    (
        "STR-WC-006",
        "Povidone-Iodine Solution (500ml)",
        "Wound Care",
        "Antiseptics",
        "bottle",
        "65.00",
        100,
    ),
    (
        "STR-WC-007",
        "Hydrogen Peroxide (500ml)",
        "Wound Care",
        "Antiseptics",
        "bottle",
        "30.00",
        100,
    ),
    (
        "STR-WC-008",
        "Sterile Cotton Balls",
        "Wound Care",
        "Cotton",
        "pack",
        "18.00",
        500,
    ),
    (
        "STR-WC-009",
        "Elastic Adhesive Bandage (10cm)",
        "Wound Care",
        "Bandages",
        "roll",
        "40.00",
        200,
    ),
    (
        "STR-WC-010",
        "Wound Closure Strip",
        "Wound Care",
        "Closure",
        "pack",
        "55.00",
        100,
    ),
    // ── Lab Consumables ───────────────────────────────────────
    (
        "STR-LB-001",
        "Vacutainer EDTA (Purple)",
        "Lab",
        "Collection Tubes",
        "piece",
        "8.00",
        1000,
    ),
    (
        "STR-LB-002",
        "Vacutainer Plain (Red)",
        "Lab",
        "Collection Tubes",
        "piece",
        "7.00",
        1000,
    ),
    (
        "STR-LB-003",
        "Vacutainer Citrate (Blue)",
        "Lab",
        "Collection Tubes",
        "piece",
        "9.00",
        500,
    ),
    (
        "STR-LB-004",
        "Blood Collection Needle 21G",
        "Lab",
        "Needles",
        "piece",
        "5.00",
        1000,
    ),
    (
        "STR-LB-005",
        "Tourniquet (Disposable)",
        "Lab",
        "Accessories",
        "piece",
        "3.00",
        500,
    ),
    (
        "STR-LB-006",
        "Alcohol Swab",
        "Lab",
        "Swabs",
        "piece",
        "1.50",
        2000,
    ),
    (
        "STR-LB-007",
        "Urine Container (Sterile)",
        "Lab",
        "Containers",
        "piece",
        "10.00",
        500,
    ),
    (
        "STR-LB-008",
        "Sputum Container",
        "Lab",
        "Containers",
        "piece",
        "8.00",
        300,
    ),
    (
        "STR-LB-009",
        "Glass Slides (Box of 50)",
        "Lab",
        "Slides",
        "box",
        "60.00",
        50,
    ),
    (
        "STR-LB-010",
        "Lancet (Disposable)",
        "Lab",
        "Lancets",
        "piece",
        "2.00",
        2000,
    ),
    // ── Housekeeping ──────────────────────────────────────────
    (
        "STR-HK-001",
        "Biohazard Waste Bag (Red)",
        "Housekeeping",
        "Waste",
        "piece",
        "8.00",
        500,
    ),
    (
        "STR-HK-002",
        "General Waste Bag (Black)",
        "Housekeeping",
        "Waste",
        "piece",
        "5.00",
        500,
    ),
    (
        "STR-HK-003",
        "Sharps Container (1L)",
        "Housekeeping",
        "Waste",
        "piece",
        "25.00",
        200,
    ),
    (
        "STR-HK-004",
        "Sharps Container (5L)",
        "Housekeeping",
        "Waste",
        "piece",
        "65.00",
        100,
    ),
    (
        "STR-HK-005",
        "Hand Sanitizer (500ml)",
        "Housekeeping",
        "Hygiene",
        "bottle",
        "80.00",
        100,
    ),
    (
        "STR-HK-006",
        "Surface Disinfectant (5L)",
        "Housekeeping",
        "Cleaning",
        "can",
        "250.00",
        50,
    ),
    (
        "STR-HK-007",
        "Bed Sheet (Disposable)",
        "Housekeeping",
        "Linen",
        "piece",
        "30.00",
        200,
    ),
    (
        "STR-HK-008",
        "Pillow Cover (Disposable)",
        "Housekeeping",
        "Linen",
        "piece",
        "12.00",
        200,
    ),
    // ── Office / Administrative ───────────────────────────────
    (
        "STR-OF-001",
        "Patient Wristband (White)",
        "Office",
        "Identification",
        "piece",
        "5.00",
        500,
    ),
    (
        "STR-OF-002",
        "Patient Wristband (Red — Allergy)",
        "Office",
        "Identification",
        "piece",
        "5.00",
        200,
    ),
    (
        "STR-OF-003",
        "Prescription Pad (100 sheets)",
        "Office",
        "Stationery",
        "pad",
        "40.00",
        100,
    ),
    (
        "STR-OF-004",
        "Consent Form (Pre-printed)",
        "Office",
        "Stationery",
        "pack",
        "60.00",
        50,
    ),
    (
        "STR-OF-005",
        "Thermal Paper Roll (80mm)",
        "Office",
        "Printing",
        "roll",
        "35.00",
        100,
    ),
    (
        "STR-OF-006",
        "A4 Paper (500 sheets)",
        "Office",
        "Stationery",
        "ream",
        "180.00",
        50,
    ),
    (
        "STR-OF-007",
        "Lab Report Envelope",
        "Office",
        "Stationery",
        "piece",
        "2.00",
        1000,
    ),
    (
        "STR-OF-008",
        "Discharge Summary Folder",
        "Office",
        "Stationery",
        "piece",
        "8.00",
        500,
    ),
    // ── Respiratory ───────────────────────────────────────────
    (
        "STR-RS-001",
        "Oxygen Mask (Adult)",
        "Respiratory",
        "Masks",
        "piece",
        "25.00",
        200,
    ),
    (
        "STR-RS-002",
        "Oxygen Nasal Prong",
        "Respiratory",
        "Cannulae",
        "piece",
        "15.00",
        200,
    ),
    (
        "STR-RS-003",
        "Nebulizer Kit (Adult)",
        "Respiratory",
        "Nebulizers",
        "piece",
        "45.00",
        100,
    ),
    (
        "STR-RS-004",
        "Endotracheal Tube 7.0mm",
        "Respiratory",
        "ET Tubes",
        "piece",
        "65.00",
        50,
    ),
    (
        "STR-RS-005",
        "Endotracheal Tube 7.5mm",
        "Respiratory",
        "ET Tubes",
        "piece",
        "65.00",
        50,
    ),
    (
        "STR-RS-006",
        "Ambu Bag (Adult)",
        "Respiratory",
        "Resuscitation",
        "piece",
        "350.00",
        20,
    ),
];

/// Seed store catalog items for the DEFAULT tenant.
/// Idempotent — skips items that already exist.
pub(super) async fn seed_store_catalog(
    pool: &PgPool,
    tenant_id: uuid::Uuid,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut tx = pool.begin().await?;

    sqlx::query("SELECT set_config('app.tenant_id', $1::text, true)")
        .bind(tenant_id.to_string())
        .execute(&mut *tx)
        .await?;

    for &(code, name, category, sub_category, unit, base_price, reorder_level) in ITEMS {
        sqlx::query(
            "INSERT INTO store_catalog \
             (tenant_id, code, name, category, sub_category, unit, base_price, reorder_level) \
             VALUES ($1, $2, $3, $4, $5, $6, $7::numeric, $8) \
             ON CONFLICT (tenant_id, code) DO NOTHING",
        )
        .bind(tenant_id)
        .bind(code)
        .bind(name)
        .bind(category)
        .bind(sub_category)
        .bind(unit)
        .bind(base_price)
        .bind(reorder_level)
        .execute(&mut *tx)
        .await?;
    }

    tx.commit().await?;
    tracing::info!("Seeded {} store catalog items", ITEMS.len());
    Ok(())
}
