import { P } from "./permissions.js";
import { TOKEN_BOARD_SURFACES, type TokenBoardSurfaceId } from "./token-board-surfaces.js";

export type AccessMatrixSurfaceKind =
  | "screen"
  | "tab"
  | "table"
  | "column"
  | "input"
  | "action"
  | "print"
  | "widget";

export type AccessMatrixPlatform = "web" | "mobile" | "tv" | "kiosk";

export type AccessMatrixPrintCopy =
  | "customer"
  | "office"
  | "clinical"
  | "mrd"
  | "lab"
  | "pharmacy"
  | "police"
  | "duplicate";

export type AccessMatrixMaskingBehavior =
  | "none"
  | "identity"
  | "clinical"
  | "financial"
  | "regulatory"
  | "operational";

export interface AccessMatrixSurface {
  id: string;
  module: string;
  area: string;
  label: string;
  kind: AccessMatrixSurfaceKind;
  route?: string;
  tab?: string;
  table?: string;
  fieldAccessKeys: readonly string[];
  requiredPermissions: readonly string[];
  activatesAfter: readonly string[];
  platforms: readonly AccessMatrixPlatform[];
  masking: AccessMatrixMaskingBehavior;
  printArtifacts: readonly string[];
  printCopies: readonly AccessMatrixPrintCopy[];
  printerProfiles: readonly string[];
  requiresPrinter: boolean;
  standardRefs: readonly string[];
}

type SurfaceInput = Omit<
  AccessMatrixSurface,
  | "activatesAfter"
  | "fieldAccessKeys"
  | "platforms"
  | "printArtifacts"
  | "printCopies"
  | "printerProfiles"
  | "requiresPrinter"
  | "standardRefs"
> & {
  activatesAfter?: readonly string[];
  fieldAccessKeys?: readonly string[];
  platforms?: readonly AccessMatrixPlatform[];
  printArtifacts?: readonly string[];
  printCopies?: readonly AccessMatrixPrintCopy[];
  printerProfiles?: readonly string[];
  requiresPrinter?: boolean;
  standardRefs?: readonly string[];
};

function surface(input: SurfaceInput): AccessMatrixSurface {
  return {
    activatesAfter: [],
    fieldAccessKeys: [],
    platforms: ["web"],
    printArtifacts: [],
    printCopies: [],
    printerProfiles: [],
    requiresPrinter: false,
    standardRefs: [],
    ...input,
  };
}

const PATIENT_IDENTITY_FIELDS = [
  "patients.uhid",
  "patients.first_name",
  "patients.middle_name",
  "patients.last_name",
  "patients.full_name_local",
  "patients.phone",
  "patients.date_of_birth",
] as const;

const PATIENT_REGISTRATION_FIELDS = [
  ...PATIENT_IDENTITY_FIELDS,
  "patients.phone_secondary",
  "patients.email",
  "patients.address",
  "patients.abha_id",
  "patients.identifiers.id_number",
] as const;

const IPD_ATTENDER_FIELDS = [
  "ipd.attenders.name",
  "ipd.attenders.relationship",
  "ipd.attenders.phone",
  "ipd.attenders.address",
  "ipd.attenders.id_proof_number",
] as const;

const EMERGENCY_MLC_FIELDS = [
  "emergency.mlc.fir_number",
  "emergency.mlc.police_station",
  "emergency.mlc.informant_name",
  "emergency.mlc.informant_relation",
  "emergency.mlc.informant_contact",
  "emergency.mlc.history_of_incident",
  "emergency.mlc.examination_findings",
  "emergency.mlc.medical_opinion",
  "emergency.mlc.cause_of_death",
  "emergency.mlc.pocso_report",
] as const;

const CAMP_REGISTRATION_FIELDS = [
  "camp.registrations.person_name",
  "camp.registrations.phone",
  "camp.registrations.id_proof_number",
] as const;

const CAMP_MANAGEMENT_FIELDS = [
  "camp.camps.name",
  "camp.camps.location",
  "camp.camps.schedule",
] as const;

const PHARMACY_PRICE_FIELDS = [
  "pharmacy.catalog.base_price",
  "pharmacy.pricing.unit_price",
  "pharmacy.batches.purchase_rate",
  "pharmacy.batches.selling_rate",
] as const;

const PHARMACY_BATCH_FIELDS = ["pharmacy.batches.batch_number", "pharmacy.batches.source"] as const;

const BILLING_AMOUNT_FIELDS = ["billing.amount"] as const;

const BILLING_PAYER_FIELDS = [
  "billing.corporate.contact_email",
  "billing.corporate.contact_phone",
  "insurance.verification.member_id",
  "insurance.prior_auth.auth_number",
  "insurance.prior_auth.denial_reason",
] as const;

const MRD_CASE_SHEET_FIELDS = [
  ...PATIENT_IDENTITY_FIELDS,
  "mrd.case_sheets.packet_number",
  "mrd.case_sheets.source_snapshot",
] as const;

const MRD_STORAGE_FIELDS = ["mrd.storage_locations.code", "mrd.case_sheets.packet_number"] as const;

const SETTINGS_CONFIGURATION_FIELDS = [
  "settings.configuration.values",
  "settings.master_data.status",
  "settings.print_templates.version",
] as const;

const LAB_PUBLIC_QUEUE_FIELDS = [
  ...PATIENT_IDENTITY_FIELDS,
  "lab.test_name",
  "lab.results",
  "lab.critical_flag",
] as const;

const RADIOLOGY_PUBLIC_QUEUE_FIELDS = [
  ...PATIENT_IDENTITY_FIELDS,
  "radiology.body_part",
  "radiology.indication",
  "radiology.preparation_instructions",
  "radiology.report",
] as const;

const PHARMACY_PUBLIC_QUEUE_FIELDS = [
  ...PATIENT_IDENTITY_FIELDS,
  "pharmacy.drug_name",
  "pharmacy.prescription_notes",
] as const;

const BILLING_PUBLIC_QUEUE_FIELDS = [
  ...PATIENT_IDENTITY_FIELDS,
  ...BILLING_AMOUNT_FIELDS,
  ...BILLING_PAYER_FIELDS,
] as const;

const TOKEN_BOARD_VIEW_PERMISSIONS = [
  ...TOKEN_BOARD_SURFACES.opd.requiredAnyPermissions,
  ...TOKEN_BOARD_SURFACES.lab.requiredAnyPermissions,
  ...TOKEN_BOARD_SURFACES.radiology.requiredAnyPermissions,
  ...TOKEN_BOARD_SURFACES.emergency.requiredAnyPermissions,
  ...TOKEN_BOARD_SURFACES.pharmacy.requiredAnyPermissions,
  ...TOKEN_BOARD_SURFACES.billing.requiredAnyPermissions,
] as const;

const TOKEN_BOARD_PUBLIC_FIELDS = [
  ...PATIENT_IDENTITY_FIELDS,
  ...LAB_PUBLIC_QUEUE_FIELDS,
  ...RADIOLOGY_PUBLIC_QUEUE_FIELDS,
  ...EMERGENCY_MLC_FIELDS,
  ...PHARMACY_PUBLIC_QUEUE_FIELDS,
  ...BILLING_PUBLIC_QUEUE_FIELDS,
] as const;

function tokenBoardAccessSurface({
  activatesAfter,
  fieldAccessKeys,
  id,
  masking,
}: {
  activatesAfter: readonly string[];
  fieldAccessKeys: readonly string[];
  id: TokenBoardSurfaceId;
  masking: AccessMatrixMaskingBehavior;
}): AccessMatrixSurface {
  const board = TOKEN_BOARD_SURFACES[id];
  return surface({
    id: `token_boards.${id}.public_display`,
    module: board.module,
    area: "Public Token Boards",
    label: `${board.title} public token board`,
    kind: "screen",
    route: board.targets.tvDeepLink,
    requiredPermissions: board.requiredAnyPermissions,
    fieldAccessKeys,
    masking,
    activatesAfter,
    platforms: ["web", "mobile", "tv", "kiosk"],
    standardRefs: [...board.standardRefs, "DPDP Act data minimisation"],
  });
}

const TOKEN_BOARD_ACCESS_SURFACES: readonly AccessMatrixSurface[] = [
  surface({
    id: "front_office.token_boards.workspace",
    module: "front_office",
    area: "Public Token Boards",
    label: "Front-office live token-board workspace",
    kind: "screen",
    route: "/front-office#token-boards",
    requiredPermissions: TOKEN_BOARD_VIEW_PERMISSIONS,
    fieldAccessKeys: TOKEN_BOARD_PUBLIC_FIELDS,
    masking: "identity",
    activatesAfter: [
      "opd.encounter.created",
      "lab.sample.created",
      "radiology.order.created",
      "emergency.visit.created",
      "pharmacy.order.created",
      "billing.invoice.created",
    ],
    platforms: ["web", "mobile"],
    standardRefs: ["IPSG public queue privacy", "DPDP Act data minimisation"],
  }),
  tokenBoardAccessSurface({
    id: "opd",
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    activatesAfter: ["opd.encounter.created"],
  }),
  tokenBoardAccessSurface({
    id: "lab",
    fieldAccessKeys: LAB_PUBLIC_QUEUE_FIELDS,
    masking: "clinical",
    activatesAfter: ["lab.sample.created", "lab.result.posted"],
  }),
  tokenBoardAccessSurface({
    id: "radiology",
    fieldAccessKeys: RADIOLOGY_PUBLIC_QUEUE_FIELDS,
    masking: "regulatory",
    activatesAfter: ["radiology.order.created", "radiology.report.verified"],
  }),
  tokenBoardAccessSurface({
    id: "emergency",
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, ...EMERGENCY_MLC_FIELDS],
    masking: "regulatory",
    activatesAfter: ["emergency.visit.created", "emergency.triage.updated"],
  }),
  tokenBoardAccessSurface({
    id: "pharmacy",
    fieldAccessKeys: PHARMACY_PUBLIC_QUEUE_FIELDS,
    masking: "clinical",
    activatesAfter: ["pharmacy.order.created", "pharmacy.order.dispensed"],
  }),
  tokenBoardAccessSurface({
    id: "billing",
    fieldAccessKeys: BILLING_PUBLIC_QUEUE_FIELDS,
    masking: "financial",
    activatesAfter: ["billing.invoice.created", "billing.payment.received"],
  }),
];

export const ACCESS_MATRIX_SURFACES: readonly AccessMatrixSurface[] = [
  ...TOKEN_BOARD_ACCESS_SURFACES,
  surface({
    id: "patients.directory.screen",
    module: "patients",
    area: "Patient Registration",
    label: "Patient directory",
    kind: "screen",
    route: "/patients",
    table: "patients",
    requiredPermissions: [P.PATIENTS.LIST],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    platforms: ["web", "mobile"],
    standardRefs: ["NABH AAC patient identification", "DPDP Act data minimisation"],
  }),
  surface({
    id: "patients.directory.identity_columns",
    module: "patients",
    area: "Patient Registration",
    label: "Directory UHID, name, DOB and phone columns",
    kind: "column",
    route: "/patients",
    table: "patients",
    requiredPermissions: [P.PATIENTS.LIST],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    standardRefs: ["NABH AAC patient identification"],
  }),
  surface({
    id: "patients.register.screen",
    module: "patients",
    area: "Patient Registration",
    label: "Register patient route",
    kind: "screen",
    route: "/patients/register",
    requiredPermissions: [P.PATIENTS.CREATE],
    fieldAccessKeys: PATIENT_REGISTRATION_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.search.completed"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["NABH AAC registration", "IPSG two identifiers"],
  }),
  surface({
    id: "patients.register.identity_inputs",
    module: "patients",
    area: "Patient Registration",
    label: "Registration identity and contact inputs",
    kind: "input",
    route: "/patients/register",
    requiredPermissions: [P.PATIENTS.CREATE],
    fieldAccessKeys: PATIENT_REGISTRATION_FIELDS,
    masking: "identity",
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["DPDP Act consent and purpose limitation"],
  }),
  surface({
    id: "patients.detail.screen",
    module: "patients",
    area: "Patient Longitudinal Record",
    label: "Patient detail workspace",
    kind: "screen",
    route: "/patients/:id#overview",
    requiredPermissions: [P.PATIENTS.VIEW],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH IMS confidentiality"],
  }),
  surface({
    id: "patients.detail.tabs",
    module: "patients",
    area: "Patient Longitudinal Record",
    label: "Overview, allergies, visits, orders, billing, documents and merge tabs",
    kind: "tab",
    route: "/patients/:id#overview",
    requiredPermissions: [P.PATIENTS.VIEW],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created"],
    standardRefs: ["NABH AAC continuity of care"],
  }),
  surface({
    id: "patients.edit.screen",
    module: "patients",
    area: "Patient Registration",
    label: "Edit patient route",
    kind: "screen",
    route: "/patients/:id/edit",
    requiredPermissions: [P.PATIENTS.UPDATE],
    fieldAccessKeys: PATIENT_REGISTRATION_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created"],
    standardRefs: ["DPDP Act correction rights"],
  }),
  surface({
    id: "patients.context.actions",
    module: "patients",
    area: "Patient Longitudinal Record",
    label: "Edit, share, print card and module handoff actions",
    kind: "action",
    route: "/patients/:id#overview",
    requiredPermissions: [P.PATIENTS.VIEW, P.PATIENTS.UPDATE],
    fieldAccessKeys: PATIENT_REGISTRATION_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created", "patient.updated", "patient.access_shared"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["DPDP Act lawful processing and correction rights", "NABH IMS confidentiality"],
  }),
  surface({
    id: "patients.registration.printables",
    module: "patients",
    area: "Patient Registration",
    label: "Registration slip, patient card and identity printables",
    kind: "print",
    route: "/patients/:id#overview",
    requiredPermissions: [P.PATIENTS.VIEW],
    fieldAccessKeys: PATIENT_REGISTRATION_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created"],
    platforms: ["web", "mobile", "kiosk"],
    printArtifacts: ["Registration slip", "Patient card"],
    printCopies: ["customer", "office"],
    printerProfiles: ["registration-a4", "patient-card"],
    requiresPrinter: true,
    standardRefs: ["IPSG two identifiers", "patient card QR/ABHA print"],
  }),
  surface({
    id: "opd.queue.screen",
    module: "opd",
    area: "OPD Queue",
    label: "OPD queue and appointment workspace",
    kind: "screen",
    route: "/opd",
    table: "opd_queue",
    requiredPermissions: [P.OPD.QUEUE_LIST],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created", "opd.encounter.created"],
    platforms: ["web", "mobile", "tv"],
    standardRefs: ["NABH AAC access and continuity"],
  }),
  surface({
    id: "opd.queue.table_columns",
    module: "opd",
    area: "OPD Queue",
    label: "Queue patient, token, appointment and status columns",
    kind: "column",
    route: "/opd",
    table: "opd_queue",
    requiredPermissions: [P.OPD.QUEUE_LIST],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    standardRefs: ["IPSG patient identification"],
  }),
  surface({
    id: "opd.new_visit.screen",
    module: "opd",
    area: "OPD Queue",
    label: "New OPD visit route",
    kind: "screen",
    route: "/opd/new?patient_id=:patientId",
    requiredPermissions: [P.OPD.VISIT_CREATE],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["NABH AAC registration to encounter"],
  }),
  surface({
    id: "opd.queue.token_printables",
    module: "opd",
    area: "OPD Queue",
    label: "Queue token and appointment slip printables",
    kind: "print",
    route: "/opd",
    requiredPermissions: [P.OPD.QUEUE_VIEW],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    activatesAfter: ["opd.encounter.created"],
    platforms: ["web", "mobile", "kiosk"],
    printArtifacts: ["Queue token slip", "Appointment confirmation slip"],
    printCopies: ["customer", "office"],
    printerProfiles: ["opd-token-thermal", "opd-a4"],
    requiresPrinter: true,
    standardRefs: ["NABH AAC access and continuity", "IPSG patient identification"],
  }),
  surface({
    id: "opd.vitals.route",
    module: "opd",
    area: "OPD Queue",
    label: "Queue vitals route",
    kind: "screen",
    route: "/opd/queue/:queueEntryId/vitals",
    requiredPermissions: [P.OPD.QUEUE_VIEW, P.OPD.VITALS.CREATE],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "clinical",
    activatesAfter: ["opd.encounter.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH COP initial assessment"],
  }),
  surface({
    id: "opd.encounter.screen",
    module: "opd",
    area: "OPD Encounter",
    label: "OPD encounter workspace",
    kind: "screen",
    route: "/opd/encounters/:encounterId#consultation",
    requiredPermissions: [P.OPD.QUEUE_VIEW],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "opd.soap_note", "opd.diagnosis"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH COP clinical record"],
  }),
  surface({
    id: "opd.encounter.clinical_tabs",
    module: "opd",
    area: "OPD Encounter",
    label: "Vitals, consultation, history, ROS and physical exam tabs",
    kind: "tab",
    route: "/opd/encounters/:encounterId#consultation",
    requiredPermissions: [P.OPD.QUEUE_VIEW],
    fieldAccessKeys: ["opd.soap_note"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created"],
    standardRefs: ["NABH COP clinical assessment"],
  }),
  surface({
    id: "opd.encounter.assessment_tabs",
    module: "opd",
    area: "OPD Encounter",
    label: "Diagnoses, procedures, referrals, certificates, reminders and consents tabs",
    kind: "tab",
    route: "/opd/encounters/:encounterId#diagnoses",
    requiredPermissions: [P.OPD.DIAGNOSES.LIST],
    fieldAccessKeys: ["opd.diagnosis"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created"],
    standardRefs: ["NABH COP orders and discharge advice"],
  }),
  surface({
    id: "opd.encounter.clinical_inputs",
    module: "opd",
    area: "OPD Encounter",
    label: "Vitals, SOAP, diagnosis, procedure, referral and consent inputs",
    kind: "input",
    route: "/opd/encounters/:encounterId#consultation",
    requiredPermissions: [
      P.OPD.VISIT_UPDATE,
      P.OPD.VITALS.CREATE,
      P.OPD.DIAGNOSES.CREATE,
      P.OPD.PROCEDURES.CREATE,
      P.OPD.REFERRALS.CREATE,
      P.OPD.CONSENTS.CREATE,
    ],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "opd.soap_note", "opd.diagnosis"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH COP clinical assessment", "IPSG patient identification before orders"],
  }),
  surface({
    id: "opd.encounter.order_actions",
    module: "opd",
    area: "OPD Encounter",
    label: "Medication, lab and imaging order actions",
    kind: "action",
    route: "/opd/encounters/:encounterId#consultation",
    requiredPermissions: [P.ORDER_BASKET.SIGN],
    fieldAccessKeys: ["opd.diagnosis"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created"],
    standardRefs: ["NABH MOM medication order safety"],
  }),
  surface({
    id: "mobile.clinical.medication_order_action",
    module: "opd",
    area: "Mobile Patient Flow",
    label: "Mobile medication order handoff",
    kind: "action",
    route: "medbrains://mobile/prescription",
    requiredPermissions: [P.OPD.VISIT_UPDATE],
    fieldAccessKeys: ["pharmacy.drug_name", "pharmacy.prescription_notes"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created", "bed.assigned"],
    platforms: ["mobile"],
    standardRefs: ["NABH MOM medication order safety", "IPSG medication safety"],
  }),
  surface({
    id: "mobile.clinical.lab_order_action",
    module: "lab",
    area: "Mobile Patient Flow",
    label: "Mobile lab order handoff",
    kind: "action",
    route: "medbrains://mobile/lab-order",
    requiredPermissions: [P.LAB.ORDERS_CREATE],
    fieldAccessKeys: ["lab.test_name"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created", "bed.assigned"],
    platforms: ["mobile"],
    standardRefs: ["NABH AAC", "NABL traceability"],
  }),
  surface({
    id: "mobile.clinical.radiology_order_action",
    module: "radiology",
    area: "Mobile Patient Flow",
    label: "Mobile imaging order handoff",
    kind: "action",
    route: "medbrains://mobile/radiology-order",
    requiredPermissions: [P.RADIOLOGY.ORDERS_CREATE, P.RADIOLOGY.ORDERS_LIST],
    fieldAccessKeys: [
      "radiology.body_part",
      "radiology.indication",
      "radiology.preparation_instructions",
    ],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created", "bed.assigned"],
    platforms: ["mobile"],
    standardRefs: ["NABH AAC", "DICOM integration", "Radiology contrast safety checks"],
  }),
  surface({
    id: "opd.encounter.mrd_case_sheet_action",
    module: "opd",
    area: "OPD Encounter",
    label: "Send or update OPD case sheet packet in MRD",
    kind: "action",
    route: "/opd/encounters/:encounterId#consultation",
    requiredPermissions: [P.MRD.CASE_SHEETS_GENERATE],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "opd.soap_note", "opd.diagnosis"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH MRD record completeness", "MRD printable audit trail"],
  }),
  surface({
    id: "opd.encounter.visit_summary_print",
    module: "opd",
    area: "OPD Encounter",
    label: "OPD visit summary and advice printable",
    kind: "print",
    route: "/opd/encounters/:encounterId#consultation",
    requiredPermissions: [P.OPD.QUEUE_VIEW],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "opd.soap_note", "opd.diagnosis"],
    masking: "clinical",
    activatesAfter: ["opd.encounter.created"],
    platforms: ["web", "mobile"],
    printArtifacts: ["OPD prescription", "OPD consultation summary", "Follow-up reminder slip"],
    printCopies: ["customer", "office", "clinical", "mrd", "pharmacy"],
    printerProfiles: ["opd-a4", "opd-summary"],
    requiresPrinter: true,
    standardRefs: ["NABH COP OPD record", "IPSG patient identification"],
  }),
  surface({
    id: "opd.encounter.certificate_consent_printables",
    module: "opd",
    area: "OPD Encounter",
    label: "Certificates, referral letters and consent printables",
    kind: "print",
    route: "/opd/encounters/:encounterId#certificates",
    requiredPermissions: [
      P.OPD.CERTIFICATES.PRINT,
      P.OPD.CERTIFICATES.REPRINT,
      P.OPD.CONSENTS.PRINT,
      P.OPD.CONSENTS.REPRINT,
    ],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "opd.diagnosis"],
    masking: "clinical",
    activatesAfter: ["opd.certificate.created", "opd.consent.signed"],
    platforms: ["web", "mobile"],
    printArtifacts: [
      "Medical certificate",
      "Fitness certificate",
      "Referral letter",
      "Consent form",
    ],
    printCopies: ["customer", "office", "clinical", "duplicate"],
    printerProfiles: ["opd-certificate-a4", "consent-a4"],
    requiresPrinter: true,
    standardRefs: ["NABH patient rights", "consent print audit"],
  }),
  surface({
    id: "ipd.admissions.screen",
    module: "ipd",
    area: "IPD Admissions",
    label: "IPD admissions list",
    kind: "screen",
    route: "/ipd",
    table: "admissions",
    requiredPermissions: [P.IPD.ADMISSIONS_LIST],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    activatesAfter: ["ipd.admission.created"],
    platforms: ["web", "mobile", "tv"],
    standardRefs: ["NABH AAC inpatient admission"],
  }),
  surface({
    id: "ipd.new_admission.screen",
    module: "ipd",
    area: "IPD Admissions",
    label: "New IPD admission route",
    kind: "screen",
    route: "/ipd/new?patient_id=:patientId",
    requiredPermissions: [P.IPD.ADMISSIONS_CREATE],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "ipd.admissions.provisional_diagnosis"],
    masking: "clinical",
    activatesAfter: ["patient.created", "opd.encounter.created", "emergency.visit.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH AAC admission consent and assessment"],
  }),
  surface({
    id: "ipd.detail.screen",
    module: "ipd",
    area: "IPD Workspace",
    label: "IPD admission workspace",
    kind: "screen",
    route: "/ipd/admissions/:admissionId#overview",
    requiredPermissions: [P.IPD.ADMISSIONS_VIEW],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "ipd.admissions.provisional_diagnosis"],
    masking: "clinical",
    activatesAfter: ["ipd.admission.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH COP inpatient record"],
  }),
  surface({
    id: "ipd.detail.command_tabs",
    module: "ipd",
    area: "IPD Workspace",
    label: "Overview, notes, assessments, MAR, prescriptions, I/O and nursing tabs",
    kind: "tab",
    route: "/ipd/admissions/:admissionId#overview",
    requiredPermissions: [P.IPD.ADMISSIONS_VIEW],
    fieldAccessKeys: ["ipd.admissions.provisional_diagnosis"],
    masking: "clinical",
    activatesAfter: ["ipd.admission.created"],
    standardRefs: ["IPSG medication administration", "NABH NRM"],
  }),
  surface({
    id: "ipd.detail.attender_inputs",
    module: "ipd",
    area: "IPD Workspace",
    label: "Attender identity and contact inputs",
    kind: "input",
    route: "/ipd/admissions/:admissionId#attenders",
    requiredPermissions: [P.IPD.ATTENDERS_MANAGE],
    fieldAccessKeys: IPD_ATTENDER_FIELDS,
    masking: "identity",
    activatesAfter: ["ipd.admission.created"],
    standardRefs: ["NABH patient rights and responsibilities"],
  }),
  surface({
    id: "ipd.detail.discharge_tabs",
    module: "ipd",
    area: "IPD Workspace",
    label: "Discharge checklist, summary, death/birth records and TAT tabs",
    kind: "tab",
    route: "/ipd/admissions/:admissionId#discharge-summary",
    requiredPermissions: [P.IPD.DISCHARGE_TAT_VIEW],
    fieldAccessKeys: [
      "ipd.discharge_summary.final_diagnosis",
      "ipd.admissions.provisional_diagnosis",
    ],
    masking: "clinical",
    activatesAfter: ["ipd.discharge.initiated"],
    standardRefs: ["NABH AAC discharge process"],
  }),
  surface({
    id: "ipd.detail.discharge_printables",
    module: "ipd",
    area: "IPD Workspace",
    label: "Discharge, transfer, death and DAMA/LAMA printables",
    kind: "print",
    route: "/ipd/admissions/:admissionId#discharge-summary",
    requiredPermissions: [P.IPD.DISCHARGE_SUMMARY_FINALIZE, P.IPD.DISCHARGE_CHECKLIST_LIST],
    fieldAccessKeys: [
      ...PATIENT_IDENTITY_FIELDS,
      "ipd.discharge_summary.final_diagnosis",
      "ipd.admissions.provisional_diagnosis",
    ],
    masking: "clinical",
    activatesAfter: ["ipd.discharge.initiated", "ipd.discharge.finalized"],
    platforms: ["web", "mobile"],
    printArtifacts: [
      "Discharge summary",
      "Death summary",
      "Transfer summary",
      "DAMA/LAMA form",
      "Take-home medication list",
    ],
    printCopies: ["customer", "office", "clinical", "mrd", "duplicate"],
    printerProfiles: ["ipd-discharge-a4", "mrd-a4"],
    requiresPrinter: true,
    standardRefs: ["NABH AAC discharge process", "ICD-coded discharge summary"],
  }),
  surface({
    id: "ipd.detail.action_bar",
    module: "ipd",
    area: "IPD Workspace",
    label: "Wristband, transfer, DAMA/LAMA, death and order actions",
    kind: "action",
    route: "/ipd/admissions/:admissionId#overview",
    requiredPermissions: [P.IPD.ADMISSIONS_VIEW],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "clinical",
    activatesAfter: ["ipd.admission.created"],
    standardRefs: ["IPSG patient identification", "NABH AAC transfer and discharge"],
  }),
  surface({
    id: "ipd.detail.admission_printables",
    module: "ipd",
    area: "IPD Workspace",
    label: "Admission sheet, case-sheet cover and wristband printables",
    kind: "print",
    route: "/ipd/admissions/:admissionId#overview",
    requiredPermissions: [
      P.IPD.ADMISSIONS_PRINT,
      P.IPD.ADMISSIONS_REPRINT,
      P.IPD.WRISTBAND_PRINT,
      P.IPD.WRISTBAND_REPRINT,
    ],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "ipd.admissions.provisional_diagnosis"],
    masking: "clinical",
    activatesAfter: ["ipd.admission.created"],
    platforms: ["web", "kiosk"],
    printArtifacts: [
      "Admission sheet",
      "Case-sheet cover page",
      "Patient wristband",
      "Admission consent",
    ],
    printCopies: ["customer", "office", "clinical", "mrd", "duplicate"],
    printerProfiles: ["ipd-a4", "wristband-label"],
    requiresPrinter: true,
    standardRefs: ["IPSG patient identification", "NABH inpatient case sheet"],
  }),
  surface({
    id: "ipd.detail.mrd_case_sheet_action",
    module: "ipd",
    area: "IPD Workspace",
    label: "Send or update IPD case-sheet packet in MRD",
    kind: "action",
    route: "/ipd/admissions/:admissionId#overview",
    requiredPermissions: [P.MRD.CASE_SHEETS_GENERATE],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "ipd.admissions.provisional_diagnosis"],
    masking: "clinical",
    activatesAfter: ["ipd.admission.created", "mrd.case_sheet.generated"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH MRD record completeness", "MRD printable audit trail"],
  }),
  surface({
    id: "emergency.visits.screen",
    module: "emergency",
    area: "Emergency",
    label: "Emergency visits and triage board",
    kind: "screen",
    route: "/emergency",
    table: "er_visits",
    requiredPermissions: [P.EMERGENCY.VISITS_LIST],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created", "emergency.visit.created"],
    platforms: ["web", "mobile", "tv", "kiosk"],
    standardRefs: ["NABH AAC emergency access"],
  }),
  surface({
    id: "emergency.triage.table",
    module: "emergency",
    area: "Emergency",
    label: "Triage board patient, priority, MLC and disposition table",
    kind: "table",
    route: "/emergency",
    table: "er_visits",
    requiredPermissions: [P.EMERGENCY.VISITS_LIST],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "patients.mlc_number"],
    masking: "clinical",
    activatesAfter: ["emergency.visit.created", "mlc.created"],
    platforms: ["web", "mobile", "tv", "kiosk"],
    standardRefs: ["NABH AAC emergency triage", "NABH IMS confidentiality"],
  }),
  surface({
    id: "emergency.new_visit.screen",
    module: "emergency",
    area: "Emergency",
    label: "Emergency visit registration",
    kind: "screen",
    route: "/emergency/visits/new?patient_id=:patientId",
    requiredPermissions: [P.EMERGENCY.VISITS_CREATE],
    fieldAccessKeys: PATIENT_REGISTRATION_FIELDS,
    masking: "identity",
    activatesAfter: ["patient.created"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["NABH AAC emergency registration"],
  }),
  surface({
    id: "emergency.detail.screen",
    module: "emergency",
    area: "Emergency",
    label: "Emergency visit workspace",
    kind: "screen",
    route: "/emergency/visits/:visitId",
    requiredPermissions: [P.EMERGENCY.VISITS_LIST],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "clinical",
    activatesAfter: ["emergency.visit.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH COP emergency care"],
  }),
  surface({
    id: "emergency.triage.actions",
    module: "emergency",
    area: "Emergency",
    label: "Triage, resuscitation and code activation actions",
    kind: "action",
    route: "/emergency/visits/:visitId",
    requiredPermissions: [P.EMERGENCY.TRIAGE_CREATE, P.EMERGENCY.RESUSCITATION_CREATE],
    fieldAccessKeys: PATIENT_IDENTITY_FIELDS,
    masking: "clinical",
    activatesAfter: ["emergency.visit.created"],
    platforms: ["web", "mobile", "tv"],
    standardRefs: ["NABH emergency triage", "IPSG communication"],
  }),
  surface({
    id: "emergency.mlc.inputs",
    module: "emergency",
    area: "Emergency MLC",
    label: "MLC, FIR, informant, POCSO and death fields",
    kind: "input",
    route: "/emergency/visits/:visitId#mlc",
    requiredPermissions: [P.EMERGENCY.MLC_LIST],
    fieldAccessKeys: EMERGENCY_MLC_FIELDS,
    masking: "regulatory",
    activatesAfter: ["emergency.visit.created", "mlc.created"],
    standardRefs: ["MLC SOP", "POCSO Act", "NABH IMS confidentiality"],
  }),
  surface({
    id: "emergency.mlc.printables",
    module: "emergency",
    area: "Emergency MLC",
    label: "MLC certificate and police-intimation printables",
    kind: "print",
    route: "/emergency/visits/:visitId#mlc",
    requiredPermissions: [P.EMERGENCY.MLC_PRINT, P.EMERGENCY.MLC_POLICE_INTIMATIONS.PRINT],
    fieldAccessKeys: EMERGENCY_MLC_FIELDS,
    masking: "regulatory",
    activatesAfter: ["mlc.created", "emergency.mlc_police_intimation.created"],
    platforms: ["web"],
    printArtifacts: ["MLC certificate", "Police intimation", "MLC register extract"],
    printCopies: ["office", "clinical", "police", "mrd", "duplicate"],
    printerProfiles: ["emergency-a4", "mlc-secure-printer"],
    requiresPrinter: true,
    standardRefs: ["MLC SOP", "police intimation audit"],
  }),
  surface({
    id: "camp.management.screen",
    module: "camp",
    area: "Camp",
    label: "Camp planning and analytics",
    kind: "screen",
    route: "/camp",
    table: "camps",
    requiredPermissions: [P.CAMP.LIST],
    fieldAccessKeys: CAMP_MANAGEMENT_FIELDS,
    masking: "operational",
    platforms: ["web", "mobile"],
    standardRefs: ["NABH community outreach records"],
  }),
  surface({
    id: "camp.work.tabs",
    module: "camp",
    area: "Camp",
    label: "Camp registrations, screenings, follow-up and report tabs",
    kind: "tab",
    route: "/camp/:campId/work#registrations",
    requiredPermissions: [P.CAMP.LIST],
    fieldAccessKeys: CAMP_REGISTRATION_FIELDS,
    masking: "identity",
    activatesAfter: ["camp.started"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["NABH outreach continuity"],
  }),
  surface({
    id: "camp.registrations.inputs",
    module: "camp",
    area: "Camp",
    label: "Unlinked participant identity inputs",
    kind: "input",
    route: "/camp/:campId/work#registrations",
    requiredPermissions: [P.CAMP.REGISTRATIONS_CREATE],
    fieldAccessKeys: CAMP_REGISTRATION_FIELDS,
    masking: "identity",
    activatesAfter: ["camp.started"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["DPDP Act data minimisation"],
  }),
  surface({
    id: "camp.clinical.actions",
    module: "camp",
    area: "Camp",
    label: "Screening, lab sample, billing and OPD conversion actions",
    kind: "action",
    route: "/camp/:campId/work#screenings",
    requiredPermissions: [P.CAMP.SCREENINGS_MANAGE],
    fieldAccessKeys: CAMP_REGISTRATION_FIELDS,
    masking: "clinical",
    activatesAfter: ["camp.registration.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["NABH outreach clinical documentation"],
  }),
  surface({
    id: "camp.registration.printables",
    module: "camp",
    area: "Camp",
    label: "Camp token, registration slip and follow-up advice printables",
    kind: "print",
    route: "/camp/:campId/work#registrations",
    requiredPermissions: [P.CAMP.LIST],
    fieldAccessKeys: CAMP_REGISTRATION_FIELDS,
    masking: "identity",
    activatesAfter: ["camp.registration.created"],
    platforms: ["web", "mobile", "kiosk"],
    printArtifacts: ["Camp token", "Registration slip", "Follow-up advice slip"],
    printCopies: ["customer", "office"],
    printerProfiles: ["camp-token-thermal", "camp-a4"],
    requiresPrinter: true,
    standardRefs: ["DPDP Act data minimisation", "camp visit audit"],
  }),
  surface({
    id: "pharmacy.rx_queue.screen",
    module: "pharmacy",
    area: "Pharmacy",
    label: "Prescription review queue",
    kind: "screen",
    route: "/pharmacy?tab=rx-queue",
    table: "pharmacy_rx_queue",
    requiredPermissions: [P.PHARMACY.RX_QUEUE_LIST],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, ...PHARMACY_PRICE_FIELDS],
    masking: "clinical",
    activatesAfter: ["order.created"],
    platforms: ["web", "mobile", "tv"],
    standardRefs: ["NABH MOM medication safety"],
  }),
  surface({
    id: "pharmacy.orders.screen",
    module: "pharmacy",
    area: "Pharmacy",
    label: "Dispensing orders",
    kind: "screen",
    route: "/pharmacy?tab=orders&patient_id=:patientId",
    table: "pharmacy_orders",
    requiredPermissions: [P.PHARMACY.PRESCRIPTIONS_LIST],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, ...PHARMACY_PRICE_FIELDS],
    masking: "clinical",
    activatesAfter: ["order.created"],
    platforms: ["web", "mobile", "tv"],
    standardRefs: ["Drugs and Cosmetics Act", "NABH MOM"],
  }),
  surface({
    id: "pharmacy.order_detail.actions",
    module: "pharmacy",
    area: "Pharmacy",
    label: "Dispense, partial dispense, cancel and void actions",
    kind: "action",
    route: "/pharmacy/orders/:orderId",
    requiredPermissions: [P.PHARMACY.PRESCRIPTIONS_VIEW],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, ...PHARMACY_PRICE_FIELDS],
    masking: "clinical",
    activatesAfter: ["order.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["FEFO", "LASA", "NDPS where applicable"],
  }),
  surface({
    id: "pharmacy.catalog.price_inputs",
    module: "pharmacy",
    area: "Pharmacy Catalog",
    label: "Catalog, unit price and batch price inputs",
    kind: "input",
    route: "/pharmacy?tab=catalog",
    requiredPermissions: [P.PHARMACY.STOCK_MANAGE],
    fieldAccessKeys: PHARMACY_PRICE_FIELDS,
    masking: "financial",
    platforms: ["web"],
    standardRefs: ["Drug formulary governance"],
  }),
  surface({
    id: "pharmacy.batch_columns",
    module: "pharmacy",
    area: "Pharmacy Inventory",
    label: "Batch, lot, expiry, source and FEFO columns",
    kind: "column",
    route: "/pharmacy?tab=batches",
    table: "pharmacy_batches",
    requiredPermissions: [P.PHARMACY.STOCK_MANAGE],
    fieldAccessKeys: PHARMACY_BATCH_FIELDS,
    masking: "operational",
    standardRefs: ["Batch traceability", "FEFO"],
  }),
  surface({
    id: "pharmacy.ndps.register",
    module: "pharmacy",
    area: "Pharmacy NDPS",
    label: "NDPS register balances, users and witnesses",
    kind: "table",
    route: "/pharmacy?tab=ndps",
    table: "ndps_register",
    requiredPermissions: [P.PHARMACY.NDPS_LIST],
    fieldAccessKeys: [
      "pharmacy.ndps.balance_after",
      "pharmacy.ndps.user_ids",
      "pharmacy.ndps.witnessed_by",
    ],
    masking: "regulatory",
    activatesAfter: ["pharmacy.ndps.movement.created"],
    platforms: ["web"],
    standardRefs: ["NDPS Act controlled-substance register"],
  }),
  surface({
    id: "pharmacy.pos.inputs",
    module: "pharmacy",
    area: "Pharmacy POS",
    label: "POS walk-in identity and phone inputs",
    kind: "input",
    route: "/pharmacy?tab=pos",
    requiredPermissions: [P.PHARMACY.POS_CREATE],
    fieldAccessKeys: ["pharmacy.pos.patient_name", "pharmacy.pos.patient_phone"],
    masking: "identity",
    platforms: ["web", "kiosk"],
    standardRefs: ["DPDP Act customer data minimisation"],
  }),
  surface({
    id: "pharmacy.dispense.printables",
    module: "pharmacy",
    area: "Pharmacy",
    label: "Dispense receipt, drug label and controlled-drug copy printables",
    kind: "print",
    route: "/pharmacy?tab=orders",
    requiredPermissions: [P.PHARMACY.PRESCRIPTIONS_VIEW],
    fieldAccessKeys: [
      ...PATIENT_IDENTITY_FIELDS,
      ...PHARMACY_PRICE_FIELDS,
      ...PHARMACY_BATCH_FIELDS,
    ],
    masking: "clinical",
    activatesAfter: ["pharmacy.order.dispensed"],
    platforms: ["web", "mobile"],
    printArtifacts: [
      "Dispense receipt",
      "Drug label",
      "Controlled-drug register copy",
      "Counseling slip",
    ],
    printCopies: ["customer", "pharmacy", "office", "duplicate"],
    printerProfiles: ["pharmacy-receipt-80mm", "pharmacy-drug-label"],
    requiresPrinter: true,
    standardRefs: ["Drugs and Cosmetics Act", "batch traceability", "NDPS where applicable"],
  }),
  surface({
    id: "lab.report.printables",
    module: "lab",
    area: "Laboratory",
    label: "Lab report and investigation requisition printables",
    kind: "print",
    route: "/lab?tab=reports",
    requiredPermissions: [P.LAB.REPORTS_VIEW],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "lab.results", "lab.critical_flag"],
    masking: "clinical",
    activatesAfter: ["lab.result.verified"],
    platforms: ["web", "mobile"],
    printArtifacts: [
      "Lab report",
      "Cumulative lab report",
      "Microbiology culture sensitivity report",
      "Investigation requisition form",
    ],
    printCopies: ["customer", "office", "lab", "duplicate"],
    printerProfiles: ["lab-report-a4"],
    requiresPrinter: true,
    standardRefs: ["NABL report print", "LOINC result coding"],
  }),
  surface({
    id: "radiology.report.printables",
    module: "radiology",
    area: "Radiology",
    label: "Radiology report and key image printables",
    kind: "print",
    route: "/radiology?tab=reports",
    requiredPermissions: [P.RADIOLOGY.ORDERS_VIEW],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, "radiology.report"],
    masking: "clinical",
    activatesAfter: ["radiology.report.verified"],
    platforms: ["web", "mobile"],
    printArtifacts: ["Radiology report", "Key image sheet", "Investigation requisition form"],
    printCopies: ["customer", "office", "clinical", "duplicate"],
    printerProfiles: ["radiology-report-a4"],
    requiresPrinter: true,
    standardRefs: ["DICOM image reference", "AERB radiation safety where applicable"],
  }),
  surface({
    id: "billing.invoices.screen",
    module: "billing",
    area: "Billing",
    label: "Invoice list and patient ledger",
    kind: "screen",
    route: "/billing?tab=invoices&patient_id=:patientId",
    table: "invoices",
    requiredPermissions: [P.BILLING.INVOICES_LIST],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, ...BILLING_AMOUNT_FIELDS],
    masking: "financial",
    activatesAfter: ["billing.invoice.created", "order.created"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["DPDP Act financial data", "PCI scoping if card payment is enabled"],
  }),
  surface({
    id: "billing.invoice_detail.screen",
    module: "billing",
    area: "Billing",
    label: "Invoice detail, charges, payments and receipts",
    kind: "screen",
    route: "/billing/invoices/:invoiceId",
    requiredPermissions: [P.BILLING.INVOICES_VIEW],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, ...BILLING_AMOUNT_FIELDS],
    masking: "financial",
    activatesAfter: ["billing.invoice.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["GST and hospital billing audit"],
  }),
  surface({
    id: "billing.amount_columns",
    module: "billing",
    area: "Billing",
    label: "Total, paid, balance, refund, credit and concession columns",
    kind: "column",
    route: "/billing?tab=invoices",
    table: "invoices",
    requiredPermissions: [P.BILLING.INVOICES_LIST],
    fieldAccessKeys: BILLING_AMOUNT_FIELDS,
    masking: "financial",
    standardRefs: ["DPDP Act financial data minimisation"],
  }),
  surface({
    id: "billing.invoice_charge_inputs",
    module: "billing",
    area: "Billing",
    label: "Invoice line-item, tax, concession and package charge inputs",
    kind: "input",
    route: "/billing/invoices/:invoiceId#billing-items",
    requiredPermissions: [P.BILLING.INVOICES_UPDATE],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, ...BILLING_AMOUNT_FIELDS],
    masking: "financial",
    activatesAfter: ["billing.invoice.created"],
    platforms: ["web", "mobile"],
    standardRefs: ["GST charge audit", "NABH PRE financial counselling"],
  }),
  surface({
    id: "billing.payment_inputs",
    module: "billing",
    area: "Billing",
    label: "Cashier payment amount, settlement and gateway handoff inputs",
    kind: "input",
    route: "/billing/invoices/:invoiceId#billing-payments",
    requiredPermissions: [P.BILLING.PAYMENTS_CREATE],
    fieldAccessKeys: BILLING_AMOUNT_FIELDS,
    masking: "financial",
    activatesAfter: ["billing.invoice.finalized"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["PCI DSS SAQ A target if cards are externalized", "NABH PRE receipt audit"],
  }),
  surface({
    id: "billing.adjustment_inputs",
    module: "billing",
    area: "Billing",
    label: "Discount, refund, credit-note and write-off amount inputs",
    kind: "input",
    route: "/billing/invoices/:invoiceId#billing-discounts",
    requiredPermissions: [
      P.BILLING.INVOICES_UPDATE,
      P.BILLING.CREDIT_MANAGE,
      P.BILLING.WRITE_OFF_CREATE,
    ],
    fieldAccessKeys: BILLING_AMOUNT_FIELDS,
    masking: "financial",
    activatesAfter: ["billing.invoice.created", "billing.payment.received"],
    platforms: ["web"],
    standardRefs: ["Concession approval audit", "SOC 2 financial change evidence"],
  }),
  surface({
    id: "billing.tpa_claim_inputs",
    module: "billing",
    area: "Billing TPA",
    label: "Corporate, TPA member, pre-auth and denial inputs",
    kind: "input",
    route: "/billing?tab=insurance",
    requiredPermissions: [P.BILLING.CORPORATE_ENROLL],
    fieldAccessKeys: [
      ...PATIENT_IDENTITY_FIELDS,
      ...BILLING_AMOUNT_FIELDS,
      ...BILLING_PAYER_FIELDS,
    ],
    masking: "financial",
    activatesAfter: ["patient.created", "billing.invoice.created"],
    platforms: ["web"],
    standardRefs: ["Insurance claim audit", "DPDP Act financial data minimisation"],
  }),
  surface({
    id: "billing.payment_actions",
    module: "billing",
    area: "Billing",
    label: "Record payment, print receipt and reprint receipt actions",
    kind: "action",
    route: "/billing/invoices/:invoiceId",
    requiredPermissions: [P.BILLING.PAYMENTS_CREATE],
    fieldAccessKeys: BILLING_AMOUNT_FIELDS,
    masking: "financial",
    activatesAfter: ["billing.invoice.created", "billing.invoice.finalized"],
    platforms: ["web", "mobile", "kiosk"],
    standardRefs: ["PCI DSS SAQ A target if cards are externalized"],
  }),
  surface({
    id: "billing.receipt_printables",
    module: "billing",
    area: "Billing",
    label: "Invoice, payment receipt and reprint copy outputs",
    kind: "print",
    route: "/billing/invoices/:invoiceId",
    requiredPermissions: [P.BILLING.RECEIPTS_PRINT, P.BILLING.RECEIPTS_REPRINT],
    fieldAccessKeys: [...PATIENT_IDENTITY_FIELDS, ...BILLING_AMOUNT_FIELDS],
    masking: "financial",
    activatesAfter: ["billing.payment.received", "billing.invoice.finalized"],
    platforms: ["web", "mobile", "kiosk"],
    printArtifacts: [
      "OPD bill",
      "IPD interim bill",
      "IPD final bill",
      "Payment receipt",
      "Refund receipt",
      "Credit note",
      "GST invoice",
      "TPA claim copy",
    ],
    printCopies: ["customer", "office", "duplicate"],
    printerProfiles: ["billing-receipt-80mm", "billing-a4"],
    requiresPrinter: true,
    standardRefs: ["GST invoice audit", "PCI DSS SAQ A target if cards are externalized"],
  }),
  surface({
    id: "billing.master_tabs",
    module: "billing",
    area: "Billing Configuration",
    label: "Charge master, packages, rate plans, tax and settings tabs",
    kind: "tab",
    route: "/billing?tab=charge-master",
    requiredPermissions: [P.BILLING.CATALOG_MANAGE],
    fieldAccessKeys: BILLING_AMOUNT_FIELDS,
    masking: "financial",
    platforms: ["web"],
    standardRefs: ["Hospital tariff governance"],
  }),
  surface({
    id: "billing.reports_tabs",
    module: "billing",
    area: "Billing Reports",
    label: "Reports, day-close, audit, GST/TDS, journal and MIS tabs",
    kind: "tab",
    route: "/billing?tab=reports",
    requiredPermissions: [P.BILLING.REPORTS_VIEW],
    fieldAccessKeys: BILLING_AMOUNT_FIELDS,
    masking: "financial",
    activatesAfter: ["billing.payment.received"],
    platforms: ["web"],
    standardRefs: ["GST audit", "SOC 2 evidence"],
  }),
  surface({
    id: "mrd.case_sheets.screen",
    module: "mrd",
    area: "MRD Case Sheets",
    label: "OPD/IPD case-sheet packet workspace",
    kind: "screen",
    route: "/mrd#case-sheets",
    table: "mrd_case_sheet_packets",
    requiredPermissions: [P.MRD.CASE_SHEETS_VIEW],
    fieldAccessKeys: MRD_CASE_SHEET_FIELDS,
    masking: "clinical",
    activatesAfter: ["mrd.case_sheet.generated"],
    platforms: ["web"],
    standardRefs: ["NABH MRD record completeness", "DPDP Act clinical data minimisation"],
  }),
  surface({
    id: "mrd.case_sheets.packet_columns",
    module: "mrd",
    area: "MRD Case Sheets",
    label: "Packet, patient, workflow, status, printed and shelf columns",
    kind: "column",
    route: "/mrd#case-sheets",
    table: "mrd_case_sheet_packets",
    requiredPermissions: [P.MRD.CASE_SHEETS_VIEW],
    fieldAccessKeys: MRD_CASE_SHEET_FIELDS,
    masking: "clinical",
    activatesAfter: ["mrd.case_sheet.generated"],
    standardRefs: ["MRD filing audit", "IPSG patient identification"],
  }),
  surface({
    id: "mrd.case_sheets.page_checklist",
    module: "mrd",
    area: "MRD Case Sheets",
    label: "Case-sheet completeness and page checklist drawer",
    kind: "table",
    route: "/mrd#case-sheets",
    table: "mrd_case_sheet_pages",
    requiredPermissions: [P.MRD.CASE_SHEETS_VIEW],
    fieldAccessKeys: ["mrd.case_sheets.source_snapshot"],
    masking: "clinical",
    activatesAfter: ["mrd.case_sheet.generated"],
    platforms: ["web"],
    standardRefs: ["NABH MRD completeness review"],
  }),
  surface({
    id: "mrd.case_sheets.print_actions",
    module: "mrd",
    area: "MRD Case Sheets",
    label: "Print and audited reprint case-sheet packets",
    kind: "print",
    route: "/mrd#case-sheets",
    requiredPermissions: [P.MRD.CASE_SHEETS_PRINT, P.MRD.CASE_SHEETS_REPRINT],
    fieldAccessKeys: [...MRD_CASE_SHEET_FIELDS, "mrd.case_sheets.reprint_reason"],
    masking: "clinical",
    activatesAfter: ["mrd.case_sheet.generated", "mrd.case_sheet.printed"],
    platforms: ["web"],
    printArtifacts: [
      "Case-sheet cover page",
      "History and physical examination sheet",
      "Progress notes sheet",
      "MAR chart",
      "Vital signs chart",
      "Intake-output chart",
      "Discharge checklist",
      "MLC documentation form",
      "OPD recent case-sheet packet",
    ],
    printCopies: ["office", "clinical", "mrd", "duplicate"],
    printerProfiles: ["mrd-a4", "mrd-record-room"],
    requiresPrinter: true,
    standardRefs: ["MRD duplicate watermark", "SOC 2 print audit evidence"],
  }),
  surface({
    id: "mrd.case_sheets.file_action",
    module: "mrd",
    area: "MRD Case Sheets",
    label: "File printed case-sheet packet into MRD storage",
    kind: "action",
    route: "/mrd#case-sheets",
    requiredPermissions: [P.MRD.CASE_SHEETS_FILE],
    fieldAccessKeys: MRD_STORAGE_FIELDS,
    masking: "operational",
    activatesAfter: ["mrd.case_sheet.printed"],
    platforms: ["web"],
    standardRefs: ["MRD storage location control", "NABH medical record retrieval"],
  }),
  surface({
    id: "mrd.storage.location_inputs",
    module: "mrd",
    area: "MRD Storage",
    label: "MRD rack, shelf, bin and barcode configuration inputs",
    kind: "input",
    route: "/mrd#storage",
    requiredPermissions: [P.MRD.STORAGE_MANAGE],
    fieldAccessKeys: MRD_STORAGE_FIELDS,
    masking: "operational",
    platforms: ["web"],
    standardRefs: ["MRD physical record storage control"],
  }),
  surface({
    id: "settings.access_matrix.screen",
    module: "admin",
    area: "Settings",
    label: "Access matrix settings",
    kind: "screen",
    route: "/admin/settings#access-matrix",
    requiredPermissions: [P.ADMIN.ROLES.LIST],
    fieldAccessKeys: [],
    masking: "none",
    platforms: ["web"],
    standardRefs: ["SOC 2 access review evidence"],
  }),
  surface({
    id: "settings.configuration.tabs",
    module: "admin",
    area: "Settings",
    label: "Access matrix, master data, templates and device configuration tabs",
    kind: "tab",
    route: "/admin/settings#access-matrix",
    requiredPermissions: [P.ADMIN.ROLES.LIST, P.ADMIN.SETTINGS.GENERAL.MANAGE],
    fieldAccessKeys: SETTINGS_CONFIGURATION_FIELDS,
    masking: "operational",
    platforms: ["web"],
    standardRefs: ["NABH ROM governance", "SOC 2 change-management evidence"],
  }),
  surface({
    id: "settings.master_data.screen",
    module: "admin",
    area: "Settings",
    label: "Module master-data and configuration status",
    kind: "screen",
    route: "/admin/settings#master-data",
    requiredPermissions: [P.ADMIN.SETTINGS.GENERAL.MANAGE],
    fieldAccessKeys: ["settings.master_data.status"],
    masking: "operational",
    platforms: ["web"],
    standardRefs: ["NABH governance and configuration control"],
  }),
  surface({
    id: "reports.enterprise.screen",
    module: "analytics",
    area: "Reports",
    label: "Reports and indicators workspace",
    kind: "screen",
    route: "/reports",
    requiredPermissions: [P.ANALYTICS.VIEW],
    fieldAccessKeys: ["billing.amount", "pharmacy.analytics.value"],
    masking: "financial",
    activatesAfter: ["billing.payment.received", "lab.result.posted", "bed.assigned"],
    platforms: ["web", "tv"],
    standardRefs: ["NABH indicators", "SOC 2 reporting evidence"],
  }),
  surface({
    id: "reports.enterprise.tabs",
    module: "analytics",
    area: "Reports",
    label: "NABH, revenue, operations, pharmacy and clinical indicator tabs",
    kind: "tab",
    route: "/reports#nabh",
    requiredPermissions: [P.ANALYTICS.VIEW],
    fieldAccessKeys: ["billing.amount", "pharmacy.analytics.value"],
    masking: "financial",
    activatesAfter: ["billing.payment.received", "lab.result.posted", "bed.assigned"],
    platforms: ["web", "tv"],
    standardRefs: ["NABH indicators", "SOC 2 reporting evidence"],
  }),
  surface({
    id: "reports.dashboard.widgets",
    module: "analytics",
    area: "Reports",
    label: "Dashboard, NABH, revenue, pharmacy and operational widgets",
    kind: "widget",
    route: "/dashboard",
    requiredPermissions: [P.DASHBOARD.VIEW],
    fieldAccessKeys: ["billing.amount", "pharmacy.analytics.value"],
    masking: "financial",
    activatesAfter: ["billing.invoice.created", "pharmacy.order.dispensed", "bed.assigned"],
    platforms: ["web", "mobile", "tv"],
    standardRefs: ["NABH indicators", "WCAG chart text alternatives"],
  }),
];

export function accessMatrixModules() {
  return [...new Set(ACCESS_MATRIX_SURFACES.map((surfaceEntry) => surfaceEntry.module))].sort();
}

export function accessMatrixSurfaceKinds() {
  return [...new Set(ACCESS_MATRIX_SURFACES.map((surfaceEntry) => surfaceEntry.kind))].sort();
}
