/**
 * Fields that can be redacted per role.
 *
 * GENERATED by scripts/generate_field_catalogue.py — do not edit.
 *
 * Each entry corresponds to a `const *_FIELD` in the Rust sources that a
 * handler looks up in the resolved field-access map. Offering a field here
 * that no handler reads would put a switch in the admin UI that changes
 * nothing; omitting one a handler reads would make it unconfigurable. The
 * generator keeps both from happening, and `--check` runs in CI.
 */

// `FieldAccessLevel` is defined once in ./common and re-used here.
// Redeclaring it would give the package two exports of the same name and
// let the two drift apart, which for an access-control type is the kind
// of drift nobody notices until a level stops being honoured.
import type { FieldAccessLevel } from "./common";

export type { FieldAccessLevel };

export interface RedactableField {
  /** The key the backend matches on. */
  key: string;
  /** The part after the module prefix, for display. */
  label: string;
  /** Present when redaction here is a regulatory matter, not a preference. */
  note?: string;
}

export interface RedactableFieldGroup {
  module: string;
  label: string;
  fields: RedactableField[];
}

/** 49 fields across 7 modules. */
export const REDACTABLE_FIELDS: RedactableFieldGroup[] = [
  {
    module: "billing",
    label: "Billing",
    fields: [
      { key: "billing.amount", label: "amount" },
    ],
  },
  {
    module: "camp",
    label: "Camp registration",
    fields: [
      { key: "camp.registrations.id_proof_number", label: "registrations · id proof number", note: "government ID" },
      { key: "camp.registrations.person_name", label: "registrations · person name" },
      { key: "camp.registrations.phone", label: "registrations · phone" },
    ],
  },
  {
    module: "emergency",
    label: "Medico-legal (MLC)",
    fields: [
      { key: "emergency.mlc.cause_of_death", label: "mlc · cause of death", note: "medico-legal" },
      { key: "emergency.mlc.examination_findings", label: "mlc · examination findings" },
      { key: "emergency.mlc.fir_number", label: "mlc · fir number", note: "police record" },
      { key: "emergency.mlc.history_of_incident", label: "mlc · history of incident" },
      { key: "emergency.mlc.informant_contact", label: "mlc · informant contact" },
      { key: "emergency.mlc.informant_name", label: "mlc · informant name" },
      { key: "emergency.mlc.informant_relation", label: "mlc · informant relation" },
      { key: "emergency.mlc.medical_opinion", label: "mlc · medical opinion" },
      { key: "emergency.mlc.pocso_report", label: "mlc · pocso report", note: "POCSO — statutory confidentiality" },
      { key: "emergency.mlc.police_station", label: "mlc · police station" },
    ],
  },
  {
    module: "ipd",
    label: "Inpatient",
    fields: [
      { key: "ipd.admissions.provisional_diagnosis", label: "admissions · provisional diagnosis" },
      { key: "ipd.attenders.address", label: "attenders · address" },
      { key: "ipd.attenders.alt_phone", label: "attenders · alt phone" },
      { key: "ipd.attenders.id_proof_number", label: "attenders · id proof number" },
      { key: "ipd.attenders.name", label: "attenders · name" },
      { key: "ipd.attenders.phone", label: "attenders · phone" },
      { key: "ipd.attenders.relationship", label: "attenders · relationship" },
      { key: "ipd.discharge_summary.final_diagnosis", label: "discharge summary · final diagnosis" },
    ],
  },
  {
    module: "opd",
    label: "OPD consultation",
    fields: [
      { key: "opd.diagnosis", label: "diagnosis" },
      { key: "opd.soap_note", label: "soap note" },
    ],
  },
  {
    module: "patients",
    label: "Patient identity",
    fields: [
      { key: "patients.abha_id", label: "abha id", note: "ABDM health identifier" },
      { key: "patients.address", label: "address" },
      { key: "patients.date_of_birth", label: "date of birth" },
      { key: "patients.email", label: "email" },
      { key: "patients.first_name", label: "first name" },
      { key: "patients.full_name_local", label: "full name local" },
      { key: "patients.identifiers.id_number", label: "identifiers · id number", note: "government ID" },
      { key: "patients.last_name", label: "last name" },
      { key: "patients.middle_name", label: "middle name" },
      { key: "patients.mlc_number", label: "mlc number", note: "medico-legal" },
      { key: "patients.phone", label: "phone" },
      { key: "patients.phone_secondary", label: "phone secondary" },
      { key: "patients.uhid", label: "uhid", note: "hospital identifier — hiding it breaks patient lookup" },
    ],
  },
  {
    module: "pharmacy",
    label: "Pharmacy",
    fields: [
      { key: "pharmacy.analytics.value", label: "analytics · value" },
      { key: "pharmacy.batches.batch_number", label: "batches · batch number" },
      { key: "pharmacy.batches.purchase_rate", label: "batches · purchase rate" },
      { key: "pharmacy.batches.selling_rate", label: "batches · selling rate" },
      { key: "pharmacy.batches.source", label: "batches · source" },
      { key: "pharmacy.catalog.base_price", label: "catalog · base price" },
      { key: "pharmacy.ndps.balance_after", label: "ndps · balance after" },
      { key: "pharmacy.ndps.user_ids", label: "ndps · user ids", note: "NDPS register" },
      { key: "pharmacy.ndps.witnessed_by", label: "ndps · witnessed by", note: "NDPS witness record" },
      { key: "pharmacy.pos.patient_name", label: "pos · patient name" },
      { key: "pharmacy.pos.patient_phone", label: "pos · patient phone" },
      { key: "pharmacy.pricing.unit_price", label: "pricing · unit price" },
    ],
  },
];

/** Every key, flat — for validating what the server returns. */
export const REDACTABLE_FIELD_KEYS: readonly string[] = REDACTABLE_FIELDS.flatMap((g) => g.fields.map((f) => f.key));
