/**
 * MedBrains TV — entry component.
 *
 * Composes the medbrains mobile-shell with this app's modules,
 * variant, and platform shims. Generated by
 * medbrains-create-mobile-app (variant: tv).
 */

import {
  clearNativeAuthTokens,
  configureNativeAuth,
  setApiBase,
  setNativeAuthSession,
} from "@medbrains/api";
import { PaperProvider } from "react-native-paper";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { StatusBar } from "expo-status-bar";
import {
  ExpoSecureStoreAdapter,
  SECRET_KEYS,
  Shell,
  buildDeviceTheme,
  useAuthStore,
} from "@medbrains/mobile-shell";
import type { SecretStore } from "@medbrains/mobile-shell";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useEffect } from "react";
import { config } from "./src/config";
import { Navigator } from "./src/navigator";
import { TvPairingScreen } from "./src/components/tv-pairing";
import { MODULES } from "./src/modules";

setApiBase(config.apiBase);
configureNativeAuth("medbrains-tv");

const secretStore = new ExpoSecureStoreAdapter();
const theme = buildDeviceTheme("light");
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnReconnect: true,
      retry: 1,
      staleTime: 5_000,
    },
  },
});

function NativeAuthBridge({ store }: { store: SecretStore }) {
  const identity = useAuthStore((state) => state.identity);

  useEffect(() => {
    let cancelled = false;

    async function syncNativeAuthSession() {
      if (!identity?.jwt) {
        clearNativeAuthTokens();
        return;
      }

      // The refresh token is optional and must never gate the access token.
      // A paired display is issued a JWT and no refresh token at all, so a
      // throw or a miss here used to abandon the function before the session
      // was set -- the screen looked signed in, every request went out
      // unauthenticated, and the board showed "feed unreachable".
      let refreshToken: string | null = null;
      try {
        refreshToken = await store.getItem(SECRET_KEYS.refreshToken, {
          requireAuthentication: false,
        });
      } catch {
        refreshToken = null;
      }
      if (!cancelled) {
        setNativeAuthSession(identity.jwt, refreshToken);
      }
    }

    void syncNativeAuthSession();
    return () => {
      cancelled = true;
    };
  }, [identity?.jwt, store]);

  return null;
}

export default function App() {
  return (
    <SafeAreaProvider>
      <PaperProvider theme={theme}>
        <QueryClientProvider client={queryClient}>
          <StatusBar style="dark" />
          <NativeAuthBridge store={secretStore} />
          <Shell
            variant="tv"
            modules={MODULES}
            secretStore={secretStore}
            cachePath="medbrains-cache"
            Navigator={Navigator}
            unlockPromptMessage="Unlock MedBrains TV"
            loginGate={<TvPairingScreen secretStore={secretStore} />}
          />
        </QueryClientProvider>
      </PaperProvider>
    </SafeAreaProvider>
  );
}
