/**
 * MedBrains TV — entry component.
 *
 * Composes the medbrains mobile-shell with this app's modules,
 * variant, and platform shims. Generated by
 * medbrains-create-mobile-app (variant: tv).
 */

import {
  api,
  clearNativeAuthTokens,
  configureNativeAuth,
  setApiBase,
  setNativeAuthSession,
} from "@medbrains/api";
import { PaperProvider } from "react-native-paper";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { StatusBar } from "expo-status-bar";
import {
  ExpoSecureStoreAdapter,
  LoginScreen,
  SECRET_KEYS,
  Shell,
  buildForestCopperTheme,
  useAuthStore,
} from "@medbrains/mobile-shell";
import type { SecretStore } from "@medbrains/mobile-shell";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useEffect } from "react";
import { config } from "./src/config";
import { Navigator } from "./src/navigator";
import { MODULES } from "./src/modules";

setApiBase(config.apiBase);
configureNativeAuth("medbrains-tv");

const secretStore = new ExpoSecureStoreAdapter();
const theme = buildForestCopperTheme("light");
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnReconnect: true,
      retry: 1,
      staleTime: 5_000,
    },
  },
});

function NativeAuthBridge({ store }: { store: SecretStore }) {
  const identity = useAuthStore((state) => state.identity);

  useEffect(() => {
    let cancelled = false;

    async function syncNativeAuthSession() {
      if (!identity?.jwt) {
        clearNativeAuthTokens();
        return;
      }

      const refreshToken = await store.getItem(SECRET_KEYS.refreshToken, {
        requireAuthentication: false,
      });
      if (!cancelled) {
        setNativeAuthSession(identity.jwt, refreshToken);
      }
    }

    void syncNativeAuthSession();
    return () => {
      cancelled = true;
    };
  }, [identity?.jwt, store]);

  return null;
}

export default function App() {
  return (
    <SafeAreaProvider>
      <PaperProvider theme={theme}>
        <QueryClientProvider client={queryClient}>
          <StatusBar style="dark" />
          <NativeAuthBridge store={secretStore} />
          <Shell
            variant="tv"
            modules={MODULES}
            secretStore={secretStore}
            cachePath="medbrains-cache"
            Navigator={Navigator}
            unlockPromptMessage="Unlock MedBrains TV"
            loginGate={
              <LoginScreen
                title="MedBrains TV"
                subtitle="Sign in to show live hospital display boards"
                onSubmit={async (identifier, password) => {
                  const result = await api.login({ username: identifier, password });
                  if (!result.token) {
                    throw new Error("Login response did not include a TV session token");
                  }
                  return {
                    identity: {
                      departmentIds: result.department_ids,
                      jwt: result.token,
                      permissions: result.permissions,
                      role: result.user.role,
                      tenantId: result.user.tenant_id,
                      userId: result.user.id,
                    },
                    refreshToken: result.refresh_token,
                  };
                }}
              />
            }
          />
        </QueryClientProvider>
      </PaperProvider>
    </SafeAreaProvider>
  );
}
