//! Care management leaf crate: chronic care, bedside patient portal, case management.

use axum::{Router, routing::{get, post, put}};
use medbrains_server_core::state::AppState;

pub mod bedside_portal;
pub mod case_mgmt;
pub mod chronic_care;
pub mod nurse_calls;

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/api/chronic-care/programs",
            get(chronic_care::list_programs).post(chronic_care::create_program),
        )
        .route(
            "/api/chronic-care/programs/{id}",
            put(chronic_care::update_program).delete(chronic_care::delete_program),
        )
        .route(
            "/api/chronic-care/enrollments",
            get(chronic_care::list_enrollments).post(chronic_care::create_enrollment),
        )
        .route(
            "/api/chronic-care/patients/{patient_id}/enrollments",
            get(chronic_care::patient_enrollments),
        )
        .route(
            "/api/chronic-care/enrollments/{id}",
            put(chronic_care::update_enrollment),
        )
        .route(
            "/api/chronic-care/enrollments/{id}/status",
            put(chronic_care::update_enrollment_status),
        )
        .route(
            "/api/chronic-care/patients/{patient_id}/drug-timeline",
            get(chronic_care::drug_timeline),
        )
        .route(
            "/api/chronic-care/patients/{patient_id}/drug-timeline/with-labs",
            get(chronic_care::drug_timeline_with_labs),
        )
        .route(
            "/api/chronic-care/timeline-events",
            post(chronic_care::create_timeline_event),
        )
        .route(
            "/api/chronic-care/enrollments/{enrollment_id}/adherence",
            get(chronic_care::list_adherence),
        )
        .route(
            "/api/chronic-care/adherence",
            post(chronic_care::record_adherence),
        )
        .route(
            "/api/chronic-care/enrollments/{enrollment_id}/adherence-summary",
            get(chronic_care::adherence_summary),
        )
        .route(
            "/api/chronic-care/patients/{patient_id}/targets",
            get(chronic_care::list_outcome_targets),
        )
        .route(
            "/api/chronic-care/targets",
            post(chronic_care::create_outcome_target),
        )
        .route(
            "/api/chronic-care/targets/{id}",
            put(chronic_care::update_outcome_target),
        )
        .route(
            "/api/chronic-care/patients/{patient_id}/outcome-dashboard",
            get(chronic_care::outcome_dashboard),
        )
        .route(
            "/api/chronic-care/patients/{patient_id}/interaction-alerts",
            get(chronic_care::list_interaction_alerts),
        )
        .route(
            "/api/chronic-care/patients/{patient_id}/check-interactions",
            post(chronic_care::check_polypharmacy),
        )
        .route(
            "/api/chronic-care/interaction-alerts/{id}/acknowledge",
            put(chronic_care::acknowledge_alert),
        )
        .route(
            "/api/chronic-care/patients/{patient_id}/treatment-summary",
            get(chronic_care::treatment_summary),
        )
        .route(
            "/api/bedside/sessions",
            get(bedside_portal::list_sessions).post(bedside_portal::create_session),
        )
        .route(
            "/api/bedside/sessions/{id}/end",
            put(bedside_portal::end_session),
        )
        .route(
            "/api/bedside/{admission_id}/schedule",
            get(bedside_portal::get_daily_schedule),
        )
        .route(
            "/api/bedside/{admission_id}/medications",
            get(bedside_portal::get_medications),
        )
        .route(
            "/api/bedside/{admission_id}/vitals",
            get(bedside_portal::get_vitals),
        )
        .route(
            "/api/bedside/{admission_id}/lab-results",
            get(bedside_portal::get_lab_results),
        )
        .route(
            "/api/bedside/{admission_id}/diet-order",
            get(bedside_portal::get_diet_order),
        )
        .route(
            "/api/bedside/{admission_id}/nurse-request",
            post(bedside_portal::create_nurse_request),
        )
        .route(
            "/api/bedside/{admission_id}/nurse-requests",
            get(bedside_portal::list_nurse_requests),
        )
        .route(
            "/api/bedside/nurse-requests/{id}/status",
            put(bedside_portal::update_request_status),
        )
        .route(
            "/api/bedside/nurse-calls/active",
            get(nurse_calls::active_nurse_calls),
        )
        .route(
            "/api/bedside/videos",
            get(bedside_portal::list_videos).post(bedside_portal::create_video),
        )
        .route(
            "/api/bedside/videos/{id}",
            put(bedside_portal::update_video),
        )
        .route(
            "/api/bedside/{admission_id}/video-view",
            post(bedside_portal::record_video_view),
        )
        .route(
            "/api/bedside/{admission_id}/feedback",
            post(bedside_portal::submit_feedback).get(bedside_portal::list_feedback),
        )
        .route(
            "/api/case-mgmt/assignments",
            get(case_mgmt::list_assignments).post(case_mgmt::create_assignment),
        )
        .route(
            "/api/case-mgmt/assignments/{id}",
            get(case_mgmt::get_assignment).put(case_mgmt::update_assignment),
        )
        .route(
            "/api/case-mgmt/caseload",
            get(case_mgmt::caseload_summary),
        )
        .route(
            "/api/case-mgmt/auto-assign",
            post(case_mgmt::auto_assign),
        )
        .route(
            "/api/case-mgmt/barriers",
            get(case_mgmt::list_barriers).post(case_mgmt::create_barrier),
        )
        .route(
            "/api/case-mgmt/barriers/{id}",
            put(case_mgmt::update_barrier),
        )
        .route(
            "/api/case-mgmt/referrals",
            get(case_mgmt::list_referrals).post(case_mgmt::create_referral),
        )
        .route(
            "/api/case-mgmt/referrals/{id}",
            put(case_mgmt::update_referral),
        )
        .route(
            "/api/case-mgmt/analytics/dispositions",
            get(case_mgmt::disposition_analytics),
        )
        .route(
            "/api/case-mgmt/analytics/barriers",
            get(case_mgmt::barrier_analytics),
        )
        .route(
            "/api/case-mgmt/analytics/outcomes",
            get(case_mgmt::outcome_analytics),
        )
}
