use sqlx::PgPool;

/// Github-tracked diagnosis reference (national IDSP notifiable list + common
/// OPD diagnoses), generated by `scripts/build_ckb_seed.py`. Committed CSV is
/// the source of truth + backup. Columns:
/// `icd10_code,name,department,is_notifiable,reporting_body,report_timeframe`.
const DIAGNOSIS_REFERENCE_CSV: &str = include_str!("data/diagnosis_reference.csv");

/// Seed the GLOBAL `cds_diagnosis_reference` from the committed CSV. Idempotent
/// (`ON CONFLICT (icd10_code)`); refreshes the notifiable flag/body on re-seed.
pub(super) async fn seed_diagnosis_reference(
    pool: &PgPool,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut tx = pool.begin().await?;
    let mut count = 0usize;

    for line in DIAGNOSIS_REFERENCE_CSV.lines().skip(1) {
        let line = line.trim_end();
        if line.is_empty() {
            continue;
        }
        let cols = parse_csv_row(line);
        // icd10_code,name,department,is_notifiable,reporting_body,report_timeframe
        let Some(icd) = cols.first().map(String::as_str).filter(|s| !s.is_empty()) else {
            continue;
        };
        let name = cols.get(1).map_or("", String::as_str);
        let department = non_empty(cols.get(2));
        let is_notifiable = cols.get(3).map_or("false", String::as_str) == "true";
        let reporting_body = non_empty(cols.get(4));
        let report_timeframe = non_empty(cols.get(5));

        sqlx::query(
            "INSERT INTO cds_diagnosis_reference \
               (icd10_code, name, department, is_notifiable, reporting_body, report_timeframe) \
             VALUES ($1, $2, $3, $4, $5, $6) \
             ON CONFLICT (icd10_code) DO UPDATE SET \
               name = EXCLUDED.name, department = EXCLUDED.department, \
               is_notifiable = EXCLUDED.is_notifiable, \
               reporting_body = EXCLUDED.reporting_body, \
               report_timeframe = EXCLUDED.report_timeframe, updated_at = now()",
        )
        .bind(icd)
        .bind(name)
        .bind(department)
        .bind(is_notifiable)
        .bind(reporting_body)
        .bind(report_timeframe)
        .execute(&mut *tx)
        .await?;
        count += 1;
    }

    tx.commit().await?;
    tracing::info!(rows = count, "Seeded cds_diagnosis_reference");
    Ok(())
}

/// Github-tracked drug formulary (curated public CDS reference + paediatric
/// mg/kg from the local pharmacology dataset), generated by
/// `scripts/build_ckb_seed.py`. Columns:
/// `generic_name,inn_name,atc_code,max_dose_per_day,max_single_dose,dose_per_kg,
///  renal_adjust_egfr_threshold,renal_adjust_rule,hepatic_caution,pregnancy_category`.
const DRUG_FORMULARY_CSV: &str = include_str!("data/drug_formulary.csv");

/// Seed the GLOBAL `cds_drug_reference` from the committed CSV. Idempotent
/// (`ON CONFLICT (generic_name)`).
pub(super) async fn seed_drug_reference(pool: &PgPool) -> Result<(), Box<dyn std::error::Error>> {
    let mut tx = pool.begin().await?;
    let mut count = 0usize;

    for line in DRUG_FORMULARY_CSV.lines().skip(1) {
        let line = line.trim_end();
        if line.is_empty() {
            continue;
        }
        let c = parse_csv_row(line);
        let Some(generic) = c.first().map(String::as_str).filter(|s| !s.is_empty()) else {
            continue;
        };
        // numeric eGFR threshold (column 6) — pass as text, cast in SQL.
        let egfr = non_empty(c.get(6));

        sqlx::query(
            "INSERT INTO cds_drug_reference \
               (generic_name, inn_name, atc_code, max_dose_per_day, max_single_dose, \
                dose_per_kg, renal_adjust_egfr_threshold, renal_adjust_rule, \
                hepatic_caution, pregnancy_category) \
             VALUES ($1, $2, $3, $4, $5, $6, $7::numeric, $8, $9, $10) \
             ON CONFLICT (generic_name) DO UPDATE SET \
               inn_name = EXCLUDED.inn_name, atc_code = EXCLUDED.atc_code, \
               max_dose_per_day = EXCLUDED.max_dose_per_day, \
               max_single_dose = EXCLUDED.max_single_dose, dose_per_kg = EXCLUDED.dose_per_kg, \
               renal_adjust_egfr_threshold = EXCLUDED.renal_adjust_egfr_threshold, \
               renal_adjust_rule = EXCLUDED.renal_adjust_rule, \
               hepatic_caution = EXCLUDED.hepatic_caution, \
               pregnancy_category = EXCLUDED.pregnancy_category, updated_at = now()",
        )
        .bind(generic.to_lowercase())
        .bind(non_empty(c.get(1)))
        .bind(non_empty(c.get(2)))
        .bind(non_empty(c.get(3)))
        .bind(non_empty(c.get(4)))
        .bind(non_empty(c.get(5)))
        .bind(egfr)
        .bind(non_empty(c.get(7)))
        .bind(non_empty(c.get(8)))
        .bind(non_empty(c.get(9)))
        .execute(&mut *tx)
        .await?;
        count += 1;
    }

    tx.commit().await?;
    tracing::info!(rows = count, "Seeded cds_drug_reference");
    Ok(())
}

fn non_empty(value: Option<&String>) -> Option<&str> {
    value.map(String::as_str).filter(|s| !s.is_empty())
}

/// Minimal RFC-4180 row parser (handles quoted fields containing commas).
fn parse_csv_row(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut field = String::new();
    let mut in_quotes = false;
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' if in_quotes && chars.peek() == Some(&'"') => {
                field.push('"');
                chars.next();
            }
            '"' => in_quotes = !in_quotes,
            ',' if !in_quotes => out.push(std::mem::take(&mut field)),
            _ => field.push(c),
        }
    }
    out.push(field);
    out
}
