use sqlx::PgPool;

/// Github-tracked diagnosis reference (national IDSP notifiable list + common
/// OPD diagnoses), generated by `scripts/build_ckb_seed.py`. Committed CSV is
/// the source of truth + backup. Columns:
/// `icd10_code,name,department,is_notifiable,reporting_body,report_timeframe`.
const DIAGNOSIS_REFERENCE_CSV: &str = include_str!("data/diagnosis_reference.csv");

/// Seed the GLOBAL `cds_diagnosis_reference` from the committed CSV. Idempotent
/// (`ON CONFLICT (icd10_code)`); refreshes the notifiable flag/body on re-seed.
pub(super) async fn seed_diagnosis_reference(
    pool: &PgPool,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut tx = pool.begin().await?;
    let mut count = 0usize;

    for line in DIAGNOSIS_REFERENCE_CSV.lines().skip(1) {
        let line = line.trim_end();
        if line.is_empty() {
            continue;
        }
        let cols = parse_csv_row(line);
        // icd10_code,name,department,is_notifiable,reporting_body,report_timeframe
        let Some(icd) = cols.first().map(String::as_str).filter(|s| !s.is_empty()) else {
            continue;
        };
        let name = cols.get(1).map_or("", String::as_str);
        let department = non_empty(cols.get(2));
        let is_notifiable = cols.get(3).map_or("false", String::as_str) == "true";
        let reporting_body = non_empty(cols.get(4));
        let report_timeframe = non_empty(cols.get(5));

        sqlx::query(
            "INSERT INTO cds_diagnosis_reference \
               (icd10_code, name, department, is_notifiable, reporting_body, report_timeframe) \
             VALUES ($1, $2, $3, $4, $5, $6) \
             ON CONFLICT (icd10_code) DO UPDATE SET \
               name = EXCLUDED.name, department = EXCLUDED.department, \
               is_notifiable = EXCLUDED.is_notifiable, \
               reporting_body = EXCLUDED.reporting_body, \
               report_timeframe = EXCLUDED.report_timeframe, updated_at = now()",
        )
        .bind(icd)
        .bind(name)
        .bind(department)
        .bind(is_notifiable)
        .bind(reporting_body)
        .bind(report_timeframe)
        .execute(&mut *tx)
        .await?;
        count += 1;
    }

    tx.commit().await?;
    tracing::info!(rows = count, "Seeded cds_diagnosis_reference");
    Ok(())
}

fn non_empty(value: Option<&String>) -> Option<&str> {
    value.map(String::as_str).filter(|s| !s.is_empty())
}

/// Minimal RFC-4180 row parser (handles quoted fields containing commas).
fn parse_csv_row(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut field = String::new();
    let mut in_quotes = false;
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' if in_quotes && chars.peek() == Some(&'"') => {
                field.push('"');
                chars.next();
            }
            '"' => in_quotes = !in_quotes,
            ',' if !in_quotes => out.push(std::mem::take(&mut field)),
            _ => field.push(c),
        }
    }
    out.push(field);
    out
}
