// GENERATED by scripts/generate_native_tokens.py from packages/design-system/src/theme/tokens.ts — DO NOT EDIT.
package com.medbrains.ui

import androidx.compose.ui.graphics.Color

/** Carbon design tokens. Name a token; never write a hex. */
object Carbon {
    /** 10-step palette; index 0 is the lightest. */
    val blue: List<Color> = listOf(Color(0xFFEDF5FF), Color(0xFFD0E2FF), Color(0xFFA6C8FF), Color(0xFF78A9FF), Color(0xFF4589FF), Color(0xFF0F62FE), Color(0xFF0043CE), Color(0xFF002D9C), Color(0xFF001D6C), Color(0xFF001141))
    /** 10-step palette; index 0 is the lightest. */
    val cinnabar: List<Color> = listOf(Color(0xFFDEFBE6), Color(0xFFA7F0BA), Color(0xFF6FDC8C), Color(0xFF74E792), Color(0xFF42BE65), Color(0xFF42BE65), Color(0xFF0E6027), Color(0xFF044317), Color(0xFF022D0D), Color(0xFF071908))
    /** 4-step palette; index 0 is the lightest. */
    val signatureSpectrumStops: List<Color> = listOf(Color(0xFF001D6C), Color(0xFF0F62FE), Color(0xFF4589FF), Color(0xFFA6C8FF))
    /** 10-step palette; index 0 is the lightest. */
    val mint: List<Color> = listOf(Color(0xFFDEFBE6), Color(0xFFA7F0BA), Color(0xFF6FDC8C), Color(0xFF42BE65), Color(0xFF24A148), Color(0xFF198038), Color(0xFF0E6027), Color(0xFF044317), Color(0xFF022D0D), Color(0xFF08130B))
    /** 11-step palette; index 0 is the lightest. */
    val ink: List<Color> = listOf(Color(0xFFFFFFFF), Color(0xFFF4F4F4), Color(0xFFE0E0E0), Color(0xFFC6C6C6), Color(0xFFA8A8A8), Color(0xFF8D8D8D), Color(0xFF6F6F6F), Color(0xFF525252), Color(0xFF393939), Color(0xFF262626), Color(0xFF161616))
    /** 10-step palette; index 0 is the lightest. */
    val inkDark: List<Color> = listOf(Color(0xFFF5F5F7), Color(0xFFE5E5EA), Color(0xFFC7C7CC), Color(0xFF8E8E93), Color(0xFF636366), Color(0xFF48484A), Color(0xFF3A3A3C), Color(0xFF2C2C2E), Color(0xFF1C1C1E), Color(0xFF000000))
    /** 10-step palette; index 0 is the lightest. */
    val amber: List<Color> = listOf(Color(0xFFFCF4D6), Color(0xFFFDDC69), Color(0xFFF1C21B), Color(0xFFD2A106), Color(0xFFB28600), Color(0xFFF1C21B), Color(0xFF8E6A00), Color(0xFF684E00), Color(0xFF483700), Color(0xFF302400))
    /** 10-step palette; index 0 is the lightest. */
    val rose: List<Color> = listOf(Color(0xFFFFF1F1), Color(0xFFFFD7D9), Color(0xFFFFB3B8), Color(0xFFFF8389), Color(0xFFFA4D56), Color(0xFFDA1E28), Color(0xFFA2191F), Color(0xFF750E13), Color(0xFF520408), Color(0xFF2D0709))
    /** 10-step palette; index 0 is the lightest. */
    val sky: List<Color> = listOf(Color(0xFFE5F6FF), Color(0xFFBAE6FF), Color(0xFF82CFFF), Color(0xFF33B1FF), Color(0xFF1192E8), Color(0xFF0072C3), Color(0xFF00539A), Color(0xFF003A6D), Color(0xFF012749), Color(0xFF061727))
    /** 10-step palette; index 0 is the lightest. */
    val violet: List<Color> = listOf(Color(0xFFEFEEFF), Color(0xFFD7D5FF), Color(0xFFB8B5FF), Color(0xFF9591FF), Color(0xFF7472FF), Color(0xFF5E5CE6), Color(0xFF4B4ABD), Color(0xFF383894), Color(0xFF26266B), Color(0xFF141342))
    /** 10-step palette; index 0 is the lightest. */
    val ochre: List<Color> = listOf(Color(0xFFFFF7ED), Color(0xFFFFEDD5), Color(0xFFFED7AA), Color(0xFFFDBA74), Color(0xFFFB923C), Color(0xFFF97316), Color(0xFFEA580C), Color(0xFFC2410C), Color(0xFF9A3412), Color(0xFF7C2D12))
    /** 10-step palette; index 0 is the lightest. */
    val teal: List<Color> = listOf(Color(0xFFF0FDFA), Color(0xFFCCFBF1), Color(0xFF99F6E4), Color(0xFF5EEAD4), Color(0xFF2DD4BF), Color(0xFF14B8A6), Color(0xFF0D9488), Color(0xFF0F766E), Color(0xFF115E59), Color(0xFF134E4A))
    /** 10-step palette; index 0 is the lightest. */
    val slate: List<Color> = listOf(Color(0xFFF8FAFC), Color(0xFFF1F5F9), Color(0xFFE2E8F0), Color(0xFFCBD5E1), Color(0xFF94A3B8), Color(0xFF64748B), Color(0xFF475569), Color(0xFF334155), Color(0xFF1E293B), Color(0xFF0F172A))

    /** Emergency codes — patient-safety constants, identical on every deployment. */
    object EmergencyCode {
        val blue = Color(0xFF1E63B8)
        val red = Color(0xFFC8102E)
        val pink = Color(0xFFE24C94)
        val black = Color(0xFF0A0A0A)
        val yellow = Color(0xFFE6B422)
        val orange = Color(0xFFE86A1F)
    }
}
