{{- if and (not .Values.database.existingSecret) .Values.database.url -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "medbrains-server.fullname" . }}-db
  labels:
    {{- include "medbrains-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
