/**
 * Smoke for the file-writing logic. We can't easily test the prompt
 * loop with piped stdin (readline's EOF semantics differ from a TTY),
 * so this exercises the synchronous write helpers in isolation. The
 * real CLI is exercised manually against a real TTY when you run it.
 */

import { describe, it, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// We import the index for its side-effect-free exports. main() runs
// only when the file is invoked as a script (`node index.mjs`).
//
// Because the script's helpers aren't exported today, we replicate
// the helper logic here as a contract test — if you change the
// helper output, update this fixture.

function writeTfvarsFixture(path, ctx) {
  const lines = [
    "# DNS section — generated by medbrains-setup-tenant-dns.",
    "# Edit by hand or re-run the tool to regenerate.",
    "",
    `tenant_id            = "${ctx.tenantId}"`,
    `provision_dns        = true`,
    `dns_provider         = "${ctx.provider}"`,
    `dns_zone_name        = "${ctx.zoneName}"`,
    `dns_record_subdomain = "${ctx.subdomain}"`,
  ];
  for (const [k, v] of Object.entries(ctx.extras ?? {})) {
    if (v !== "" && v != null) {
      lines.push(`${k.padEnd(20)} = ${typeof v === "boolean" ? v : `"${v}"`}`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

function shellQuote(v) {
  return `'${String(v).replace(/'/g, "'\\''")}'`;
}

const tmpRoots = [];
after(() => {
  for (const t of tmpRoots) {
    rmSync(t, { recursive: true, force: true });
  }
});

describe("writeTfvars output", () => {
  it("emits valid HCL key=value pairs", () => {
    const out = writeTfvarsFixture(null, {
      tenantId: "hospital-x",
      provider: "godaddy",
      zoneName: "acmehealth.com",
      subdomain: "",
      extras: {},
    });
    assert.match(out, /tenant_id\s*=\s*"hospital-x"/);
    assert.match(out, /dns_provider\s*=\s*"godaddy"/);
    assert.match(out, /dns_zone_name\s*=\s*"acmehealth.com"/);
    assert.match(out, /dns_record_subdomain\s*=\s*""/);
  });

  it("includes provider extras when present", () => {
    const out = writeTfvarsFixture(null, {
      tenantId: "hospital-y",
      provider: "azure",
      zoneName: "az.example.com",
      subdomain: "hospitals",
      extras: { dns_azure_resource_group: "rg-prod" },
    });
    assert.match(out, /dns_azure_resource_group\s*=\s*"rg-prod"/);
  });

  it("renders boolean extras without quotes", () => {
    const out = writeTfvarsFixture(null, {
      tenantId: "h",
      provider: "namecheap",
      zoneName: "n.com",
      subdomain: "",
      extras: { dns_namecheap_overwrite: true },
    });
    assert.match(out, /dns_namecheap_overwrite\s*=\s*true/);
    assert.doesNotMatch(out, /"true"/);
  });
});

describe("shellQuote", () => {
  it("wraps in single quotes", () => {
    assert.equal(shellQuote("plain"), "'plain'");
  });

  it("escapes embedded single quotes", () => {
    assert.equal(shellQuote("a'b"), "'a'\\''b'");
  });

  it("handles empty strings", () => {
    assert.equal(shellQuote(""), "''");
  });
});
