#!/usr/bin/env node
/**
 * `medbrains-setup-tenant-dns` — interactive scaffolder for the DNS
 * portion of a tenant's terraform.tfvars. Asks the operator for the
 * apex zone, the DNS provider, and the matching credentials, then
 * writes:
 *
 *   infra/terraform/envs/tenants/<tenant-id>/terraform.tfvars  (DNS keys only)
 *   infra/terraform/envs/tenants/<tenant-id>/env.sh            (secret env vars; gitignored)
 *
 * Run from the workspace root:
 *
 *   node medbrains/tools/setup-tenant-dns/src/index.mjs
 *
 * Or with a tenant id pre-filled:
 *
 *   node medbrains/tools/setup-tenant-dns/src/index.mjs --tenant=hospital-a
 *
 * GoDaddy is the default provider (it's the only one we currently
 * have credentials for); the script asks for the API key + secret
 * and runs a pre-flight `curl` against api.godaddy.com to confirm
 * the account qualifies before writing anything.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ask, askChoice, askSecret, askYesNo, closePrompts } from "./prompts.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..", "..", "..", "..");
const TENANT_BASE = join(REPO_ROOT, "medbrains", "infra", "terraform", "envs", "tenants");

const PROVIDERS = [
  { value: "godaddy", label: "GoDaddy (currently the only one with active credentials)" },
  { value: "cloudflare", label: "Cloudflare (recommended for new tenants)" },
  { value: "route53", label: "AWS Route53" },
  { value: "azure", label: "Azure DNS" },
  { value: "google", label: "Google Cloud DNS" },
  { value: "digitalocean", label: "DigitalOcean" },
  { value: "namecheap", label: "Namecheap" },
];

function parseArgs(argv) {
  const flags = {};
  for (const a of argv) {
    const m = a.match(/^--([\w-]+)(?:=(.*))?$/u);
    if (m) flags[m[1]] = m[2] ?? "true";
  }
  return flags;
}

async function main() {
  const flags = parseArgs(process.argv.slice(2));
  console.log("\nMedBrains — tenant DNS setup\n");

  const tenantId =
    flags.tenant ?? (await ask("Tenant id (lowercase, hyphenated)", "hospital-a"));
  if (!/^[a-z][a-z0-9-]{2,40}$/u.test(tenantId)) {
    throw new Error(`invalid tenant id: ${tenantId}`);
  }

  const tenantDir = join(TENANT_BASE, tenantId);
  if (!existsSync(tenantDir)) {
    console.log(`\nNo env dir at ${tenantDir} — creating it.`);
    mkdirSync(tenantDir, { recursive: true });
  }

  const tfvarsPath = join(tenantDir, "terraform.tfvars");
  const envPath = join(tenantDir, "env.sh");

  if (existsSync(tfvarsPath)) {
    const overwrite = await askYesNo(
      `${tfvarsPath} already exists. Overwrite the DNS section?`,
      false,
    );
    if (!overwrite) {
      console.log("Aborted.");
      process.exit(0);
    }
  }

  const provider = await askChoice("Which DNS provider hosts this tenant's zone?", PROVIDERS, 0);
  const zoneName = await ask("Apex zone (e.g. acmehealthcare.com — no trailing dot)");
  if (!zoneName.includes(".")) {
    throw new Error(`invalid zone: ${zoneName}`);
  }
  const subdomain = await ask(
    'Subdomain prefix for tenant records (empty = at the apex; e.g. "hospitals" → headscale.hospitals.<zone>)',
    "",
  );

  const extras = await collectProviderExtras(provider);
  const credentials = await collectCredentials(provider);

  if (provider === "godaddy") {
    await preflightGoDaddy(credentials.GODADDY_API_KEY, credentials.GODADDY_API_SECRET);
  }

  writeTfvars(tfvarsPath, {
    tenantId,
    provider,
    zoneName,
    subdomain,
    extras,
  });
  writeEnv(envPath, credentials);

  console.log(`\nWrote:\n  ${tfvarsPath}\n  ${envPath}\n`);
  console.log("Next steps:");
  console.log(`  1. cd ${tenantDir}`);
  console.log("  2. source ./env.sh");
  console.log("  3. terraform init && terraform plan");
  console.log(
    "\nReminder: env.sh holds API secrets. Add it to .gitignore if not already there.\n",
  );
}

function writeTfvars(path, ctx) {
  const lines = [
    "# DNS section — generated by medbrains-setup-tenant-dns.",
    "# Edit by hand or re-run the tool to regenerate.",
    "",
    `tenant_id            = "${ctx.tenantId}"`,
    `provision_dns        = true`,
    `dns_provider         = "${ctx.provider}"`,
    `dns_zone_name        = "${ctx.zoneName}"`,
    `dns_record_subdomain = "${ctx.subdomain}"`,
  ];
  for (const [k, v] of Object.entries(ctx.extras)) {
    if (v !== "" && v != null) {
      lines.push(`${k.padEnd(20)} = ${typeof v === "boolean" ? v : `"${v}"`}`);
    }
  }
  lines.push("");

  if (existsSync(path)) {
    appendFileSync(path, "\n" + lines.join("\n"));
  } else {
    writeFileSync(path, lines.join("\n"));
  }
}

function writeEnv(path, credentials) {
  const lines = [
    "#!/bin/sh",
    "# Tenant DNS credentials — source before running terraform.",
    "# DO NOT COMMIT.",
    "",
  ];
  for (const [k, v] of Object.entries(credentials)) {
    lines.push(`export ${k}=${shellQuote(v)}`);
  }
  lines.push("");
  writeFileSync(path, lines.join("\n"), { mode: 0o600 });
}

function shellQuote(v) {
  return `'${String(v).replace(/'/g, "'\\''")}'`;
}

async function collectProviderExtras(provider) {
  const out = {};
  if (provider === "azure") {
    out.dns_azure_resource_group = await ask("Azure resource group hosting the zone");
  } else if (provider === "google") {
    out.dns_google_project = await ask("GCP project id");
    out.dns_google_managed_zone = await ask(
      "GCP Cloud DNS managed zone resource name (often differs from zone)",
    );
  } else if (provider === "namecheap") {
    out.dns_namecheap_overwrite = await askYesNo(
      "Use Namecheap OVERWRITE mode (deletes existing records)?",
      false,
    );
  }
  return out;
}

async function collectCredentials(provider) {
  const out = {};
  switch (provider) {
    case "godaddy":
      out.GODADDY_API_KEY = await askSecret("GoDaddy API key");
      out.GODADDY_API_SECRET = await askSecret("GoDaddy API secret");
      break;
    case "cloudflare":
      out.CLOUDFLARE_API_TOKEN = await askSecret("Cloudflare API token");
      break;
    case "route53":
      console.log("Route53 reuses the AWS provider's credentials.");
      console.log("Make sure AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY are exported");
      console.log("before running terraform.");
      break;
    case "azure":
      out.ARM_CLIENT_ID = await askSecret("Azure client id");
      out.ARM_CLIENT_SECRET = await askSecret("Azure client secret");
      out.ARM_TENANT_ID = await askSecret("Azure tenant id");
      out.ARM_SUBSCRIPTION_ID = await askSecret("Azure subscription id");
      break;
    case "google":
      out.GOOGLE_APPLICATION_CREDENTIALS = await ask(
        "Path to GCP service-account JSON (absolute)",
      );
      break;
    case "digitalocean":
      out.DIGITALOCEAN_TOKEN = await askSecret("DigitalOcean API token");
      break;
    case "namecheap":
      out.NAMECHEAP_USER_NAME = await ask("Namecheap account username");
      out.NAMECHEAP_API_USER = await ask("Namecheap API user", out.NAMECHEAP_USER_NAME);
      out.NAMECHEAP_API_KEY = await askSecret("Namecheap API key");
      out.NAMECHEAP_CLIENT_IP = await ask(
        "Namecheap client IP (must be allowlisted in Namecheap admin)",
      );
      break;
    default:
      throw new Error(`unknown provider: ${provider}`);
  }
  return out;
}

async function preflightGoDaddy(key, secret) {
  console.log("\nRunning GoDaddy API pre-flight…");
  const result = await fetch("https://api.godaddy.com/v1/domains", {
    headers: { Authorization: `sso-key ${key}:${secret}` },
  });
  if (result.status === 200) {
    const domains = await result.json();
    console.log(
      `  OK — account qualifies (${Array.isArray(domains) ? domains.length : "?"} domains visible).`,
    );
    return;
  }
  if (result.status === 403) {
    console.error("  FAIL — 403 from GoDaddy. The account does NOT qualify for API access.");
    console.error(
      "  Recommended path: register / keep the domain at GoDaddy, but DELEGATE the apex's NS",
    );
    console.error(
      "  records to Cloudflare (free) and re-run this script with --provider=cloudflare.",
    );
    console.error("  See modules/dns/README.md for details.");
    process.exit(1);
  }
  console.error(`  FAIL — unexpected status ${result.status}: ${await result.text()}`);
  process.exit(1);
}

main()
  .catch((err) => {
    console.error(`\nfailed: ${err.message}\n`);
    process.exit(1);
  })
  .finally(closePrompts);
