import {
  IconAmbulance,
  IconAppWindow,
  IconBabyCarriage,
  IconBed,
  IconBrain,
  IconBuildingFactory2,
  IconBuildingHospital,
  IconCalendar,
  IconCalendarStats,
  IconChartBar,
  IconClipboardCheck,
  IconDashboard,
  IconDental,
  IconDeviceDesktopAnalytics,
  IconDeviceTablet,
  IconDoorEnter,
  IconDroplet,
  IconFileAnalytics,
  IconFileCertificate,
  IconFileText,
  IconFileTypePdf,
  IconFirstAidKit,
  IconFlask,
  IconForms,
  IconHeadset,
  IconHeartbeat,
  IconHeartHandshake,
  IconHeartPlus,
  IconHeartRateMonitor,
  IconHistory,
  IconIdBadge2,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconListDetails,
  IconLockSquareRounded,
  IconMessage,
  IconMicroscope,
  IconNews,
  IconPackage,
  IconPill,
  IconPlug,
  IconQrcode,
  IconRadioactive,
  IconReceipt,
  IconReport,
  IconReportMedical,
  IconScale,
  IconSchool,
  IconScissors,
  IconSettings,
  IconShieldCheck,
  IconShieldHalfFilled,
  IconShieldLock,
  IconSignature,
  IconSpray,
  IconStethoscope,
  IconStretching2,
  IconToolsKitchen2,
  IconTruck,
  IconUrgent,
  IconUserCog,
  IconUserSearch,
  IconUserShield,
  IconUsers,
  IconUsersGroup,
  IconVideo,
  IconVirus,
  IconWash,
} from "@tabler/icons-react";
import type { TFunction } from "i18next";
import type { ReactNode } from "react";
import { createElement } from "react";

// ── Types ──

export interface NavItemConfig {
  /** i18n key in the "nav" namespace */
  i18nKey: string;
  path: string;
  /** Icon name string — resolved via ICON_MAP */
  icon: string;
  requiredPermission?: string;
  requiredPermissions?: readonly string[];
  children?: NavItemConfig[];
}

export interface NavGroupConfig {
  key: string;
  items: NavItemConfig[];
}

// ── Icon Map ──

const ICON_MAP: Record<string, React.ComponentType<{ size?: number; stroke?: number }>> = {
  IconLayoutGrid,
  IconHeadset,
  IconNews,
  IconAmbulance,
  IconAppWindow,
  IconMessage,
  IconBed,
  IconBuildingHospital,
  IconBuildingFactory2,
  IconDeviceTablet,
  IconWash,
  IconIdBadge2,
  IconFileCertificate,
  IconFirstAidKit,
  IconCalendar,
  IconChartBar,
  IconDashboard,
  IconDeviceDesktopAnalytics,
  IconDoorEnter,
  IconDroplet,
  IconFileText,
  IconFlask,
  IconForms,
  IconHeartRateMonitor,
  IconLayoutDashboard,
  IconPackage,
  IconPill,
  IconFileTypePdf,
  IconPlug,
  IconQrcode,
  IconRadioactive,
  IconReceipt,
  IconReport,
  IconSchool,
  IconScissors,
  IconSettings,
  IconShieldCheck,
  IconShieldLock,
  IconSignature,
  IconSpray,
  IconStethoscope,
  IconToolsKitchen2,
  IconTruck,
  IconUrgent,
  IconUserCog,
  IconUserShield,
  IconUsers,
  IconUsersGroup,
  IconHeartbeat,
  IconMicroscope,
  IconBrain,
  IconStretching2,
  IconHeartHandshake,
  IconBabyCarriage,
  IconScale,
  IconListDetails,
  IconLockSquareRounded,
  IconShieldHalfFilled,
  IconReportMedical,
  IconVirus,
  IconHeartPlus,
  IconClipboardCheck,
  IconUserSearch,
  IconCalendarStats,
  IconHistory,
  IconFileAnalytics,
  IconDental,
  IconVideo,
};

export function resolveIcon(name: string, size = 20, stroke = 1.5): ReactNode {
  const Icon = ICON_MAP[name];
  if (!Icon) return null;
  return createElement(Icon, { size, stroke });
}

// ── Module identity badges (Adobe-style mark, Carbon-styled) ──
// A short 2–3 letter mark + a hand-picked unique identity colour per module,
// shown in the nav rail and page headers in place of the icon — a compact,
// memorable wayfinding aid. Marks use natural clinical acronyms (OPD, IPD, ICU,
// MRD…); colours are deliberately distinct and dark enough for white text.
export interface ModuleBadge {
  abbr: string;
  color: string;
}

const MODULE_BADGE_DEFS: Record<string, ModuleBadge> = {
  "/dashboard": { abbr: "DB", color: "#4f5b67" },
  "/health-pulse": { abbr: "HP", color: "#0e6027" },
  "/token-board": { abbr: "TB", color: "#4f2d7f" },
  "/token-console": { abbr: "TC", color: "#6929c4" },
  "/patients": { abbr: "Pt", color: "#0f9d8c" },
  "/opd": { abbr: "OPD", color: "#1192e8" },
  "/opd/appointments": { abbr: "Apt", color: "#005d5d" },
  "/telemedicine": { abbr: "Tel", color: "#4589ff" },
  "/doctor/signoffs": { abbr: "Sig", color: "#491d8b" },
  "/emergency": { abbr: "ER", color: "#da1e28" },
  "/order-sets": { abbr: "OS", color: "#009d9a" },
  "/chronic-care": { abbr: "CC", color: "#5e2750" },
  "/radiology": { abbr: "Rad", color: "#0043ce" },
  "/pharmacy": { abbr: "Rx", color: "#8a3ffc" },
  "/pharmacy/finance": { abbr: "PhF", color: "#6020a0" },
  "/blood-bank": { abbr: "BB", color: "#a2191f" },
  "/ipd": { abbr: "IPD", color: "#1f6f8b" },
  "/care-view": { abbr: "CV", color: "#0072c3" },
  "/icu": { abbr: "ICU", color: "#b81921" },
  "/nurse": { abbr: "Nur", color: "#007d79" },
  "/ot": { abbr: "OT", color: "#9f1853" },
  "/diet-kitchen": { abbr: "DK", color: "#8e6a00" },
  "/bedside-portal": { abbr: "BP", color: "#5a6872" },
  "/billing": { abbr: "Bil", color: "#0e7c95" },
  "/insurance": { abbr: "Ins", color: "#0050e6" },
  "/indent": { abbr: "Ind", color: "#6c4b9c" },
  "/procurement": { abbr: "Pro", color: "#a56403" },
  "/cssd": { abbr: "CSD", color: "#4d7c0f" },
  "/housekeeping": { abbr: "HK", color: "#7a5901" },
  "/front-office": { abbr: "FO", color: "#198038" },
  "/lms": { abbr: "LMS", color: "#8a3800" },
  "/bme": { abbr: "BME", color: "#3d5a80" },
  "/assets": { abbr: "Ast", color: "#565656" },
  "/ambulance": { abbr: "Amb", color: "#c5172e" },
  "/communications": { abbr: "Com", color: "#0062ff" },
  "/camp": { abbr: "Cmp", color: "#2a7e3b" },
  "/command-center": { abbr: "CMD", color: "#393939" },
  "/facilities": { abbr: "Fac", color: "#5b6b23" },
  "/mrd": { abbr: "MRD", color: "#57534e" },
  "/clinical-kb": { abbr: "KB", color: "#3b1a8c" },
  "/security": { abbr: "Sec", color: "#6f2da8" },
  "/occupational-health": { abbr: "OH", color: "#15803d" },
  "/utilization-review": { abbr: "UR", color: "#475569" },
  "/case-management": { abbr: "CM", color: "#1c5d4a" },
  "/scheduling": { abbr: "Sch", color: "#0067a0" },
  "/quality": { abbr: "QA", color: "#00767a" },
  "/infection-control": { abbr: "IC", color: "#9a3412" },
  "/consent": { abbr: "Cns", color: "#5d4037" },
  "/regulatory": { abbr: "Reg", color: "#7c5e10" },
  "/analytics": { abbr: "Ana", color: "#1062fe" },
  "/reports": { abbr: "Rep", color: "#4a5568" },
  "/audit": { abbr: "Aud", color: "#6b4226" },
  "/specialty/cath-lab": { abbr: "CL", color: "#9c1a4f" },
  "/specialty/endoscopy": { abbr: "End", color: "#6b6101" },
  "/specialty/psychiatry": { abbr: "Psy", color: "#5a3e9c" },
  "/specialty/pmr": { abbr: "PMR", color: "#3a6b35" },
  "/specialty/palliative": { abbr: "Pal", color: "#715aa6" },
  "/specialty/maternity": { abbr: "Mat", color: "#9e2a6e" },
  "/specialty/other": { abbr: "Spc", color: "#5f5f5f" },
  "/admin/users": { abbr: "Usr", color: "#0f62fe" },
  "/admin/doctors": { abbr: "Doc", color: "#0e4f6b" },
  "/admin/roles": { abbr: "Rol", color: "#5b3ca8" },
  "/admin/groups": { abbr: "Grp", color: "#3949ab" },
  "/admin/sso": { abbr: "SSO", color: "#00539a" },
  "/admin/access-requests": { abbr: "AR", color: "#6d4534" },
  "/admin/nabh-indicators": { abbr: "NB", color: "#11774e" },
  "/setup": { abbr: "Set", color: "#3f3f46" },
  "/admin/settings": { abbr: "Cfg", color: "#525866" },
  "/admin/document-templates": { abbr: "DT", color: "#6b4f9e" },
  "/admin/integration-hub": { abbr: "IH", color: "#0e8a8f" },
  "/admin/doctor-schedules": { abbr: "DS", color: "#00766c" },
  "/admin/documents": { abbr: "Dcs", color: "#4d5358" },
  "/retrospective": { abbr: "Rsp", color: "#7a4a2b" },
  "/admin/devices": { abbr: "Dev", color: "#4151b3" },
  "/admin/paired-devices": { abbr: "PD", color: "#5457d6" },
};

/** Module badge for an exact nav path, or undefined if the module has none. */
export function getModuleBadge(path: string): ModuleBadge | undefined {
  return MODULE_BADGE_DEFS[path];
}

/** Module badge for a live location (longest-prefix match, e.g. /patients/42). */
export function matchModuleBadge(pathname: string): ModuleBadge | undefined {
  let best: string | undefined;
  for (const key of Object.keys(MODULE_BADGE_DEFS)) {
    if ((pathname === key || pathname.startsWith(`${key}/`)) && key.length > (best?.length ?? 0)) {
      best = key;
    }
  }
  return best ? getModuleBadge(best) : undefined;
}

// ── Nav Groups ──

const SETTINGS_NAV_PERMISSIONS = [
  "admin.settings.general.manage",
  "admin.settings.facilities.list",
  "admin.settings.locations.list",
  "admin.settings.departments.list",
  "admin.doctors.list",
  "admin.users.list",
  "admin.roles.list",
  "admin.settings.modules.manage",
  "admin.settings.sequences.manage",
  "admin.settings.services.list",
  "admin.settings.clinical_masters.list",
  "admin.settings.bed_types.manage",
  "admin.settings.billing_tax.manage",
  "admin.settings.branding.manage",
  "admin.settings.regulatory.manage",
  "assets.list",
  "billing.corporate.list",
  "billing.invoices.list",
  "billing.journal.list",
  "communications.config.manage",
  "consent.templates.list",
  "diet.templates.list",
  "documents.templates.list",
  "indent.list",
  "integration.view",
  "ipd.admissions.list",
  "ipd.bed_dashboard.view",
  "ipd.discharge_summary.create",
  "ipd.discharge_summary.finalize",
  "ipd.wards.manage",
  "opd.queue.view",
  "opd.visit.create",
  "opd.visit.update",
  "opd.procedures.list",
  "ipd.tariffs.list",
  "ipd.tariffs.manage",
  "ot.rooms.list",
  "lab.orders.list",
  "lab.reports.view",
  "mrd.records.list",
  "order_sets.templates.list",
  "pharmacy.prescriptions.list",
  "pharmacy.stores.list",
  "pharmacy.stores.manage",
  "procurement.rc.list",
  "procurement.stores.list",
  "procurement.stores.manage",
  "procurement.vendors.list",
  "specialty.other.templates.list",
] as const;

const ADMIN_NAV_PERMISSIONS = [
  "admin.users.list",
  "admin.doctors.list",
  "admin.roles.list",
  "security.access.list",
  "quality.indicators.list",
  ...SETTINGS_NAV_PERMISSIONS,
  "integration.list",
  "opd.schedule.list",
  "documents.templates.list",
  "retrospective.list",
  "devices.list",
  "devices.pairing.paired.list",
] as const;

export const NAV_GROUPS: NavGroupConfig[] = [
  {
    key: "main",
    items: [
      {
        i18nKey: "dashboard",
        path: "/dashboard",
        icon: "IconDashboard",
        requiredPermission: "dashboard.view",
      },
      {
        i18nKey: "healthPulse",
        path: "/health-pulse",
        icon: "IconNews",
        requiredPermission: "dashboard.view",
      },
      {
        i18nKey: "tokenBoard",
        path: "/token-board",
        icon: "IconLayoutGrid",
        requiredPermission: "front_office.queue.list",
      },
      {
        i18nKey: "tokenConsole",
        path: "/token-console",
        icon: "IconHeadset",
        requiredPermission: "front_office.queue.manage",
      },
    ],
  },
  {
    key: "clinical",
    items: [
      {
        i18nKey: "patients",
        path: "/patients",
        icon: "IconUsers",
        requiredPermission: "patients.list",
      },
      {
        i18nKey: "opdQueue",
        path: "/opd",
        icon: "IconStethoscope",
        requiredPermission: "opd.queue.list",
        requiredPermissions: [
          "opd.queue.list",
          "opd.queue.view",
          "opd.visit.create",
          "opd.visit.update",
          "opd.token.manage",
          "opd.appointment.list",
          "opd.referrals.list",
          "opd.referrals.create",
          "opd.vitals.list",
          "opd.vitals.create",
          "opd.diagnoses.list",
          "opd.diagnoses.create",
          "opd.diagnoses.update",
          "opd.diagnoses.delete",
          "opd.procedures.list",
          "opd.procedures.create",
          "opd.procedures.cancel",
          "opd.certificates.list",
          "opd.certificates.create",
          "opd.certificates.print",
          "opd.certificates.reprint",
          "opd.certificates.void",
          "opd.reminders.list",
          "opd.reminders.create",
          "opd.reminders.update",
          "opd.feedback.list",
          "opd.feedback.create",
          "opd.consents.list",
          "opd.consents.create",
          "opd.consents.sign",
          "opd.consents.print",
          "opd.consents.reprint",
          "opd.consents.revoke",
          "opd.schedule.list",
          "opd.schedule.manage",
          "nurse.vitals.record",
        ],
      },
      {
        i18nKey: "appointments",
        path: "/opd/appointments",
        icon: "IconCalendar",
        requiredPermission: "opd.appointment.list",
      },
      {
        i18nKey: "telemedicine",
        path: "/telemedicine",
        icon: "IconVideo",
        requiredPermission: "opd.queue.view",
      },
      {
        i18nKey: "doctorSignoffs",
        path: "/doctor/signoffs",
        icon: "IconSignature",
        requiredPermission: "doctor.signoffs.view_own",
      },
      {
        i18nKey: "emergency",
        path: "/emergency",
        icon: "IconUrgent",
        requiredPermission: "emergency.visits.list",
        requiredPermissions: [
          "emergency.visits.list",
          "emergency.visits.create",
          "emergency.visits.update",
          "emergency.triage.list",
          "emergency.triage.create",
          "emergency.resuscitation.list",
          "emergency.resuscitation.create",
          "emergency.codes.list",
          "emergency.codes.create",
          "emergency.codes.update",
          "emergency.mlc.list",
          "emergency.mlc.create",
          "emergency.mlc.update",
          "emergency.mlc.print",
          "emergency.mlc.reprint",
          "emergency.mlc_documents.sbar.create",
          "emergency.mlc_documents.age_estimation.create",
          "emergency.mlc_documents.pocso.create",
          "emergency.mlc_documents.court_summons.create",
          "emergency.mlc_police_intimations.list",
          "emergency.mlc_police_intimations.create",
          "emergency.mlc_police_intimations.confirm",
          "emergency.mlc_police_intimations.print",
          "emergency.mlc_police_intimations.reprint",
          "emergency.mass_casualty.list",
          "emergency.mass_casualty.create",
          "emergency.mass_casualty.update",
          "emergency.mass_casualty.close",
        ],
      },
      {
        i18nKey: "orderSets",
        path: "/order-sets",
        icon: "IconListDetails",
        requiredPermission: "order_sets.templates.list",
      },
      {
        i18nKey: "chronicCare",
        path: "/chronic-care",
        icon: "IconReportMedical",
        requiredPermission: "chronic.enrollments.list",
      },
    ],
  },
  {
    key: "diagnostics",
    items: [
      { i18nKey: "lab", path: "/lab", icon: "IconFlask", requiredPermission: "lab.orders.list" },
      {
        i18nKey: "radiology",
        path: "/radiology",
        icon: "IconRadioactive",
        requiredPermission: "radiology.orders.list",
      },
      {
        i18nKey: "pharmacy",
        path: "/pharmacy",
        icon: "IconPill",
        requiredPermission: "pharmacy.prescriptions.list",
        requiredPermissions: [
          "pharmacy.prescriptions.list",
          "pharmacy.prescriptions.view",
          "pharmacy.dispensing.create",
          "pharmacy.dispensing.partial",
          "pharmacy.dispensing.cancel",
          "pharmacy.dispensing.void",
          "pharmacy.rx_queue.list",
          "pharmacy.rx_queue.review",
          "pharmacy.pos.view",
          "pharmacy.pos.create",
          "pharmacy.pos.cancel",
          "pharmacy.pos.return",
          "pharmacy.stock.manage",
          "pharmacy.ndps.list",
          "pharmacy.ndps.manage",
          "pharmacy.stores.list",
          "pharmacy.stores.manage",
          "pharmacy.analytics.view",
          "pharmacy.returns.list",
          "pharmacy.returns.request",
          "pharmacy.returns.approve",
          "pharmacy.returns.restock",
          "pharmacy.returns.destroy",
          "pharmacy.returns.reject",
          "pharmacy.safety.view",
        ],
      },
      {
        i18nKey: "pharmacyFinance",
        path: "/pharmacy/finance",
        icon: "IconReceipt",
        requiredPermissions: [
          "pharmacy_finance.cash_drawer.view",
          "pharmacy_finance.cash_drawer.open",
          "pharmacy_finance.cash_drawer.close",
          "pharmacy_finance.petty_cash.view",
          "pharmacy_finance.petty_cash.record",
          "pharmacy_finance.supplier_payments.view",
          "pharmacy_finance.supplier_payments.manage",
          "pharmacy_finance.free_dispensing.view",
          "pharmacy_finance.finance_reports.view",
        ],
      },
      {
        i18nKey: "bloodBank",
        path: "/blood-bank",
        icon: "IconDroplet",
        requiredPermission: "blood_bank.donors.list",
      },
    ],
  },
  {
    key: "inpatient",
    items: [
      {
        i18nKey: "ipd",
        path: "/ipd",
        icon: "IconBed",
        requiredPermission: "ipd.admissions.list",
        requiredPermissions: [
          "ipd.admissions.list",
          "ipd.admissions.view",
          "ipd.admissions.create",
          "ipd.admissions.update",
          "ipd.admissions.print",
          "ipd.admissions.reprint",
          "ipd.attenders.manage",
          "ipd.wristband.print",
          "ipd.wristband.reprint",
          "ipd.discharge.create",
          "ipd.progress_notes.list",
          "ipd.progress_notes.create",
          "ipd.assessments.list",
          "ipd.assessments.create",
          "ipd.mar.list",
          "ipd.mar.create",
          "ipd.mar.update",
          "ipd.io_chart.list",
          "ipd.io_chart.create",
          "ipd.nursing_assessment.list",
          "ipd.nursing_assessment.create",
          "ipd.care_plans.list",
          "ipd.care_plans.create",
          "ipd.handover.list",
          "ipd.handover.create",
          "ipd.discharge_checklist.list",
          "ipd.discharge_checklist.update",
          "ipd.discharge_summary.create",
          "ipd.discharge_summary.finalize",
          "ipd.clinical_docs.list",
          "ipd.clinical_docs.create",
          "ipd.transfers.create",
          "ipd.death_records.manage",
          "ipd.birth_records.manage",
          "ipd.tariffs.list",
          "ipd.tariffs.manage",
          "ipd.bed_dashboard.view",
          "ipd.beds.manage",
          "ipd.reservations.manage",
          "ipd.wards.manage",
          "ipd.reports.view",
          "ipd.discharge_tat.view",
          "ipd.discharge_tat.update",
          "ipd.discharge_tat.billing.update",
          "ipd.discharge_tat.pharmacy.update",
          "ipd.discharge_tat.nursing.update",
          "ipd.discharge_tat.doctor.update",
          "ipd.discharge_tat.complete",
          "pharmacy.prescriptions.list",
          "pharmacy.dispensing.create",
          "billing.invoices.list",
          "billing.invoices.view",
          "billing.advances.list",
          "billing.corporate.list",
          "consent.signatures.list",
          "emergency.mlc.list",
          "lab.orders.list",
          "lab.orders.view",
          "lab.reports.view",
          "lab.orders.create",
          "radiology.orders.list",
          "radiology.orders.view",
          "radiology.orders.create",
          "ot.bookings.list",
          "ot.bookings.create",
          "diet.orders.list",
          "diet.orders.create",
          "bedside.view",
          "nurse.dashboard.view",
          "nurse.mar.view",
          "nurse.vitals.view",
          "nurse.vitals.record",
          "nurse.intake_output.view",
          "nurse.intake_output.record",
          "nurse.pain.view",
          "nurse.pain.record",
          "nurse.fall_risk.view",
          "nurse.fall_risk.record",
          "nurse.wound.view",
          "nurse.wound.record",
          "nurse.handoff.view",
          "nurse.handoff.record",
          "nurse.equipment.view",
          "nurse.equipment.record",
          "nurse.code_blue.view",
          "nurse.code_blue.record",
          "indent.list",
          "indent.consumables.list",
          "assets.list",
          "bme.equipment.list",
          "infection_control.surveillance.list",
          "infection_control.biowaste.list",
          "facilities.gas.list",
          "mrd.case_sheets.generate",
        ],
      },
      {
        i18nKey: "careView",
        path: "/care-view",
        icon: "IconHeartbeat",
        requiredPermission: "care_view.view",
      },
      {
        i18nKey: "icu",
        path: "/icu",
        icon: "IconHeartRateMonitor",
        requiredPermission: "icu.flowsheets.list",
      },
      {
        i18nKey: "nurseActivities",
        path: "/nurse",
        icon: "IconClipboardCheck",
        requiredPermissions: [
          "nurse.dashboard.view",
          "nurse.mar.view",
          "nurse.vitals.view",
          "nurse.vitals.record",
          "nurse.intake_output.view",
          "nurse.intake_output.record",
          "nurse.pain.view",
          "nurse.pain.record",
          "nurse.fall_risk.view",
          "nurse.fall_risk.record",
          "nurse.wound.view",
          "nurse.wound.record",
          "nurse.handoff.view",
          "nurse.handoff.record",
          "nurse.code_blue.view",
          "nurse.code_blue.record",
          "nurse.equipment.view",
          "nurse.equipment.record",
        ],
      },
      {
        i18nKey: "ot",
        path: "/ot",
        icon: "IconScissors",
        requiredPermissions: [
          "ot.bookings.list",
          "ot.bookings.create",
          "ot.rooms.list",
          "ot.rooms.manage",
          "ot.preferences.list",
          "ot.preferences.manage",
          "ot.reports.view",
        ],
      },
      {
        i18nKey: "dietKitchen",
        path: "/diet-kitchen",
        icon: "IconToolsKitchen2",
        requiredPermission: "diet.orders.list",
        requiredPermissions: [
          "diet.orders.list",
          "diet.orders.create",
          "diet.templates.list",
          "diet.templates.manage",
          "diet.kitchen.list",
          "diet.kitchen.manage",
          "diet.inventory.list",
          "diet.inventory.manage",
          "diet.audits.list",
          "diet.audits.create",
        ],
      },
      {
        i18nKey: "bedsidePortal",
        path: "/bedside-portal",
        icon: "IconDeviceTablet",
        requiredPermissions: [
          "bedside.view",
          "bedside.request",
          "bedside.videos.list",
          "bedside.videos.manage",
          "bedside.feedback.list",
          "bedside.feedback.create",
          "bedside.sessions.list",
          "bedside.sessions.manage",
        ],
      },
    ],
  },
  {
    key: "finance",
    items: [
      {
        i18nKey: "billing",
        path: "/billing",
        icon: "IconReceipt",
        requiredPermission: "billing.invoices.list",
        requiredPermissions: [
          "billing.invoices.list",
          "billing.invoices.view",
          "billing.invoices.create",
          "billing.invoices.update",
          "billing.invoices.cancel",
          "billing.catalog.manage",
          "billing.payments.create",
          "billing.payments.void",
          "billing.receipts.print",
          "billing.receipts.reprint",
          "billing.advances.list",
          "billing.advances.create",
          "billing.advances.adjust",
          "billing.advances.refund",
          "billing.corporate.list",
          "billing.corporate.create",
          "billing.corporate.update",
          "billing.corporate.enroll",
          "billing.corporate.unenroll",
          "billing.reports.view",
          "billing.day_close.create",
          "billing.day_close.verify",
          "billing.write_off.create",
          "billing.write_off.approve",
          "billing.audit.view",
          "billing.credit.list",
          "billing.credit.manage",
          "billing.credit.apply",
          "billing.journal.list",
          "billing.journal.create",
          "billing.journal.post",
          "billing.bank_recon.list",
          "billing.bank_recon.manage",
          "billing.tds.list",
          "billing.tds.manage",
          "billing.gst_returns.list",
          "billing.gst_returns.manage",
          "billing.erp.export",
          "billing.concessions.list",
          "billing.concessions.create",
          "billing.concessions.approve",
        ],
      },
      {
        i18nKey: "insurance",
        path: "/insurance",
        icon: "IconShieldHalfFilled",
        requiredPermission: "insurance.verification.list",
      },
    ],
  },
  {
    key: "operations",
    items: [
      {
        i18nKey: "indent",
        path: "/indent",
        icon: "IconPackage",
        requiredPermission: "indent.list",
      },
      {
        i18nKey: "procurement",
        path: "/procurement",
        icon: "IconTruck",
        requiredPermissions: [
          "procurement.vendors.list",
          "procurement.po.list",
          "procurement.grn.list",
          "procurement.rc.list",
          "procurement.stores.list",
          "procurement.stores.manage",
          "procurement.payments.list",
          "procurement.performance.view",
          "indent.stock.manage",
        ],
      },
      {
        i18nKey: "cssd",
        path: "/cssd",
        icon: "IconSpray",
        requiredPermission: "cssd.instruments.list",
      },
      {
        i18nKey: "housekeeping",
        path: "/housekeeping",
        icon: "IconWash",
        requiredPermission: "housekeeping.cleaning.list",
      },
      {
        i18nKey: "frontOffice",
        path: "/front-office",
        icon: "IconDoorEnter",
        requiredPermissions: [
          "front_office.visitors.list",
          "front_office.visitors.create",
          "front_office.visitors.manage",
          "front_office.passes.list",
          "front_office.passes.manage",
          "front_office.queue.list",
          "front_office.queue.manage",
          "front_office.enquiry.list",
          "front_office.enquiry.create",
          "front_office.enquiry.manage",
          "patients.create",
          "opd.visit.create",
          "emergency.visits.create",
          "billing.invoices.create",
        ],
      },
      { i18nKey: "hr", path: "/hr", icon: "IconIdBadge2", requiredPermission: "hr.employees.list" },
      {
        i18nKey: "lms",
        path: "/lms",
        icon: "IconSchool",
        requiredPermission: "lms.my_learning.view",
      },
      {
        i18nKey: "bme",
        path: "/bme",
        icon: "IconDeviceDesktopAnalytics",
        requiredPermission: "bme.equipment.list",
      },
      {
        i18nKey: "assets",
        path: "/assets",
        icon: "IconPackage",
        requiredPermission: "assets.list",
      },
      {
        i18nKey: "ambulance",
        path: "/ambulance",
        icon: "IconAmbulance",
        requiredPermission: "ambulance.fleet.list",
      },
      {
        i18nKey: "communications",
        path: "/communications",
        icon: "IconMessage",
        requiredPermission: "communications.messages.list",
      },
      {
        i18nKey: "camp",
        path: "/camp",
        icon: "IconFirstAidKit",
        requiredPermission: "camp.list",
        requiredPermissions: [
          "camp.list",
          "camp.create",
          "camp.update",
          "camp.assets.manage",
          "camp.registrations.list",
          "camp.registrations.create",
          "camp.registrations.update",
          "camp.screenings.list",
          "camp.screenings.manage",
          "camp.referrals.create",
          "camp.referrals.update",
          "camp.referrals.status",
          "camp.lab.list",
          "camp.lab.manage",
          "camp.billing.list",
          "camp.billing.create",
          "camp.followups.list",
          "camp.followups.schedule",
          "camp.followups.outcome",
          "camp.followups.convert",
        ],
      },
      {
        i18nKey: "commandCenter",
        path: "/command-center",
        icon: "IconLayoutDashboard",
        requiredPermission: "command_center.view",
      },
      {
        i18nKey: "facilities",
        path: "/facilities",
        icon: "IconBuildingFactory2",
        requiredPermission: "facilities.gas.list",
      },
      {
        i18nKey: "mrd",
        path: "/mrd",
        icon: "IconFileCertificate",
        requiredPermission: "mrd.records.list",
      },
      {
        i18nKey: "clinicalKb",
        path: "/clinical-kb",
        icon: "IconVirus",
        requiredPermission: "ckb.view",
      },
      {
        i18nKey: "security",
        path: "/security",
        icon: "IconShieldLock",
        requiredPermission: "security.access.list",
      },
      {
        i18nKey: "occHealth",
        path: "/occupational-health",
        icon: "IconHeartPlus",
        requiredPermission: "occ_health.screenings.list",
      },
      {
        i18nKey: "utilizationReview",
        path: "/utilization-review",
        icon: "IconClipboardCheck",
        requiredPermission: "ur.reviews.list",
      },
      {
        i18nKey: "caseManagement",
        path: "/case-management",
        icon: "IconUserSearch",
        requiredPermission: "case_mgmt.assignments.list",
      },
      {
        i18nKey: "scheduling",
        path: "/scheduling",
        icon: "IconCalendarStats",
        requiredPermission: "scheduling.predictions.list",
      },
    ],
  },
  {
    key: "compliance",
    items: [
      {
        i18nKey: "quality",
        path: "/quality",
        icon: "IconReport",
        requiredPermission: "quality.indicators.list",
      },
      {
        i18nKey: "infectionControl",
        path: "/infection-control",
        icon: "IconShieldCheck",
        requiredPermission: "infection_control.surveillance.list",
        requiredPermissions: [
          "infection_control.surveillance.list",
          "infection_control.stewardship.list",
          "infection_control.biowaste.list",
          "infection_control.hygiene.list",
          "infection_control.outbreak.list",
        ],
      },
      {
        i18nKey: "consent",
        path: "/consent",
        icon: "IconSignature",
        requiredPermission: "consent.templates.list",
      },
      {
        i18nKey: "regulatory",
        path: "/regulatory",
        icon: "IconScale",
        requiredPermission: "regulatory.dashboard.view",
      },
      {
        i18nKey: "analytics",
        path: "/analytics",
        icon: "IconChartBar",
        requiredPermission: "analytics.view",
      },
      {
        i18nKey: "reports",
        path: "/reports",
        icon: "IconReport",
        requiredPermission: "analytics.view",
      },
      {
        i18nKey: "audit",
        path: "/audit",
        icon: "IconFileAnalytics",
        requiredPermission: "audit.log.view",
      },
    ],
  },
  {
    key: "specialty",
    items: [
      {
        i18nKey: "cathLab",
        path: "/specialty/cath-lab",
        icon: "IconHeartbeat",
        requiredPermission: "specialty.cath_lab.procedures.list",
      },
      {
        i18nKey: "endoscopy",
        path: "/specialty/endoscopy",
        icon: "IconMicroscope",
        requiredPermission: "specialty.endoscopy.procedures.list",
      },
      {
        i18nKey: "psychiatry",
        path: "/specialty/psychiatry",
        icon: "IconBrain",
        requiredPermission: "specialty.psychiatry.patients.list",
      },
      {
        i18nKey: "pmr",
        path: "/specialty/pmr",
        icon: "IconStretching2",
        requiredPermission: "specialty.pmr.plans.list",
      },
      {
        i18nKey: "palliative",
        path: "/specialty/palliative",
        icon: "IconHeartHandshake",
        requiredPermissions: [
          "specialty.palliative.dnr.list",
          "specialty.palliative.dnr.manage",
          "specialty.palliative.pain.list",
          "specialty.palliative.pain.create",
          "specialty.palliative.mortuary.list",
          "specialty.palliative.mortuary.manage",
          "specialty.palliative.nucmed.list",
          "specialty.palliative.nucmed.create",
          "specialty.palliative.nucmed.manage",
        ],
      },
      {
        i18nKey: "maternity",
        path: "/specialty/maternity",
        icon: "IconBabyCarriage",
        requiredPermission: "specialty.maternity.registrations.list",
      },
      {
        i18nKey: "otherSpecialties",
        path: "/specialty/other",
        icon: "IconStethoscope",
        requiredPermission: "specialty.other.records.list",
      },
    ],
  },
  {
    key: "admin",
    items: [
      {
        i18nKey: "admin",
        path: "/admin/users",
        icon: "IconSettings",
        requiredPermissions: ADMIN_NAV_PERMISSIONS,
        children: [
          {
            i18nKey: "users",
            path: "/admin/users",
            icon: "IconUserCog",
            requiredPermission: "admin.users.list",
          },
          {
            i18nKey: "doctors",
            path: "/admin/doctors",
            icon: "IconStethoscope",
            requiredPermission: "admin.doctors.list",
          },
          {
            i18nKey: "roles",
            path: "/admin/roles",
            icon: "IconUserShield",
            requiredPermission: "admin.roles.list",
          },
          {
            i18nKey: "groups",
            path: "/admin/groups",
            icon: "IconUsersGroup",
            requiredPermission: "admin.users.list",
          },
          {
            i18nKey: "sso",
            path: "/admin/sso",
            icon: "IconLockSquareRounded",
            requiredPermission: "admin.settings.general.manage",
          },
          {
            i18nKey: "accessRequests",
            path: "/admin/access-requests",
            icon: "IconShieldLock",
            requiredPermission: "security.access.list",
          },
          {
            i18nKey: "nabhIndicators",
            path: "/admin/nabh-indicators",
            icon: "IconChartBar",
            requiredPermission: "quality.indicators.list",
          },
          {
            i18nKey: "setupCenter",
            path: "/setup",
            icon: "IconListDetails",
            requiredPermission: "admin.settings.general.manage",
          },
          {
            i18nKey: "settings",
            path: "/admin/settings",
            icon: "IconSettings",
            requiredPermission: "admin.settings.general.manage",
            requiredPermissions: SETTINGS_NAV_PERMISSIONS,
          },
          {
            i18nKey: "documentTemplates",
            path: "/admin/document-templates",
            icon: "IconFileTypePdf",
            requiredPermission: "admin.settings.general.manage",
          },
          {
            i18nKey: "integrationHub",
            path: "/admin/integration-hub",
            icon: "IconPlug",
            requiredPermission: "integration.list",
          },
          {
            i18nKey: "doctorSchedules",
            path: "/admin/doctor-schedules",
            icon: "IconCalendar",
            requiredPermission: "opd.schedule.list",
          },
          {
            i18nKey: "documents",
            path: "/admin/documents",
            icon: "IconFileText",
            requiredPermission: "documents.templates.list",
          },
          {
            i18nKey: "retrospective",
            path: "/retrospective",
            icon: "IconHistory",
            requiredPermission: "retrospective.list",
          },
          {
            i18nKey: "devices",
            path: "/admin/devices",
            icon: "IconPlug",
            requiredPermission: "devices.list",
          },
          {
            i18nKey: "pairedDevices",
            path: "/admin/paired-devices",
            icon: "IconQrcode",
            requiredPermission: "devices.pairing.paired.list",
          },
        ],
      },
    ],
  },
];

// ── Breadcrumb path labels ──

/** Walk the nav tree and build a path→label map using the given translation function. */
export function buildPathLabels(groups: NavGroupConfig[], t: TFunction): Record<string, string> {
  const labels: Record<string, string> = {};

  function walk(items: NavItemConfig[]) {
    for (const item of items) {
      labels[item.path] = t(item.i18nKey, { ns: "nav" });
      if (item.children) walk(item.children);
    }
  }

  for (const group of groups) {
    walk(group.items);
  }

  // Extra labels for parent breadcrumb segments not in the nav tree
  labels["/admin"] = t("administration", { ns: "nav" });
  labels["/specialty"] = t("specialty", { ns: "nav" });
  labels["/m"] = t("modules", { ns: "nav" });
  labels["/patients/register"] = "Register Patient";
  labels["/opd/new"] = "New Visit";
  labels["/opd/queue"] = "Queue";
  labels["/billing/invoices"] = "Invoice";
  labels["/ipd/new"] = "New Admission";
  labels["/ipd/admissions"] = "Admission";
  labels["/camp/new"] = "New Camp";

  return labels;
}
