//! Ancillary leaf crate: clinical trials registry + front office. Billing-free.

use axum::{Router, routing::{get,post,put}};
use medbrains_server_core::state::AppState;

pub mod clinical_trials;
pub mod front_office;

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/api/clinical-trials",
            get(clinical_trials::list_trials).post(clinical_trials::create_trial),
        )
        .route(
            "/api/clinical-trials/{id}",
            get(clinical_trials::get_trial).put(clinical_trials::update_trial),
        )
        .route(
            "/api/clinical-trials/{id}/candidates",
            get(clinical_trials::screen_candidates),
        )
        .route(
            "/api/clinical-trials/{id}/consents",
            get(clinical_trials::list_trial_consents).post(clinical_trials::record_trial_consent),
        )
        .route(
            "/api/clinical-trials/{id}/visits",
            get(clinical_trials::list_trial_visits).post(clinical_trials::schedule_visit),
        )
        .route(
            "/api/trial-visits/{id}",
            put(clinical_trials::update_visit),
        )
        .route(
            "/api/clinical-trials/{id}/adverse-events",
            get(clinical_trials::list_adverse_events).post(clinical_trials::report_adverse_event),
        )
        .route(
            "/api/trial-adverse-events/{id}",
            put(clinical_trials::update_adverse_event),
        )
        .route(
            "/api/clinical-trials/{id}/randomizations",
            get(clinical_trials::list_randomizations).post(clinical_trials::randomize_patient),
        )
        .route(
            "/api/trial-randomizations/{id}/unblind",
            post(clinical_trials::unblind_randomization),
        )
        .route(
            "/api/clinical-trials/{id}/irb",
            get(clinical_trials::list_irb_submissions).post(clinical_trials::create_irb_submission),
        )
        .route(
            "/api/trial-irb/{id}",
            put(clinical_trials::update_irb_submission),
        )
        .route(
            "/api/clinical-trials/{id}/export",
            get(clinical_trials::export_trial),
        )
        .route(
            "/api/front-office/visiting-hours",
            get(front_office::list_visiting_hours)
                .post(front_office::upsert_visiting_hours),
        )
        .route(
            "/api/front-office/visitors",
            get(front_office::list_visitors)
                .post(front_office::create_visitor),
        )
        .route(
            "/api/front-office/passes",
            get(front_office::list_passes)
                .post(front_office::create_pass),
        )
        .route(
            "/api/front-office/passes/{id}/revoke",
            put(front_office::revoke_pass),
        )
        .route(
            "/api/front-office/visitor-logs",
            get(front_office::list_visitor_logs),
        )
        .route(
            "/api/front-office/visitor-logs/{pass_id}/check-in",
            post(front_office::check_in_visitor),
        )
        .route(
            "/api/front-office/visitor-logs/{pass_id}/check-out",
            put(front_office::check_out_visitor),
        )
        .route(
            "/api/front-office/queue-priority",
            get(front_office::list_queue_priority_rules)
                .post(front_office::upsert_queue_priority),
        )
        .route(
            "/api/front-office/display-config",
            get(front_office::list_display_config)
                .post(front_office::upsert_display_config),
        )
        .route(
            "/api/front-office/enquiries",
            get(front_office::list_enquiries)
                .post(front_office::create_enquiry),
        )
        .route(
            "/api/front-office/enquiries/{id}/resolve",
            put(front_office::resolve_enquiry),
        )
        .route(
            "/api/front-office/queue-stats",
            get(front_office::get_queue_stats),
        )
        .route(
            "/api/front-office/analytics",
            get(front_office::visitor_analytics),
        )
        .route(
            "/api/front-office/queue/metrics",
            get(front_office::queue_metrics),
        )
}
