// Reports static catalog — the built-in NABH/clinical/financial report family definitions.
// Pure move from reports.tsx (fallback catalog when the API returns none).

import { P } from "@medbrains/types";
import {
  IconCalendarStats,
  IconChartBar,
  IconCurrencyRupee,
  IconFileAnalytics,
  IconFlask,
  IconHeartRateMonitor,
  IconScale,
  IconStethoscope,
} from "@tabler/icons-react";
import type { ReportExport, ReportFamily } from "./types";

const STANDARD_EXPORTS: ReportExport[] = ["PDF", "Excel", "CSV", "PNG"];
const GOVERNED_EXPORTS: ReportExport[] = ["PDF", "PNG", "Excel", "CSV"];

export const REPORT_FAMILIES: readonly ReportFamily[] = [
  {
    id: "executive",
    title: "Executive Command",
    eyebrow: "Hospital operating board",
    description:
      "Morning command center for leadership: capacity, money, safety, queues, and red flags.",
    icon: IconChartBar,
    accent: "blue",
    reports: [
      {
        id: "enterprise-kpi-command-board",
        title: "Enterprise KPI command board",
        purpose:
          "OPD visits, IPD census, occupancy, collections, TAT breaches, and incidents in one board.",
        sourceTables: [
          "appointments",
          "admissions",
          "invoices",
          "payments",
          "quality_indicators",
          "quality_incidents",
        ],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["line", "gauge", "custom KPI cards"],
        visualKind: "command",
        refresh: "Intraday / daily",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["service line", "facility", "department", "exception list"],
      },
      {
        id: "occupancy-queue-pressure",
        title: "Occupancy and queue pressure",
        purpose: "Congestion signal across beds, ICU, transfers, and OPD queues.",
        sourceTables: ["admissions", "wards", "beds", "opd_queues", "bed_reservations"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["line", "stacked bar", "heat strip"],
        visualKind: "heatmap",
        refresh: "5-15 min",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["ward", "room", "bed", "clinic", "doctor"],
      },
      {
        id: "revenue-collections-leakage",
        title: "Revenue, collections, and leakage",
        purpose: "Gross billing, net billing, concessions, refunds, and write-down direction.",
        sourceTables: ["invoices", "payments", "billing_concessions", "refunds", "credit_notes"],
        permissions: [P.BILLING.REPORTS_VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["line", "waterfall", "stacked bar"],
        visualKind: "sankey",
        refresh: "Intraday / day close",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["invoice class", "payer", "department", "refund approval"],
      },
      {
        id: "safety-compliance-red-flags",
        title: "Safety and compliance red flags",
        purpose:
          "Open incidents, overdue CAPA, critical alerts, unsigned records, and audit slippage.",
        sourceTables: [
          "quality_incidents",
          "quality_capa",
          "quality_audits",
          "lab_critical_alerts",
          "audit_log",
          "signed_records",
        ],
        permissions: [P.QUALITY.INDICATORS_LIST],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["matrix", "heatmap", "alert list"],
        visualKind: "matrix",
        refresh: "Near-real-time / daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["severity", "department", "owner", "case drawer"],
      },
    ],
  },
  {
    id: "opd",
    title: "OPD",
    eyebrow: "Front door demand",
    description:
      "Registration, queue, consultant load, cancellations, no-shows, revisits, and patient source.",
    icon: IconStethoscope,
    accent: "teal",
    reports: [
      {
        id: "opd-registration-arrivals",
        title: "Registration and arrival trend",
        purpose: "Registrations, arrivals, walk-ins, and conversion to encounter.",
        sourceTables: ["patients", "appointments", "encounters"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["line", "area", "bar"],
        visualKind: "line",
        refresh: "5-15 min / intraday",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["clinic", "consultant", "patient type", "age/sex"],
      },
      {
        id: "opd-queue-wait-heatmap",
        title: "Queue wait heatmap",
        purpose: "Median and 90th percentile wait by day, hour, clinic, and doctor.",
        sourceTables: ["opd_queues", "appointments", "encounters", "queue_tokens"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["heatmap", "line"],
        visualKind: "heatmap",
        refresh: "5-15 min",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["hour", "clinic", "consultant", "patient queue list"],
      },
      {
        id: "opd-consultant-slot-utilization",
        title: "Consultant load and slot utilization",
        purpose: "Slots booked, filled, overrun, idle capacity, and clinic-template pressure.",
        sourceTables: ["appointments", "encounters", "doctor_schedules", "doctor_profiles"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["stacked bar", "line"],
        visualKind: "line",
        refresh: "Intraday",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["consultant", "specialty", "slot duration", "payer"],
      },
      {
        id: "opd-no-show-revisit",
        title: "No-show, cancellation, and revisit behavior",
        purpose: "No-show percentage, short-notice cancellations, and revisit within 7/30 days.",
        sourceTables: ["appointments", "encounters", "noshow_prediction_scores", "patients"],
        permissions: [P.SCHEDULING.ANALYTICS_VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["cohort heatmap", "line"],
        visualKind: "heatmap",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["clinic", "consultant", "time band", "cohort"],
      },
    ],
  },
  {
    id: "ipd",
    title: "IPD",
    eyebrow: "Beds / discharge / utilization",
    description:
      "Ward census, occupancy, length of stay, bed turnaround, and discharge bottlenecks.",
    icon: IconHeartRateMonitor,
    accent: "cyan",
    reports: [
      {
        id: "ipd-census-bed-occupancy",
        title: "Census and bed occupancy",
        purpose: "Daily census, occupancy percentage, ICU load, and reserve vs available beds.",
        sourceTables: ["admissions", "wards", "beds", "bed_reservations"],
        permissions: [P.IPD.REPORTS_VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["line", "stacked bar"],
        visualKind: "line",
        refresh: "Near-real-time / hourly",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["ward", "specialty", "bed class", "ICU/non-ICU"],
      },
      {
        id: "ipd-alos-case-mix",
        title: "ALOS vs case mix",
        purpose: "Length of stay by service line versus baseline and outlier distribution.",
        sourceTables: ["admissions", "encounters", "diagnoses", "billing_packages"],
        permissions: [P.IPD.REPORTS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["boxplot", "control line"],
        visualKind: "boxplot",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["specialty", "diagnosis group", "payer", "outlier admission"],
      },
      {
        id: "ipd-bed-turnaround-delay",
        title: "Bed turnaround and housekeeping delay",
        purpose: "Vacate-to-clean, clean-to-ready, transfer friction, and bed-supply blockers.",
        sourceTables: ["bed_turnaround_log", "beds", "wards", "room_turnarounds"],
        permissions: [P.IPD.REPORTS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["boxplot", "bar"],
        visualKind: "boxplot",
        refresh: "Real-time / shift",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["ward", "bed class", "housekeeping shift", "bed"],
      },
      {
        id: "ipd-discharge-delay-readmission",
        title: "Discharge delay and readmission",
        purpose: "Delay causes, discharge bottlenecks, and 7/30-day readmission watch.",
        sourceTables: ["admissions", "ipd_discharge_tat_log", "encounters", "discharge_barriers"],
        permissions: [P.IPD.REPORTS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["funnel", "line"],
        visualKind: "funnel",
        refresh: "Shift / daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["specialty", "consultant", "payer", "delay reason"],
      },
    ],
  },
  {
    id: "lab",
    title: "Laboratory",
    eyebrow: "TAT / quality / traceability",
    description: "Turnaround, critical alerts, sample rejections, QC, EQAS, and outsourced tests.",
    icon: IconFlask,
    accent: "grape",
    reports: [
      {
        id: "lab-end-to-end-tat",
        title: "End-to-end lab TAT",
        purpose: "Order-to-collection, collection-to-result, and result-to-validation TAT.",
        sourceTables: ["lab_orders", "lab_results", "tat_records"],
        permissions: [P.LAB.REPORTS_VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["line", "boxplot"],
        visualKind: "boxplot",
        refresh: "15 min / hourly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["test group", "priority", "ward/OPD", "lab section"],
      },
      {
        id: "lab-critical-value-notification",
        title: "Critical value notification compliance",
        purpose: "Critical values within target time, read-back, and acknowledgement lag.",
        sourceTables: ["lab_critical_alerts", "lab_results", "comm_critical_alerts"],
        permissions: [P.LAB.REPORTS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["funnel", "bullet bar"],
        visualKind: "funnel",
        refresh: "Near-real-time",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["test", "shift", "ward", "ordering doctor"],
      },
      {
        id: "lab-sample-rejection-recollection",
        title: "Sample rejection and recollection",
        purpose: "Rejection rate, reason Pareto, and recollection burden by unit.",
        sourceTables: ["lab_sample_rejections", "lab_orders", "lab_phlebotomy_queue"],
        permissions: [P.LAB.REPORTS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["Pareto bar", "heatmap"],
        visualKind: "heatmap",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["collection point", "unit", "phlebotomist", "sample type"],
      },
      {
        id: "lab-qc-eqas-outsourced",
        title: "QC/EQAS and outsourced dependency",
        purpose: "QC failures, EQAS trend, outsourced test share, and external TAT.",
        sourceTables: ["lab_qc_results", "lab_eqas_results", "lab_outsourced_orders"],
        permissions: [P.LAB.REPORTS_VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["heatmap", "stacked bar"],
        visualKind: "heatmap",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["analyzer", "test class", "vendor", "section"],
      },
    ],
  },
  {
    id: "radiology",
    title: "Radiology / DICOM",
    eyebrow: "Imaging workflow",
    description: "Modality use, RIS/PACS/DICOM status, reports, dose, and critical findings.",
    icon: IconFlask,
    accent: "violet",
    reports: [
      {
        id: "radiology-modality-utilization",
        title: "Modality load and scheduling utilization",
        purpose: "CT/MRI/X-ray/USG volume, slot utilization, idle time, and machine pressure.",
        sourceTables: ["radiology_orders", "radiology_dicom_studies", "radiology_modalities"],
        permissions: [P.RADIOLOGY.ORDERS_LIST],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["stacked bar", "calendar heatmap"],
        visualKind: "heatmap",
        refresh: "15 min / hourly",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["modality", "machine", "shift", "ordering unit"],
      },
      {
        id: "radiology-order-report-tat-backlog",
        title: "Order-to-report TAT and backlog",
        purpose: "Order-to-scan, scan-to-prelim, prelim-to-final, and aged backlog.",
        sourceTables: ["radiology_orders", "radiology_reports", "tat_records"],
        permissions: [P.RADIOLOGY.ORDERS_LIST],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["boxplot", "burn-down line"],
        visualKind: "boxplot",
        refresh: "15 min / hourly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["modality", "priority", "radiologist", "department"],
      },
      {
        id: "radiology-dose-dosimetry",
        title: "Dose/dosimetry and radiation safety",
        purpose: "Patient dose trends, staff TLD compliance, and protocol outliers.",
        sourceTables: [
          "radiation_dose_records",
          "radiology_dosimetry_records",
          "radiology_dicom_studies",
        ],
        permissions: [P.RADIOLOGY.ORDERS_LIST],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["control chart", "heatmap"],
        visualKind: "heatmap",
        refresh: "Daily / monthly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["modality", "protocol", "machine", "staff role"],
      },
      {
        id: "radiology-quality-critical-findings",
        title: "Report quality, amendments, and critical findings",
        purpose: "Amendment rate, unsigned reports, critical result acknowledgement, and severity.",
        sourceTables: ["radiology_reports", "signed_records", "audit_log", "comm_critical_alerts"],
        permissions: [P.RADIOLOGY.ORDERS_LIST],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["bar", "funnel"],
        visualKind: "funnel",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["radiologist", "modality", "report type", "severity"],
      },
    ],
  },
  {
    id: "pharmacy",
    title: "Pharmacy",
    eyebrow: "Medication safety / inventory",
    description:
      "Dispensing, stock, expiry, NDPS, high-risk drugs, returns, ADR, and margin leakage.",
    icon: IconHeartRateMonitor,
    accent: "green",
    reports: [
      {
        id: "pharmacy-fulfillment-turnaround",
        title: "Prescription fulfillment and turnaround",
        purpose: "Ordered vs dispensed, partial fills, substitutions, and dispense time.",
        sourceTables: ["pharmacy_prescriptions", "pharmacy_orders", "pharmacy_order_items"],
        permissions: [P.PHARMACY.ANALYTICS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["funnel", "line"],
        visualKind: "funnel",
        refresh: "15 min / hourly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["doctor", "department", "formulation", "IP/OP"],
      },
      {
        id: "pharmacy-stockout-expiry-days-on-hand",
        title: "Stockout risk, near-expiry, days on hand",
        purpose: "At-risk SKUs, expiry exposure, replenishment urgency, and wastage.",
        sourceTables: ["pharmacy_batches", "pharmacy_stock_transactions", "purchase_orders"],
        permissions: [P.PHARMACY.ANALYTICS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["heatmap", "treemap"],
        visualKind: "treemap",
        refresh: "15 min / hourly",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["store", "SKU", "category", "vendor", "ABC/VED class"],
      },
      {
        id: "pharmacy-ndps-high-risk-compliance",
        title: "NDPS and high-risk medication compliance",
        purpose: "Controlled-drug issue logs, dual-check completion, variance, and witness gaps.",
        sourceTables: ["pharmacy_ndps_register", "pharmacy_catalog", "pharmacy_orders"],
        permissions: [P.PHARMACY.ANALYTICS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["heatmap", "control chart"],
        visualKind: "heatmap",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["store", "drug", "pharmacist", "shift"],
      },
      {
        id: "pharmacy-safety-returns-margin-leakage",
        title: "Medication safety, ADRs, returns, and margin leakage",
        purpose: "High-risk alerts, ADR trend, returns, credit leakage, and drug margin loss.",
        sourceTables: [
          "pharmacy_allergy_check_log",
          "adr_reports",
          "pharmacy_returns",
          "pharmacy_credit_notes",
          "pharmacy_drug_margin_daily",
        ],
        permissions: [P.PHARMACY.ANALYTICS_VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["sankey", "waterfall", "line"],
        visualKind: "sankey",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["drug class", "unit", "pharmacist", "doctor", "vendor"],
      },
    ],
  },
  {
    id: "finance",
    title: "Billing / Finance",
    eyebrow: "Revenue cycle",
    description:
      "Gross-to-net, collections, settlement, aging, DNFB, denials, refunds, concessions.",
    icon: IconCurrencyRupee,
    accent: "lime",
    reports: [
      {
        id: "billing-gross-net-payer-mix",
        title: "Gross-to-net revenue and payer mix",
        purpose: "Gross charges, deductions, package mix, payer mix, and service-line performance.",
        sourceTables: ["invoices", "invoice_items", "payments", "billing_concessions"],
        permissions: [P.BILLING.REPORTS_VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["stacked bar", "line", "sunburst"],
        visualKind: "treemap",
        refresh: "Intraday / daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["payer", "department", "package", "service line"],
      },
      {
        id: "billing-collections-settlement",
        title: "Collections, cash, and daily settlement",
        purpose: "POS cash, digital collections, payment mode, and settlement variance.",
        sourceTables: ["payments", "invoices", "day_end_closes", "payment_gateway_transactions"],
        permissions: [P.BILLING.REPORTS_VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["line", "waterfall"],
        visualKind: "sankey",
        refresh: "Intraday / day close",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["counter", "cashier", "payment mode", "payer"],
      },
      {
        id: "billing-ar-dnfb-unpaid-discharge",
        title: "A/R aging, DNFB, unpaid discharge",
        purpose: "Aging buckets, discharged-not-final-billed, and discharge without clearance.",
        sourceTables: ["invoices", "payments", "admissions", "credit_patients", "insurance_claims"],
        permissions: [P.BILLING.REPORTS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["heatmap", "bar"],
        visualKind: "heatmap",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["payer", "aging bucket", "department", "ward"],
      },
      {
        id: "billing-denials-refunds-concessions",
        title: "Denials, refunds, and concessions",
        purpose: "Rejections by cause, refund load, concession trend, and leakage path.",
        sourceTables: ["refunds", "credit_notes", "billing_concessions", "insurance_claims"],
        permissions: [P.BILLING.REPORTS_VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["sankey", "waterfall", "Pareto"],
        visualKind: "sankey",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["payer", "denial code", "package", "department"],
      },
    ],
  },
  {
    id: "camp",
    title: "Camp",
    eyebrow: "Outreach / remote operations",
    description:
      "Coverage, turnout, screenings, referrals, offline sync, supplies, and field incidents.",
    icon: IconCalendarStats,
    accent: "orange",
    reports: [
      {
        id: "camp-coverage-turnout",
        title: "Camp coverage and turnout trend",
        purpose:
          "Camp count, registrations, turnout, location performance, and organizer workload.",
        sourceTables: ["camps", "camp_registrations", "camp_remote_setups"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["line", "map", "stacked bar"],
        visualKind: "map",
        refresh: "After event / daily",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["village", "organizer", "camp type", "date"],
      },
      {
        id: "camp-screening-referral-conversion",
        title: "Screening yield and referral conversion",
        purpose:
          "Positive-screen yield, referral issued, referral arrived, and admitted conversion.",
        sourceTables: ["camp_screenings", "camp_referrals", "camp_lab_samples"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["funnel", "treemap"],
        visualKind: "funnel",
        refresh: "Daily",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["camp", "condition", "age/sex", "village"],
      },
      {
        id: "camp-disease-followup-map",
        title: "Disease cluster and follow-up map",
        purpose: "Geographic clustering of positives and follow-up completion.",
        sourceTables: ["camp_screenings", "camp_referrals", "camp_followups", "patient_addresses"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["geo scatter", "heatmap"],
        visualKind: "map",
        refresh: "Daily / weekly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["disease", "geography", "date window", "camp type"],
      },
      {
        id: "camp-sync-supplies-incidents",
        title: "Offline sync, supplies, and incident health",
        purpose: "Sync lag, failed uploads, supply use, field incidents, and device reliability.",
        sourceTables: ["camp_sync_events", "camp_supply_items", "camp_incidents"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["status matrix", "line", "bar"],
        visualKind: "matrix",
        refresh: "Real-time during camp",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["device", "field worker", "camp", "date"],
      },
    ],
  },
  {
    id: "quality",
    title: "NABH / Quality",
    eyebrow: "Evidence / incidents / CAPA",
    description:
      "NABH indicator evidence, incidents, sentinel events, CAPA, audit closure, feedback, and complaints.",
    icon: IconScale,
    accent: "red",
    reports: [
      {
        id: "nabh-evidence-matrix",
        title: "NABH indicator evidence matrix",
        purpose:
          "Indicator status, evidence completeness, trend direction, and submission readiness.",
        sourceTables: ["quality_indicators", "quality_indicator_values", "quality_audits"],
        permissions: [P.QUALITY.INDICATORS_LIST],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["matrix", "sparkline"],
        visualKind: "matrix",
        refresh: "Daily / weekly / monthly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["indicator", "chapter", "department", "month/quarter"],
      },
      {
        id: "quality-incident-sentinel-trend",
        title: "Incident and sentinel-event trend",
        purpose: "Incident count, severity mix, near-miss ratio, and event type Pareto.",
        sourceTables: ["quality_incidents", "quality_committees"],
        permissions: [P.QUALITY.INDICATORS_LIST],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["line", "stacked bar", "Pareto"],
        visualKind: "line",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["severity", "department", "event type", "shift"],
      },
      {
        id: "quality-capa-audit-aging",
        title: "CAPA and audit nonconformity aging",
        purpose: "Open CAPAs, overdue actions, audit NC closure time, and owner discipline.",
        sourceTables: ["quality_capa", "quality_audits", "quality_action_items"],
        permissions: [P.QUALITY.INDICATORS_LIST],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["funnel", "boxplot"],
        visualKind: "funnel",
        refresh: "Weekly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["chapter", "owner", "department", "severity"],
      },
      {
        id: "quality-feedback-complaints-prem-prom",
        title: "Patient feedback, complaints, PROM/PREM",
        purpose: "Complaint aging, satisfaction trend, patient experience, and service recovery.",
        sourceTables: ["patient_feedback", "comm_complaints", "quality_indicators"],
        permissions: [P.QUALITY.INDICATORS_LIST],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["line", "radar", "bar"],
        visualKind: "radar",
        refresh: "Daily / monthly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["touchpoint", "unit", "doctor", "cohort"],
      },
    ],
  },
  {
    id: "community",
    title: "Community / Geo",
    eyebrow: "Catchment / disease / access",
    description:
      "Patient origins, disease hotspots, referral networks, access gaps, and outreach strategy.",
    icon: IconFileAnalytics,
    accent: "indigo",
    reports: [
      {
        id: "geo-patient-origin-service-area",
        title: "Patient origin and service area map",
        purpose: "Where patients come from, referral catchment, and service intensity.",
        sourceTables: ["patient_addresses", "encounters", "appointments", "admissions"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["choropleth", "flow lines"],
        visualKind: "map",
        refresh: "Daily / weekly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["pincode", "district", "village", "specialty", "payer"],
      },
      {
        id: "geo-disease-hotspot-seasonality",
        title: "Disease burden hotspot and seasonality",
        purpose: "Case density by geography, disease, month, age/sex, and season.",
        sourceTables: ["encounters", "diagnoses", "lab_results", "patient_addresses"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["map", "calendar heatmap"],
        visualKind: "map",
        refresh: "Daily / weekly / monthly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["disease", "geography", "month", "age/sex"],
      },
      {
        id: "geo-referral-network-catchment-flow",
        title: "Referral network and catchment flow",
        purpose: "Source-to-destination referral patterns and load concentration.",
        sourceTables: ["referrals", "camp_referrals", "appointments", "admissions"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["graph", "sankey"],
        visualKind: "graph",
        refresh: "Weekly",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["source village", "spoke site", "specialty", "date"],
      },
      {
        id: "geo-access-gap-underserved",
        title: "Access gap and underserved geography",
        purpose:
          "Long travel burden, weak utilization, weak follow-up, and low service penetration.",
        sourceTables: ["geo_towns", "facilities", "appointments", "camp_registrations"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P3",
        readiness: "capture_needed",
        chartTypes: ["isochrone map", "scatter"],
        visualKind: "map",
        refresh: "Monthly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["geography", "payer", "age/sex", "service line"],
      },
    ],
  },
  {
    id: "body",
    title: "Body / Clinical Maps",
    eyebrow: "Anatomy-aware views",
    description: "Dental, pain, wound, pressure-ulcer, eye, ENT, ortho, and body-part findings.",
    icon: IconStethoscope,
    accent: "pink",
    reports: [
      {
        id: "body-dental-odontogram",
        title: "Dental findings odontogram",
        purpose:
          "Tooth-level findings, missing/treated/restored distribution, and treatment burden.",
        sourceTables: ["specialty_records", "camp_screenings", "diagnoses"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P3",
        readiness: "capture_needed",
        chartTypes: ["custom SVG odontogram"],
        visualKind: "body",
        refresh: "Encounter close / daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["encounter", "provider", "age/sex", "tooth region"],
      },
      {
        id: "body-pain-location-map",
        title: "Pain location intensity map",
        purpose: "Body-region pain burden, follow-up movement, and response tracking.",
        sourceTables: ["pain_assessments", "pain_score_entries", "encounters"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P3",
        readiness: "query_buildable",
        chartTypes: ["custom SVG heatmap"],
        visualKind: "body",
        refresh: "Encounter close / daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["provider", "diagnosis", "severity", "date range"],
      },
      {
        id: "body-wound-pressure-ulcer-map",
        title: "Wound, pressure-ulcer, lesion body map",
        purpose: "Site, stage, progression, healing trajectory, and safety surveillance.",
        sourceTables: ["wound_assessments", "ipd_nursing_assessments", "admissions"],
        permissions: [P.QUALITY.INDICATORS_LIST],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["custom SVG", "timeline"],
        visualKind: "body",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["ward", "wound type", "stage", "date"],
      },
      {
        id: "body-specialty-regional-findings",
        title: "Eye, ENT, ortho regional findings map",
        purpose: "Specialty-region findings mapped to anatomy and laterality.",
        sourceTables: ["specialty_records", "radiology_orders", "diagnoses"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P3",
        readiness: "capture_needed",
        chartTypes: ["custom SVG"],
        visualKind: "body",
        refresh: "Encounter close / daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["specialty", "provider", "side", "severity"],
      },
    ],
  },
  {
    id: "security",
    title: "Security / Data Quality",
    eyebrow: "Trust / identity / audit",
    description:
      "Registration quality, ABHA linkage, duplicate identity risk, unsigned records, and access anomalies.",
    icon: IconScale,
    accent: "dark",
    reports: [
      {
        id: "data-quality-abha-linkage",
        title: "Registration completeness and ABHA linkage",
        purpose:
          "Missing demographics, ABHA linkage percentage, invalid fields, and consent coverage.",
        sourceTables: ["patients", "patient_abha_links", "patient_identifiers", "patient_consents"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["heatmap", "bar"],
        visualKind: "heatmap",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["registration desk", "unit", "staff", "date"],
      },
      {
        id: "security-duplicate-uhid-risk",
        title: "Duplicate UHID identity risk graph",
        purpose: "Suspected duplicates and match-confidence clusters.",
        sourceTables: ["patients", "patient_identifiers", "patient_merge_history"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "query_buildable",
        chartTypes: ["graph", "table"],
        visualKind: "graph",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["site", "age band", "match confidence", "registrar"],
      },
      {
        id: "security-unsigned-amended-records",
        title: "Unsigned and amended records aging",
        purpose: "Pending signatures, amended reports, old open drafts, and legal exposure.",
        sourceTables: ["audit_log", "signed_records", "radiology_reports", "lab_results"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["bar", "boxplot"],
        visualKind: "boxplot",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["document type", "unit", "clinician", "age bucket"],
      },
      {
        id: "security-access-anomaly-surveillance",
        title: "Access anomaly and audit-trail surveillance",
        purpose:
          "After-hours access, cross-location access, unusual record views, and break-glass.",
        sourceTables: ["audit_log", "access_log", "break_glass_events", "access_alerts"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P1",
        readiness: "live_api",
        chartTypes: ["scatter", "calendar heatmap", "network"],
        visualKind: "graph",
        refresh: "Near-real-time / daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["user", "role", "location", "time band", "record type"],
      },
    ],
  },
  {
    id: "predictive",
    title: "Predictive Models",
    eyebrow: "Forecast / anomaly",
    description:
      "Bed demand, no-show, OPD load, stockout, infection/outbreak, incident, and simulator signals.",
    icon: IconFileAnalytics,
    accent: "yellow",
    reports: [
      {
        id: "predict-bed-demand-discharge",
        title: "Bed demand and discharge forecast",
        purpose: "Occupancy forecast, expected discharges, and likely bottlenecks.",
        sourceTables: ["admissions", "beds", "ipd_discharge_tat_log", "bed_reservations"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P2",
        readiness: "predictive",
        chartTypes: ["forecast line", "interval band"],
        visualKind: "forecast",
        refresh: "Daily",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["ward", "bed class", "season", "holiday/event window"],
      },
      {
        id: "predict-opd-noshow-load",
        title: "No-show and OPD load forecast",
        purpose: "Probability of no-show and future clinic crowding.",
        sourceTables: ["appointments", "opd_queues", "encounters", "noshow_prediction_scores"],
        permissions: [P.SCHEDULING.ANALYTICS_VIEW],
        priority: "P2",
        readiness: "predictive",
        chartTypes: ["forecast line", "risk heatmap"],
        visualKind: "forecast",
        refresh: "Daily",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["clinic", "consultant", "slot", "payer"],
      },
      {
        id: "predict-stockout-near-expiry",
        title: "Stockout and near-expiry forecast",
        purpose: "Future shortage risk, expiry exposure, and replenishment priority.",
        sourceTables: ["pharmacy_stock_transactions", "pharmacy_batches", "pharmacy_order_items"],
        permissions: [P.PHARMACY.ANALYTICS_VIEW],
        priority: "P2",
        readiness: "predictive",
        chartTypes: ["forecast line", "treemap"],
        visualKind: "forecast",
        refresh: "Daily",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["SKU", "store", "vendor", "ABC/VED class"],
      },
      {
        id: "predict-infection-outbreak-incident",
        title: "Infection, outbreak, incident early warning",
        purpose:
          "Statistical anomaly detection over cases, incidents, screenings, or notifiable events.",
        sourceTables: [
          "infection_surveillance_events",
          "outbreak_events",
          "lab_results",
          "camp_screenings",
        ],
        permissions: [P.QUALITY.INDICATORS_LIST],
        priority: "P2",
        readiness: "predictive",
        chartTypes: ["anomaly line", "map", "alert band"],
        visualKind: "forecast",
        refresh: "Daily / weekly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["disease", "ward", "unit", "geography", "date"],
      },
    ],
  },
  {
    id: "nmc",
    title: "NMC Overlay",
    eyebrow: "Teaching hospital evidence",
    description:
      "Conditional overlay for teaching hospitals: bed occupancy, OPD attendance, clinical material, MRD completeness.",
    icon: IconScale,
    accent: "gray",
    reports: [
      {
        id: "nmc-specialty-bed-occupancy",
        title: "Specialty bed occupancy vs NMC threshold",
        purpose: "Specialty-wise bed occupancy versus expected minimums.",
        sourceTables: ["admissions", "wards", "departments"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["line", "target band"],
        visualKind: "line",
        refresh: "Monthly / quarterly",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["specialty", "month", "unit"],
      },
      {
        id: "nmc-opd-clinical-material",
        title: "Specialty OPD attendance and clinical material",
        purpose: "OPD attendance by specialty and teaching-load adequacy.",
        sourceTables: ["appointments", "encounters", "departments", "doctor_profiles"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["line", "stacked bar"],
        visualKind: "line",
        refresh: "Monthly / quarterly",
        exports: STANDARD_EXPORTS,
        exportMode: "standard",
        drilldowns: ["specialty", "session", "faculty unit"],
      },
      {
        id: "nmc-procedure-case-mix",
        title: "Procedure and case-mix teaching material adequacy",
        purpose: "Breadth and depth of procedures and cases available for teaching.",
        sourceTables: ["procedure_orders", "surgeries", "ot_case_records", "admissions"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P3",
        readiness: "capture_needed",
        chartTypes: ["treemap", "boxplot"],
        visualKind: "treemap",
        refresh: "Monthly / quarterly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["specialty", "procedure class", "month/quarter"],
      },
      {
        id: "nmc-mrd-completeness-availability",
        title: "MRD completeness and record availability",
        purpose: "Record completion, availability, and retention readiness.",
        sourceTables: ["mrd_medical_records", "mrd_record_movements", "ipd_discharge_summaries"],
        permissions: [P.ANALYTICS.VIEW],
        priority: "P2",
        readiness: "query_buildable",
        chartTypes: ["heatmap", "KPI tiles"],
        visualKind: "heatmap",
        refresh: "Monthly / quarterly",
        exports: GOVERNED_EXPORTS,
        exportMode: "governed",
        drilldowns: ["department", "record type", "age bucket", "missing field"],
      },
    ],
  },
];
