export type ActorGroup =
  | "patient_public"
  | "hospital_user"
  | "external_user"
  | "external_system";

export type JourneyPriority = "P0" | "P1" | "P2" | "P3";
export type JourneyTimeScope =
  | "same_day"
  | "multi_shift"
  | "multi_day"
  | "longitudinal";
export type JourneyExecutionLayer =
  | "ui"
  | "api"
  | "hybrid"
  | "contract"
  | "catalog";
export type JourneyAutomationStatus =
  | "automated"
  | "candidate"
  | "backlog";

export interface UserJourneyCase {
  id: string;
  title: string;
  actorGroup: ActorGroup;
  priority: JourneyPriority;
  actors: string[];
  modules: string[];
  entryPoint: string;
  exitPoint: string;
  timeScope: JourneyTimeScope;
  executionLayer: JourneyExecutionLayer;
  automationStatus: JourneyAutomationStatus;
  existingSpec?: string;
  regulatoryAnchors: string[];
  assertions: string[];
}

export const REQUIRED_ACTOR_GROUPS: ActorGroup[] = [
  "patient_public",
  "hospital_user",
  "external_user",
  "external_system",
];

export const JOURNEY_CASES: UserJourneyCase[] = [
  {
    id: "JNY-PAT-001",
    title: "Public OPD booking to kiosk check-in",
    actorGroup: "patient_public",
    priority: "P0",
    actors: ["patient", "kiosk_user"],
    modules: ["public_appointments", "opd_queue", "tv_tokens"],
    entryPoint: "public appointment booking",
    exitPoint: "checked-in token issued",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "automated",
    existingSpec: "actor-perspective-journeys.spec.ts",
    regulatoryAnchors: ["patient identification", "queue privacy"],
    assertions: ["slot capacity is enforced", "QR check-in creates a token"],
  },
  {
    id: "JNY-PAT-002",
    title: "Walk-in registration to OPD token",
    actorGroup: "patient_public",
    priority: "P0",
    actors: ["walk_in_patient", "receptionist"],
    modules: ["patients", "opd_queue"],
    entryPoint: "front desk registration",
    exitPoint: "OPD token waiting",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["two identifiers", "duplicate patient prevention"],
    assertions: ["patient is created with UHID", "queue token links to patient"],
  },
  {
    id: "JNY-PAT-003",
    title: "Patient report access after lab completion",
    actorGroup: "patient_public",
    priority: "P0",
    actors: ["patient", "lab_technician", "doctor"],
    modules: ["lab", "patient_portal", "communications"],
    entryPoint: "completed lab result",
    exitPoint: "patient-visible report",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["critical value routing", "result confidentiality"],
    assertions: ["report is not visible before verification", "verified report is available to patient"],
  },
  {
    id: "JNY-PAT-004",
    title: "Bedside portal nurse request",
    actorGroup: "patient_public",
    priority: "P1",
    actors: ["ipd_patient", "nurse"],
    modules: ["bedside_portal", "ipd", "nurse"],
    entryPoint: "active bedside session",
    exitPoint: "nurse request acknowledged",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["patient privacy", "response audit trail"],
    assertions: ["only admitted patient session can create request", "nurse can update request status"],
  },
  {
    id: "JNY-PAT-005",
    title: "Radiology public viewer token",
    actorGroup: "patient_public",
    priority: "P1",
    actors: ["patient", "radiology_tech", "doctor"],
    modules: ["radiology", "public_viewer"],
    entryPoint: "shared radiology viewer link",
    exitPoint: "token-scoped imaging result visible",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "backlog",
    regulatoryAnchors: ["DICOM readiness", "token expiry", "patient confidentiality"],
    assertions: ["expired token is rejected", "valid token exposes only scoped study"],
  },
  {
    id: "JNY-PAT-006",
    title: "Discharge follow-up scheduling",
    actorGroup: "patient_public",
    priority: "P1",
    actors: ["patient", "doctor", "nurse"],
    modules: ["ipd", "opd", "communications"],
    entryPoint: "discharge summary completion",
    exitPoint: "follow-up appointment reminder scheduled",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["discharge counseling", "continuity of care"],
    assertions: ["follow-up date is recorded", "patient reminder is queued"],
  },
  {
    id: "JNY-PAT-007",
    title: "Patient feedback after visit",
    actorGroup: "patient_public",
    priority: "P2",
    actors: ["patient", "quality_officer"],
    modules: ["opd", "patient_experience", "quality"],
    entryPoint: "completed visit",
    exitPoint: "feedback item captured for quality review",
    timeScope: "same_day",
    executionLayer: "ui",
    automationStatus: "backlog",
    regulatoryAnchors: ["patient rights", "grievance tracking"],
    assertions: ["anonymous feedback is accepted where allowed", "quality dashboard shows new feedback"],
  },
  {
    id: "JNY-PAT-008",
    title: "Patient package subscription and consumption",
    actorGroup: "patient_public",
    priority: "P1",
    actors: ["patient", "billing_clerk", "doctor"],
    modules: ["patient_packages", "billing", "opd"],
    entryPoint: "package subscription",
    exitPoint: "package benefit consumed in visit",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["financial transparency", "receipt audit"],
    assertions: ["package balance decreases on consumption", "invoice references package adjustment"],
  },
  {
    id: "JNY-PAT-009",
    title: "Emergency patient triage to MLC intimation",
    actorGroup: "patient_public",
    priority: "P0",
    actors: ["emergency_patient", "nurse", "doctor", "audit_officer"],
    modules: ["emergency", "mlc", "audit"],
    entryPoint: "ER arrival",
    exitPoint: "triage and MLC record created",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["MLC documentation", "mandatory reporting", "patient stabilization"],
    assertions: ["triage acuity is recorded", "MLC police intimation can be printed"],
  },
  {
    id: "JNY-PAT-010",
    title: "Longitudinal chronic care follow-up",
    actorGroup: "patient_public",
    priority: "P2",
    actors: ["patient", "doctor", "nurse_call_center"],
    modules: ["chronic_care", "opd", "communications"],
    entryPoint: "program enrollment",
    exitPoint: "follow-up outcome recorded",
    timeScope: "longitudinal",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["continuity of care", "patient consent"],
    assertions: ["enrollment timeline records clinical events", "missed follow-up is escalated"],
  },

  {
    id: "JNY-HOS-001",
    title: "Receptionist to doctor OPD handoff",
    actorGroup: "hospital_user",
    priority: "P0",
    actors: ["receptionist", "doctor"],
    modules: ["patients", "opd"],
    entryPoint: "patient registration",
    exitPoint: "doctor consultation created",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "automated",
    existingSpec: "actor-perspective-journeys.spec.ts",
    regulatoryAnchors: ["two identifiers", "clinical documentation"],
    assertions: ["doctor uses role-owned credentials", "consultation links to encounter"],
  },
  {
    id: "JNY-HOS-002",
    title: "Doctor order to lab result review",
    actorGroup: "hospital_user",
    priority: "P0",
    actors: ["doctor", "lab_technician"],
    modules: ["opd", "lab"],
    entryPoint: "doctor lab order",
    exitPoint: "lab order visible to lab role",
    timeScope: "same_day",
    executionLayer: "api",
    automationStatus: "candidate",
    regulatoryAnchors: ["LOINC readiness", "critical result routing"],
    assertions: ["lab role can see assigned order", "doctor can review completed result"],
  },
  {
    id: "JNY-HOS-003",
    title: "Prescription to pharmacy dispense",
    actorGroup: "hospital_user",
    priority: "P0",
    actors: ["doctor", "pharmacist", "billing_clerk"],
    modules: ["opd", "pharmacy", "billing"],
    entryPoint: "e-prescription",
    exitPoint: "dispensed medication billed",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "automated",
    existingSpec: "actor-perspective-journeys.spec.ts",
    regulatoryAnchors: ["drug schedule", "allergy check", "batch traceability"],
    assertions: ["dispense links to prescription", "billing captures medicine charge"],
  },
  {
    id: "JNY-HOS-004",
    title: "Billing invoice issue and receipt",
    actorGroup: "hospital_user",
    priority: "P0",
    actors: ["billing_clerk", "patient"],
    modules: ["billing", "payments"],
    entryPoint: "billable encounter",
    exitPoint: "issued invoice and receipt",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "automated",
    existingSpec: "billing-invoice.spec.ts",
    regulatoryAnchors: ["GST handling", "receipt audit"],
    assertions: ["invoice status moves to issued", "payment receipt references invoice"],
  },
  {
    id: "JNY-HOS-005",
    title: "IPD admission to multi-day rounds",
    actorGroup: "hospital_user",
    priority: "P0",
    actors: ["doctor", "nurse", "billing_clerk"],
    modules: ["ipd", "nurse", "billing"],
    entryPoint: "IPD admission",
    exitPoint: "multi-day clinical and billing evidence",
    timeScope: "multi_day",
    executionLayer: "api",
    automationStatus: "automated",
    existingSpec: "actor-perspective-journeys.spec.ts",
    regulatoryAnchors: ["MAR 5 rights", "SBAR handover", "I/O chart", "fall risk"],
    assertions: ["progress notes span multiple dates", "handover is acknowledged"],
  },
  {
    id: "JNY-HOS-006",
    title: "Nurse MAR administration with hold/refusal",
    actorGroup: "hospital_user",
    priority: "P0",
    actors: ["nurse", "doctor"],
    modules: ["ipd", "nurse", "pharmacy"],
    entryPoint: "scheduled MAR",
    exitPoint: "administration or exception recorded",
    timeScope: "multi_shift",
    executionLayer: "api",
    automationStatus: "candidate",
    regulatoryAnchors: ["5 rights", "high-alert medication", "barcode verification"],
    assertions: ["given medication records timestamp", "held/refused requires notes"],
  },
  {
    id: "JNY-HOS-007",
    title: "Discharge checklist to MRD seal",
    actorGroup: "hospital_user",
    priority: "P0",
    actors: ["doctor", "nurse", "pharmacist", "billing_clerk", "mrd_officer"],
    modules: ["ipd", "pharmacy", "billing", "mrd"],
    entryPoint: "discharge initiated",
    exitPoint: "case sheet sealed",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "automated",
    existingSpec: "golden-patient-journey.spec.ts",
    regulatoryAnchors: ["discharge counseling", "medication reconciliation", "record retention"],
    assertions: ["all clearance steps complete", "MRD record links discharge summary"],
  },
  {
    id: "JNY-HOS-008",
    title: "OT procedure with consent and CSSD tracking",
    actorGroup: "hospital_user",
    priority: "P1",
    actors: ["doctor", "ot_staff", "cssd_technician", "nurse"],
    modules: ["ot", "consent", "cssd", "billing"],
    entryPoint: "procedure scheduled",
    exitPoint: "procedure completed and instruments accounted",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["informed consent", "surgical safety checklist", "sterilization traceability"],
    assertions: ["procedure cannot proceed without consent", "instrument batch is traced"],
  },
  {
    id: "JNY-HOS-009",
    title: "Radiology order to report sign-off",
    actorGroup: "hospital_user",
    priority: "P1",
    actors: ["doctor", "radiology_tech", "radiologist"],
    modules: ["radiology", "opd", "billing"],
    entryPoint: "radiology order",
    exitPoint: "signed report available",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["AERB safety", "DICOM", "PCPNDT where applicable"],
    assertions: ["unsafe modality warnings are enforced", "report requires sign-off"],
  },
  {
    id: "JNY-HOS-010",
    title: "Blood requisition to issue",
    actorGroup: "hospital_user",
    priority: "P1",
    actors: ["doctor", "blood_bank_tech", "nurse"],
    modules: ["blood_bank", "ipd", "billing"],
    entryPoint: "blood component request",
    exitPoint: "component issued to patient",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["blood bank regulations", "crossmatch", "traceability"],
    assertions: ["crossmatch compatibility is recorded", "issue links unit to patient"],
  },
  {
    id: "JNY-HOS-011",
    title: "Maternity ANC to delivery and newborn record",
    actorGroup: "hospital_user",
    priority: "P1",
    actors: ["doctor", "nurse", "maternity_staff"],
    modules: ["maternity", "ipd", "birth_records"],
    entryPoint: "ANC registration",
    exitPoint: "delivery and newborn record",
    timeScope: "longitudinal",
    executionLayer: "hybrid",
    automationStatus: "automated",
    existingSpec: "maternity-journey.spec.ts",
    regulatoryAnchors: ["MTP/PCPNDT awareness", "birth record", "maternal safety"],
    assertions: ["ANC history carries forward", "newborn record links mother"],
  },
  {
    id: "JNY-HOS-012",
    title: "Infection control HAI surveillance",
    actorGroup: "hospital_user",
    priority: "P1",
    actors: ["infection_control_officer", "nurse", "doctor"],
    modules: ["infection_control", "ipd", "quality"],
    entryPoint: "suspected HAI event",
    exitPoint: "surveillance item reviewed",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["HAI surveillance", "biomedical waste", "antimicrobial stewardship"],
    assertions: ["event is linked to admission", "stewardship review is auditable"],
  },
  {
    id: "JNY-HOS-013",
    title: "Diet order to kitchen fulfillment",
    actorGroup: "hospital_user",
    priority: "P2",
    actors: ["doctor", "dietitian", "canteen_staff", "nurse"],
    modules: ["diet", "ipd", "kitchen"],
    entryPoint: "diet order",
    exitPoint: "meal served and acknowledged",
    timeScope: "multi_shift",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["allergy awareness", "nutrition documentation"],
    assertions: ["restricted diet is visible to kitchen", "meal delivery is recorded"],
  },
  {
    id: "JNY-HOS-014",
    title: "Housekeeping bed turnaround",
    actorGroup: "hospital_user",
    priority: "P2",
    actors: ["nurse", "housekeeping_staff", "bed_manager"],
    modules: ["ipd", "housekeeping", "beds"],
    entryPoint: "patient discharge",
    exitPoint: "bed marked ready",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["infection control", "turnaround TAT"],
    assertions: ["dirty bed cannot be allocated", "cleaning completion changes bed status"],
  },
  {
    id: "JNY-HOS-015",
    title: "Ambulance dispatch to ER handoff",
    actorGroup: "hospital_user",
    priority: "P1",
    actors: ["ambulance_driver", "emergency_nurse", "doctor"],
    modules: ["ambulance", "emergency", "communications"],
    entryPoint: "ambulance call",
    exitPoint: "ER arrival handoff",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["emergency response TAT", "handover communication"],
    assertions: ["dispatch timestamps are captured", "handover links to ER visit"],
  },
  {
    id: "JNY-HOS-016",
    title: "HR roster to access permissions",
    actorGroup: "hospital_user",
    priority: "P2",
    actors: ["hr_officer", "hospital_admin", "nurse"],
    modules: ["hr", "admin", "permissions"],
    entryPoint: "employee onboarding",
    exitPoint: "role permissions active",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["least privilege", "credential audit"],
    assertions: ["new user receives role template", "revoked user cannot access protected route"],
  },
  {
    id: "JNY-HOS-017",
    title: "Audit officer break-glass review",
    actorGroup: "hospital_user",
    priority: "P1",
    actors: ["doctor", "audit_officer"],
    modules: ["audit", "patients", "access_control"],
    entryPoint: "break-glass access",
    exitPoint: "audit review completed",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["privacy audit", "least privilege"],
    assertions: ["break-glass requires reason", "audit officer can review event"],
  },
  {
    id: "JNY-HOS-018",
    title: "Camp screening to hospital referral",
    actorGroup: "hospital_user",
    priority: "P2",
    actors: ["camp_coordinator", "doctor", "receptionist"],
    modules: ["camp", "patients", "opd"],
    entryPoint: "camp registration",
    exitPoint: "hospital referral converted",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["patient consent", "continuity of care"],
    assertions: ["camp patient data maps to hospital patient", "referral status is tracked"],
  },
  {
    id: "JNY-HOS-019",
    title: "Pharmacy return and restock",
    actorGroup: "hospital_user",
    priority: "P1",
    actors: ["patient", "pharmacist", "billing_clerk"],
    modules: ["pharmacy", "billing", "inventory"],
    entryPoint: "dispensed medicine return",
    exitPoint: "stock and billing adjusted",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["batch traceability", "refund audit"],
    assertions: ["return references original dispense", "restocked quantity is updated"],
  },
  {
    id: "JNY-HOS-020",
    title: "Critical lab value escalation",
    actorGroup: "hospital_user",
    priority: "P0",
    actors: ["lab_technician", "doctor", "nurse"],
    modules: ["lab", "communications", "ipd"],
    entryPoint: "critical lab result entry",
    exitPoint: "doctor acknowledgement recorded",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["critical value policy", "closed-loop communication"],
    assertions: ["critical flag triggers notification", "acknowledgement timestamp is stored"],
  },

  {
    id: "JNY-EXTU-001",
    title: "Vendor PO dispatch to GRN and payment",
    actorGroup: "external_user",
    priority: "P1",
    actors: ["vendor", "procurement_officer", "store_keeper"],
    modules: ["procurement", "indent", "supplier_payments"],
    entryPoint: "purchase order sent to vendor",
    exitPoint: "supplier payment pending",
    timeScope: "multi_day",
    executionLayer: "api",
    automationStatus: "automated",
    existingSpec: "actor-perspective-journeys.spec.ts",
    regulatoryAnchors: ["GRN inspection", "vendor audit", "payment controls"],
    assertions: ["PO status reaches sent_to_vendor", "GRN and payment link to vendor"],
  },
  {
    id: "JNY-EXTU-002",
    title: "TPA pre-authorization to claim packet",
    actorGroup: "external_user",
    priority: "P1",
    actors: ["insurance_officer", "tpa_user", "doctor", "billing_clerk"],
    modules: ["insurance", "billing", "ipd"],
    entryPoint: "pre-auth request",
    exitPoint: "claim packet generated",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["NHCX readiness", "financial consent", "claim audit"],
    assertions: ["pre-auth status changes are auditable", "claim packet includes discharge and invoice"],
  },
  {
    id: "JNY-EXTU-003",
    title: "Referral doctor case referral",
    actorGroup: "external_user",
    priority: "P2",
    actors: ["referral_doctor", "case_manager", "doctor"],
    modules: ["opd", "case_mgmt", "communications"],
    entryPoint: "external referral",
    exitPoint: "referral accepted or rejected",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["patient consent", "referral audit trail"],
    assertions: ["referral source is captured", "case status is visible to case manager"],
  },
  {
    id: "JNY-EXTU-004",
    title: "Outsourced lab pickup to result import",
    actorGroup: "external_user",
    priority: "P1",
    actors: ["external_lab", "lab_technician", "doctor"],
    modules: ["lab", "outsourced_lab", "communications"],
    entryPoint: "outsourced order created",
    exitPoint: "external result reconciled",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["sample chain of custody", "critical result policy"],
    assertions: ["external reference number is stored", "result maps back to original order"],
  },
  {
    id: "JNY-EXTU-005",
    title: "Corporate sponsor enrollment to invoice",
    actorGroup: "external_user",
    priority: "P2",
    actors: ["corporate_sponsor", "billing_clerk", "patient"],
    modules: ["billing", "corporates", "patients"],
    entryPoint: "corporate enrollment",
    exitPoint: "corporate invoice generated",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["contractual billing", "patient consent"],
    assertions: ["patient is enrolled under corporate", "corporate invoice includes covered services"],
  },
  {
    id: "JNY-EXTU-006",
    title: "Biomedical vendor service closure",
    actorGroup: "external_user",
    priority: "P2",
    actors: ["biomed_engineer", "vendor_service_engineer"],
    modules: ["bme", "procurement", "quality"],
    entryPoint: "equipment breakdown",
    exitPoint: "vendor service evaluated",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["equipment safety", "maintenance audit"],
    assertions: ["service vendor is linked to asset", "closure records downtime and evaluation"],
  },
  {
    id: "JNY-EXTU-007",
    title: "Blood donor registration to donation",
    actorGroup: "external_user",
    priority: "P2",
    actors: ["blood_donor", "blood_bank_tech"],
    modules: ["blood_bank", "donor_management"],
    entryPoint: "donor registration",
    exitPoint: "donation unit quarantined or available",
    timeScope: "same_day",
    executionLayer: "hybrid",
    automationStatus: "backlog",
    regulatoryAnchors: ["donor eligibility", "blood bank traceability"],
    assertions: ["ineligible donor is blocked", "accepted unit has traceable donor link"],
  },
  {
    id: "JNY-EXTU-008",
    title: "Camp sponsor commitment to utilization report",
    actorGroup: "external_user",
    priority: "P3",
    actors: ["camp_sponsor", "camp_coordinator", "billing_clerk"],
    modules: ["camp", "billing", "reports"],
    entryPoint: "camp sponsor agreement",
    exitPoint: "utilization report exported",
    timeScope: "multi_day",
    executionLayer: "catalog",
    automationStatus: "backlog",
    regulatoryAnchors: ["financial transparency", "patient privacy"],
    assertions: ["sponsor sees aggregate-only report", "patient identifiers are masked"],
  },
  {
    id: "JNY-EXTU-009",
    title: "Supplier consignment implant usage",
    actorGroup: "external_user",
    priority: "P1",
    actors: ["vendor", "store_keeper", "ot_staff", "billing_clerk"],
    modules: ["indent", "procurement", "ot", "billing"],
    entryPoint: "consignment stock received",
    exitPoint: "implant usage billed and vendor liability updated",
    timeScope: "multi_day",
    executionLayer: "hybrid",
    automationStatus: "candidate",
    regulatoryAnchors: ["implant traceability", "batch/serial tracking", "billing audit"],
    assertions: ["implant serial links to patient", "consignment balance reduces after usage"],
  },
  {
    id: "JNY-EXTU-010",
    title: "External ambulance partner handoff",
    actorGroup: "external_user",
    priority: "P2",
    actors: ["ambulance_partner", "emergency_nurse", "doctor"],
    modules: ["ambulance", "emergency", "communications"],
    entryPoint: "external ambulance arrival",
    exitPoint: "ER handoff accepted",
    timeScope: "same_day",
    executionLayer: "catalog",
    automationStatus: "backlog",
    regulatoryAnchors: ["handover communication", "emergency TAT"],
    assertions: ["partner details are captured", "handoff notes attach to ER visit"],
  },

  {
    id: "JNY-EXTS-001",
    title: "FHIR capability and patient read",
    actorGroup: "external_system",
    priority: "P0",
    actors: ["fhir_client"],
    modules: ["fhir", "patients", "opd"],
    entryPoint: "FHIR metadata request",
    exitPoint: "Patient resource returned",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "automated",
    existingSpec: "actor-perspective-journeys.spec.ts",
    regulatoryAnchors: ["FHIR R4", "access audit"],
    assertions: ["CapabilityStatement declares FHIR version", "Patient read returns FHIR Patient resource"],
  },
  {
    id: "JNY-EXTS-002",
    title: "FHIR patient everything bundle",
    actorGroup: "external_system",
    priority: "P0",
    actors: ["fhir_client"],
    modules: ["fhir", "patients", "opd", "lab"],
    entryPoint: "FHIR Patient everything request",
    exitPoint: "Bundle returned",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "automated",
    existingSpec: "actor-perspective-journeys.spec.ts",
    regulatoryAnchors: ["FHIR R4", "minimum necessary access"],
    assertions: ["bundle includes patient", "bundle entries are scoped to tenant"],
  },
  {
    id: "JNY-EXTS-003",
    title: "Bridge agent registration and heartbeat",
    actorGroup: "external_system",
    priority: "P0",
    actors: ["bridge_agent"],
    modules: ["bridge", "devices"],
    entryPoint: "bridge register",
    exitPoint: "heartbeat accepted",
    timeScope: "same_day",
    executionLayer: "api",
    automationStatus: "automated",
    existingSpec: "actor-perspective-journeys.spec.ts",
    regulatoryAnchors: ["device audit", "integration availability"],
    assertions: ["agent receives id", "heartbeat status is ok"],
  },
  {
    id: "JNY-EXTS-004",
    title: "ABDM ABHA public certificate",
    actorGroup: "external_system",
    priority: "P1",
    actors: ["abdm_client"],
    modules: ["abdm", "identity"],
    entryPoint: "ABHA certificate request",
    exitPoint: "certificate payload returned",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "candidate",
    regulatoryAnchors: ["ABDM", "consent architecture"],
    assertions: ["public certificate endpoint is reachable", "response does not expose private key material"],
  },
  {
    id: "JNY-EXTS-005",
    title: "NHCX callback verification",
    actorGroup: "external_system",
    priority: "P1",
    actors: ["nhcx_gateway"],
    modules: ["insurance", "billing", "callbacks"],
    entryPoint: "signed NHCX callback",
    exitPoint: "claim status reconciled",
    timeScope: "multi_day",
    executionLayer: "contract",
    automationStatus: "backlog",
    regulatoryAnchors: ["NHCX", "signature verification", "claim audit"],
    assertions: ["invalid signature is rejected", "valid callback updates matched claim"],
  },
  {
    id: "JNY-EXTS-006",
    title: "Device pairing and ingest",
    actorGroup: "external_system",
    priority: "P1",
    actors: ["device_gateway", "nurse"],
    modules: ["devices", "nurse_vitals", "audit"],
    entryPoint: "device pairing token",
    exitPoint: "vital observation ingested",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "candidate",
    regulatoryAnchors: ["device identity", "clinical observation audit"],
    assertions: ["pairing token cannot be reused", "ingested vital links to patient and device"],
  },
  {
    id: "JNY-EXTS-007",
    title: "LIS analyzer result ingest",
    actorGroup: "external_system",
    priority: "P1",
    actors: ["lis_analyzer", "lab_technician"],
    modules: ["lab", "devices", "bridge"],
    entryPoint: "analyzer message",
    exitPoint: "lab result candidate created",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "backlog",
    regulatoryAnchors: ["LOINC", "critical value", "instrument audit"],
    assertions: ["unknown sample is quarantined", "known sample maps to lab order"],
  },
  {
    id: "JNY-EXTS-008",
    title: "PACS DICOM study readiness",
    actorGroup: "external_system",
    priority: "P1",
    actors: ["pacs_server", "radiology_tech"],
    modules: ["radiology", "dicom", "public_viewer"],
    entryPoint: "DICOM study received",
    exitPoint: "study linked to radiology order",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "backlog",
    regulatoryAnchors: ["DICOM", "AERB safety", "patient privacy"],
    assertions: ["study patient identifiers are matched", "viewer token does not leak unrelated studies"],
  },
  {
    id: "JNY-EXTS-009",
    title: "Payment gateway webhook",
    actorGroup: "external_system",
    priority: "P1",
    actors: ["payment_gateway"],
    modules: ["billing", "payment_gateway", "audit"],
    entryPoint: "payment webhook",
    exitPoint: "invoice payment reconciled",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "candidate",
    regulatoryAnchors: ["PCI scope", "payment audit", "no card logging"],
    assertions: ["invalid webhook signature is rejected", "successful payment updates invoice balance"],
  },
  {
    id: "JNY-EXTS-010",
    title: "SMS or WhatsApp delivery callback",
    actorGroup: "external_system",
    priority: "P2",
    actors: ["message_gateway"],
    modules: ["communications", "appointments", "billing"],
    entryPoint: "gateway delivery callback",
    exitPoint: "message delivery state updated",
    timeScope: "same_day",
    executionLayer: "contract",
    automationStatus: "backlog",
    regulatoryAnchors: ["patient consent", "communication audit"],
    assertions: ["callback maps to outbound message", "PHI is not logged in callback diagnostics"],
  },
];

export function journeyCasesByActorGroup(actorGroup: ActorGroup): UserJourneyCase[] {
  return JOURNEY_CASES.filter((journey) => journey.actorGroup === actorGroup);
}
