/**
 * MedBrains Vendor — entry component.
 *
 * Composes the medbrains mobile-shell with this app's modules,
 * variant, and platform shims. Generated by
 * medbrains-create-mobile-app (variant: vendor).
 */

import { PaperProvider } from "react-native-paper";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { StatusBar } from "expo-status-bar";
import {
  ExpoSecureStoreAdapter,
  Shell,
  buildForestCopperTheme,
} from "@medbrains/mobile-shell";
import { Navigator } from "./src/navigator";
import { MODULES } from "./src/modules";

const secretStore = new ExpoSecureStoreAdapter();
const theme = buildForestCopperTheme("light");

export default function App() {
  return (
    <SafeAreaProvider>
      <PaperProvider theme={theme}>
        <StatusBar style="dark" />
        <Shell
          variant="vendor"
          modules={MODULES}
          secretStore={secretStore}
          cachePath="medbrains-cache"
          Navigator={Navigator}
          unlockPromptMessage="Unlock MedBrains Vendor"
        />
      </PaperProvider>
    </SafeAreaProvider>
  );
}
