"""Enterprise-audit backlog: 13 epics, 70 user stories.

Source: ENTERPRISE_READINESS_AUDIT.md (2026-06-11). Effort: S <1d, M 1-3d, L 1-2wk, XL >2wk.
"""

M1 = "M1 — Week 1: Critical security & infra"
M2 = "M2 — Weeks 2-4: Reliability & revenue"
M3 = "M3 — Weeks 5-8: Hardening & onboarding"
M4 = "M4 — Weeks 9-12: Compliance & platform"


def story(title, role, want, so_that, ac, refs, files, effort, priority, area, milestone):
    return {
        "title": title,
        "role": role,
        "want": want,
        "so_that": so_that,
        "ac": ac,
        "refs": refs,
        "files": files,
        "effort": effort,
        "priority": priority,
        "area": area,
        "milestone": milestone,
    }


EPICS = [
    {
        "key": "01-security",
        "title": "Epic: Security hardening",
        "priority": "P0-critical",
        "area": "area:security",
        "milestone": M1,
        "summary": (
            "Close the P0 security findings from the enterprise audit: leaked secrets, weak "
            "startup key handling, seed credentials, open SSH, and missing account-protection "
            "flows (lockout, reset, MFA). Audit refs: P0 #1-#7."
        ),
        "stories": [
            story(
                "Fail startup when production JWT keys are missing",
                "sysadmin",
                "the server to refuse to start in production if JWT_PRIVATE_KEY/JWT_PUBLIC_KEY are unset",
                "a restart never silently regenerates keys and invalidates every active session",
                [
                    "Production env without both keys → startup error with clear message",
                    "Dev/test keep auto-generated Ed25519 keypair behaviour",
                    "Deployment docs updated with key provisioning steps",
                ],
                "P0 #1",
                ["crates/medbrains-server/src/config.rs:186-306"],
                "S", "P0-critical", "area:security", M1,
            ),
            story(
                "Gate seed credentials and force first-login password change",
                "hospital admin",
                "demo/seed accounts (admin/admin123 etc.) created only when MEDBRAINS_ALLOW_SEED=true and forced to change password on first login",
                "default credentials can never reach a production tenant",
                [
                    "Seed runs only with MEDBRAINS_ALLOW_SEED=true",
                    "Seeded users flagged must_change_password; login flow enforces change",
                    "Existing deployments documented for credential rotation",
                ],
                "P0 #2",
                ["crates/medbrains-server/src/seed/mod.rs:77", "crates/medbrains-server/src/seed/demo_patients.rs:18-62"],
                "M", "P0-critical", "area:security", M1,
            ),
            story(
                "Restrict SSH ingress on EC2 security group",
                "devops engineer",
                "SSH limited to operator IPs or SSM Session Manager instead of 0.0.0.0/0",
                "the hospital server is not exposed to internet-wide brute force",
                [
                    "Security group port 22 restricted to allowlisted CIDRs or removed in favour of SSM",
                    "terraform apply produces working end-state (no manual steps)",
                ],
                "P0 #3",
                ["infra/terraform/modules/standalone-vm/aws-ec2/main.tf:106-112"],
                "S", "P0-critical", "area:infra", M1,
            ),
            story(
                "Rotate leaked PAT/AWS credentials and move secrets out of git",
                "security officer",
                "the committed GitHub PAT and AWS creds rotated immediately and all secrets sourced from Secrets Manager / env injection",
                "leaked credentials cannot be abused and the repo holds no live secrets",
                [
                    "PAT and AWS keys rotated; old ones revoked",
                    ".env files with secrets removed from git history tracking and gitignored",
                    "Server reads secrets from AWS Secrets Manager or instance env",
                ],
                "P0 #4",
                ["medbrains/.env:33", "infra/.env:15-26"],
                "M", "P0-critical", "area:security", M1,
            ),
            story(
                "Add per-account lockout after failed logins",
                "security officer",
                "accounts to lock temporarily after N failed attempts (tracked per user, not just per IP)",
                "credential stuffing across distributed IPs is blocked",
                [
                    "users gain failed_login_attempts + locked_until columns",
                    "Lockout threshold/window configurable per tenant",
                    "Audit log entry on lockout; clear unlock path for admins",
                ],
                "P0 #6",
                ["crates/medbrains-server/src/routes/auth.rs"],
                "M", "P0-critical", "area:security", M2,
            ),
            story(
                "Build password reset / forgot-password flow",
                "staff user",
                "a self-service email/SMS reset with time-limited tokens",
                "I can recover access without an admin manually resetting my password",
                [
                    "Reset request → time-limited single-use token via email/SMS",
                    "Token verify + new password (Argon2id) endpoint",
                    "Frontend pages for request + reset; rate-limited",
                ],
                "P0 #7",
                ["crates/medbrains-server/src/routes/auth.rs", "apps/web/src/pages/login.tsx"],
                "L", "P0-critical", "area:security", M2,
            ),
            story(
                "Add TOTP MFA, mandatory for doctor/admin roles",
                "hospital admin",
                "TOTP-based MFA with enforced enrollment for privileged roles",
                "PHI access meets HIPAA/NIST authentication requirements",
                [
                    "TOTP enroll/verify endpoints + recovery codes",
                    "Role-based enforcement policy (doctor/admin mandatory)",
                    "Login flow supports MFA challenge; E2E test",
                ],
                "P0 #5",
                ["crates/medbrains-server/src/routes/auth.rs"],
                "L", "P0-critical", "area:security", M3,
            ),
        ],
    },
    {
        "key": "02-db-integrity",
        "title": "Epic: Multi-tenancy & database integrity",
        "priority": "P0-critical",
        "area": "area:database",
        "milestone": M1,
        "summary": (
            "Close cross-tenant leak risk (44 tables without RLS) and structural DB debt: "
            "missing indexes (~1,600 FK columns, 58 zero-index tables, 286 JSONB no GIN), "
            "unconstrained status columns, unpartitioned log tables. Audit refs: P0 #8, P1 Database."
        ),
        "stories": [
            story(
                "Enable RLS on the 44 tenant tables missing it",
                "hospital admin",
                "every tenant-scoped table protected by RLS tenant policy",
                "no query path can leak another hospital's data",
                [
                    "RLS + tenant policy on backup_history, cross_hospital_appointments, inter_hospital_stock_transfers, 6 camp tables, iam_access_requests, lab_sample_routes, patient_transfers, 32 relation_tuples_p* partitions",
                    "Migration applies cleanly; RLS coverage check = 100% of tenant tables",
                ],
                "P0 #8",
                ["crates/medbrains-db/src/migrations (0001, 0003, 0011, 0028, 0053, 0117, 0120)"],
                "M", "P0-critical", "area:database", M1,
            ),
            story(
                "Backfill FK and (tenant_id, status) composite indexes",
                "developer",
                "indexes on hot FK columns and tenant+status composites",
                "joins, cascades, and filtered lists stop full-scanning as data grows",
                [
                    "Audit-driven index list; prioritize high-traffic tables (patients, orders, invoices, encounters)",
                    "CONCURRENTLY migrations; before/after query plans on top 10 endpoints",
                ],
                "P1 Database",
                ["crates/medbrains-db/src/migrations"],
                "L", "P1-high", "area:database", M3,
            ),
            story(
                "Add GIN indexes on queried JSONB columns",
                "developer",
                "GIN indexes on JSONB columns used in WHERE/contains queries",
                "JSON filtering does not full-scan (286 JSONB columns, 0 GIN today)",
                ["Identify JSONB columns referenced in queries; add GIN selectively", "No index bloat on write-heavy tables without query need"],
                "P1 Database",
                ["crates/medbrains-db/src/migrations"],
                "M", "P1-high", "area:database", M3,
            ),
            story(
                "Add CHECK constraints to free-text status columns",
                "developer",
                "CHECK constraints (or enums) on the ~36 status TEXT columns",
                "invalid states cannot be inserted and state machines stay trustworthy",
                ["Inventory of status columns + allowed values", "Constraints added with data cleanup for existing violations"],
                "P1 Database",
                ["crates/medbrains-db/src/migrations"],
                "M", "P1-high", "area:database", M3,
            ),
            story(
                "Partition and archive log/event tables",
                "sysadmin",
                "time-based partitioning + archival policy for the 50+ unbounded log/event tables",
                "audit/event growth cannot fill the disk or slow queries",
                ["Partition strategy (monthly) for audit_log, outbox, job_queue history, ws events", "Archival/retention job; payments + billing_audit_log gain updated_at"],
                "P1 Database",
                ["crates/medbrains-db/src/migrations"],
                "L", "P1-high", "area:database", M3,
            ),
        ],
    },
    {
        "key": "03-backend",
        "title": "Epic: Backend hardening",
        "priority": "P0-critical",
        "area": "area:backend",
        "milestone": M1,
        "summary": (
            "Fix cross-tenant bridge bug, unbounded queries, unchecked setup handlers, and "
            "resilience/audit gaps (graceful shutdown, rate limits, PHI read auditing, retention "
            "enforcement, public-booking identity). Audit refs: P0 #9-#11, P1 Backend."
        ),
        "stories": [
            story(
                "Scope bridge heartbeat UPDATE by tenant",
                "security officer",
                "the device-bridge heartbeat UPDATE to include WHERE tenant_id = $2",
                "an agent from one hospital cannot hijack another tenant's bridge row",
                ["UPDATE filtered by tenant_id; regression test with two tenants"],
                "P0 #9",
                ["crates/medbrains-server/src/routes/devices.rs:585-600"],
                "S", "P0-critical", "area:backend", M1,
            ),
            story(
                "Default pagination + LIMIT on all list endpoints",
                "developer",
                "every fetch_all list endpoint to enforce default page size and max LIMIT",
                "large tenants cannot OOM the server or stall the UI (~40+ unbounded endpoints)",
                [
                    "Shared pagination extractor (page/per_page, max cap)",
                    "Worst offenders first: pharmacy_dispense_ops, ambulance, bedside_portal, analytics",
                    "Frontend list calls pass pagination; responses include meta.total",
                ],
                "P0 #10",
                ["crates/medbrains-server/src/routes (systemic, ~1,180 fetch_all calls)"],
                "L", "P0-critical", "area:backend", M2,
            ),
            story(
                "Add permission checks to unchecked setup handlers",
                "hospital admin",
                "require_permission on update_tenant/get_tenant and the ~30 unchecked setup.rs handlers",
                "tenant configuration cannot be read or changed by unauthorized staff",
                ["All setup.rs handlers call require_permission", "RBAC matrix test covers setup routes"],
                "P0 #11",
                ["crates/medbrains-server/src/routes/setup.rs:72-180"],
                "M", "P0-critical", "area:backend", M1,
            ),
            story(
                "Implement graceful shutdown on SIGTERM",
                "devops engineer",
                "the server to drain in-flight requests and close pools on SIGTERM",
                "deploys/restarts do not abort mid-transaction",
                ["axum graceful shutdown wired; in-flight transactions complete or roll back cleanly", "systemd stop within timeout"],
                "P1 Backend",
                ["crates/medbrains-server/src/main.rs:432"],
                "S", "P1-high", "area:backend", M2,
            ),
            story(
                "Extend rate limiting beyond login",
                "sysadmin",
                "rate limits on analytics, exports, and list endpoints",
                "a single client cannot saturate the server",
                ["Tiered limits (auth, read, export); 429 with Retry-After", "Config per tenant"],
                "P1 Backend",
                ["crates/medbrains-server/src/middleware/rate_limit.rs:20-26"],
                "M", "P1-high", "area:backend", M2,
            ),
            story(
                "Audit PHI list/read endpoints",
                "compliance officer",
                "list endpoints (GET /patients etc.) recorded in the audit log",
                "mass PHI exports are traceable (HIPAA read-tracking)",
                ["Read-audit middleware for PHI-bearing list endpoints with actor, filter, count", "No material latency regression"],
                "P1 Backend",
                ["crates/medbrains-server/src/middleware/audit.rs:51-52"],
                "M", "P1-high", "area:backend", M2,
            ),
            story(
                "Enforce data retention with a purge job",
                "compliance officer",
                "the configured retention policies actually executed by a scheduled purge/anonymize job",
                "stored data matches declared retention commitments",
                ["Scheduled job reads retention config and purges/archives eligible rows", "Dry-run mode + audit entry per purge batch"],
                "P1 Backend",
                ["crates/medbrains-server/src/routes/security.rs", "crates/medbrains-server/src/routes/mrd.rs"],
                "M", "P1-high", "area:backend", M3,
            ),
            story(
                "Verify public booking identity with OTP",
                "patient",
                "phone OTP verification before a public booking attaches to my patient record",
                "a name+phone collision cannot book into someone else's medical record",
                ["OTP send/verify step in public booking flow", "Unverified bookings create provisional records only"],
                "P1 Backend",
                ["crates/medbrains-server/src/routes/appointments/public.rs:31"],
                "M", "P1-high", "area:backend", M2,
            ),
        ],
    },
    {
        "key": "04-infra",
        "title": "Epic: Infrastructure reliability",
        "priority": "P0-critical",
        "area": "area:infra",
        "milestone": M1,
        "summary": (
            "Single-EC2 deployment has no alarms, no auto-recovery, data-loss-on-termination, "
            "local TF state, and no rollback path. Make the Starter tier survivable and observable. "
            "Audit refs: P0 #12-#15, P1 Infra."
        ),
        "stories": [
            story(
                "Add CloudWatch alarms and EC2 auto-recovery",
                "devops engineer",
                "StatusCheckFailed auto-recovery plus CPU>80%, disk>80%, and 5xx alarms with notifications",
                "instance death or disk-full is acted on instead of discovered by the hospital",
                ["Terraform-managed alarms + SNS topic", "Starter-tier limits documented (single AZ, no LB)"],
                "P0 #12, #14",
                ["infra/terraform/modules/standalone-vm/aws-ec2/main.tf"],
                "M", "P0-critical", "area:infra", M1,
            ),
            story(
                "Keep EBS on termination and split data volume",
                "devops engineer",
                "root volume delete_on_termination=false and a separate persistent data volume for Postgres",
                "terminating the instance cannot destroy hospital data",
                ["Flags set in terraform; data volume mounted for docker Postgres", "Recreate-instance drill keeps data"],
                "P0 #13",
                ["infra/terraform/modules/standalone-vm/aws-ec2/main.tf:150-161"],
                "S", "P0-critical", "area:infra", M1,
            ),
            story(
                "Move standalone terraform state to S3 with locking",
                "devops engineer",
                "S3 backend + DynamoDB lock for standalone/alagappa state",
                "state is encrypted, shared, and protected from concurrent applies",
                ["Backend block + migration of existing state", "Documented in infra README"],
                "P0 #15",
                ["infra/terraform/envs/standalone/alagappa/main.tf:25-27"],
                "S", "P0-critical", "area:infra", M1,
            ),
            story(
                "Add deploy rollback and pre-deploy backup gate",
                "devops engineer",
                "ship-cold to snapshot the previous binary + take a DB backup before swap, with one-command rollback",
                "a failed deploy can be reverted instead of leaving the hospital down",
                ["Previous binary retained; rollback make target", "Pre-deploy pg backup gate; migration stage separated from app startup"],
                "P1 Infra",
                ["Makefile:544-551", "deploy.sh"],
                "M", "P1-high", "area:infra", M3,
            ),
            story(
                "Add log rotation and uptime synthetics",
                "devops engineer",
                "bounded journald/log storage and an external health-check on /api/health",
                "disks don't silently fill and downtime is detected within minutes",
                ["journald SystemMaxUse + StartLimitBurst on service unit", "Synthetic monitor (Route53 health check or equivalent) with alert"],
                "P1 Infra",
                ["infra (systemd unit, terraform)"],
                "S", "P1-high", "area:infra", M2,
            ),
            story(
                "Run a backup restore drill and write the runbook",
                "devops engineer",
                "a verified pg restore path from the S3 backups, documented as an incident runbook",
                "backups are known-good before we need them",
                ["Restore to clean instance succeeds; RTO/RPO recorded", "Runbook in docs/sops; backup-bucket IAM tightened"],
                "P1 Infra",
                ["docs/sops/"],
                "M", "P1-high", "area:infra", M2,
            ),
        ],
    },
    {
        "key": "05-clinical-safety",
        "title": "Epic: Clinical safety & compliance",
        "priority": "P0-critical",
        "area": "area:clinical-safety",
        "milestone": M2,
        "summary": (
            "Critical lab values must reach a doctor reliably; NABH/JCI checklist machinery (34 "
            "departments, 700+ criteria) is unbuilt; QC and specialty compliance gaps. "
            "Audit refs: P0 #16-#17, Part 2 specialty findings."
        ),
        "stories": [
            story(
                "Deliver critical lab values via SMS with acknowledgment",
                "doctor",
                "critical results pushed over SMS (not just WebSocket) with delivery retry and an ack workflow",
                "a panic value is never missed because a browser tab was closed",
                [
                    "SMS via existing Twilio connector to ordering doctor",
                    "Escalation if unacknowledged within configurable window",
                    "Ack recorded with timestamp + user (NABH critical-value reporting)",
                ],
                "P0 #16",
                ["crates/medbrains-server/src/routes/lab.rs:1115-1140"],
                "L", "P0-critical", "area:clinical-safety", M2,
            ),
            story(
                "Build NABH/JCI checklist engine",
                "quality manager",
                "a checklist schema + templates covering the 34 department checklists (700+ criteria)",
                "accreditation compliance is tracked in-system instead of on paper",
                ["Checklist template/instance/response schema with scoring", "Seed from ACMSRC evaluation checklists; department dashboards"],
                "P0 #17",
                ["new module"],
                "XL", "P0-critical", "area:clinical-safety", M4,
            ),
            story(
                "Enforce WHO surgical safety checklist in OT flow",
                "OT nurse",
                "sign-in/time-out/sign-out gates enforced before case milestones",
                "IPSG surgical-safety compliance is guaranteed per case",
                ["Checklist completion blocks stage transitions", "Printable record per surgery"],
                "P0 #17 / IPSG",
                ["crates/medbrains-server/src/routes/ot.rs"],
                "M", "P0-critical", "area:clinical-safety", M4,
            ),
            story(
                "Add lab QC hold/recheck/supervisor-approval workflow",
                "lab supervisor",
                "analyzer results held for QC review with recheck + approval before release",
                "NABL-compliant result verification instead of auto-posting",
                ["QC hold state on bridge-ingested results", "Supervisor approve/reject with audit; release gates report print"],
                "Part 2 Devices (lab)",
                ["crates/medbrains-bridge", "crates/medbrains-server/src/routes/lab.rs"],
                "L", "P1-high", "area:clinical-safety", M4,
            ),
            story(
                "Track dialyzer reuse and machine scheduling",
                "dialysis in-charge",
                "dialyzer reuse counts and machine slot scheduling on dialysis sessions",
                "reuse limits are enforced (compliance) and machines are utilized safely",
                ["Dialyzer reuse counter with max-reuse enforcement", "Machine master + session slot allocation"],
                "Part 2 Specialized (nephrology)",
                ["crates/medbrains-server/src/routes/dialysis.rs"],
                "M", "P1-high", "area:clinical-safety", M4,
            ),
            story(
                "Generate PCPNDT statutory form for maternity scans",
                "radiologist",
                "the mandatory PCPNDT Form F auto-generated from ultrasound orders on pregnant patients",
                "statutory PCPNDT compliance is automatic, not manual paperwork",
                ["Form F data capture + print template", "Register report for PCPNDT authority"],
                "Part 2 Specialized (maternity)",
                ["crates/medbrains-server/src/routes/maternity.rs", "print templates"],
                "M", "P1-high", "area:clinical-safety", M4,
            ),
        ],
    },
    {
        "key": "06-revenue-linkages",
        "title": "Epic: Revenue & module linkages",
        "priority": "P1-high",
        "area": "area:backend",
        "milestone": M2,
        "summary": (
            "Six revenue-leak linkage gaps: manual bed charges, manual discharge settlement, "
            "undelivered reminders, unenforced TPA pre-auth, manual queue entry, manual billing "
            "reversal. Audit ref: P1 Revenue leakage."
        ),
        "stories": [
            story(
                "Auto-bill room rent daily on IPD admission",
                "billing clerk",
                "daily bed/room charges auto-created from admission + bed assignment",
                "no admitted day goes unbilled",
                ["Scheduled job posts daily room-rent lines per occupied bed", "Bed transfers prorate correctly; uses auto_charge idempotency"],
                "P1 Revenue",
                ["crates/medbrains-server/src/routes/ipd.rs", "crates/medbrains-server/src/routes/billing.rs"],
                "L", "P1-high", "area:backend", M2,
            ),
            story(
                "Finalize invoice on IPD discharge",
                "billing clerk",
                "discharge checklist to trigger invoice finalization/settlement",
                "patients cannot leave with unbilled services",
                ["Discharge step aggregates pending charges into final invoice", "Discharge blocked (configurable) until settlement or credit approval"],
                "P1 Revenue",
                ["crates/medbrains-server/src/routes/ipd_post_discharge.rs:69+"],
                "M", "P1-high", "area:backend", M2,
            ),
            story(
                "Deliver appointment reminders via SMS/email job",
                "receptionist",
                "stored reminders actually sent through a scheduled delivery job",
                "no-shows drop (currently reminders are stored, never delivered)",
                ["Scheduled job sends due reminders via Twilio/SMTP", "Delivery status tracked; retries on failure"],
                "P1 Revenue",
                ["crates/medbrains-server/src/routes/appointments/reminders.rs:24+"],
                "M", "P1-high", "area:backend", M2,
            ),
            story(
                "Enforce TPA pre-authorization at billing",
                "insurance desk officer",
                "charges above pre-auth limits flagged/blocked for insured patients",
                "claim denials from unauthorized charges stop",
                ["Billing checks active pre-auth before posting covered charges", "Override path with reason + audit"],
                "P1 Revenue",
                ["crates/medbrains-server/src/routes/billing.rs:366+", "crates/medbrains-server/src/routes/insurance.rs"],
                "M", "P1-high", "area:backend", M2,
            ),
            story(
                "Create OPD queue entry on appointment check-in",
                "receptionist",
                "check-in to automatically place the patient in the OPD queue",
                "patients are not lost between front office and consultation",
                ["Check-in creates queue token; TV board updates via WebSocket", "E2E: book → check-in → appears in doctor queue"],
                "P1 Revenue",
                ["crates/medbrains-server/src/routes/front_office.rs", "crates/medbrains-server/src/routes/opd.rs"],
                "S", "P1-high", "area:backend", M2,
            ),
            story(
                "Auto-reverse billing lines on clinical cancellation",
                "billing clerk",
                "cancelling an order/procedure to reverse its billing line automatically",
                "patients are not charged for cancelled services (0112 backbone exists)",
                ["Cancellation events trigger reversal via existing 0112 backbone", "Reversal audit trail; partial-completion handling"],
                "P1 Revenue",
                ["crates/medbrains-server/src/routes/billing.rs", "crates/medbrains-server/src/orchestration"],
                "M", "P1-high", "area:backend", M2,
            ),
        ],
    },
    {
        "key": "07-frontend-stability",
        "title": "Epic: Frontend stability & UX safety",
        "priority": "P0-critical",
        "area": "area:frontend",
        "milestone": M2,
        "summary": (
            "Silent mutation failures, unconfirmed destructive actions, blank tables on API "
            "errors, unvalidated responses, missing skeletons/empty states, i18n bypasses. "
            "Also supersedes the 112 auto-filed client-error issues closed in favour of this epic. "
            "Audit refs: P0 #18-#19, P1/P2 Frontend, Part 3."
        ),
        "stories": [
            story(
                "Add onError handling to all mutations",
                "nurse",
                "every mutation to surface failures as a toast instead of failing silently",
                "I know when a save did not happen (25+ silent mutations in OPD/pharmacy/emergency)",
                ["All useMutation calls have onError → notification", "Shared mutation-error helper; i18n'd messages, no raw backend strings"],
                "P0 #18",
                ["apps/web/src/pages/opd.tsx:1083-1199", "apps/web/src/pages/pharmacy.tsx", "apps/web/src/pages/emergency.tsx"],
                "M", "P0-critical", "area:frontend", M2,
            ),
            story(
                "Wrap destructive actions in confirmation dialogs",
                "billing clerk",
                "delete/void/cancel actions to require modals.openConfirmModal",
                "accidental clicks cannot permanently destroy records (15+ unguarded actions)",
                ["All destructive actions confirmed with consequence text", "Shared confirmDestructive helper"],
                "P0 #19",
                ["apps/web/src/pages/billing.tsx:2554", "apps/web/src/pages/ipd.tsx:3006", "apps/web/src/pages/pharmacy.tsx"],
                "S", "P0-critical", "area:frontend", M2,
            ),
            story(
                "Render query error states on all pages",
                "staff user",
                "tables/pages to show an error + retry UI when a query fails",
                "an API failure looks like a failure, not an empty list (~100 of 142 pages blank)",
                ["Shared QueryError component with retry", "Rolled out via DataTable/page wrapper so coverage is systematic"],
                "P1 Frontend",
                ["apps/web/src/pages (systemic)", "apps/web/src/components/DataTable.tsx"],
                "L", "P1-high", "area:frontend", M3,
            ),
            story(
                "Validate API responses with Zod at runtime",
                "developer",
                "API responses parsed through Zod schemas (1 safeParse in 142 pages today)",
                "backend shape drift fails loudly instead of rendering wrong data",
                ["Schemas in packages/schemas for high-risk modules first (billing, pharmacy, lab)", "Client wrapper validates; dev-mode throws, prod logs"],
                "P1 Frontend",
                ["packages/schemas/src", "packages/api/src/client.ts"],
                "L", "P1-high", "area:frontend", M3,
            ),
            story(
                "Add skeletons and empty states",
                "staff user",
                "loading skeletons (60+ tables) and explicit empty-state UI (110+ pages)",
                "blank screens are unambiguous: loading vs empty vs error",
                ["Shared EmptyState component; PageSkeleton reuse", "Top-20 traffic pages first"],
                "P2 Frontend",
                ["apps/web/src/pages (systemic)"],
                "M", "P2-medium", "area:frontend", M3,
            ),
            story(
                "Move hardcoded notification strings into i18n",
                "non-English staff user",
                "the ~40 hardcoded English strings (pharmacy 25+, opd 15+) translated via i18n namespaces",
                "critical flows speak my language",
                ["Strings moved to locale JSON; no literal English in notifications.show", "Biome/grep check to prevent regressions"],
                "P2 Frontend",
                ["apps/web/src/pages/pharmacy.tsx", "apps/web/src/pages/opd.tsx", "apps/web/public/locales"],
                "S", "P2-medium", "area:frontend", M3,
            ),
        ],
    },
    {
        "key": "08-notifications",
        "title": "Epic: Notifications & connector delivery",
        "priority": "P1-high",
        "area": "area:integration",
        "milestone": M2,
        "summary": (
            "Backbone (outbox, job queue, scheduler) works; delivery doesn't: SMTP and WhatsApp "
            "are stubs, 8 of 9 notification events have no channel, no on-call lookup. "
            "Audit refs: P1/P2 Notifications, Part 2 Connectors."
        ),
        "stories": [
            story(
                "Implement real SMTP email delivery",
                "patient",
                "the SMTP connector to actually send (receipts, discharge docs) instead of returning 'queued'",
                "emails the system claims to send actually arrive",
                ["lettre-based SMTP send with per-tenant config", "Outbox handler delivers; failures retry via DLQ; delivery status stored"],
                "Part 2 Connectors",
                ["crates/medbrains-server/src/connectors"],
                "M", "P1-high", "area:integration", M2,
            ),
            story(
                "Implement WhatsApp connector delivery",
                "patient",
                "invoice/appointment WhatsApp messages sent via Business API",
                "patients get documents on the channel they actually read",
                ["WhatsApp Business API (or BSP) integration with template messages", "Opt-in tracking; failures fall back to SMS"],
                "Part 2 Connectors",
                ["crates/medbrains-server/src/connectors"],
                "M", "P1-high", "area:integration", M3,
            ),
            story(
                "Wire the 8 missing notification events",
                "pharmacist",
                "low-stock, lab-report-ready, invoice-issued, claim-approved, prescription-expiry, incident-escalation, token-call SMS, report-ready fan-out delivered",
                "the events the system already detects reach the people who must act",
                ["Each event mapped to channel + recipient rule via outbox", "Per-tenant enable/disable config"],
                "P2 Notifications",
                ["crates/medbrains-server/src/orchestration/default_pipelines.rs"],
                "L", "P1-high", "area:integration", M4,
            ),
            story(
                "Add on-call roster lookup for alert routing",
                "doctor",
                "critical alerts routed to the on-call doctor from the duty roster when the ordering doctor is off",
                "alerts always reach someone who can act",
                ["Roster query resolves current on-call per department", "Used by critical-value SMS escalation"],
                "P1 (supports P0 #16)",
                ["crates/medbrains-server/src/routes/hr.rs", "crates/medbrains-server/src/routes/lab.rs"],
                "M", "P1-high", "area:integration", M2,
            ),
        ],
    },
    {
        "key": "09-onboarding-etl",
        "title": "Epic: Onboarding & ETL",
        "priority": "P1-high",
        "area": "area:onboarding",
        "milestone": M3,
        "summary": (
            "Single-record CRUD makes hospital onboarding take 6-12 weeks of manual entry. "
            "Bulk import for catalogs is the single biggest onboarding lever. "
            "Audit refs: P1 Onboarding blocker, P2 Configuration."
        ),
        "stories": [
            story(
                "Bulk import lab catalog, formulary, tariffs, patients via CSV/Excel",
                "hospital admin",
                "CSV/Excel import with validation, preview, and error report for the big masters",
                "onboarding takes days, not 6-12 weeks (1000+ lab tests, 5000+ drugs)",
                [
                    "Import endpoints + UI for lab catalog, pharmacy formulary, tariffs, patient masters, ICD mapping",
                    "Row-level validation report; idempotent re-run; template downloads",
                ],
                "P1 Onboarding",
                ["new: routes/import.rs", "apps/web/src/pages/admin"],
                "L", "P1-high", "area:onboarding", M3,
            ),
            story(
                "Make operational settings configurable via UI",
                "hospital admin",
                "working hours/holidays, queue rules, lab critical thresholds, shift definitions, auto-billing toggles, print/consent templates editable in admin UI",
                "each hospital tunes behaviour without engineering involvement",
                ["Settings surfaces grouped in admin; persisted to tenant_settings", "Backend reads config instead of hardcoded values"],
                "P2 Configuration",
                ["apps/web/src/pages/admin/settings.tsx", "crates/medbrains-server/src/routes/setup.rs"],
                "L", "P2-medium", "area:onboarding", M3,
            ),
            story(
                "Export/import tenant configuration between environments",
                "implementation engineer",
                "a config bundle export/import (settings, templates, masters)",
                "staging-validated config promotes to production exactly",
                ["Versioned JSON bundle export + validated import", "Diff preview before apply"],
                "P2 Configuration",
                ["crates/medbrains-server/src/routes/setup.rs"],
                "M", "P2-medium", "area:onboarding", M3,
            ),
        ],
    },
    {
        "key": "10-component-consolidation",
        "title": "Epic: Component library consolidation",
        "priority": "P2-medium",
        "area": "area:ux",
        "milestone": M3,
        "summary": (
            "Shared library is good but under-adopted: 45 pages duplicate status maps, 48 pages "
            "use raw tables, 748 inline notification calls, 26 duplicate formatters, StatCard "
            "used in 2 of 132 candidate pages. Audit ref: Part 5."
        ),
        "stories": [
            story(
                "Consolidate status→color maps into StatusBadge",
                "developer",
                "all 45 inline status-color maps replaced by an extended shared StatusBadge",
                "status colors are consistent across every module",
                ["StatusBadge statusMap extended per domain (pharmacy, ambulance, comms, indent…)", "45 pages migrated; inline maps deleted"],
                "Part 5 #1",
                ["apps/web/src/components/StatusBadge.tsx"],
                "M", "P2-medium", "area:ux", M3,
            ),
            story(
                "Migrate raw Mantine tables to shared DataTable",
                "developer",
                "the 48 pages on raw <Table> moved to DataTable",
                "pagination/sorting/error/empty behaviour is uniform (194 duplicated column defs today)",
                ["48 pages migrated incl. lab.tsx, mrd.tsx, blood-bank.tsx modals", "No raw <thead> rendering left in pages"],
                "Part 5 #2",
                ["apps/web/src/components/DataTable.tsx", "apps/web/src/pages/lab.tsx", "apps/web/src/pages/mrd.tsx"],
                "L", "P2-medium", "area:ux", M3,
            ),
            story(
                "Extract FormModal scaffold for RHF+Zod forms",
                "developer",
                "a shared FormModal/useFormModal wrapping the repeated modal+form+submit pattern (286 zodResolver sites)",
                "mega-files shrink 15-20% and form UX is uniform",
                ["FormModal component with submit state, error display, close handling", "Adopted in billing.tsx, pharmacy.tsx, emergency.tsx, ipd.tsx"],
                "Part 5 #3",
                ["apps/web/src/components", "apps/web/src/pages/billing.tsx"],
                "M", "P2-medium", "area:ux", M3,
            ),
            story(
                "Centralize formatters (money, percent, bytes)",
                "developer",
                "formatMoney/formatPercent/formatBytes added to lib and the 26 local copies replaced",
                "currency and dates render identically everywhere",
                ["lib/date-utils.ts (+number-utils.ts) extended", "26 pages import shared formatters; local copies deleted"],
                "Part 5 #5",
                ["apps/web/src/lib/date-utils.ts"],
                "S", "P2-medium", "area:ux", M4,
            ),
            story(
                "Add showNotification helper and migrate inline calls",
                "developer",
                "a typed showNotification(type, title, message) helper replacing 748 inline notifications.show calls",
                "toasts are consistent and i18n-enforced in one place",
                ["Helper in lib/ with success/error/warning variants", "Mega-pages migrated first; Biome rule or grep check"],
                "Part 5 #4",
                ["apps/web/src/lib"],
                "M", "P2-medium", "area:ux", M4,
            ),
            story(
                "Promote StatCard and add useCRUDMutation hook",
                "developer",
                "StatCard adopted on dashboard/report pages and a shared useCRUDMutation(queryKey) hook",
                "stat cards stop being hand-rolled (132 pages) and invalidation boilerplate (448 calls) shrinks",
                ["StatCard used in top dashboard/report pages", "hooks/useCRUDMutation.ts adopted in 10+ pages"],
                "Part 5 #6, #7",
                ["apps/web/src/components/StatCard.tsx", "apps/web/src/hooks"],
                "M", "P2-medium", "area:ux", M4,
            ),
        ],
    },
    {
        "key": "11-workflow-forms",
        "title": "Epic: Workflow engine & forms/printing runtime",
        "priority": "P1-high",
        "area": "area:backend",
        "milestone": M4,
        "summary": (
            "Workflow engine tables exist but are dormant (0 templates vs RFC-002's 120+); form "
            "builder has schema but no routes/UI/runtime; print queue has no daemon; thermal "
            "formats unimplemented. Audit refs: P2 Workflow, Part 2 Forms & Printables."
        ),
        "stories": [
            story(
                "Decide: activate or remove the workflow engine",
                "product owner",
                "an explicit decision with implementation plan — either seed templates + rules engine + UI, or delete the dormant tables in favour of hardcoded pipelines",
                "we stop carrying dead schema while RFC-002 promises stay unresolved",
                ["Decision doc comparing both paths with effort", "Chosen path gets follow-up stories; dead code removed if dropped"],
                "P2 Workflow",
                ["crates/medbrains-db migrations 0001 (workflow_*)", "crates/medbrains-server/src/orchestration"],
                "M", "P2-medium", "area:backend", M4,
            ),
            story(
                "Build form-builder routes and runtime renderer",
                "hospital admin",
                "CRUD routes for form_masters/form_fields plus a runtime renderer so hospitals customize clinical forms",
                "the 30+ hardcoded TSX forms become per-hospital configurable",
                ["Form template CRUD + versioning routes", "Runtime form renderer component; one pilot form (consent) migrated"],
                "Part 2 Forms (builder 15%)",
                ["crates/medbrains-core/src/form.rs", "0007_forms.sql", "apps/web/src/components"],
                "XL", "P1-high", "area:backend", M4,
            ),
            story(
                "Build print-job daemon and thermal ZPL/ESC-POS output",
                "ward clerk",
                "the print_jobs queue actually delivered to printers, including label/wristband thermal formats",
                "wristbands and labels print on real hardware instead of browser-print only",
                ["Bridge-side print worker polls print_jobs", "ZPL/ESC-POS generation for wristband + label templates"],
                "Part 2 Forms (print infra)",
                ["crates/medbrains-bridge", "print_jobs schema"],
                "L", "P2-medium", "area:backend", M4,
            ),
            story(
                "Add pharmacy dispensing-label endpoint",
                "pharmacist",
                "a label print endpoint for dispensed items (struct exists, no endpoint)",
                "dispensed medication carries patient/dose/expiry labels",
                ["Endpoint renders label from dispense record", "Wired into pharmacy dispense flow UI"],
                "Part 2 Forms (HIGH)",
                ["crates/medbrains-server/src/routes/pharmacy_dispense_ops.rs", "print templates"],
                "S", "P1-high", "area:backend", M4,
            ),
        ],
    },
    {
        "key": "12-integration-platform",
        "title": "Epic: External integration & API platform",
        "priority": "P1-high",
        "area": "area:integration",
        "milestone": M4,
        "summary": (
            "No API keys/OAuth, no outbound webhooks, FHIR missing DiagnosticReport (ABDM "
            "blocker), PACS/DICOM at 5%. Audit refs: Part 2 Devices & PACS, Integrations."
        ),
        "stories": [
            story(
                "Build API key issuance, scopes, and outbound webhooks",
                "integration partner",
                "scoped API keys (issue/rotate/revoke) and subscribable outbound webhooks",
                "third parties can integrate without sharing staff JWTs",
                ["API key auth middleware with scopes + rate limits", "Webhook subscriptions with signed payloads + retry", "OpenAPI spec published"],
                "Part 2 Integrations (0%)",
                ["crates/medbrains-server/src/middleware", "new routes/api_keys.rs"],
                "XL", "P1-high", "area:integration", M4,
            ),
            story(
                "Add FHIR DiagnosticReport resource",
                "ABDM gateway",
                "lab/radiology results exposed as FHIR R4 DiagnosticReport",
                "ABDM interop stops being blocked (HIP role incomplete without it)",
                ["DiagnosticReport read + $everything inclusion", "LOINC-coded observations linked"],
                "Part 2 FHIR",
                ["crates/medbrains-server/src/routes/fhir.rs"],
                "M", "P1-high", "area:integration", M4,
            ),
            story(
                "Implement PACS/DICOM integration",
                "radiologist",
                "modality worklist from orders, C-STORE ingestion, and an embedded OHIF viewer",
                "imaging actually flows: order → modality → study → report (today 5%)",
                ["MWL SCP serves radiology orders", "C-STORE (or Orthanc proxy) ingests studies linked to orders", "OHIF/Cornerstone embed replaces external links"],
                "Part 2 PACS (CRITICAL gap)",
                ["crates/medbrains-bridge", "radiology_dicom_studies", "apps/web/src/pages/radiology.tsx"],
                "XL", "P1-high", "area:integration", M4,
            ),
            story(
                "Implement HL7 outbound and ASTM analyzer parser",
                "lab in-charge",
                "outbound HL7 (orders→analyzers) and the ASTM serial parser for Sysmex-class devices",
                "bidirectional analyzer integration instead of result-receive only",
                ["ORM order messages outbound via bridge", "ASTM E1381/E1394 parser behind existing adapter config"],
                "Part 2 Devices",
                ["crates/medbrains-bridge"],
                "L", "P2-medium", "area:integration", M4,
            ),
        ],
    },
    {
        "key": "13-missing-modules",
        "title": "Epic: Missing modules — build or decide",
        "priority": "P1-high",
        "area": "area:backend",
        "milestone": M4,
        "summary": (
            "Zero-implementation areas that need a build or an explicit defer decision: "
            "telemedicine, dental, ophthalmology, CMS handlers (501s), marketing/CRM. "
            "Audit refs: Part 2 scorecard 0-5% rows."
        ),
        "stories": [
            story(
                "Build telemedicine module",
                "doctor",
                "video consult scheduling, virtual OPD encounters, and e-prescription per Telemedicine Practice Guidelines 2020",
                "remote patients can be seen (regulatory + market expectation, currently 0%)",
                ["Consult scheduling + video provider integration", "Virtual encounter type flows into normal OPD/billing/prescription"],
                "Part 2 (0%)",
                ["new module"],
                "XL", "P1-high", "area:backend", M4,
            ),
            story(
                "Build dental charting backend and UI",
                "dentist",
                "odontogram charting, treatment plans, and dental consent backed by real endpoints",
                "a common OP revenue line works (today: print template only)",
                ["Tooth-chart schema + CRUD", "Odontogram UI; treatment plan → billing linkage"],
                "Part 2 Specialized (stub)",
                ["new routes/dental.rs", "apps/web/src/pages/dental.tsx"],
                "L", "P1-high", "area:backend", M4,
            ),
            story(
                "Build ophthalmology module",
                "ophthalmologist",
                "vision/refraction workup, spectacle prescription, and exam records",
                "eye OPD is supported (currently missing entirely)",
                ["Refraction + visual-acuity capture", "Spectacle Rx print; links to OPD encounter"],
                "Part 2 Specialized (missing)",
                ["new routes/ophthalmology.rs"],
                "L", "P2-medium", "area:backend", M4,
            ),
            story(
                "Implement CMS content handlers (replace 501s)",
                "communications officer",
                "the CMS CRUD routes implemented over the existing 11-table schema",
                "the hospital website/content workflow works (all routes return 501 today)",
                ["Posts/pages CRUD with medical-review workflow states", "Public rendering already works — wire authoring end"],
                "Part 2 CMS (5%)",
                ["crates/medbrains-server/src/routes/cms.rs"],
                "L", "P2-medium", "area:backend", M4,
            ),
            story(
                "Decide marketing/CRM scope",
                "product owner",
                "an explicit build/defer/integrate decision for leads, campaigns, recalls, loyalty (currently 0%)",
                "we either plan the stack or consciously defer instead of leaving a silent gap",
                ["Decision doc: build vs integrate (e.g. external CRM) vs defer", "If build: follow-up epic with scoped stories"],
                "Part 2 Marketing (0%)",
                ["decision doc"],
                "S", "P2-medium", "area:backend", M4,
            ),
        ],
    },
]
