#!/usr/bin/env python3
"""
Find permission codes defined but never referenced.

Walks `medbrains-core/src/permissions.rs`, extracts every `pub const X: &str = "...";`
within `pub mod ...` nesting, then greps the entire repo (Rust + TypeScript) for usage.

A permission is "dead" if:
- Never referenced in route handlers (`require_permission(...)`)
- Never referenced in frontend (`P.MODULE.ACTION` or string `"module.action"`)
- Never referenced in seeds or role templates

Outputs medbrains/docs/audit/dead-permissions.md.

Usage:
    python3 scripts/check_dead_permissions.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PERM_FILE = REPO_ROOT / "medbrains" / "crates" / "medbrains-core" / "src" / "permissions.rs"
SCAN_DIRS = [
    REPO_ROOT / "medbrains" / "crates",
    REPO_ROOT / "medbrains" / "apps",
    REPO_ROOT / "medbrains" / "packages",
]
OUT = REPO_ROOT / "medbrains" / "docs" / "audit" / "dead-permissions.md"

# Match: pub const NAME: &str = "module.x.y";
RE_CONST = re.compile(r'pub\s+const\s+(\w+)\s*:\s*&str\s*=\s*"([^"]+)"\s*;')


def main() -> int:
    if not PERM_FILE.exists():
        print(f"ERROR: {PERM_FILE} not found", file=sys.stderr)
        return 2

    src = PERM_FILE.read_text()

    # Collect (const_name, code_string) pairs
    perms: list[tuple[str, str]] = []
    for m in RE_CONST.finditer(src):
        perms.append((m.group(1), m.group(2)))

    # Build a single corpus to grep (fast — one pass)
    corpus = ""
    for d in SCAN_DIRS:
        for ext in ("*.rs", "*.ts", "*.tsx"):
            for f in d.rglob(ext):
                if f == PERM_FILE:
                    continue
                try:
                    corpus += f.read_text(errors="replace") + "\n"
                except OSError:
                    pass

    rows: list[tuple[str, str, int]] = []
    for const_name, code in perms:
        # Two ways to reference: by const name (Rust) or by string literal (TS / seed)
        c1 = corpus.count(const_name)
        c2 = corpus.count(f'"{code}"')
        c3 = corpus.count(f"'{code}'")
        rows.append((const_name, code, c1 + c2 + c3))

    rows.sort(key=lambda r: r[2])

    lines = [
        "# Dead-permission sweep",
        "",
        f"_Generated by `scripts/check_dead_permissions.py`. {len(rows)} permissions defined. "
        "Refs counts both Rust const-name usage (`permissions::module::X`) and string-literal "
        "usage (`\"module.x.y\"` in seed.rs / TypeScript). **DEAD** = zero refs. Manual review "
        "needed — some perms might be defined now to be granted later as part of a future role._",
        "",
        "| Const | Code | Refs | Status |",
        "|---|---|---:|:---:|",
    ]
    dead = 0
    for const_name, code, refs in rows:
        status = "DEAD" if refs == 0 else "lightly-used" if refs <= 2 else "active"
        if refs == 0:
            dead += 1
        lines.append(f"| `{const_name}` | `{code}` | {refs} | {status} |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")

    print(f"dead-permissions: {len(rows)} defined, {dead} DEAD. Output: {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
