#!/usr/bin/env python3
"""
Find React components with zero importers.

Walks `apps/web/src/components/**/*.{ts,tsx}` and `apps/web/src/lib/**/*.{ts,tsx}`,
extracts each named export, then greps the rest of the source tree to count
external usages. Components with zero non-self imports are deletion candidates.

False-positive sources:
- Component used only via dynamic import / lazy()
- Component referenced by string in a config map
- Re-exports (file just re-exports another file)

Outputs medbrains/docs/audit/dead-components.md with a table:
  | rel-path | exports | imports | risk |

Usage:
    python3 scripts/check_dead_components.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WEB = REPO_ROOT / "medbrains" / "apps" / "web"
SRC = WEB / "src"
OUT = REPO_ROOT / "medbrains" / "docs" / "audit" / "dead-components.md"

SCAN_DIRS = [SRC / "components", SRC / "lib", SRC / "hooks"]
ALL_DIR = SRC

RE_EXPORT_NAMED = re.compile(
    r"export\s+(?:const|function|class|interface|type|enum|default function)\s+(\w+)"
)
RE_EXPORT_DEFAULT = re.compile(r"export\s+default\s+(?:function\s+)?(\w+)")
RE_RE_EXPORT = re.compile(r'export\s+\{[^}]+\}\s+from\s+["\']([^"\']+)["\']')


def collect_exports(path: Path) -> list[str]:
    src = path.read_text(errors="replace")
    names = set()
    for m in RE_EXPORT_NAMED.finditer(src):
        names.add(m.group(1))
    for m in RE_EXPORT_DEFAULT.finditer(src):
        names.add(m.group(1))
    return sorted(names)


def main() -> int:
    candidates: list[tuple[Path, list[str]]] = []
    for d in SCAN_DIRS:
        if not d.exists():
            continue
        for f in d.rglob("*.tsx"):
            exports = collect_exports(f)
            if exports:
                candidates.append((f, exports))
        for f in d.rglob("*.ts"):
            exports = collect_exports(f)
            if exports:
                candidates.append((f, exports))

    # Build a lookup: file → number of imports of any of its exports
    all_src = ""
    for f in ALL_DIR.rglob("*.tsx"):
        all_src += f.read_text(errors="replace") + "\n"
    for f in ALL_DIR.rglob("*.ts"):
        all_src += f.read_text(errors="replace") + "\n"

    rows: list[tuple[Path, list[str], int]] = []
    for path, exports in candidates:
        # Strip self-references — count imports of the symbol elsewhere only
        used = 0
        for name in exports:
            # Match import { name } from ... or import name from ...
            pat = re.compile(r"\b" + re.escape(name) + r"\b")
            count = len(pat.findall(all_src))
            # Heuristic: name appears once per definition + once per import.
            # >1 means at least one external user.
            used += max(count - 1, 0)
        rows.append((path, exports, used))

    rows.sort(key=lambda r: r[2])

    # Pre-render
    lines = [
        "# Dead-component sweep",
        "",
        f"_Generated by `scripts/check_dead_components.py`. Scanned {len(rows)} files. "
        "Risk levels: **HIGH** = zero non-self references; **MEDIUM** = ≤2 references "
        "(might be re-exported via index.ts); **LOW** = used widely. Manual review "
        "needed before deletion — components referenced only via string-map / lazy() "
        "/ component-name dispatch will appear as HIGH._",
        "",
        "| Path | Exports | Refs | Risk |",
        "|---|---|---:|:---:|",
    ]
    for path, exports, used in rows:
        rel = path.relative_to(REPO_ROOT)
        risk = "HIGH" if used == 0 else "MEDIUM" if used <= 2 else "LOW"
        ex = ", ".join(exports[:5])
        if len(exports) > 5:
            ex += f", … (+{len(exports) - 5})"
        lines.append(f"| `{rel}` | `{ex}` | {used} | {risk} |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")

    high = sum(1 for r in rows if r[2] == 0)
    print(f"dead-components: {len(rows)} files scanned, {high} HIGH-risk (zero refs). Output: {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
