#!/usr/bin/env python3
"""
Smoke Test Generator — generates Playwright API smoke test files from the
API contract data.

Parses:
  - crates/medbrains-server/src/routes/mod.rs → backend routes

Generates:
  - apps/web/e2e/smoke/<module>.smoke.spec.ts — one per API module prefix

Usage:
    python3 scripts/generate_smoke_tests.py
    # or:
    make generate-smoke

The generated tests make real HTTP requests against a running backend
and assert:
  - Response status is not 500 (no server errors)
  - GET list endpoints return valid JSON
"""

import re
import sys
from pathlib import Path
from collections import defaultdict

# ── Paths ────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
ROUTES_RS = REPO_ROOT / "medbrains" / "crates" / "medbrains-server" / "src" / "routes" / "mod.rs"
SMOKE_DIR = REPO_ROOT / "medbrains" / "apps" / "web" / "e2e" / "smoke"

# ── Backend route extraction (reuse from check_api_contract.py) ──────

RE_ROUTE = re.compile(
    r'\.route\(\s*"(/api/[^"]+)"\s*,\s*([^)]+\)(?:\s*\.\s*\w+\([^)]*\))*)',
    re.DOTALL,
)
RE_HANDLER = re.compile(r"\b(get|post|put|delete|patch)\s*\(")

# Axum path params: {param} or :param
RE_PARAM = re.compile(r"\{(\w+)\}")


def extract_routes() -> list[tuple[str, str]]:
    """
    Extract (method, path) from routes/mod.rs.
    """
    source = ROUTES_RS.read_text()
    endpoints: list[tuple[str, str]] = []

    for match in RE_ROUTE.finditer(source):
        raw_path = match.group(1).strip().rstrip("/")
        handler_chain = match.group(2)
        methods = [m.group(1).upper() for m in RE_HANDLER.finditer(handler_chain)]

        for method in methods:
            endpoints.append((method, raw_path))

    return endpoints


def get_module_from_path(path: str) -> str:
    """
    Extract module name from API path.
    /api/auth/login → auth
    /api/patients/{id} → patients
    /api/opd/encounters → opd
    /api/setup/departments → setup
    """
    parts = path.strip("/").split("/")
    if len(parts) >= 2:
        return parts[1]  # /api/<module>/...
    return "misc"


def has_path_params(path: str) -> bool:
    return bool(RE_PARAM.search(path))


def make_test_path(path: str) -> str:
    """
    Replace {param} with a dummy UUID for testing.
    """
    return RE_PARAM.sub("00000000-0000-0000-0000-000000000000", path)


# Skip patterns — endpoints that shouldn't be smoke tested
SKIP_PATTERNS = [
    "DELETE /api/",       # Don't delete things
    "POST /api/auth/logout",
    "POST /api/onboarding/init",
    "POST /api/setup/seed",
    "/api/health",        # Already tested by server startup
]


def should_skip(method: str, path: str) -> bool:
    key = f"{method} {path}"
    for pat in SKIP_PATTERNS:
        if key.startswith(pat) or path.startswith(pat.lstrip("DELETE POST GET ")):
            pass
    # More precise check
    if method == "DELETE":
        return True
    if path == "/api/health":
        return True
    if path == "/api/auth/logout":
        return True
    if path.startswith("/api/onboarding"):
        return True
    return False


def generate_module_spec(
    module: str,
    endpoints: list[tuple[str, str]],
) -> str:
    """Generate a smoke test file for a module."""
    lines = [
        '/**',
        f' * Auto-generated smoke tests for /api/{module}/*',
        ' * Generated by: python3 scripts/generate_smoke_tests.py',
        ' *',
        ' * These tests verify that API endpoints respond without 500 errors.',
        ' * They run against a live backend server.',
        ' */',
        '',
        'import { test, expect } from "@playwright/test";',
        'import { getAuthToken, BACKEND_URL } from "../helpers";',
        '',
        f'test.describe("/api/{module} smoke tests", () => {{',
        '  let cookies: string;',
        '',
        '  test.beforeAll(async ({ request }) => {',
        '    const auth = await getAuthToken(request);',
        '    cookies = auth.cookies;',
        '  });',
        '',
    ]

    for method, path in sorted(endpoints, key=lambda x: (x[1], x[0])):
        if should_skip(method, path):
            continue

        test_path = make_test_path(path)
        test_name = f"{method} {path}"

        # Escape quotes in test name
        test_name_escaped = test_name.replace('"', '\\"')

        if method == "GET":
            lines.extend([
                f'  test("{test_name_escaped}", async ({{ request }}) => {{',
                f'    const resp = await request.get(`${{BACKEND_URL}}{test_path}`, {{',
                '      headers: { Cookie: cookies },',
                '    });',
                '    expect(resp.status()).toBeLessThan(500);',
                '    if (resp.status() === 200) {',
                '      const body = await resp.json();',
                '      expect(body).toBeDefined();',
                '    }',
                '  });',
                '',
            ])
        elif method == "POST":
            lines.extend([
                f'  test("{test_name_escaped}", async ({{ request }}) => {{',
                f'    const resp = await request.post(`${{BACKEND_URL}}{test_path}`, {{',
                '      headers: {',
                '        Cookie: cookies,',
                '        "Content-Type": "application/json",',
                '      },',
                '      data: {},',
                '    });',
                '    // POST with empty body may return 400/422, but should never 500',
                '    expect(resp.status()).toBeLessThan(500);',
                '  });',
                '',
            ])
        elif method in ("PUT", "PATCH"):
            lines.extend([
                f'  test("{test_name_escaped}", async ({{ request }}) => {{',
                f'    const resp = await request.{method.lower()}(`${{BACKEND_URL}}{test_path}`, {{',
                '      headers: {',
                '        Cookie: cookies,',
                '        "Content-Type": "application/json",',
                '      },',
                '      data: {},',
                '    });',
                '    // Update with empty body may return 400/404, but should never 500',
                '    expect(resp.status()).toBeLessThan(500);',
                '  });',
                '',
            ])

    lines.append("});")
    lines.append("")

    return "\n".join(lines)


# ── Main ─────────────────────────────────────────────────────────────


def main():
    if not ROUTES_RS.exists():
        print(f"ERROR: Routes file not found: {ROUTES_RS}")
        sys.exit(2)

    # Extract all routes
    routes = extract_routes()
    print(f"Extracted {len(routes)} routes from mod.rs")

    # Group by module
    by_module: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for method, path in routes:
        module = get_module_from_path(path)
        by_module[module].append((method, path))

    # Create output directory
    SMOKE_DIR.mkdir(parents=True, exist_ok=True)

    # Generate per-module spec files
    generated = 0
    total_tests = 0
    for module in sorted(by_module.keys()):
        endpoints = by_module[module]
        # Filter out skipped endpoints for count
        testable = [(m, p) for m, p in endpoints if not should_skip(m, p)]
        if not testable:
            continue

        spec_content = generate_module_spec(module, endpoints)
        spec_path = SMOKE_DIR / f"{module}.smoke.spec.ts"
        spec_path.write_text(spec_content)
        generated += 1
        total_tests += len(testable)
        print(f"  Generated {spec_path.name}: {len(testable)} tests")

    print()
    print(f"Generated {generated} smoke test files with {total_tests} total tests")
    print(f"Output directory: {SMOKE_DIR}")
    print()
    print("To run: make smoke-test (requires running backend on port 3000)")


if __name__ == "__main__":
    main()
