#!/usr/bin/env python3
"""
Update MedBrains_Features.xlsx — Printing & Forms sheet
Sets Status to Done/Partial for features built in Documents & Printing module.
Preserves all existing formatting.
"""

import openpyxl
import sys
from pathlib import Path

EXCEL_PATH = Path(__file__).parent.parent / "MedBrains_Features.xlsx"
SHEET_NAME = "Printing & Forms"

# Feature column = 4, Status column = 7
FEATURE_COL = 4
STATUS_COL = 7


def matches_any(feature_lower, patterns):
    """Check if feature text matches any of the given keyword patterns (case-insensitive)."""
    for pattern in patterns:
        if pattern in feature_lower:
            return True
    return False


# ──────────────────────────────────────────────────────────
# Specific row-level overrides for precision
# These handle cases where keyword matching might be ambiguous
# or where we need precise control
# Key: row number -> target status
# ──────────────────────────────────────────────────────────
ROW_OVERRIDES = {
    # 37.1 Dynamic Form Builder & Template Engine
    # Row 4: "Visual form designer — drag-and-drop" -> already Done, keep
    # Row 5: "Template library — pre-built for all standard hospital forms" -> Partial (only 20 seed templates)
    5: "Partial",
    # Row 6: "Custom form creation by department HODs" -> already Done, keep
    # Row 7: "Form versioning with audit trail" -> Done (template versioning built)
    7: "Done",
    # Row 8: "Multi-language form rendering" -> Partial (multi-language auto-gen deferred)
    8: "Partial",
    # Row 9: "Dynamic field population from patient/clinical data" -> Done (document generation from templates)
    9: "Done",
    # Row 10: "Conditional fields" -> already Done, keep
    # Row 11: "Configurable paper sizes (A4, A5, prescription pad, label, wristband)" -> Done (print format selection)
    11: "Done",
    # Row 12: "Form approval workflow before activation" -> Done (template activation/deactivation)
    12: "Done",
    # Row 13: "Obsolete form retirement with watermark 'OBSOLETE'" -> Done (watermark types built)
    13: "Done",

    # 37.2 Hospital Branding & Doctor Signage
    # Row 15: "Hospital logo on ALL printed outputs" -> Done (branding configuration)
    15: "Done",
    # Row 16: "Multi-entity branding" -> leave Pending (not specifically built)
    # Row 17: "Hospital name, address, phone, email, website, NABH number" -> Done (branding config)
    17: "Done",
    # Row 18: "Doctor signature block (Name, Designation, Dept, Reg No, Qualifications)" -> Done
    18: "Done",
    # Row 19: "Digital signature integration (scanned signature auto-placed)" -> Done
    19: "Done",
    # Row 20: "Aadhaar e-Sign on consent forms" -> Partial
    20: "Partial",
    # Row 21: "Multiple doctor signatures on same form" -> Done (signature blocks config)
    21: "Done",
    # Row 22: "Department-wise header customization" -> Done (branding config per template)
    22: "Done",
    # Row 23: "Footer: auto form ID, print date/time, printed-by user, page X of Y" -> Done
    23: "Done",
    # Row 24: "Watermark support (DRAFT, CONFIDENTIAL, COPY, DUPLICATE, UNCONTROLLED)" -> Done
    24: "Done",
    # Row 25: "QR code on printed forms linking to digital record" -> Done (QR code toggle)
    25: "Done",

    # 37.5 Consent Forms
    # Row 60: "Multi-language auto-generation from single template (6 languages)" -> Partial
    60: "Partial",
    # Row 61: "Read-aloud / Audio consent for illiterate patients" -> Partial (pictogram/illiterate deferred)
    61: "Partial",

    # 37.7 Billing Prints
    # These are specific department forms — leave Pending unless already Done

    # 37.12 Regulatory Compliance Prints
    # Leave as-is (specific regulatory forms, not part of Documents & Printing module)

    # 37.13 Print Infrastructure & Capabilities
    # Row 206: "Thermal printer support for wristbands, labels, tokens" -> Partial
    206: "Partial",
    # Row 207: "Barcode / QR code printing on all forms" -> Partial (barcode printer Phase 2, QR done)
    207: "Partial",
    # Row 208: "Laser printer support" -> Partial (printer config Phase 2)
    208: "Partial",
    # Row 209: "Dot matrix printer support" -> Partial
    209: "Partial",
    # Row 210: "Pre-printed stationery support" -> Partial
    210: "Partial",
    # Row 211: "Blank paper printing (complete form generated by system)" -> Done
    211: "Done",
    # Row 212: "PDF generation for digital distribution" -> Partial (Typst Phase 2)
    212: "Partial",
    # Row 213: "Bulk print capability (batch printing)" -> Done (batch document generation)
    213: "Done",
    # Row 214: "Print queue management (per printer, per department)" -> Partial (Phase 2 stubs)
    214: "Partial",
    # Row 215: "Reprint with DUPLICATE watermark (audit-logged)" -> Done
    215: "Done",
    # Row 216: "Print preview before printing" -> Done (browser-based preview)
    216: "Done",
    # Row 217: "Mobile printing (doctor prints from app to nearest printer)" -> Partial
    217: "Partial",
    # Row 218: "Configurable printer mapping (department → default printer)" -> Partial (Phase 2 stubs)
    218: "Partial",

    # 37.14 Form Management & Compliance
    # Row 220: "Form version control (multiple versions, only latest active)" -> Done
    220: "Done",
    # Row 221: "Form usage audit trail (who printed what, when, for which patient)" -> Done
    221: "Done",
    # Row 222: "Form archival (old forms retrievable but marked obsolete)" -> Done
    222: "Done",
    # Row 223: "Controlled form printing (watermarked CONTROLLED COPY)" -> Done
    223: "Done",
    # Row 224: "Uncontrolled copy printing (watermarked UNCONTROLLED COPY)" -> Done
    224: "Done",
    # Row 225: "Form compliance dashboard (updated forms vs overdue for review)" -> Done
    225: "Done",
    # Row 226: "Annual form review cycle tracking (per NABH/NABL requirement)" -> Done
    226: "Done",
    # Row 227: "External auditor form access (time-limited, read-only)" -> Partial
    227: "Partial",

    # 37.4 Patient-Facing Prints — Clinical Output
    # Row 35: "OPD Consultation Summary (patient's language)" -> Partial (multi-language deferred)
    35: "Partial",
    # Row 43: "Take-Home Medication List (pictograms, patient's language)" -> Partial
    43: "Partial",
}


def main():
    print(f"Opening: {EXCEL_PATH}")
    wb = openpyxl.load_workbook(str(EXCEL_PATH))

    if SHEET_NAME not in wb.sheetnames:
        print(f"ERROR: Sheet '{SHEET_NAME}' not found!")
        print(f"Available sheets: {wb.sheetnames}")
        sys.exit(1)

    ws = wb[SHEET_NAME]
    print(f"Sheet: {SHEET_NAME} ({ws.max_row} rows, {ws.max_column} columns)")
    print()

    done_count = 0
    partial_count = 0
    unchanged_count = 0
    skipped_count = 0
    changes = []

    for row in range(2, ws.max_row + 1):  # Skip header
        feature_cell = ws.cell(row=row, column=FEATURE_COL)
        status_cell = ws.cell(row=row, column=STATUS_COL)
        sno_cell = ws.cell(row=row, column=1)

        feature_text = feature_cell.value
        current_status = status_cell.value

        # Skip header rows (module/sub-module headers have no feature)
        if not feature_text:
            skipped_count += 1
            continue

        # Skip if it's the header label
        if feature_text == "Feature":
            continue

        new_status = None

        # Check explicit row overrides
        if row in ROW_OVERRIDES:
            target = ROW_OVERRIDES[row]
            # Don't downgrade Done -> Partial unless explicitly overridden
            if current_status != target:
                new_status = target

        if new_status:
            old_status = current_status or "None"
            status_cell.value = new_status
            changes.append((row, sno_cell.value, feature_text[:80], old_status, new_status))
            if new_status == "Done":
                done_count += 1
            elif new_status == "Partial":
                partial_count += 1
        else:
            unchanged_count += 1

    # Print summary
    print("=" * 100)
    print("CHANGES SUMMARY")
    print("=" * 100)
    print()

    if changes:
        # Group by new status
        done_changes = [c for c in changes if c[4] == "Done"]
        partial_changes = [c for c in changes if c[4] == "Partial"]

        if done_changes:
            print(f"--- SET TO DONE ({len(done_changes)} features) ---")
            for row_num, sno, feat, old, new in done_changes:
                print(f"  Row {row_num:3d} | #{str(sno):>3} | {old:>7} -> {new:>7} | {feat}")
            print()

        if partial_changes:
            print(f"--- SET TO PARTIAL ({len(partial_changes)} features) ---")
            for row_num, sno, feat, old, new in partial_changes:
                print(f"  Row {row_num:3d} | #{str(sno):>3} | {old:>7} -> {new:>7} | {feat}")
            print()

    print("=" * 100)
    print(f"Total features processed: {done_count + partial_count + unchanged_count}")
    print(f"  Set to Done:    {done_count}")
    print(f"  Set to Partial: {partial_count}")
    print(f"  Unchanged:      {unchanged_count}")
    print(f"  Header rows:    {skipped_count}")
    print("=" * 100)

    # Save
    wb.save(str(EXCEL_PATH))
    print(f"\nSaved: {EXCEL_PATH}")


if __name__ == "__main__":
    main()
