// Curated string → Tabler icon map for dashboard widgets. Widgets and
// quick-actions store their icon as a name (e.g. "IconUserPlus") in JSON; this
// resolves it to a component. Curated (not `import * as`) so the bundle only
// ships the icons actually used. Unknown names fall back to a neutral dot.
import {
  type Icon,
  IconAlertTriangle,
  IconArrowsTransferDown,
  IconBed,
  IconBuildingHospital,
  IconCalendar,
  IconCalendarCheck,
  IconCash,
  IconCheck,
  IconClipboardCheck,
  IconClock,
  IconCoin,
  IconDroplet,
  IconFileCheck,
  IconFileText,
  IconFlame,
  IconFlask,
  IconHeartbeat,
  IconId,
  IconList,
  IconPackage,
  IconPill,
  IconPointFilled,
  IconPrescription,
  IconReceipt,
  IconRocket,
  IconServer,
  IconSettings,
  IconShield,
  IconStethoscope,
  IconTestPipe,
  IconTool,
  IconTrendingUp,
  IconUserPlus,
  IconUsers,
  IconWallet,
} from "@tabler/icons-react";

const ICONS: Record<string, Icon> = {
  IconAlertTriangle,
  IconArrowsTransferDown,
  IconBed,
  IconBuildingHospital,
  IconCalendar,
  IconCalendarCheck,
  IconCash,
  IconCheck,
  IconClipboardCheck,
  IconClock,
  IconCoin,
  IconDroplet,
  IconFileCheck,
  IconFileText,
  IconFlame,
  IconFlask,
  IconHeartbeat,
  IconId,
  IconList,
  IconPackage,
  IconPill,
  IconPrescription,
  IconReceipt,
  IconRocket,
  IconServer,
  IconSettings,
  IconShield,
  IconStethoscope,
  IconTestPipe,
  IconTool,
  IconTrendingUp,
  IconUserPlus,
  IconUsers,
  IconWallet,
};

/** Render a widget icon by its stored name, falling back to a neutral dot. */
export function WidgetIcon({ name, size = 18 }: { name?: string | null; size?: number }) {
  const Cmp = (name && ICONS[name]) || IconPointFilled;
  return <Cmp size={size} />;
}
