import { api } from "@medbrains/api";

export const campService = {
  listCamps: api.listCamps,
  createCamp: api.createCamp,
  approveCamp: api.approveCamp,
  activateCamp: api.activateCamp,
  completeCamp: api.completeCamp,
  cancelCamp: api.cancelCamp,
  listCampTeamMembers: api.listCampTeamMembers,
  getCampStats: api.getCampStats,
  getCampRemoteOperations: api.getCampRemoteOperations,
  addCampTeamMember: api.addCampTeamMember,
  removeCampTeamMember: api.removeCampTeamMember,
  getCampPacket: api.getCampPacket,
  updateCampRemoteChecklistItem: api.updateCampRemoteChecklistItem,
  createCampSupplyItem: api.createCampSupplyItem,
  createCampIncident: api.createCampIncident,
  listCampRegistrations: api.listCampRegistrations,
  createCampRegistration: api.createCampRegistration,
  openCampRegistrationEncounter: api.openCampRegistrationEncounter,
  listCampScreenings: api.listCampScreenings,
  listCampLabSamples: api.listCampLabSamples,
  createCampScreening: api.createCampScreening,
  createCampLabSample: api.createCampLabSample,
  listCampFollowups: api.listCampFollowups,
  createCampFollowup: api.createCampFollowup,
  updateCampFollowup: api.updateCampFollowup,
  campAnalytics: api.campAnalytics,
  campReport: api.campReport,
};
