import { api } from "@medbrains/api";

export const homeHealthService = {
  listHomeMeds: api.listHomeMeds,
  scheduleHomeMed: api.scheduleHomeMed,
  recordHomeMed: api.recordHomeMed,
  listEscalations: api.listEscalations,
  raiseEscalation: api.raiseEscalation,
  updateEscalation: api.updateEscalation,
  listProgressNotes: api.listHomeProgressNotes,
  addProgressNote: api.addHomeProgressNote,
  listDischargeProgram: api.listDischargeProgram,
  addDischargeItem: api.addDischargeItem,
  toggleDischargeItem: api.toggleDischargeItem,
  listHomeVisits: api.listHomeVisits,
  scheduleHomeVisit: api.scheduleHomeVisit,
  updateHomeVisit: api.updateHomeVisit,
  documentHomeVisit: api.documentHomeVisit,
  listRemoteVitals: api.listRemoteVitals,
  ingestRemoteVital: api.ingestRemoteVital,
  listHomeCarePackages: api.listHomeCarePackages,
  createHomeCarePackage: api.createHomeCarePackage,
  consumePackageVisit: api.consumePackageVisit,
  billHomeVisit: api.billHomeVisit,
  listCaregiverEducation: api.listCaregiverEducation,
  recordCaregiverEducation: api.recordCaregiverEducation,
  listHospiceEnrollments: api.listHospiceEnrollments,
  enrollHospice: api.enrollHospice,
  updateHospice: api.updateHospice,
  listAdvanceDirectives: api.listAdvanceDirectives,
  createAdvanceDirective: api.createAdvanceDirective,
  revokeAdvanceDirective: api.revokeAdvanceDirective,
  listBereavement: api.listBereavement,
  scheduleBereavement: api.scheduleBereavement,
  updateBereavement: api.updateBereavement,
};
