//! Documents/records leaf crate: document management, ingestion, ROI, storage
//! lifecycle, signatures. Mounted via router().

use axum::{Router, routing::{delete,get,post,put}};
use medbrains_server_core::state::AppState;

pub mod document_ingestion;
pub mod documents;
pub mod roi;
pub mod signatures;
pub mod storage;

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/api/documents/templates",
            get(documents::list_templates).post(documents::create_template),
        )
        .route(
            "/api/documents/templates/defaults",
            get(documents::list_default_templates),
        )
        .route(
            "/api/documents/templates/{id}",
            get(documents::get_template)
                .put(documents::update_template)
                .delete(documents::delete_template),
        )
        .route(
            "/api/documents/templates/{id}/versions",
            get(documents::list_template_versions),
        )
        .route(
            "/api/documents/templates/{id}/set-default",
            post(documents::set_default_template),
        )
        .route(
            "/api/documents/generate",
            post(documents::generate_document),
        )
        .route(
            "/api/documents/generate/preview",
            post(documents::preview_document),
        )
        .route(
            "/api/documents/generate/batch",
            post(documents::batch_generate),
        )
        .route(
            "/api/documents/outputs",
            get(documents::list_outputs),
        )
        .route(
            "/api/documents/outputs/stats",
            get(documents::output_stats),
        )
        .route(
            "/api/documents/outputs/patient/{patient_id}",
            get(documents::list_patient_outputs),
        )
        .route(
            "/api/documents/outputs/{id}",
            get(documents::get_output),
        )
        .route(
            "/api/documents/outputs/{id}/print",
            post(documents::record_print),
        )
        .route(
            "/api/documents/outputs/{id}/void",
            post(documents::void_output),
        )
        .route(
            "/api/documents/outputs/{id}/signatures",
            get(documents::list_output_signatures)
                .post(documents::add_output_signature),
        )
        .route(
            "/api/documents/outputs/{id}/signatures/{sig_id}",
            delete(documents::delete_output_signature),
        )
        .route(
            "/api/documents/review-schedule",
            get(documents::list_review_schedule)
                .post(documents::create_review_schedule),
        )
        .route(
            "/api/documents/review-schedule/{id}",
            put(documents::mark_reviewed),
        )
        .route(
            "/api/documents/printers",
            get(documents::list_printers).post(documents::create_printer),
        )
        .route(
            "/api/documents/print-editor/capabilities",
            get(documents::print_editor_capabilities),
        )
        .route(
            "/api/documents/print-editor/mock-render",
            post(documents::mock_render_print_template),
        )
        .route(
            "/api/documents/print-jobs",
            get(documents::list_print_jobs),
        )
        .route(
            "/api/documents/print-jobs/{id}",
            put(documents::update_print_job),
        )
        .route(
            "/api/document-ingestion/batches",
            get(document_ingestion::list_batches).post(document_ingestion::create_batch),
        )
        .route(
            "/api/document-ingestion/batches/{batch_id}/items",
            get(document_ingestion::list_items).post(document_ingestion::add_item),
        )
        .route(
            "/api/document-ingestion/items/{item_id}/link",
            put(document_ingestion::link_item),
        )
        .route(
            "/api/document-ingestion/items/{item_id}/file",
            put(document_ingestion::file_item),
        )
        .route(
            "/api/document-ingestion/items/{item_id}/ocr",
            put(document_ingestion::ocr_item),
        )
        .route(
            "/api/document-ingestion/search",
            get(document_ingestion::search_ingested),
        )
        .route(
            "/api/roi-requests",
            get(roi::list_roi_requests).post(roi::create_roi_request),
        )
        .route("/api/roi-requests/{id}/review", put(roi::review_roi_request))
        .route("/api/roi-requests/{id}/access", post(roi::record_roi_access))
        .route(
            "/api/roi-requests/{id}/access-log",
            get(roi::list_roi_access_log),
        )
        .route(
            "/api/admin/storage/policies",
            get(storage::list_policies),
        )
        .route(
            "/api/admin/storage/policies/{category}",
            put(storage::update_policy),
        )
        .route("/api/admin/storage/usage", get(storage::get_usage))
        .route(
            "/api/admin/storage/transitions",
            get(storage::list_transitions),
        )
        .route(
            "/api/admin/storage/restore/{doc_id}",
            post(storage::request_restore),
        )
        .route(
            "/api/admin/storage/sweep-now",
            post(storage::trigger_sweep),
        )
        .route(
            "/api/admin/signature-credentials",
            get(signatures::list_credentials).post(signatures::issue_credential),
        )
        .route(
            "/api/admin/signature-credentials/{id}/revoke",
            post(signatures::revoke_credential),
        )
        .route(
            "/api/signatures/my-credentials",
            get(signatures::list_my_credentials),
        )
        .route(
            "/api/signatures/preview",
            get(signatures::preview_sign_record_get),
        )
        .route(
            "/api/signatures/sign",
            post(signatures::sign_record),
        )
        .route(
            "/api/signatures/list",
            get(signatures::list_signatures),
        )
        .route(
            "/api/signatures/verify",
            post(signatures::verify_signature),
        )
}
