import type { ClinicalJourneyMessageValues, PatientJourneyTranslator } from "@medbrains/types";

export const MOBILE_PATIENT_JOURNEY_BLOCKERS = {
  openActiveIpdEncounterBeforeMobileInpatientOrders:
    "patientJourney.mobile.blockers.openActiveIpdEncounterBeforeMobileInpatientOrders",
  openOpdEncounterBeforeMobileConsultation:
    "patientJourney.mobile.blockers.openOpdEncounterBeforeMobileConsultation",
  openOpdEncounterBeforeMobileOrders:
    "patientJourney.mobile.blockers.openOpdEncounterBeforeMobileOrders",
} as const;

export const MOBILE_PATIENT_JOURNEY_TEXT = {
  actionPanel: {
    title: "patientJourney.mobile.actionPanel.title",
    subtitle: "patientJourney.mobile.actionPanel.subtitle",
  },
  flow: {
    title: "patientJourney.mobile.flow.title",
    handoffs: {
      billing: "patientJourney.mobile.flow.handoffs.billing",
      camp: "patientJourney.mobile.flow.handoffs.camp",
      emergency: "patientJourney.mobile.flow.handoffs.emergency",
      ipd: "patientJourney.mobile.flow.handoffs.ipd",
      opd: "patientJourney.mobile.flow.handoffs.opd",
      patient: "patientJourney.mobile.flow.handoffs.patient",
      pharmacy: "patientJourney.mobile.flow.handoffs.pharmacy",
    },
  },
  status: {
    blocked: "patientJourney.mobile.status.blocked",
    emitsEvent: "patientJourney.mobile.status.emitsEvent",
    ready: "patientJourney.mobile.status.ready",
  },
  summary: {
    awaitingEventCount: "patientJourney.mobile.summary.awaitingEventCount",
    blockedCount: "patientJourney.mobile.summary.blockedCount",
    configCount: "patientJourney.mobile.summary.configCount",
    maskingCount: "patientJourney.mobile.summary.maskingCount",
    permissionCount: "patientJourney.mobile.summary.permissionCount",
    readyCount: "patientJourney.mobile.summary.readyCount",
    regulatoryCount: "patientJourney.mobile.summary.regulatoryCount",
  },
} as const;

export const MOBILE_CARE_CONTEXT_TEXT = {
  common: {
    activeCount: "patientJourney.mobile.careContext.common.activeCount",
    hiddenField: "patientJourney.mobile.careContext.common.hiddenField",
    linked: "patientJourney.mobile.careContext.common.linked",
    noUhid: "patientJourney.mobile.careContext.common.noUhid",
    notRecorded: "patientJourney.mobile.careContext.common.notRecorded",
    patient: "patientJourney.mobile.careContext.common.patient",
    patientContext: "patientJourney.mobile.careContext.common.patientContext",
    patientIdentity: "patientJourney.mobile.careContext.common.patientIdentity",
    restricted: "patientJourney.mobile.careContext.common.restricted",
    selected: "patientJourney.mobile.careContext.common.selected",
  },
  camp: {
    chiefComplaint: "patientJourney.mobile.careContext.camp.chiefComplaint",
    registeredAt: "patientJourney.mobile.careContext.camp.registeredAt",
    serviceLine: "patientJourney.mobile.careContext.camp.serviceLine",
  },
  empty: {
    contextUnavailableTitle: "patientJourney.mobile.careContext.empty.contextUnavailableTitle",
    noCampMessage: "patientJourney.mobile.careContext.empty.noCampMessage",
    noCampTitle: "patientJourney.mobile.careContext.empty.noCampTitle",
    noEmergencyMessage: "patientJourney.mobile.careContext.empty.noEmergencyMessage",
    noEmergencyTitle: "patientJourney.mobile.careContext.empty.noEmergencyTitle",
    noIpdMessage: "patientJourney.mobile.careContext.empty.noIpdMessage",
    noIpdTitle: "patientJourney.mobile.careContext.empty.noIpdTitle",
    restrictedTitle: "patientJourney.mobile.careContext.empty.restrictedTitle",
  },
  emergency: {
    arrivedAt: "patientJourney.mobile.careContext.emergency.arrivedAt",
    bay: "patientJourney.mobile.careContext.emergency.bay",
    chiefComplaint: "patientJourney.mobile.careContext.emergency.chiefComplaint",
    mlc: "patientJourney.mobile.careContext.emergency.mlc",
    triage: "patientJourney.mobile.careContext.emergency.triage",
    unassigned: "patientJourney.mobile.careContext.emergency.unassigned",
  },
  identity: {
    loadingPatient: "patientJourney.mobile.careContext.identity.loadingPatient",
    patientIdentityUnavailable:
      "patientJourney.mobile.careContext.identity.patientIdentityUnavailable",
    uhidUnavailable: "patientJourney.mobile.careContext.identity.uhidUnavailable",
  },
  ipd: {
    admittedAt: "patientJourney.mobile.careContext.ipd.admittedAt",
    admittingDoctor: "patientJourney.mobile.careContext.ipd.admittingDoctor",
    bedAssigned: "patientJourney.mobile.careContext.ipd.bedAssigned",
    bedPending: "patientJourney.mobile.careContext.ipd.bedPending",
    bedPendingDescription: "patientJourney.mobile.careContext.ipd.bedPendingDescription",
    recordVitals: "patientJourney.mobile.careContext.ipd.recordVitals",
    wardPending: "patientJourney.mobile.careContext.ipd.wardPending",
  },
  loading: {
    handoffContext: "patientJourney.mobile.careContext.loading.handoffContext",
  },
  modules: {
    campTitle: "patientJourney.mobile.careContext.modules.campTitle",
    campSubtitle: "patientJourney.mobile.careContext.modules.campSubtitle",
    campPermission: "patientJourney.mobile.careContext.modules.campPermission",
    campUnavailable: "patientJourney.mobile.careContext.modules.campUnavailable",
    emergencyTitle: "patientJourney.mobile.careContext.modules.emergencyTitle",
    emergencyMlcTitle: "patientJourney.mobile.careContext.modules.emergencyMlcTitle",
    emergencySubtitle: "patientJourney.mobile.careContext.modules.emergencySubtitle",
    emergencyPermission: "patientJourney.mobile.careContext.modules.emergencyPermission",
    emergencyUnavailable: "patientJourney.mobile.careContext.modules.emergencyUnavailable",
    ipdTitle: "patientJourney.mobile.careContext.modules.ipdTitle",
    ipdAdmitTitle: "patientJourney.mobile.careContext.modules.ipdAdmitTitle",
    ipdSubtitle: "patientJourney.mobile.careContext.modules.ipdSubtitle",
    ipdPermission: "patientJourney.mobile.careContext.modules.ipdPermission",
    ipdUnavailable: "patientJourney.mobile.careContext.modules.ipdUnavailable",
  },
} as const;

export const MOBILE_PATIENT_DETAIL_TEXT = {
  actions: {
    activationHint: "patientJourney.mobile.patientDetail.actions.activationHint",
    activeEr: "patientJourney.mobile.patientDetail.actions.activeEr",
    activeIpd: "patientJourney.mobile.patientDetail.actions.activeIpd",
    activeOpd: "patientJourney.mobile.patientDetail.actions.activeOpd",
    bedPending: "patientJourney.mobile.patientDetail.actions.bedPending",
    campStatus: "patientJourney.mobile.patientDetail.actions.campStatus",
    missingCareContextHint: "patientJourney.mobile.patientDetail.actions.missingCareContextHint",
    mlc: "patientJourney.mobile.patientDetail.actions.mlc",
    pendingBillPlural: "patientJourney.mobile.patientDetail.actions.pendingBillPlural",
    pendingBillSingular: "patientJourney.mobile.patientDetail.actions.pendingBillSingular",
    rxHandoff: "patientJourney.mobile.patientDetail.actions.rxHandoff",
    title: "patientJourney.mobile.patientDetail.actions.title",
    vitals: "patientJourney.mobile.patientDetail.actions.vitals",
  },
  empty: {
    noRecentVisits: "patientJourney.mobile.patientDetail.empty.noRecentVisits",
    patientNotFound: "patientJourney.mobile.patientDetail.empty.patientNotFound",
  },
  fields: {
    address: "patientJourney.mobile.patientDetail.fields.address",
    ageMasked: "patientJourney.mobile.patientDetail.fields.ageMasked",
    ageYearPlural: "patientJourney.mobile.patientDetail.fields.ageYearPlural",
    ageYearSingular: "patientJourney.mobile.patientDetail.fields.ageYearSingular",
    dateMasked: "patientJourney.mobile.patientDetail.fields.dateMasked",
    dateOfBirth: "patientJourney.mobile.patientDetail.fields.dateOfBirth",
    hiddenField: "patientJourney.mobile.patientDetail.fields.hiddenField",
    maritalStatus: "patientJourney.mobile.patientDetail.fields.maritalStatus",
    maskedField: "patientJourney.mobile.patientDetail.fields.maskedField",
    noUhid: "patientJourney.mobile.patientDetail.fields.noUhid",
    notSpecified: "patientJourney.mobile.patientDetail.fields.notSpecified",
    occupation: "patientJourney.mobile.patientDetail.fields.occupation",
    patientInitials: "patientJourney.mobile.patientDetail.fields.patientInitials",
    unknown: "patientJourney.mobile.patientDetail.fields.unknown",
    unknownPatient: "patientJourney.mobile.patientDetail.fields.unknownPatient",
  },
  loading: {
    patientDetails: "patientJourney.mobile.patientDetail.loading.patientDetails",
  },
  sections: {
    allergies: "patientJourney.mobile.patientDetail.sections.allergies",
    patientInformation: "patientJourney.mobile.patientDetail.sections.patientInformation",
    recentVisits: "patientJourney.mobile.patientDetail.sections.recentVisits",
  },
  status: {
    campConverted: "patientJourney.mobile.patientDetail.status.campConverted",
    campRegistered: "patientJourney.mobile.patientDetail.status.campRegistered",
    campReferred: "patientJourney.mobile.patientDetail.status.campReferred",
    campScreened: "patientJourney.mobile.patientDetail.status.campScreened",
    emergency: "patientJourney.mobile.patientDetail.status.emergency",
    female: "patientJourney.mobile.patientDetail.status.female",
    ipd: "patientJourney.mobile.patientDetail.status.ipd",
    male: "patientJourney.mobile.patientDetail.status.male",
    maritalDivorced: "patientJourney.mobile.patientDetail.status.maritalDivorced",
    maritalDomesticPartner: "patientJourney.mobile.patientDetail.status.maritalDomesticPartner",
    maritalMarried: "patientJourney.mobile.patientDetail.status.maritalMarried",
    maritalSeparated: "patientJourney.mobile.patientDetail.status.maritalSeparated",
    maritalSingle: "patientJourney.mobile.patientDetail.status.maritalSingle",
    maritalUnknown: "patientJourney.mobile.patientDetail.status.maritalUnknown",
    maritalWidowed: "patientJourney.mobile.patientDetail.status.maritalWidowed",
    opd: "patientJourney.mobile.patientDetail.status.opd",
    other: "patientJourney.mobile.patientDetail.status.other",
    unknown: "patientJourney.mobile.patientDetail.status.unknown",
  },
  visits: {
    consultation: "patientJourney.mobile.patientDetail.visits.consultation",
  },
} as const;

export const MOBILE_VITALS_ENTRY_TEXT = {
  actions: {
    save: "patientJourney.mobile.vitals.actions.save",
  },
  bmi: {
    calculated: "patientJourney.mobile.vitals.bmi.calculated",
  },
  errors: {
    invalidDiastolic: "patientJourney.mobile.vitals.errors.invalidDiastolic",
    invalidHeight: "patientJourney.mobile.vitals.errors.invalidHeight",
    invalidPulse: "patientJourney.mobile.vitals.errors.invalidPulse",
    invalidRespiration: "patientJourney.mobile.vitals.errors.invalidRespiration",
    invalidSpo2: "patientJourney.mobile.vitals.errors.invalidSpo2",
    invalidSystolic: "patientJourney.mobile.vitals.errors.invalidSystolic",
    invalidTemperature: "patientJourney.mobile.vitals.errors.invalidTemperature",
    invalidWeight: "patientJourney.mobile.vitals.errors.invalidWeight",
    noEncounterId: "patientJourney.mobile.vitals.errors.noEncounterId",
    saveFailed: "patientJourney.mobile.vitals.errors.saveFailed",
  },
  fields: {
    diastolic: "patientJourney.mobile.vitals.fields.diastolic",
    height: "patientJourney.mobile.vitals.fields.height",
    normalRange: "patientJourney.mobile.vitals.fields.normalRange",
    pulse: "patientJourney.mobile.vitals.fields.pulse",
    respiration: "patientJourney.mobile.vitals.fields.respiration",
    spo2: "patientJourney.mobile.vitals.fields.spo2",
    systolic: "patientJourney.mobile.vitals.fields.systolic",
    temperature: "patientJourney.mobile.vitals.fields.temperature",
    weight: "patientJourney.mobile.vitals.fields.weight",
  },
  sections: {
    anthropometry: "patientJourney.mobile.vitals.sections.anthropometry",
    previousVitals: "patientJourney.mobile.vitals.sections.previousVitals",
    vitalSigns: "patientJourney.mobile.vitals.sections.vitalSigns",
  },
  status: {
    saved: "patientJourney.mobile.vitals.status.saved",
  },
  summary: {
    bp: "patientJourney.mobile.vitals.summary.bp",
    pulse: "patientJourney.mobile.vitals.summary.pulse",
    recorded: "patientJourney.mobile.vitals.summary.recorded",
    spo2: "patientJourney.mobile.vitals.summary.spo2",
    temperature: "patientJourney.mobile.vitals.summary.temperature",
  },
} as const;

export const MOBILE_NAVIGATION_TEXT = {
  patient: {
    appointments: "patientJourney.mobile.navigation.patient.appointments",
    billing: "patientJourney.mobile.navigation.patient.billing",
    labResultDetails: "patientJourney.mobile.navigation.patient.labResultDetails",
    labResults: "patientJourney.mobile.navigation.patient.labResults",
    myHealth: "patientJourney.mobile.navigation.patient.myHealth",
    prescriptions: "patientJourney.mobile.navigation.patient.prescriptions",
    profile: "patientJourney.mobile.navigation.patient.profile",
    queueStatus: "patientJourney.mobile.navigation.patient.queueStatus",
  },
  phlebotomy: {
    collectSamples: "patientJourney.mobile.navigation.phlebotomy.collectSamples",
    collectionDetails: "patientJourney.mobile.navigation.phlebotomy.collectionDetails",
    homeCollections: "patientJourney.mobile.navigation.phlebotomy.homeCollections",
    tripSummary: "patientJourney.mobile.navigation.phlebotomy.tripSummary",
  },
  staff: {
    billing: "patientJourney.mobile.navigation.staff.billing",
    careContext: "patientJourney.mobile.navigation.staff.careContext",
    consultationNotes: "patientJourney.mobile.navigation.staff.consultationNotes",
    dashboard: "patientJourney.mobile.navigation.staff.dashboard",
    ePrescription: "patientJourney.mobile.navigation.staff.ePrescription",
    findPatient: "patientJourney.mobile.navigation.staff.findPatient",
    imagingOrder: "patientJourney.mobile.navigation.staff.imagingOrder",
    labOrders: "patientJourney.mobile.navigation.staff.labOrders",
    labResults: "patientJourney.mobile.navigation.staff.labResults",
    patientDetails: "patientJourney.mobile.navigation.staff.patientDetails",
    patientPharmacy: "patientJourney.mobile.navigation.staff.patientPharmacy",
    patientQueue: "patientJourney.mobile.navigation.staff.patientQueue",
    recordVitals: "patientJourney.mobile.navigation.staff.recordVitals",
    tokenBoards: "patientJourney.mobile.navigation.staff.tokenBoards",
  },
} as const;

export const MOBILE_STAFF_DASHBOARD_TEXT = {
  common: {
    greeting: "patientJourney.mobile.staffDashboard.common.greeting",
    staffFallback: "patientJourney.mobile.staffDashboard.common.staffFallback",
    staffInitials: "patientJourney.mobile.staffDashboard.common.staffInitials",
  },
  flow: {
    boards: "patientJourney.mobile.staffDashboard.flow.boards",
    empty: "patientJourney.mobile.staffDashboard.flow.empty",
    imaging: "patientJourney.mobile.staffDashboard.flow.imaging",
    orders: "patientJourney.mobile.staffDashboard.flow.orders",
    patient: "patientJourney.mobile.staffDashboard.flow.patient",
    queue: "patientJourney.mobile.staffDashboard.flow.queue",
    results: "patientJourney.mobile.staffDashboard.flow.results",
    title: "patientJourney.mobile.staffDashboard.flow.title",
    vitals: "patientJourney.mobile.staffDashboard.flow.vitals",
  },
  overview: {
    active: "patientJourney.mobile.staffDashboard.overview.active",
    completed: "patientJourney.mobile.staffDashboard.overview.completed",
    openBillingDesk: "patientJourney.mobile.staffDashboard.overview.openBillingDesk",
    openLabWorklist: "patientJourney.mobile.staffDashboard.overview.openLabWorklist",
    openOpdQueue: "patientJourney.mobile.staffDashboard.overview.openOpdQueue",
    openPatientSearch: "patientJourney.mobile.staffDashboard.overview.openPatientSearch",
    title: "patientJourney.mobile.staffDashboard.overview.title",
    tokensToday: "patientJourney.mobile.staffDashboard.overview.tokensToday",
    waiting: "patientJourney.mobile.staffDashboard.overview.waiting",
  },
  queue: {
    currentQueue: "patientJourney.mobile.staffDashboard.queue.currentQueue",
    emptyMessage: "patientJourney.mobile.staffDashboard.queue.emptyMessage",
    emptyTitle: "patientJourney.mobile.staffDashboard.queue.emptyTitle",
    loading: "patientJourney.mobile.staffDashboard.queue.loading",
    restrictedMessage: "patientJourney.mobile.staffDashboard.queue.restrictedMessage",
    restrictedTitle: "patientJourney.mobile.staffDashboard.queue.restrictedTitle",
    retry: "patientJourney.mobile.staffDashboard.queue.retry",
    unavailableMessage: "patientJourney.mobile.staffDashboard.queue.unavailableMessage",
    unavailableTitle: "patientJourney.mobile.staffDashboard.queue.unavailableTitle",
  },
  quickActions: {
    emptyMessage: "patientJourney.mobile.staffDashboard.quickActions.emptyMessage",
    emptyTitle: "patientJourney.mobile.staffDashboard.quickActions.emptyTitle",
    fabFind: "patientJourney.mobile.staffDashboard.quickActions.fabFind",
    findPatient: "patientJourney.mobile.staffDashboard.quickActions.findPatient",
    fullQueue: "patientJourney.mobile.staffDashboard.quickActions.fullQueue",
    imaging: "patientJourney.mobile.staffDashboard.quickActions.imaging",
    labOrder: "patientJourney.mobile.staffDashboard.quickActions.labOrder",
    labResults: "patientJourney.mobile.staffDashboard.quickActions.labResults",
    title: "patientJourney.mobile.staffDashboard.quickActions.title",
    tokenBoards: "patientJourney.mobile.staffDashboard.quickActions.tokenBoards",
    vitals: "patientJourney.mobile.staffDashboard.quickActions.vitals",
    writeRx: "patientJourney.mobile.staffDashboard.quickActions.writeRx",
  },
} as const;

export const MOBILE_QUEUE_ITEM_TEXT = {
  actions: {
    call: "patientJourney.mobile.queueItem.actions.call",
    done: "patientJourney.mobile.queueItem.actions.done",
    noShow: "patientJourney.mobile.queueItem.actions.noShow",
    start: "patientJourney.mobile.queueItem.actions.start",
  },
  fields: {
    doctor: "patientJourney.mobile.queueItem.fields.doctor",
    waitMinutes: "patientJourney.mobile.queueItem.fields.waitMinutes",
  },
  status: {
    called: "patientJourney.mobile.queueItem.status.called",
    completed: "patientJourney.mobile.queueItem.status.completed",
    inProgress: "patientJourney.mobile.queueItem.status.inProgress",
    noShow: "patientJourney.mobile.queueItem.status.noShow",
    waiting: "patientJourney.mobile.queueItem.status.waiting",
  },
} as const;

export const MOBILE_QUEUE_SCREEN_TEXT = {
  banner: {
    currentlySeeing: "patientJourney.mobile.queueScreen.banner.currentlySeeing",
    patientFallback: "patientJourney.mobile.queueScreen.banner.patientFallback",
  },
  empty: {
    allMessage: "patientJourney.mobile.queueScreen.empty.allMessage",
    filteredMessage: "patientJourney.mobile.queueScreen.empty.filteredMessage",
    title: "patientJourney.mobile.queueScreen.empty.title",
  },
  filters: {
    active: "patientJourney.mobile.queueScreen.filters.active",
    all: "patientJourney.mobile.queueScreen.filters.all",
    called: "patientJourney.mobile.queueScreen.filters.called",
    waiting: "patientJourney.mobile.queueScreen.filters.waiting",
  },
  loading: {
    queue: "patientJourney.mobile.queueScreen.loading.queue",
  },
  restricted: {
    message: "patientJourney.mobile.queueScreen.restricted.message",
    title: "patientJourney.mobile.queueScreen.restricted.title",
  },
  stats: {
    called: "patientJourney.mobile.queueScreen.stats.called",
    inProgress: "patientJourney.mobile.queueScreen.stats.inProgress",
    waiting: "patientJourney.mobile.queueScreen.stats.waiting",
  },
} as const;

const MOBILE_PATIENT_JOURNEY_MESSAGES: Record<string, string> = {
  "patientJourney.blockedReasons.configuration": "Configuration",
  "patientJourney.blockedReasons.context": "Context",
  "patientJourney.blockedReasons.event": "Event",
  "patientJourney.blockedReasons.masking": "Masking",
  "patientJourney.blockedReasons.permission": "Permission",
  "patientJourney.blockedReasons.regulatory": "Regulatory",
  "patientJourney.events.bed.assigned": "bed assigned",
  "patientJourney.events.billing.invoiceCreated": "billing invoice created",
  "patientJourney.events.billing.invoiceFinalized": "billing invoice finalized",
  "patientJourney.events.billing.paymentReceived": "billing payment received",
  "patientJourney.events.camp.started": "camp started",
  "patientJourney.events.camp.registrationCreated": "camp registration created",
  "patientJourney.events.camp.screeningCompleted": "camp screening completed",
  "patientJourney.events.emergency.visitCreated": "emergency visit created",
  "patientJourney.events.ipd.admissionCreated": "IPD admission created",
  "patientJourney.events.ipd.dischargeFinalized": "IPD discharge finalized",
  "patientJourney.events.opd.encounterCreated": "OPD encounter created",
  "patientJourney.events.order.created": "order created",
  "patientJourney.events.patient.created": "patient created",
  "patientJourney.events.pharmacy.orderDispensed": "pharmacy order dispensed",
  "patientJourney.events.pharmacy.prescriptionReviewed": "pharmacy prescription reviewed",
  "patientJourney.lists.orJoin": "{{left}} or {{right}}",
  "patientJourney.mobile.blockers.openActiveIpdEncounterBeforeMobileInpatientOrders":
    "Open an active IPD encounter before mobile inpatient orders",
  "patientJourney.mobile.blockers.openOpdEncounterBeforeMobileConsultation":
    "Open an OPD encounter before mobile consultation",
  "patientJourney.mobile.blockers.openOpdEncounterBeforeMobileOrders":
    "Open an OPD encounter before mobile orders",
  "patientJourney.mobile.actionPanel.title": "Patient Flow",
  "patientJourney.mobile.actionPanel.subtitle": "Event and permission driven mobile handoffs",
  "patientJourney.mobile.flow.title": "Flow Handoffs",
  "patientJourney.mobile.flow.handoffs.billing": "Bill",
  "patientJourney.mobile.flow.handoffs.camp": "Camp",
  "patientJourney.mobile.flow.handoffs.emergency": "ER",
  "patientJourney.mobile.flow.handoffs.ipd": "Ward",
  "patientJourney.mobile.flow.handoffs.opd": "Clinic",
  "patientJourney.mobile.flow.handoffs.patient": "Record",
  "patientJourney.mobile.flow.handoffs.pharmacy": "Rx",
  "patientJourney.mobile.status.blocked": "Blocked",
  "patientJourney.mobile.status.emitsEvent": "Emits {{event}}",
  "patientJourney.mobile.status.ready": "Ready",
  "patientJourney.mobile.summary.awaitingEventCount": "{{count}} awaiting event",
  "patientJourney.mobile.summary.blockedCount": "{{count}} blocked",
  "patientJourney.mobile.summary.configCount": "{{count}} config",
  "patientJourney.mobile.summary.maskingCount": "{{count}} masking",
  "patientJourney.mobile.summary.permissionCount": "{{count}} permission",
  "patientJourney.mobile.summary.readyCount": "{{enabled}}/{{total}} ready",
  "patientJourney.mobile.summary.regulatoryCount": "{{count}} regulatory",
  "patientJourney.mobile.careContext.common.activeCount": "{{count}} active",
  "patientJourney.mobile.careContext.common.hiddenField": "Restricted",
  "patientJourney.mobile.careContext.common.linked": "Linked",
  "patientJourney.mobile.careContext.common.noUhid": "No UHID",
  "patientJourney.mobile.careContext.common.notRecorded": "Not recorded",
  "patientJourney.mobile.careContext.common.patient": "Patient",
  "patientJourney.mobile.careContext.common.patientContext": "Patient context",
  "patientJourney.mobile.careContext.common.patientIdentity": "Patient identity",
  "patientJourney.mobile.careContext.common.restricted": "Restricted",
  "patientJourney.mobile.careContext.common.selected": "Selected",
  "patientJourney.mobile.careContext.camp.chiefComplaint": "Chief complaint",
  "patientJourney.mobile.careContext.camp.registeredAt": "Registered {{date}}",
  "patientJourney.mobile.careContext.camp.serviceLine": "Service line",
  "patientJourney.mobile.careContext.empty.contextUnavailableTitle": "Context unavailable",
  "patientJourney.mobile.careContext.empty.noCampMessage":
    "No outreach registrations match this patient.",
  "patientJourney.mobile.careContext.empty.noCampTitle": "No camp records",
  "patientJourney.mobile.careContext.empty.noEmergencyMessage": "No ER visits match this patient.",
  "patientJourney.mobile.careContext.empty.noEmergencyTitle": "No emergency records",
  "patientJourney.mobile.careContext.empty.noIpdMessage": "No admissions match this patient.",
  "patientJourney.mobile.careContext.empty.noIpdTitle": "No IPD records",
  "patientJourney.mobile.careContext.empty.restrictedTitle": "Restricted context",
  "patientJourney.mobile.careContext.emergency.arrivedAt": "Arrived {{date}}",
  "patientJourney.mobile.careContext.emergency.bay": "Bay",
  "patientJourney.mobile.careContext.emergency.chiefComplaint": "Chief complaint",
  "patientJourney.mobile.careContext.emergency.mlc": "MLC",
  "patientJourney.mobile.careContext.emergency.triage": "Triage",
  "patientJourney.mobile.careContext.emergency.unassigned": "Unassigned",
  "patientJourney.mobile.careContext.identity.loadingPatient": "Loading patient...",
  "patientJourney.mobile.careContext.identity.patientIdentityUnavailable":
    "Patient identity unavailable",
  "patientJourney.mobile.careContext.identity.uhidUnavailable": "UHID unavailable",
  "patientJourney.mobile.careContext.ipd.admittedAt": "Admitted {{date}}",
  "patientJourney.mobile.careContext.ipd.admittingDoctor": "Admitting doctor",
  "patientJourney.mobile.careContext.ipd.bedAssigned": "Bed assigned",
  "patientJourney.mobile.careContext.ipd.bedPending": "Bed pending",
  "patientJourney.mobile.careContext.ipd.bedPendingDescription":
    "Admission cannot proceed to bedside orders yet",
  "patientJourney.mobile.careContext.ipd.recordVitals": "Record vitals",
  "patientJourney.mobile.careContext.ipd.wardPending": "Ward pending",
  "patientJourney.mobile.careContext.loading.handoffContext": "Loading handoff context...",
  "patientJourney.mobile.careContext.modules.campPermission":
    "Camp registration list permission is required to show outreach records.",
  "patientJourney.mobile.careContext.modules.campSubtitle":
    "Review outreach registration and screening continuity for this patient.",
  "patientJourney.mobile.careContext.modules.campTitle": "Camp continuity handoff",
  "patientJourney.mobile.careContext.modules.campUnavailable":
    "The latest camp records could not be loaded.",
  "patientJourney.mobile.careContext.modules.emergencyMlcTitle": "MLC handoff",
  "patientJourney.mobile.careContext.modules.emergencyPermission":
    "Emergency visit list permission is required to show ER records.",
  "patientJourney.mobile.careContext.modules.emergencySubtitle":
    "Review emergency visits, triage state, and MLC-sensitive context.",
  "patientJourney.mobile.careContext.modules.emergencyTitle": "Emergency handoff",
  "patientJourney.mobile.careContext.modules.emergencyUnavailable":
    "The latest emergency records could not be loaded.",
  "patientJourney.mobile.careContext.modules.ipdAdmitTitle": "IPD admission handoff",
  "patientJourney.mobile.careContext.modules.ipdPermission":
    "IPD admission list permission is required to show inpatient records.",
  "patientJourney.mobile.careContext.modules.ipdSubtitle":
    "Review admission status, bed state, and inpatient handoff details.",
  "patientJourney.mobile.careContext.modules.ipdTitle": "IPD care context",
  "patientJourney.mobile.careContext.modules.ipdUnavailable":
    "The latest IPD records could not be loaded.",
  "patientJourney.mobile.patientDetail.actions.activationHint":
    "Mobile handoffs activate from OPD, IPD, ER, camp, prescription, invoice, and payment events.",
  "patientJourney.mobile.patientDetail.actions.activeEr": "Active ER",
  "patientJourney.mobile.patientDetail.actions.activeIpd": "Active IPD",
  "patientJourney.mobile.patientDetail.actions.activeOpd": "Active OPD",
  "patientJourney.mobile.patientDetail.actions.bedPending": "Bed pending",
  "patientJourney.mobile.patientDetail.actions.campStatus": "Camp {{status}}",
  "patientJourney.mobile.patientDetail.actions.missingCareContextHint":
    "Open an OPD encounter or active IPD admission before recording vitals, prescriptions, or lab orders.",
  "patientJourney.mobile.patientDetail.actions.mlc": "MLC",
  "patientJourney.mobile.patientDetail.actions.pendingBillPlural": "{{count}} bills",
  "patientJourney.mobile.patientDetail.actions.pendingBillSingular": "{{count}} bill",
  "patientJourney.mobile.patientDetail.actions.rxHandoff": "Rx handoff",
  "patientJourney.mobile.patientDetail.actions.title": "Care Actions",
  "patientJourney.mobile.patientDetail.actions.vitals": "Vitals",
  "patientJourney.mobile.patientDetail.empty.noRecentVisits": "No recent visits",
  "patientJourney.mobile.patientDetail.empty.patientNotFound": "Patient not found",
  "patientJourney.mobile.patientDetail.fields.address": "Address",
  "patientJourney.mobile.patientDetail.fields.ageMasked": "Age masked",
  "patientJourney.mobile.patientDetail.fields.ageYearPlural": "{{count}} years",
  "patientJourney.mobile.patientDetail.fields.ageYearSingular": "{{count}} year",
  "patientJourney.mobile.patientDetail.fields.dateMasked": "Date masked",
  "patientJourney.mobile.patientDetail.fields.dateOfBirth": "Date of Birth",
  "patientJourney.mobile.patientDetail.fields.hiddenField": "Restricted",
  "patientJourney.mobile.patientDetail.fields.maritalStatus": "Marital Status",
  "patientJourney.mobile.patientDetail.fields.maskedField": "Masked",
  "patientJourney.mobile.patientDetail.fields.noUhid": "No UHID",
  "patientJourney.mobile.patientDetail.fields.notSpecified": "Not specified",
  "patientJourney.mobile.patientDetail.fields.occupation": "Occupation",
  "patientJourney.mobile.patientDetail.fields.patientInitials": "PT",
  "patientJourney.mobile.patientDetail.fields.unknown": "Unknown",
  "patientJourney.mobile.patientDetail.fields.unknownPatient": "Unknown patient",
  "patientJourney.mobile.patientDetail.loading.patientDetails": "Loading patient details...",
  "patientJourney.mobile.patientDetail.sections.allergies": "Allergies",
  "patientJourney.mobile.patientDetail.sections.patientInformation": "Patient Information",
  "patientJourney.mobile.patientDetail.sections.recentVisits": "Recent Visits",
  "patientJourney.mobile.patientDetail.status.campConverted": "Converted",
  "patientJourney.mobile.patientDetail.status.campRegistered": "Registered",
  "patientJourney.mobile.patientDetail.status.campReferred": "Referred",
  "patientJourney.mobile.patientDetail.status.campScreened": "Screened",
  "patientJourney.mobile.patientDetail.status.emergency": "Emergency",
  "patientJourney.mobile.patientDetail.status.female": "Female",
  "patientJourney.mobile.patientDetail.status.ipd": "IPD",
  "patientJourney.mobile.patientDetail.status.male": "Male",
  "patientJourney.mobile.patientDetail.status.maritalDivorced": "Divorced",
  "patientJourney.mobile.patientDetail.status.maritalDomesticPartner": "Domestic partner",
  "patientJourney.mobile.patientDetail.status.maritalMarried": "Married",
  "patientJourney.mobile.patientDetail.status.maritalSeparated": "Separated",
  "patientJourney.mobile.patientDetail.status.maritalSingle": "Single",
  "patientJourney.mobile.patientDetail.status.maritalUnknown": "Unknown",
  "patientJourney.mobile.patientDetail.status.maritalWidowed": "Widowed",
  "patientJourney.mobile.patientDetail.status.opd": "OPD",
  "patientJourney.mobile.patientDetail.status.other": "Other",
  "patientJourney.mobile.patientDetail.status.unknown": "Unknown",
  "patientJourney.mobile.patientDetail.visits.consultation": "Consultation",
  "patientJourney.mobile.navigation.patient.appointments": "Appointments",
  "patientJourney.mobile.navigation.patient.billing": "Bills & Payments",
  "patientJourney.mobile.navigation.patient.labResultDetails": "Result Details",
  "patientJourney.mobile.navigation.patient.labResults": "Lab Results",
  "patientJourney.mobile.navigation.patient.myHealth": "My Health",
  "patientJourney.mobile.navigation.patient.prescriptions": "Prescriptions",
  "patientJourney.mobile.navigation.patient.profile": "Profile",
  "patientJourney.mobile.navigation.patient.queueStatus": "Queue Status",
  "patientJourney.mobile.navigation.phlebotomy.collectSamples": "Collect Samples",
  "patientJourney.mobile.navigation.phlebotomy.collectionDetails": "Collection Details",
  "patientJourney.mobile.navigation.phlebotomy.homeCollections": "Home Collections",
  "patientJourney.mobile.navigation.phlebotomy.tripSummary": "Trip Summary",
  "patientJourney.mobile.navigation.staff.billing": "Patient Billing",
  "patientJourney.mobile.navigation.staff.careContext": "Care Context",
  "patientJourney.mobile.navigation.staff.consultationNotes": "Consultation Notes",
  "patientJourney.mobile.navigation.staff.dashboard": "Dashboard",
  "patientJourney.mobile.navigation.staff.ePrescription": "E-Prescription",
  "patientJourney.mobile.navigation.staff.findPatient": "Find Patient",
  "patientJourney.mobile.navigation.staff.imagingOrder": "Imaging Order",
  "patientJourney.mobile.navigation.staff.labOrders": "Lab Orders",
  "patientJourney.mobile.navigation.staff.labResults": "Lab Results",
  "patientJourney.mobile.navigation.staff.patientDetails": "Patient Details",
  "patientJourney.mobile.navigation.staff.patientPharmacy": "Patient Pharmacy",
  "patientJourney.mobile.navigation.staff.patientQueue": "Patient Queue",
  "patientJourney.mobile.navigation.staff.recordVitals": "Record Vitals",
  "patientJourney.mobile.navigation.staff.tokenBoards": "Token Boards",
  "patientJourney.mobile.queueItem.actions.call": "Call",
  "patientJourney.mobile.queueItem.actions.done": "Done",
  "patientJourney.mobile.queueItem.actions.noShow": "Mark no-show",
  "patientJourney.mobile.queueItem.actions.start": "Start",
  "patientJourney.mobile.queueItem.fields.doctor": "Dr. {{name}}",
  "patientJourney.mobile.queueItem.fields.waitMinutes": "{{count}} min",
  "patientJourney.mobile.queueItem.status.called": "Called",
  "patientJourney.mobile.queueItem.status.completed": "Completed",
  "patientJourney.mobile.queueItem.status.inProgress": "In Progress",
  "patientJourney.mobile.queueItem.status.noShow": "No Show",
  "patientJourney.mobile.queueItem.status.waiting": "Waiting",
  "patientJourney.mobile.queueScreen.banner.currentlySeeing": "Currently seeing",
  "patientJourney.mobile.queueScreen.banner.patientFallback": "Patient",
  "patientJourney.mobile.queueScreen.empty.allMessage":
    "The queue is empty. Patients will appear here when they check in.",
  "patientJourney.mobile.queueScreen.empty.filteredMessage":
    'No patients with "{{status}}" status.',
  "patientJourney.mobile.queueScreen.empty.title": "No patients in queue",
  "patientJourney.mobile.queueScreen.filters.active": "Active",
  "patientJourney.mobile.queueScreen.filters.all": "All",
  "patientJourney.mobile.queueScreen.filters.called": "Called",
  "patientJourney.mobile.queueScreen.filters.waiting": "Waiting",
  "patientJourney.mobile.queueScreen.loading.queue": "Loading queue...",
  "patientJourney.mobile.queueScreen.restricted.message":
    "OPD queue visibility is controlled by your permission matrix.",
  "patientJourney.mobile.queueScreen.restricted.title": "Queue access restricted",
  "patientJourney.mobile.queueScreen.stats.called": "Called",
  "patientJourney.mobile.queueScreen.stats.inProgress": "In Progress",
  "patientJourney.mobile.queueScreen.stats.waiting": "Waiting",
  "patientJourney.mobile.staffDashboard.common.greeting": "Good Morning,",
  "patientJourney.mobile.staffDashboard.common.staffFallback": "Staff",
  "patientJourney.mobile.staffDashboard.common.staffInitials": "ST",
  "patientJourney.mobile.staffDashboard.flow.boards": "Boards",
  "patientJourney.mobile.staffDashboard.flow.empty":
    "No mobile workflow actions are enabled for this role.",
  "patientJourney.mobile.staffDashboard.flow.imaging": "Imaging",
  "patientJourney.mobile.staffDashboard.flow.orders": "Orders",
  "patientJourney.mobile.staffDashboard.flow.patient": "Patient",
  "patientJourney.mobile.staffDashboard.flow.queue": "Queue",
  "patientJourney.mobile.staffDashboard.flow.results": "Results",
  "patientJourney.mobile.staffDashboard.flow.title": "Enabled mobile flow",
  "patientJourney.mobile.staffDashboard.flow.vitals": "Vitals",
  "patientJourney.mobile.staffDashboard.overview.active": "Active",
  "patientJourney.mobile.staffDashboard.overview.completed": "Completed",
  "patientJourney.mobile.staffDashboard.overview.openBillingDesk": "Open billing desk",
  "patientJourney.mobile.staffDashboard.overview.openLabWorklist": "Open lab worklist",
  "patientJourney.mobile.staffDashboard.overview.openOpdQueue": "Open OPD queue",
  "patientJourney.mobile.staffDashboard.overview.openPatientSearch": "Find patient",
  "patientJourney.mobile.staffDashboard.overview.title": "Today's Overview",
  "patientJourney.mobile.staffDashboard.overview.tokensToday": "Tokens Today",
  "patientJourney.mobile.staffDashboard.overview.waiting": "Waiting",
  "patientJourney.mobile.staffDashboard.queue.currentQueue": "Current Queue",
  "patientJourney.mobile.staffDashboard.queue.emptyMessage":
    "Checked-in patients will appear here from the shared OPD queue.",
  "patientJourney.mobile.staffDashboard.queue.emptyTitle": "No active queue tokens",
  "patientJourney.mobile.staffDashboard.queue.loading": "Loading live queue...",
  "patientJourney.mobile.staffDashboard.queue.restrictedMessage":
    "OPD queue visibility is controlled by your permission matrix.",
  "patientJourney.mobile.staffDashboard.queue.restrictedTitle": "Queue restricted",
  "patientJourney.mobile.staffDashboard.queue.retry": "Retry",
  "patientJourney.mobile.staffDashboard.queue.unavailableMessage":
    "Pull from the queue screen or retry when network is stable.",
  "patientJourney.mobile.staffDashboard.queue.unavailableTitle": "Queue unavailable",
  "patientJourney.mobile.staffDashboard.quickActions.emptyMessage":
    "Your role has no mobile workflow actions enabled.",
  "patientJourney.mobile.staffDashboard.quickActions.emptyTitle": "No enabled shortcuts",
  "patientJourney.mobile.staffDashboard.quickActions.fabFind": "Find",
  "patientJourney.mobile.staffDashboard.quickActions.findPatient": "Find Patient",
  "patientJourney.mobile.staffDashboard.quickActions.fullQueue": "Full Queue",
  "patientJourney.mobile.staffDashboard.quickActions.imaging": "Imaging",
  "patientJourney.mobile.staffDashboard.quickActions.labOrder": "Lab Order",
  "patientJourney.mobile.staffDashboard.quickActions.labResults": "Lab Results",
  "patientJourney.mobile.staffDashboard.quickActions.title": "Quick Actions",
  "patientJourney.mobile.staffDashboard.quickActions.tokenBoards": "Token Boards",
  "patientJourney.mobile.staffDashboard.quickActions.vitals": "Vitals",
  "patientJourney.mobile.staffDashboard.quickActions.writeRx": "Write Rx",
  "patientJourney.mobile.vitals.actions.save": "Save Vitals",
  "patientJourney.mobile.vitals.bmi.calculated": "Calculated BMI",
  "patientJourney.mobile.vitals.errors.invalidDiastolic": "Enter a valid diastolic BP",
  "patientJourney.mobile.vitals.errors.invalidHeight": "Enter a valid height",
  "patientJourney.mobile.vitals.errors.invalidPulse": "Enter a valid pulse",
  "patientJourney.mobile.vitals.errors.invalidRespiration": "Enter a valid respiratory rate",
  "patientJourney.mobile.vitals.errors.invalidSpo2": "Enter a valid SpO2",
  "patientJourney.mobile.vitals.errors.invalidSystolic": "Enter a valid systolic BP",
  "patientJourney.mobile.vitals.errors.invalidTemperature": "Enter a valid temperature",
  "patientJourney.mobile.vitals.errors.invalidWeight": "Enter a valid weight",
  "patientJourney.mobile.vitals.errors.noEncounterId": "No encounter ID",
  "patientJourney.mobile.vitals.errors.saveFailed": "Failed to save vitals",
  "patientJourney.mobile.vitals.fields.diastolic": "Diastolic BP",
  "patientJourney.mobile.vitals.fields.height": "Height",
  "patientJourney.mobile.vitals.fields.normalRange": "Normal",
  "patientJourney.mobile.vitals.fields.pulse": "Pulse Rate",
  "patientJourney.mobile.vitals.fields.respiration": "Respiration Rate",
  "patientJourney.mobile.vitals.fields.spo2": "SpO2",
  "patientJourney.mobile.vitals.fields.systolic": "Systolic BP",
  "patientJourney.mobile.vitals.fields.temperature": "Temperature",
  "patientJourney.mobile.vitals.fields.weight": "Weight",
  "patientJourney.mobile.vitals.sections.anthropometry": "Anthropometry",
  "patientJourney.mobile.vitals.sections.previousVitals": "Previous Vitals",
  "patientJourney.mobile.vitals.sections.vitalSigns": "Vital Signs",
  "patientJourney.mobile.vitals.status.saved": "Vitals saved successfully",
  "patientJourney.mobile.vitals.summary.bp": "BP: {{systolic}}/{{diastolic}} mmHg",
  "patientJourney.mobile.vitals.summary.pulse": "Pulse: {{value}} bpm",
  "patientJourney.mobile.vitals.summary.recorded": "Vitals recorded",
  "patientJourney.mobile.vitals.summary.spo2": "SpO2: {{value}}%",
  "patientJourney.mobile.vitals.summary.temperature": "Temp: {{value}}°F",
  "patientJourney.status.available": "Available",
  "patientJourney.status.afterEvents": "After {{events}}",
};

function interpolate(
  template: string,
  values?: ClinicalJourneyMessageValues | Record<string, string | number | boolean>,
): string {
  if (!values) return template;

  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name) =>
    name in values ? String(values[name]) : placeholder,
  );
}

export const mobilePatientJourneyTranslator: PatientJourneyTranslator = (key, values) => {
  const template = MOBILE_PATIENT_JOURNEY_MESSAGES[key];

  return template ? interpolate(template, values) : key;
};

export function mobilePatientJourneyText(
  key: string,
  values?: ClinicalJourneyMessageValues | Record<string, string | number | boolean>,
): string {
  const translated = mobilePatientJourneyTranslator(key, values);
  return typeof translated === "string" ? translated : key;
}
