import type { ClinicalJourneyMessageValues, PatientJourneyTranslator } from "@medbrains/types";

export const MOBILE_PATIENT_JOURNEY_BLOCKERS = {
  openActiveIpdEncounterBeforeMobileInpatientOrders:
    "patientJourney.mobile.blockers.openActiveIpdEncounterBeforeMobileInpatientOrders",
  openOpdEncounterBeforeMobileConsultation:
    "patientJourney.mobile.blockers.openOpdEncounterBeforeMobileConsultation",
  openOpdEncounterBeforeMobileOrders:
    "patientJourney.mobile.blockers.openOpdEncounterBeforeMobileOrders",
} as const;

export const MOBILE_PATIENT_JOURNEY_TEXT = {
  actionPanel: {
    title: "patientJourney.mobile.actionPanel.title",
    subtitle: "patientJourney.mobile.actionPanel.subtitle",
  },
  flow: {
    title: "patientJourney.mobile.flow.title",
    handoffs: {
      billing: "patientJourney.mobile.flow.handoffs.billing",
      camp: "patientJourney.mobile.flow.handoffs.camp",
      emergency: "patientJourney.mobile.flow.handoffs.emergency",
      ipd: "patientJourney.mobile.flow.handoffs.ipd",
      opd: "patientJourney.mobile.flow.handoffs.opd",
      patient: "patientJourney.mobile.flow.handoffs.patient",
      pharmacy: "patientJourney.mobile.flow.handoffs.pharmacy",
    },
  },
  status: {
    blocked: "patientJourney.mobile.status.blocked",
    emitsEvent: "patientJourney.mobile.status.emitsEvent",
    ready: "patientJourney.mobile.status.ready",
  },
  summary: {
    awaitingEventCount: "patientJourney.mobile.summary.awaitingEventCount",
    blockedCount: "patientJourney.mobile.summary.blockedCount",
    configCount: "patientJourney.mobile.summary.configCount",
    maskingCount: "patientJourney.mobile.summary.maskingCount",
    permissionCount: "patientJourney.mobile.summary.permissionCount",
    readyCount: "patientJourney.mobile.summary.readyCount",
    regulatoryCount: "patientJourney.mobile.summary.regulatoryCount",
  },
} as const;

export const MOBILE_CARE_CONTEXT_TEXT = {
  common: {
    activeCount: "patientJourney.mobile.careContext.common.activeCount",
    hiddenField: "patientJourney.mobile.careContext.common.hiddenField",
    linked: "patientJourney.mobile.careContext.common.linked",
    noUhid: "patientJourney.mobile.careContext.common.noUhid",
    notRecorded: "patientJourney.mobile.careContext.common.notRecorded",
    patient: "patientJourney.mobile.careContext.common.patient",
    patientContext: "patientJourney.mobile.careContext.common.patientContext",
    patientIdentity: "patientJourney.mobile.careContext.common.patientIdentity",
    restricted: "patientJourney.mobile.careContext.common.restricted",
    selected: "patientJourney.mobile.careContext.common.selected",
  },
  camp: {
    chiefComplaint: "patientJourney.mobile.careContext.camp.chiefComplaint",
    registeredAt: "patientJourney.mobile.careContext.camp.registeredAt",
    serviceLine: "patientJourney.mobile.careContext.camp.serviceLine",
  },
  empty: {
    contextUnavailableTitle: "patientJourney.mobile.careContext.empty.contextUnavailableTitle",
    noCampMessage: "patientJourney.mobile.careContext.empty.noCampMessage",
    noCampTitle: "patientJourney.mobile.careContext.empty.noCampTitle",
    noEmergencyMessage: "patientJourney.mobile.careContext.empty.noEmergencyMessage",
    noEmergencyTitle: "patientJourney.mobile.careContext.empty.noEmergencyTitle",
    noIpdMessage: "patientJourney.mobile.careContext.empty.noIpdMessage",
    noIpdTitle: "patientJourney.mobile.careContext.empty.noIpdTitle",
    restrictedTitle: "patientJourney.mobile.careContext.empty.restrictedTitle",
  },
  emergency: {
    arrivedAt: "patientJourney.mobile.careContext.emergency.arrivedAt",
    bay: "patientJourney.mobile.careContext.emergency.bay",
    chiefComplaint: "patientJourney.mobile.careContext.emergency.chiefComplaint",
    mlc: "patientJourney.mobile.careContext.emergency.mlc",
    triage: "patientJourney.mobile.careContext.emergency.triage",
    unassigned: "patientJourney.mobile.careContext.emergency.unassigned",
  },
  identity: {
    loadingPatient: "patientJourney.mobile.careContext.identity.loadingPatient",
    patientIdentityUnavailable:
      "patientJourney.mobile.careContext.identity.patientIdentityUnavailable",
    uhidUnavailable: "patientJourney.mobile.careContext.identity.uhidUnavailable",
  },
  ipd: {
    admittedAt: "patientJourney.mobile.careContext.ipd.admittedAt",
    admittingDoctor: "patientJourney.mobile.careContext.ipd.admittingDoctor",
    bedAssigned: "patientJourney.mobile.careContext.ipd.bedAssigned",
    bedPending: "patientJourney.mobile.careContext.ipd.bedPending",
    bedPendingDescription: "patientJourney.mobile.careContext.ipd.bedPendingDescription",
    recordVitals: "patientJourney.mobile.careContext.ipd.recordVitals",
    wardPending: "patientJourney.mobile.careContext.ipd.wardPending",
  },
  loading: {
    handoffContext: "patientJourney.mobile.careContext.loading.handoffContext",
  },
  modules: {
    campTitle: "patientJourney.mobile.careContext.modules.campTitle",
    campSubtitle: "patientJourney.mobile.careContext.modules.campSubtitle",
    campPermission: "patientJourney.mobile.careContext.modules.campPermission",
    campUnavailable: "patientJourney.mobile.careContext.modules.campUnavailable",
    emergencyTitle: "patientJourney.mobile.careContext.modules.emergencyTitle",
    emergencyMlcTitle: "patientJourney.mobile.careContext.modules.emergencyMlcTitle",
    emergencySubtitle: "patientJourney.mobile.careContext.modules.emergencySubtitle",
    emergencyPermission: "patientJourney.mobile.careContext.modules.emergencyPermission",
    emergencyUnavailable: "patientJourney.mobile.careContext.modules.emergencyUnavailable",
    ipdTitle: "patientJourney.mobile.careContext.modules.ipdTitle",
    ipdAdmitTitle: "patientJourney.mobile.careContext.modules.ipdAdmitTitle",
    ipdSubtitle: "patientJourney.mobile.careContext.modules.ipdSubtitle",
    ipdPermission: "patientJourney.mobile.careContext.modules.ipdPermission",
    ipdUnavailable: "patientJourney.mobile.careContext.modules.ipdUnavailable",
  },
} as const;

export const MOBILE_PATIENT_DETAIL_TEXT = {
  actions: {
    activationHint: "patientJourney.mobile.patientDetail.actions.activationHint",
    activeEr: "patientJourney.mobile.patientDetail.actions.activeEr",
    activeIpd: "patientJourney.mobile.patientDetail.actions.activeIpd",
    activeOpd: "patientJourney.mobile.patientDetail.actions.activeOpd",
    bedPending: "patientJourney.mobile.patientDetail.actions.bedPending",
    campStatus: "patientJourney.mobile.patientDetail.actions.campStatus",
    missingCareContextHint: "patientJourney.mobile.patientDetail.actions.missingCareContextHint",
    mlc: "patientJourney.mobile.patientDetail.actions.mlc",
    pendingBillPlural: "patientJourney.mobile.patientDetail.actions.pendingBillPlural",
    pendingBillSingular: "patientJourney.mobile.patientDetail.actions.pendingBillSingular",
    rxHandoff: "patientJourney.mobile.patientDetail.actions.rxHandoff",
    title: "patientJourney.mobile.patientDetail.actions.title",
    vitals: "patientJourney.mobile.patientDetail.actions.vitals",
  },
  empty: {
    noRecentVisits: "patientJourney.mobile.patientDetail.empty.noRecentVisits",
    patientNotFound: "patientJourney.mobile.patientDetail.empty.patientNotFound",
  },
  fields: {
    address: "patientJourney.mobile.patientDetail.fields.address",
    ageMasked: "patientJourney.mobile.patientDetail.fields.ageMasked",
    ageYearPlural: "patientJourney.mobile.patientDetail.fields.ageYearPlural",
    ageYearSingular: "patientJourney.mobile.patientDetail.fields.ageYearSingular",
    dateMasked: "patientJourney.mobile.patientDetail.fields.dateMasked",
    dateOfBirth: "patientJourney.mobile.patientDetail.fields.dateOfBirth",
    hiddenField: "patientJourney.mobile.patientDetail.fields.hiddenField",
    maritalStatus: "patientJourney.mobile.patientDetail.fields.maritalStatus",
    maskedField: "patientJourney.mobile.patientDetail.fields.maskedField",
    noUhid: "patientJourney.mobile.patientDetail.fields.noUhid",
    notSpecified: "patientJourney.mobile.patientDetail.fields.notSpecified",
    occupation: "patientJourney.mobile.patientDetail.fields.occupation",
    patientInitials: "patientJourney.mobile.patientDetail.fields.patientInitials",
    unknown: "patientJourney.mobile.patientDetail.fields.unknown",
    unknownPatient: "patientJourney.mobile.patientDetail.fields.unknownPatient",
  },
  loading: {
    patientDetails: "patientJourney.mobile.patientDetail.loading.patientDetails",
  },
  sections: {
    allergies: "patientJourney.mobile.patientDetail.sections.allergies",
    patientInformation: "patientJourney.mobile.patientDetail.sections.patientInformation",
    recentVisits: "patientJourney.mobile.patientDetail.sections.recentVisits",
  },
  status: {
    campConverted: "patientJourney.mobile.patientDetail.status.campConverted",
    campRegistered: "patientJourney.mobile.patientDetail.status.campRegistered",
    campReferred: "patientJourney.mobile.patientDetail.status.campReferred",
    campScreened: "patientJourney.mobile.patientDetail.status.campScreened",
    emergency: "patientJourney.mobile.patientDetail.status.emergency",
    female: "patientJourney.mobile.patientDetail.status.female",
    ipd: "patientJourney.mobile.patientDetail.status.ipd",
    male: "patientJourney.mobile.patientDetail.status.male",
    maritalDivorced: "patientJourney.mobile.patientDetail.status.maritalDivorced",
    maritalDomesticPartner: "patientJourney.mobile.patientDetail.status.maritalDomesticPartner",
    maritalMarried: "patientJourney.mobile.patientDetail.status.maritalMarried",
    maritalSeparated: "patientJourney.mobile.patientDetail.status.maritalSeparated",
    maritalSingle: "patientJourney.mobile.patientDetail.status.maritalSingle",
    maritalUnknown: "patientJourney.mobile.patientDetail.status.maritalUnknown",
    maritalWidowed: "patientJourney.mobile.patientDetail.status.maritalWidowed",
    opd: "patientJourney.mobile.patientDetail.status.opd",
    other: "patientJourney.mobile.patientDetail.status.other",
    unknown: "patientJourney.mobile.patientDetail.status.unknown",
  },
  visits: {
    consultation: "patientJourney.mobile.patientDetail.visits.consultation",
  },
} as const;

export const MOBILE_VITALS_ENTRY_TEXT = {
  actions: {
    save: "patientJourney.mobile.vitals.actions.save",
  },
  bmi: {
    calculated: "patientJourney.mobile.vitals.bmi.calculated",
  },
  errors: {
    invalidDiastolic: "patientJourney.mobile.vitals.errors.invalidDiastolic",
    invalidHeight: "patientJourney.mobile.vitals.errors.invalidHeight",
    invalidPulse: "patientJourney.mobile.vitals.errors.invalidPulse",
    invalidRespiration: "patientJourney.mobile.vitals.errors.invalidRespiration",
    invalidSpo2: "patientJourney.mobile.vitals.errors.invalidSpo2",
    invalidSystolic: "patientJourney.mobile.vitals.errors.invalidSystolic",
    invalidTemperature: "patientJourney.mobile.vitals.errors.invalidTemperature",
    invalidWeight: "patientJourney.mobile.vitals.errors.invalidWeight",
    noEncounterId: "patientJourney.mobile.vitals.errors.noEncounterId",
    saveFailed: "patientJourney.mobile.vitals.errors.saveFailed",
  },
  fields: {
    diastolic: "patientJourney.mobile.vitals.fields.diastolic",
    height: "patientJourney.mobile.vitals.fields.height",
    normalRange: "patientJourney.mobile.vitals.fields.normalRange",
    pulse: "patientJourney.mobile.vitals.fields.pulse",
    respiration: "patientJourney.mobile.vitals.fields.respiration",
    spo2: "patientJourney.mobile.vitals.fields.spo2",
    systolic: "patientJourney.mobile.vitals.fields.systolic",
    temperature: "patientJourney.mobile.vitals.fields.temperature",
    weight: "patientJourney.mobile.vitals.fields.weight",
  },
  sections: {
    anthropometry: "patientJourney.mobile.vitals.sections.anthropometry",
    previousVitals: "patientJourney.mobile.vitals.sections.previousVitals",
    vitalSigns: "patientJourney.mobile.vitals.sections.vitalSigns",
  },
  status: {
    saved: "patientJourney.mobile.vitals.status.saved",
  },
  summary: {
    bp: "patientJourney.mobile.vitals.summary.bp",
    pulse: "patientJourney.mobile.vitals.summary.pulse",
    recorded: "patientJourney.mobile.vitals.summary.recorded",
    spo2: "patientJourney.mobile.vitals.summary.spo2",
    temperature: "patientJourney.mobile.vitals.summary.temperature",
  },
} as const;

export const MOBILE_NAVIGATION_TEXT = {
  patient: {
    appointments: "patientJourney.mobile.navigation.patient.appointments",
    billing: "patientJourney.mobile.navigation.patient.billing",
    labResultDetails: "patientJourney.mobile.navigation.patient.labResultDetails",
    labResults: "patientJourney.mobile.navigation.patient.labResults",
    myHealth: "patientJourney.mobile.navigation.patient.myHealth",
    prescriptions: "patientJourney.mobile.navigation.patient.prescriptions",
    profile: "patientJourney.mobile.navigation.patient.profile",
    queueStatus: "patientJourney.mobile.navigation.patient.queueStatus",
  },
  phlebotomy: {
    collectSamples: "patientJourney.mobile.navigation.phlebotomy.collectSamples",
    collectionDetails: "patientJourney.mobile.navigation.phlebotomy.collectionDetails",
    homeCollections: "patientJourney.mobile.navigation.phlebotomy.homeCollections",
    tripSummary: "patientJourney.mobile.navigation.phlebotomy.tripSummary",
  },
  staff: {
    billing: "patientJourney.mobile.navigation.staff.billing",
    careContext: "patientJourney.mobile.navigation.staff.careContext",
    consultationNotes: "patientJourney.mobile.navigation.staff.consultationNotes",
    dashboard: "patientJourney.mobile.navigation.staff.dashboard",
    ePrescription: "patientJourney.mobile.navigation.staff.ePrescription",
    findPatient: "patientJourney.mobile.navigation.staff.findPatient",
    imagingOrder: "patientJourney.mobile.navigation.staff.imagingOrder",
    labOrders: "patientJourney.mobile.navigation.staff.labOrders",
    labResults: "patientJourney.mobile.navigation.staff.labResults",
    patientDetails: "patientJourney.mobile.navigation.staff.patientDetails",
    patientPharmacy: "patientJourney.mobile.navigation.staff.patientPharmacy",
    patientQueue: "patientJourney.mobile.navigation.staff.patientQueue",
    recordVitals: "patientJourney.mobile.navigation.staff.recordVitals",
    tokenBoards: "patientJourney.mobile.navigation.staff.tokenBoards",
  },
} as const;

export const MOBILE_STAFF_DASHBOARD_TEXT = {
  common: {
    greeting: "patientJourney.mobile.staffDashboard.common.greeting",
    staffFallback: "patientJourney.mobile.staffDashboard.common.staffFallback",
    staffInitials: "patientJourney.mobile.staffDashboard.common.staffInitials",
  },
  flow: {
    boards: "patientJourney.mobile.staffDashboard.flow.boards",
    empty: "patientJourney.mobile.staffDashboard.flow.empty",
    imaging: "patientJourney.mobile.staffDashboard.flow.imaging",
    orders: "patientJourney.mobile.staffDashboard.flow.orders",
    patient: "patientJourney.mobile.staffDashboard.flow.patient",
    queue: "patientJourney.mobile.staffDashboard.flow.queue",
    results: "patientJourney.mobile.staffDashboard.flow.results",
    title: "patientJourney.mobile.staffDashboard.flow.title",
    vitals: "patientJourney.mobile.staffDashboard.flow.vitals",
  },
  overview: {
    active: "patientJourney.mobile.staffDashboard.overview.active",
    completed: "patientJourney.mobile.staffDashboard.overview.completed",
    openBillingDesk: "patientJourney.mobile.staffDashboard.overview.openBillingDesk",
    openLabWorklist: "patientJourney.mobile.staffDashboard.overview.openLabWorklist",
    openOpdQueue: "patientJourney.mobile.staffDashboard.overview.openOpdQueue",
    openPatientSearch: "patientJourney.mobile.staffDashboard.overview.openPatientSearch",
    title: "patientJourney.mobile.staffDashboard.overview.title",
    tokensToday: "patientJourney.mobile.staffDashboard.overview.tokensToday",
    waiting: "patientJourney.mobile.staffDashboard.overview.waiting",
  },
  queue: {
    currentQueue: "patientJourney.mobile.staffDashboard.queue.currentQueue",
    emptyMessage: "patientJourney.mobile.staffDashboard.queue.emptyMessage",
    emptyTitle: "patientJourney.mobile.staffDashboard.queue.emptyTitle",
    loading: "patientJourney.mobile.staffDashboard.queue.loading",
    restrictedMessage: "patientJourney.mobile.staffDashboard.queue.restrictedMessage",
    restrictedTitle: "patientJourney.mobile.staffDashboard.queue.restrictedTitle",
    retry: "patientJourney.mobile.staffDashboard.queue.retry",
    unavailableMessage: "patientJourney.mobile.staffDashboard.queue.unavailableMessage",
    unavailableTitle: "patientJourney.mobile.staffDashboard.queue.unavailableTitle",
  },
  quickActions: {
    emptyMessage: "patientJourney.mobile.staffDashboard.quickActions.emptyMessage",
    emptyTitle: "patientJourney.mobile.staffDashboard.quickActions.emptyTitle",
    fabFind: "patientJourney.mobile.staffDashboard.quickActions.fabFind",
    findPatient: "patientJourney.mobile.staffDashboard.quickActions.findPatient",
    fullQueue: "patientJourney.mobile.staffDashboard.quickActions.fullQueue",
    imaging: "patientJourney.mobile.staffDashboard.quickActions.imaging",
    labOrder: "patientJourney.mobile.staffDashboard.quickActions.labOrder",
    labResults: "patientJourney.mobile.staffDashboard.quickActions.labResults",
    title: "patientJourney.mobile.staffDashboard.quickActions.title",
    tokenBoards: "patientJourney.mobile.staffDashboard.quickActions.tokenBoards",
    vitals: "patientJourney.mobile.staffDashboard.quickActions.vitals",
    writeRx: "patientJourney.mobile.staffDashboard.quickActions.writeRx",
  },
} as const;

export const MOBILE_QUEUE_ITEM_TEXT = {
  actions: {
    call: "patientJourney.mobile.queueItem.actions.call",
    done: "patientJourney.mobile.queueItem.actions.done",
    noShow: "patientJourney.mobile.queueItem.actions.noShow",
    start: "patientJourney.mobile.queueItem.actions.start",
  },
  fields: {
    doctor: "patientJourney.mobile.queueItem.fields.doctor",
    waitMinutes: "patientJourney.mobile.queueItem.fields.waitMinutes",
  },
  status: {
    called: "patientJourney.mobile.queueItem.status.called",
    completed: "patientJourney.mobile.queueItem.status.completed",
    inProgress: "patientJourney.mobile.queueItem.status.inProgress",
    noShow: "patientJourney.mobile.queueItem.status.noShow",
    waiting: "patientJourney.mobile.queueItem.status.waiting",
  },
} as const;

export const MOBILE_QUEUE_SCREEN_TEXT = {
  banner: {
    currentlySeeing: "patientJourney.mobile.queueScreen.banner.currentlySeeing",
    patientFallback: "patientJourney.mobile.queueScreen.banner.patientFallback",
  },
  empty: {
    allMessage: "patientJourney.mobile.queueScreen.empty.allMessage",
    filteredMessage: "patientJourney.mobile.queueScreen.empty.filteredMessage",
    title: "patientJourney.mobile.queueScreen.empty.title",
  },
  filters: {
    active: "patientJourney.mobile.queueScreen.filters.active",
    all: "patientJourney.mobile.queueScreen.filters.all",
    called: "patientJourney.mobile.queueScreen.filters.called",
    waiting: "patientJourney.mobile.queueScreen.filters.waiting",
  },
  loading: {
    queue: "patientJourney.mobile.queueScreen.loading.queue",
  },
  restricted: {
    message: "patientJourney.mobile.queueScreen.restricted.message",
    title: "patientJourney.mobile.queueScreen.restricted.title",
  },
  stats: {
    called: "patientJourney.mobile.queueScreen.stats.called",
    inProgress: "patientJourney.mobile.queueScreen.stats.inProgress",
    waiting: "patientJourney.mobile.queueScreen.stats.waiting",
  },
} as const;

export const MOBILE_PATIENT_SEARCH_TEXT = {
  empty: {
    message: "patientJourney.mobile.patientSearch.empty.message",
    title: "patientJourney.mobile.patientSearch.empty.title",
  },
  loading: {
    patients: "patientJourney.mobile.patientSearch.loading.patients",
  },
  results: {
    countPlural: "patientJourney.mobile.patientSearch.results.countPlural",
    countSingular: "patientJourney.mobile.patientSearch.results.countSingular",
  },
  restricted: {
    message: "patientJourney.mobile.patientSearch.restricted.message",
    title: "patientJourney.mobile.patientSearch.restricted.title",
  },
  search: {
    hint: "patientJourney.mobile.patientSearch.search.hint",
    placeholder: "patientJourney.mobile.patientSearch.search.placeholder",
    title: "patientJourney.mobile.patientSearch.search.title",
  },
} as const;

export const MOBILE_PATIENT_CARD_TEXT = {
  fields: {
    ageMasked: "patientJourney.mobile.patientCard.fields.ageMasked",
    ageYearsShort: "patientJourney.mobile.patientCard.fields.ageYearsShort",
    genderFemaleShort: "patientJourney.mobile.patientCard.fields.genderFemaleShort",
    genderMaleShort: "patientJourney.mobile.patientCard.fields.genderMaleShort",
    genderOtherShort: "patientJourney.mobile.patientCard.fields.genderOtherShort",
    genderUnknownShort: "patientJourney.mobile.patientCard.fields.genderUnknownShort",
    hiddenField: "patientJourney.mobile.patientCard.fields.hiddenField",
    noUhid: "patientJourney.mobile.patientCard.fields.noUhid",
    patientInitials: "patientJourney.mobile.patientCard.fields.patientInitials",
    unknownPatient: "patientJourney.mobile.patientCard.fields.unknownPatient",
  },
} as const;

export const MOBILE_PATIENT_PHARMACY_TEXT = {
  empty: {
    message: "patientJourney.mobile.patientPharmacy.empty.message",
    title: "patientJourney.mobile.patientPharmacy.empty.title",
  },
  filters: {
    allHistory: "patientJourney.mobile.patientPharmacy.filters.allHistory",
    recent: "patientJourney.mobile.patientPharmacy.filters.recent",
  },
  handoff: {
    activeCount: "patientJourney.mobile.patientPharmacy.handoff.activeCount",
    dispenseDescription: "patientJourney.mobile.patientPharmacy.handoff.dispenseDescription",
    dispenseTitle: "patientJourney.mobile.patientPharmacy.handoff.dispenseTitle",
    pharmacyTitle: "patientJourney.mobile.patientPharmacy.handoff.pharmacyTitle",
    queueDescription: "patientJourney.mobile.patientPharmacy.handoff.queueDescription",
    reviewDescription: "patientJourney.mobile.patientPharmacy.handoff.reviewDescription",
  },
  loading: {
    context: "patientJourney.mobile.patientPharmacy.loading.context",
  },
  medication: {
    itemCountPlural: "patientJourney.mobile.patientPharmacy.medication.itemCountPlural",
    itemCountSingular: "patientJourney.mobile.patientPharmacy.medication.itemCountSingular",
    prescriberFallback: "patientJourney.mobile.patientPharmacy.medication.prescriberFallback",
    selectedOrder: "patientJourney.mobile.patientPharmacy.medication.selectedOrder",
  },
  search: {
    placeholder: "patientJourney.mobile.patientPharmacy.search.placeholder",
  },
  status: {
    active: "patientJourney.mobile.patientPharmacy.status.active",
    changed: "patientJourney.mobile.patientPharmacy.status.changed",
    discontinued: "patientJourney.mobile.patientPharmacy.status.discontinued",
    unknown: "patientJourney.mobile.patientPharmacy.status.unknown",
  },
} as const;

export const MOBILE_CONSULTATION_NOTES_TEXT = {
  actions: {
    completeSign: "patientJourney.mobile.consultationNotes.actions.completeSign",
    save: "patientJourney.mobile.consultationNotes.actions.save",
  },
  diagnoses: {
    active: "patientJourney.mobile.consultationNotes.diagnoses.active",
  },
  errors: {
    failedToSave: "patientJourney.mobile.consultationNotes.errors.failedToSave",
  },
  progress: {
    soap: "patientJourney.mobile.consultationNotes.progress.soap",
  },
  sections: {
    assessment: "patientJourney.mobile.consultationNotes.sections.assessment",
    assessmentShort: "patientJourney.mobile.consultationNotes.sections.assessmentShort",
    objective: "patientJourney.mobile.consultationNotes.sections.objective",
    objectiveShort: "patientJourney.mobile.consultationNotes.sections.objectiveShort",
    plan: "patientJourney.mobile.consultationNotes.sections.plan",
    planShort: "patientJourney.mobile.consultationNotes.sections.planShort",
    subjective: "patientJourney.mobile.consultationNotes.sections.subjective",
    subjectiveShort: "patientJourney.mobile.consultationNotes.sections.subjectiveShort",
  },
  placeholders: {
    assessment: "patientJourney.mobile.consultationNotes.placeholders.assessment",
    objective: "patientJourney.mobile.consultationNotes.placeholders.objective",
    plan: "patientJourney.mobile.consultationNotes.placeholders.plan",
    subjective: "patientJourney.mobile.consultationNotes.placeholders.subjective",
  },
  status: {
    saved: "patientJourney.mobile.consultationNotes.status.saved",
  },
  templates: {
    complainsOf: "patientJourney.mobile.consultationNotes.templates.complainsOf",
    complainsOfSnippet: "patientJourney.mobile.consultationNotes.templates.complainsOfSnippet",
    continueMeds: "patientJourney.mobile.consultationNotes.templates.continueMeds",
    continueMedsSnippet: "patientJourney.mobile.consultationNotes.templates.continueMedsSnippet",
    diagnosis: "patientJourney.mobile.consultationNotes.templates.diagnosis",
    diagnosisSnippet: "patientJourney.mobile.consultationNotes.templates.diagnosisSnippet",
    historyOf: "patientJourney.mobile.consultationNotes.templates.historyOf",
    historyOfSnippet: "patientJourney.mobile.consultationNotes.templates.historyOfSnippet",
    noAbnormality: "patientJourney.mobile.consultationNotes.templates.noAbnormality",
    noAbnormalitySnippet: "patientJourney.mobile.consultationNotes.templates.noAbnormalitySnippet",
    noKnownAllergies: "patientJourney.mobile.consultationNotes.templates.noKnownAllergies",
    noKnownAllergiesSnippet:
      "patientJourney.mobile.consultationNotes.templates.noKnownAllergiesSnippet",
    onExamination: "patientJourney.mobile.consultationNotes.templates.onExamination",
    onExaminationSnippet: "patientJourney.mobile.consultationNotes.templates.onExaminationSnippet",
    quickPhrases: "patientJourney.mobile.consultationNotes.templates.quickPhrases",
    restAdvised: "patientJourney.mobile.consultationNotes.templates.restAdvised",
    restAdvisedSnippet: "patientJourney.mobile.consultationNotes.templates.restAdvisedSnippet",
    reviewOneWeek: "patientJourney.mobile.consultationNotes.templates.reviewOneWeek",
    reviewOneWeekSnippet: "patientJourney.mobile.consultationNotes.templates.reviewOneWeekSnippet",
    ruleOut: "patientJourney.mobile.consultationNotes.templates.ruleOut",
    ruleOutSnippet: "patientJourney.mobile.consultationNotes.templates.ruleOutSnippet",
    stableCondition: "patientJourney.mobile.consultationNotes.templates.stableCondition",
    stableConditionSnippet:
      "patientJourney.mobile.consultationNotes.templates.stableConditionSnippet",
    vitalsStable: "patientJourney.mobile.consultationNotes.templates.vitalsStable",
    vitalsStableSnippet: "patientJourney.mobile.consultationNotes.templates.vitalsStableSnippet",
  },
} as const;

export const MOBILE_LAB_ORDER_TEXT = {
  actions: {
    addTest: "patientJourney.mobile.labOrder.actions.addTest",
    placePlural: "patientJourney.mobile.labOrder.actions.placePlural",
    placeSingular: "patientJourney.mobile.labOrder.actions.placeSingular",
  },
  categories: {
    biochemistry: "patientJourney.mobile.labOrder.categories.biochemistry",
    cardiology: "patientJourney.mobile.labOrder.categories.cardiology",
    clinicalPathology: "patientJourney.mobile.labOrder.categories.clinicalPathology",
    diabetes: "patientJourney.mobile.labOrder.categories.diabetes",
    general: "patientJourney.mobile.labOrder.categories.general",
    hematology: "patientJourney.mobile.labOrder.categories.hematology",
    hormones: "patientJourney.mobile.labOrder.categories.hormones",
  },
  commonTests: {
    cbc: "patientJourney.mobile.labOrder.commonTests.cbc",
    ecg: "patientJourney.mobile.labOrder.commonTests.ecg",
    hba1c: "patientJourney.mobile.labOrder.commonTests.hba1c",
    lft: "patientJourney.mobile.labOrder.commonTests.lft",
    lipid: "patientJourney.mobile.labOrder.commonTests.lipid",
    rft: "patientJourney.mobile.labOrder.commonTests.rft",
    thyroid: "patientJourney.mobile.labOrder.commonTests.thyroid",
    urine: "patientJourney.mobile.labOrder.commonTests.urine",
  },
  empty: {
    hint: "patientJourney.mobile.labOrder.empty.hint",
    noResults: "patientJourney.mobile.labOrder.empty.noResults",
    title: "patientJourney.mobile.labOrder.empty.title",
  },
  errors: {
    failedToCreate: "patientJourney.mobile.labOrder.errors.failedToCreate",
    noTestsSelected: "patientJourney.mobile.labOrder.errors.noTestsSelected",
  },
  priority: {
    routine: "patientJourney.mobile.labOrder.priority.routine",
    stat: "patientJourney.mobile.labOrder.priority.stat",
    urgent: "patientJourney.mobile.labOrder.priority.urgent",
  },
  recent: {
    description: "patientJourney.mobile.labOrder.recent.description",
    orderTitle: "patientJourney.mobile.labOrder.recent.orderTitle",
    title: "patientJourney.mobile.labOrder.recent.title",
  },
  search: {
    resultDescription: "patientJourney.mobile.labOrder.search.resultDescription",
    placeholder: "patientJourney.mobile.labOrder.search.placeholder",
  },
  sections: {
    commonTests: "patientJourney.mobile.labOrder.sections.commonTests",
    priority: "patientJourney.mobile.labOrder.sections.priority",
    selectedTests: "patientJourney.mobile.labOrder.sections.selectedTests",
  },
  status: {
    cancelled: "patientJourney.mobile.labOrder.status.cancelled",
    completed: "patientJourney.mobile.labOrder.status.completed",
    created: "patientJourney.mobile.labOrder.status.created",
    ordered: "patientJourney.mobile.labOrder.status.ordered",
    processing: "patientJourney.mobile.labOrder.status.processing",
    sampleCollected: "patientJourney.mobile.labOrder.status.sampleCollected",
    verified: "patientJourney.mobile.labOrder.status.verified",
  },
  tests: {
    tatHours: "patientJourney.mobile.labOrder.tests.tatHours",
    total: "patientJourney.mobile.labOrder.tests.total",
  },
} as const;

export const MOBILE_RADIOLOGY_ORDER_TEXT = {
  actions: {
    place: "patientJourney.mobile.radiologyOrder.actions.place",
  },
  context: {
    encounterLinked: "patientJourney.mobile.radiologyOrder.context.encounterLinked",
    noEncounter: "patientJourney.mobile.radiologyOrder.context.noEncounter",
    patientLinked: "patientJourney.mobile.radiologyOrder.context.patientLinked",
    patientRequired: "patientJourney.mobile.radiologyOrder.context.patientRequired",
    subtitle: "patientJourney.mobile.radiologyOrder.context.subtitle",
    title: "patientJourney.mobile.radiologyOrder.context.title",
  },
  empty: {
    noActiveModalities: "patientJourney.mobile.radiologyOrder.empty.noActiveModalities",
  },
  errors: {
    failedToCreate: "patientJourney.mobile.radiologyOrder.errors.failedToCreate",
    modalityRequired: "patientJourney.mobile.radiologyOrder.errors.modalityRequired",
    patientRequired: "patientJourney.mobile.radiologyOrder.errors.patientRequired",
  },
  fields: {
    bodyPart: "patientJourney.mobile.radiologyOrder.fields.bodyPart",
    clinicalIndication: "patientJourney.mobile.radiologyOrder.fields.clinicalIndication",
    modality: "patientJourney.mobile.radiologyOrder.fields.modality",
    notes: "patientJourney.mobile.radiologyOrder.fields.notes",
    patientId: "patientJourney.mobile.radiologyOrder.fields.patientId",
    selectedModality: "patientJourney.mobile.radiologyOrder.fields.selectedModality",
  },
  placeholders: {
    bodyPart: "patientJourney.mobile.radiologyOrder.placeholders.bodyPart",
    clinicalIndication: "patientJourney.mobile.radiologyOrder.placeholders.clinicalIndication",
    notes: "patientJourney.mobile.radiologyOrder.placeholders.notes",
  },
  priority: {
    routine: "patientJourney.mobile.radiologyOrder.priority.routine",
    stat: "patientJourney.mobile.radiologyOrder.priority.stat",
    urgent: "patientJourney.mobile.radiologyOrder.priority.urgent",
  },
  recent: {
    description: "patientJourney.mobile.radiologyOrder.recent.description",
    fallbackTitle: "patientJourney.mobile.radiologyOrder.recent.fallbackTitle",
    title: "patientJourney.mobile.radiologyOrder.recent.title",
  },
  restricted: {
    message: "patientJourney.mobile.radiologyOrder.restricted.message",
    title: "patientJourney.mobile.radiologyOrder.restricted.title",
  },
  safety: {
    allergyDescription: "patientJourney.mobile.radiologyOrder.safety.allergyDescription",
    allergyTitle: "patientJourney.mobile.radiologyOrder.safety.allergyTitle",
    contrastDescription: "patientJourney.mobile.radiologyOrder.safety.contrastDescription",
    contrastTitle: "patientJourney.mobile.radiologyOrder.safety.contrastTitle",
    pregnancyDescription: "patientJourney.mobile.radiologyOrder.safety.pregnancyDescription",
    pregnancyTitle: "patientJourney.mobile.radiologyOrder.safety.pregnancyTitle",
  },
  sections: {
    clinicalDetails: "patientJourney.mobile.radiologyOrder.sections.clinicalDetails",
    patientModality: "patientJourney.mobile.radiologyOrder.sections.patientModality",
    prioritySafety: "patientJourney.mobile.radiologyOrder.sections.prioritySafety",
  },
  status: {
    cancelled: "patientJourney.mobile.radiologyOrder.status.cancelled",
    completed: "patientJourney.mobile.radiologyOrder.status.completed",
    created: "patientJourney.mobile.radiologyOrder.status.created",
    inProgress: "patientJourney.mobile.radiologyOrder.status.inProgress",
    ordered: "patientJourney.mobile.radiologyOrder.status.ordered",
    reported: "patientJourney.mobile.radiologyOrder.status.reported",
    scheduled: "patientJourney.mobile.radiologyOrder.status.scheduled",
    verified: "patientJourney.mobile.radiologyOrder.status.verified",
  },
} as const;

export const MOBILE_PRESCRIPTION_TEXT = {
  actions: {
    add: "patientJourney.mobile.prescription.actions.add",
    addDrug: "patientJourney.mobile.prescription.actions.addDrug",
    cancel: "patientJourney.mobile.prescription.actions.cancel",
    copyPrevious: "patientJourney.mobile.prescription.actions.copyPrevious",
    savePlural: "patientJourney.mobile.prescription.actions.savePlural",
    saveSingular: "patientJourney.mobile.prescription.actions.saveSingular",
  },
  dialog: {
    addMedication: "patientJourney.mobile.prescription.dialog.addMedication",
    dosage: "patientJourney.mobile.prescription.dialog.dosage",
    drugName: "patientJourney.mobile.prescription.dialog.drugName",
    duration: "patientJourney.mobile.prescription.dialog.duration",
    frequency: "patientJourney.mobile.prescription.dialog.frequency",
    instructions: "patientJourney.mobile.prescription.dialog.instructions",
    route: "patientJourney.mobile.prescription.dialog.route",
    searchPlaceholder: "patientJourney.mobile.prescription.dialog.searchPlaceholder",
  },
  durations: {
    continuous: "patientJourney.mobile.prescription.durations.continuous",
    fiveDays: "patientJourney.mobile.prescription.durations.fiveDays",
    fourteenDays: "patientJourney.mobile.prescription.durations.fourteenDays",
    oneMonth: "patientJourney.mobile.prescription.durations.oneMonth",
    sevenDays: "patientJourney.mobile.prescription.durations.sevenDays",
    tenDays: "patientJourney.mobile.prescription.durations.tenDays",
    threeDays: "patientJourney.mobile.prescription.durations.threeDays",
    threeMonths: "patientJourney.mobile.prescription.durations.threeMonths",
  },
  empty: {
    hint: "patientJourney.mobile.prescription.empty.hint",
    title: "patientJourney.mobile.prescription.empty.title",
  },
  errors: {
    dosageRequired: "patientJourney.mobile.prescription.errors.dosageRequired",
    drugNameRequired: "patientJourney.mobile.prescription.errors.drugNameRequired",
    durationRequired: "patientJourney.mobile.prescription.errors.durationRequired",
    failedToSave: "patientJourney.mobile.prescription.errors.failedToSave",
    frequencyRequired: "patientJourney.mobile.prescription.errors.frequencyRequired",
    noItems: "patientJourney.mobile.prescription.errors.noItems",
    routeRequired: "patientJourney.mobile.prescription.errors.routeRequired",
    tooLong: "patientJourney.mobile.prescription.errors.tooLong",
  },
  frequencies: {
    afterMeals: "patientJourney.mobile.prescription.frequencies.afterMeals",
    asNeeded: "patientJourney.mobile.prescription.frequencies.asNeeded",
    atBedtime: "patientJourney.mobile.prescription.frequencies.atBedtime",
    beforeMeals: "patientJourney.mobile.prescription.frequencies.beforeMeals",
    fourTimesDaily: "patientJourney.mobile.prescription.frequencies.fourTimesDaily",
    onceDaily: "patientJourney.mobile.prescription.frequencies.onceDaily",
    threeTimesDaily: "patientJourney.mobile.prescription.frequencies.threeTimesDaily",
    twiceDaily: "patientJourney.mobile.prescription.frequencies.twiceDaily",
  },
  routes: {
    im: "patientJourney.mobile.prescription.routes.im",
    inhalation: "patientJourney.mobile.prescription.routes.inhalation",
    iv: "patientJourney.mobile.prescription.routes.iv",
    oral: "patientJourney.mobile.prescription.routes.oral",
    rectal: "patientJourney.mobile.prescription.routes.rectal",
    sc: "patientJourney.mobile.prescription.routes.sc",
    sublingual: "patientJourney.mobile.prescription.routes.sublingual",
    topical: "patientJourney.mobile.prescription.routes.topical",
  },
  sections: {
    current: "patientJourney.mobile.prescription.sections.current",
    previous: "patientJourney.mobile.prescription.sections.previous",
  },
  status: {
    copiedPrevious: "patientJourney.mobile.prescription.status.copiedPrevious",
    saved: "patientJourney.mobile.prescription.status.saved",
  },
  summary: {
    itemCountPlural: "patientJourney.mobile.prescription.summary.itemCountPlural",
    itemCountSingular: "patientJourney.mobile.prescription.summary.itemCountSingular",
    note: "patientJourney.mobile.prescription.summary.note",
  },
} as const;

const MOBILE_PATIENT_JOURNEY_MESSAGES: Record<string, string> = {
  "patientJourney.blockedReasons.configuration": "Configuration",
  "patientJourney.blockedReasons.context": "Context",
  "patientJourney.blockedReasons.event": "Event",
  "patientJourney.blockedReasons.masking": "Masking",
  "patientJourney.blockedReasons.permission": "Permission",
  "patientJourney.blockedReasons.regulatory": "Regulatory",
  "patientJourney.events.bed.assigned": "bed assigned",
  "patientJourney.events.billing.invoiceCreated": "billing invoice created",
  "patientJourney.events.billing.invoiceFinalized": "billing invoice finalized",
  "patientJourney.events.billing.paymentReceived": "billing payment received",
  "patientJourney.events.camp.started": "camp started",
  "patientJourney.events.camp.registrationCreated": "camp registration created",
  "patientJourney.events.camp.screeningCompleted": "camp screening completed",
  "patientJourney.events.emergency.visitCreated": "emergency visit created",
  "patientJourney.events.ipd.admissionCreated": "IPD admission created",
  "patientJourney.events.ipd.dischargeFinalized": "IPD discharge finalized",
  "patientJourney.events.opd.encounterCreated": "OPD encounter created",
  "patientJourney.events.order.created": "order created",
  "patientJourney.events.patient.created": "patient created",
  "patientJourney.events.pharmacy.orderDispensed": "pharmacy order dispensed",
  "patientJourney.events.pharmacy.prescriptionReviewed": "pharmacy prescription reviewed",
  "patientJourney.lists.orJoin": "{{left}} or {{right}}",
  "patientJourney.mobile.blockers.openActiveIpdEncounterBeforeMobileInpatientOrders":
    "Open an active IPD encounter before mobile inpatient orders",
  "patientJourney.mobile.blockers.openOpdEncounterBeforeMobileConsultation":
    "Open an OPD encounter before mobile consultation",
  "patientJourney.mobile.blockers.openOpdEncounterBeforeMobileOrders":
    "Open an OPD encounter before mobile orders",
  "patientJourney.mobile.actionPanel.title": "Patient Flow",
  "patientJourney.mobile.actionPanel.subtitle": "Event and permission driven mobile handoffs",
  "patientJourney.mobile.flow.title": "Flow Handoffs",
  "patientJourney.mobile.flow.handoffs.billing": "Bill",
  "patientJourney.mobile.flow.handoffs.camp": "Camp",
  "patientJourney.mobile.flow.handoffs.emergency": "ER",
  "patientJourney.mobile.flow.handoffs.ipd": "Ward",
  "patientJourney.mobile.flow.handoffs.opd": "Clinic",
  "patientJourney.mobile.flow.handoffs.patient": "Record",
  "patientJourney.mobile.flow.handoffs.pharmacy": "Rx",
  "patientJourney.mobile.status.blocked": "Blocked",
  "patientJourney.mobile.status.emitsEvent": "Emits {{event}}",
  "patientJourney.mobile.status.ready": "Ready",
  "patientJourney.mobile.summary.awaitingEventCount": "{{count}} awaiting event",
  "patientJourney.mobile.summary.blockedCount": "{{count}} blocked",
  "patientJourney.mobile.summary.configCount": "{{count}} config",
  "patientJourney.mobile.summary.maskingCount": "{{count}} masking",
  "patientJourney.mobile.summary.permissionCount": "{{count}} permission",
  "patientJourney.mobile.summary.readyCount": "{{enabled}}/{{total}} ready",
  "patientJourney.mobile.summary.regulatoryCount": "{{count}} regulatory",
  "patientJourney.mobile.careContext.common.activeCount": "{{count}} active",
  "patientJourney.mobile.careContext.common.hiddenField": "Restricted",
  "patientJourney.mobile.careContext.common.linked": "Linked",
  "patientJourney.mobile.careContext.common.noUhid": "No UHID",
  "patientJourney.mobile.careContext.common.notRecorded": "Not recorded",
  "patientJourney.mobile.careContext.common.patient": "Patient",
  "patientJourney.mobile.careContext.common.patientContext": "Patient context",
  "patientJourney.mobile.careContext.common.patientIdentity": "Patient identity",
  "patientJourney.mobile.careContext.common.restricted": "Restricted",
  "patientJourney.mobile.careContext.common.selected": "Selected",
  "patientJourney.mobile.careContext.camp.chiefComplaint": "Chief complaint",
  "patientJourney.mobile.careContext.camp.registeredAt": "Registered {{date}}",
  "patientJourney.mobile.careContext.camp.serviceLine": "Service line",
  "patientJourney.mobile.careContext.empty.contextUnavailableTitle": "Context unavailable",
  "patientJourney.mobile.careContext.empty.noCampMessage":
    "No outreach registrations match this patient.",
  "patientJourney.mobile.careContext.empty.noCampTitle": "No camp records",
  "patientJourney.mobile.careContext.empty.noEmergencyMessage": "No ER visits match this patient.",
  "patientJourney.mobile.careContext.empty.noEmergencyTitle": "No emergency records",
  "patientJourney.mobile.careContext.empty.noIpdMessage": "No admissions match this patient.",
  "patientJourney.mobile.careContext.empty.noIpdTitle": "No IPD records",
  "patientJourney.mobile.careContext.empty.restrictedTitle": "Restricted context",
  "patientJourney.mobile.careContext.emergency.arrivedAt": "Arrived {{date}}",
  "patientJourney.mobile.careContext.emergency.bay": "Bay",
  "patientJourney.mobile.careContext.emergency.chiefComplaint": "Chief complaint",
  "patientJourney.mobile.careContext.emergency.mlc": "MLC",
  "patientJourney.mobile.careContext.emergency.triage": "Triage",
  "patientJourney.mobile.careContext.emergency.unassigned": "Unassigned",
  "patientJourney.mobile.careContext.identity.loadingPatient": "Loading patient...",
  "patientJourney.mobile.careContext.identity.patientIdentityUnavailable":
    "Patient identity unavailable",
  "patientJourney.mobile.careContext.identity.uhidUnavailable": "UHID unavailable",
  "patientJourney.mobile.careContext.ipd.admittedAt": "Admitted {{date}}",
  "patientJourney.mobile.careContext.ipd.admittingDoctor": "Admitting doctor",
  "patientJourney.mobile.careContext.ipd.bedAssigned": "Bed assigned",
  "patientJourney.mobile.careContext.ipd.bedPending": "Bed pending",
  "patientJourney.mobile.careContext.ipd.bedPendingDescription":
    "Admission cannot proceed to bedside orders yet",
  "patientJourney.mobile.careContext.ipd.recordVitals": "Record vitals",
  "patientJourney.mobile.careContext.ipd.wardPending": "Ward pending",
  "patientJourney.mobile.careContext.loading.handoffContext": "Loading handoff context...",
  "patientJourney.mobile.careContext.modules.campPermission":
    "Camp registration list permission is required to show outreach records.",
  "patientJourney.mobile.careContext.modules.campSubtitle":
    "Review outreach registration and screening continuity for this patient.",
  "patientJourney.mobile.careContext.modules.campTitle": "Camp continuity handoff",
  "patientJourney.mobile.careContext.modules.campUnavailable":
    "The latest camp records could not be loaded.",
  "patientJourney.mobile.careContext.modules.emergencyMlcTitle": "MLC handoff",
  "patientJourney.mobile.careContext.modules.emergencyPermission":
    "Emergency visit list permission is required to show ER records.",
  "patientJourney.mobile.careContext.modules.emergencySubtitle":
    "Review emergency visits, triage state, and MLC-sensitive context.",
  "patientJourney.mobile.careContext.modules.emergencyTitle": "Emergency handoff",
  "patientJourney.mobile.careContext.modules.emergencyUnavailable":
    "The latest emergency records could not be loaded.",
  "patientJourney.mobile.careContext.modules.ipdAdmitTitle": "IPD admission handoff",
  "patientJourney.mobile.careContext.modules.ipdPermission":
    "IPD admission list permission is required to show inpatient records.",
  "patientJourney.mobile.careContext.modules.ipdSubtitle":
    "Review admission status, bed state, and inpatient handoff details.",
  "patientJourney.mobile.careContext.modules.ipdTitle": "IPD care context",
  "patientJourney.mobile.careContext.modules.ipdUnavailable":
    "The latest IPD records could not be loaded.",
  "patientJourney.mobile.patientDetail.actions.activationHint":
    "Mobile handoffs activate from OPD, IPD, ER, camp, prescription, invoice, and payment events.",
  "patientJourney.mobile.patientDetail.actions.activeEr": "Active ER",
  "patientJourney.mobile.patientDetail.actions.activeIpd": "Active IPD",
  "patientJourney.mobile.patientDetail.actions.activeOpd": "Active OPD",
  "patientJourney.mobile.patientDetail.actions.bedPending": "Bed pending",
  "patientJourney.mobile.patientDetail.actions.campStatus": "Camp {{status}}",
  "patientJourney.mobile.patientDetail.actions.missingCareContextHint":
    "Open an OPD encounter or active IPD admission before recording vitals, prescriptions, or lab orders.",
  "patientJourney.mobile.patientDetail.actions.mlc": "MLC",
  "patientJourney.mobile.patientDetail.actions.pendingBillPlural": "{{count}} bills",
  "patientJourney.mobile.patientDetail.actions.pendingBillSingular": "{{count}} bill",
  "patientJourney.mobile.patientDetail.actions.rxHandoff": "Rx handoff",
  "patientJourney.mobile.patientDetail.actions.title": "Care Actions",
  "patientJourney.mobile.patientDetail.actions.vitals": "Vitals",
  "patientJourney.mobile.patientDetail.empty.noRecentVisits": "No recent visits",
  "patientJourney.mobile.patientDetail.empty.patientNotFound": "Patient not found",
  "patientJourney.mobile.patientDetail.fields.address": "Address",
  "patientJourney.mobile.patientDetail.fields.ageMasked": "Age masked",
  "patientJourney.mobile.patientDetail.fields.ageYearPlural": "{{count}} years",
  "patientJourney.mobile.patientDetail.fields.ageYearSingular": "{{count}} year",
  "patientJourney.mobile.patientDetail.fields.dateMasked": "Date masked",
  "patientJourney.mobile.patientDetail.fields.dateOfBirth": "Date of Birth",
  "patientJourney.mobile.patientDetail.fields.hiddenField": "Restricted",
  "patientJourney.mobile.patientDetail.fields.maritalStatus": "Marital Status",
  "patientJourney.mobile.patientDetail.fields.maskedField": "Masked",
  "patientJourney.mobile.patientDetail.fields.noUhid": "No UHID",
  "patientJourney.mobile.patientDetail.fields.notSpecified": "Not specified",
  "patientJourney.mobile.patientDetail.fields.occupation": "Occupation",
  "patientJourney.mobile.patientDetail.fields.patientInitials": "PT",
  "patientJourney.mobile.patientDetail.fields.unknown": "Unknown",
  "patientJourney.mobile.patientDetail.fields.unknownPatient": "Unknown patient",
  "patientJourney.mobile.patientDetail.loading.patientDetails": "Loading patient details...",
  "patientJourney.mobile.patientDetail.sections.allergies": "Allergies",
  "patientJourney.mobile.patientDetail.sections.patientInformation": "Patient Information",
  "patientJourney.mobile.patientDetail.sections.recentVisits": "Recent Visits",
  "patientJourney.mobile.patientDetail.status.campConverted": "Converted",
  "patientJourney.mobile.patientDetail.status.campRegistered": "Registered",
  "patientJourney.mobile.patientDetail.status.campReferred": "Referred",
  "patientJourney.mobile.patientDetail.status.campScreened": "Screened",
  "patientJourney.mobile.patientDetail.status.emergency": "Emergency",
  "patientJourney.mobile.patientDetail.status.female": "Female",
  "patientJourney.mobile.patientDetail.status.ipd": "IPD",
  "patientJourney.mobile.patientDetail.status.male": "Male",
  "patientJourney.mobile.patientDetail.status.maritalDivorced": "Divorced",
  "patientJourney.mobile.patientDetail.status.maritalDomesticPartner": "Domestic partner",
  "patientJourney.mobile.patientDetail.status.maritalMarried": "Married",
  "patientJourney.mobile.patientDetail.status.maritalSeparated": "Separated",
  "patientJourney.mobile.patientDetail.status.maritalSingle": "Single",
  "patientJourney.mobile.patientDetail.status.maritalUnknown": "Unknown",
  "patientJourney.mobile.patientDetail.status.maritalWidowed": "Widowed",
  "patientJourney.mobile.patientDetail.status.opd": "OPD",
  "patientJourney.mobile.patientDetail.status.other": "Other",
  "patientJourney.mobile.patientDetail.status.unknown": "Unknown",
  "patientJourney.mobile.patientDetail.visits.consultation": "Consultation",
  "patientJourney.mobile.navigation.patient.appointments": "Appointments",
  "patientJourney.mobile.navigation.patient.billing": "Bills & Payments",
  "patientJourney.mobile.navigation.patient.labResultDetails": "Result Details",
  "patientJourney.mobile.navigation.patient.labResults": "Lab Results",
  "patientJourney.mobile.navigation.patient.myHealth": "My Health",
  "patientJourney.mobile.navigation.patient.prescriptions": "Prescriptions",
  "patientJourney.mobile.navigation.patient.profile": "Profile",
  "patientJourney.mobile.navigation.patient.queueStatus": "Queue Status",
  "patientJourney.mobile.navigation.phlebotomy.collectSamples": "Collect Samples",
  "patientJourney.mobile.navigation.phlebotomy.collectionDetails": "Collection Details",
  "patientJourney.mobile.navigation.phlebotomy.homeCollections": "Home Collections",
  "patientJourney.mobile.navigation.phlebotomy.tripSummary": "Trip Summary",
  "patientJourney.mobile.navigation.staff.billing": "Patient Billing",
  "patientJourney.mobile.navigation.staff.careContext": "Care Context",
  "patientJourney.mobile.navigation.staff.consultationNotes": "Consultation Notes",
  "patientJourney.mobile.navigation.staff.dashboard": "Dashboard",
  "patientJourney.mobile.navigation.staff.ePrescription": "E-Prescription",
  "patientJourney.mobile.navigation.staff.findPatient": "Find Patient",
  "patientJourney.mobile.navigation.staff.imagingOrder": "Imaging Order",
  "patientJourney.mobile.navigation.staff.labOrders": "Lab Orders",
  "patientJourney.mobile.navigation.staff.labResults": "Lab Results",
  "patientJourney.mobile.navigation.staff.patientDetails": "Patient Details",
  "patientJourney.mobile.navigation.staff.patientPharmacy": "Patient Pharmacy",
  "patientJourney.mobile.navigation.staff.patientQueue": "Patient Queue",
  "patientJourney.mobile.navigation.staff.recordVitals": "Record Vitals",
  "patientJourney.mobile.navigation.staff.tokenBoards": "Token Boards",
  "patientJourney.mobile.queueItem.actions.call": "Call",
  "patientJourney.mobile.queueItem.actions.done": "Done",
  "patientJourney.mobile.queueItem.actions.noShow": "Mark no-show",
  "patientJourney.mobile.queueItem.actions.start": "Start",
  "patientJourney.mobile.queueItem.fields.doctor": "Dr. {{name}}",
  "patientJourney.mobile.queueItem.fields.waitMinutes": "{{count}} min",
  "patientJourney.mobile.queueItem.status.called": "Called",
  "patientJourney.mobile.queueItem.status.completed": "Completed",
  "patientJourney.mobile.queueItem.status.inProgress": "In Progress",
  "patientJourney.mobile.queueItem.status.noShow": "No Show",
  "patientJourney.mobile.queueItem.status.waiting": "Waiting",
  "patientJourney.mobile.queueScreen.banner.currentlySeeing": "Currently seeing",
  "patientJourney.mobile.queueScreen.banner.patientFallback": "Patient",
  "patientJourney.mobile.queueScreen.empty.allMessage":
    "The queue is empty. Patients will appear here when they check in.",
  "patientJourney.mobile.queueScreen.empty.filteredMessage":
    'No patients with "{{status}}" status.',
  "patientJourney.mobile.queueScreen.empty.title": "No patients in queue",
  "patientJourney.mobile.queueScreen.filters.active": "Active",
  "patientJourney.mobile.queueScreen.filters.all": "All",
  "patientJourney.mobile.queueScreen.filters.called": "Called",
  "patientJourney.mobile.queueScreen.filters.waiting": "Waiting",
  "patientJourney.mobile.queueScreen.loading.queue": "Loading queue...",
  "patientJourney.mobile.queueScreen.restricted.message":
    "OPD queue visibility is controlled by your permission matrix.",
  "patientJourney.mobile.queueScreen.restricted.title": "Queue access restricted",
  "patientJourney.mobile.queueScreen.stats.called": "Called",
  "patientJourney.mobile.queueScreen.stats.inProgress": "In Progress",
  "patientJourney.mobile.queueScreen.stats.waiting": "Waiting",
  "patientJourney.mobile.patientSearch.empty.message": "Try searching with different criteria",
  "patientJourney.mobile.patientSearch.empty.title": "No patients found",
  "patientJourney.mobile.patientSearch.loading.patients": "Searching patients...",
  "patientJourney.mobile.patientSearch.results.countPlural": "{{count}} patients found",
  "patientJourney.mobile.patientSearch.results.countSingular": "{{count}} patient found",
  "patientJourney.mobile.patientSearch.restricted.message":
    "Patient list access is controlled by your permission matrix.",
  "patientJourney.mobile.patientSearch.restricted.title": "Patient search restricted",
  "patientJourney.mobile.patientSearch.search.hint":
    "Enter at least 2 characters to search patients.",
  "patientJourney.mobile.patientSearch.search.placeholder": "Search by UHID, name, phone...",
  "patientJourney.mobile.patientSearch.search.title": "Search Patients",
  "patientJourney.mobile.patientCard.fields.ageMasked": "Age masked",
  "patientJourney.mobile.patientCard.fields.ageYearsShort": "{{count}}Y",
  "patientJourney.mobile.patientCard.fields.genderFemaleShort": "F",
  "patientJourney.mobile.patientCard.fields.genderMaleShort": "M",
  "patientJourney.mobile.patientCard.fields.genderOtherShort": "O",
  "patientJourney.mobile.patientCard.fields.genderUnknownShort": "U",
  "patientJourney.mobile.patientCard.fields.hiddenField": "Restricted",
  "patientJourney.mobile.patientCard.fields.noUhid": "No UHID",
  "patientJourney.mobile.patientCard.fields.patientInitials": "PT",
  "patientJourney.mobile.patientCard.fields.unknownPatient": "Unknown patient",
  "patientJourney.mobile.patientPharmacy.empty.message": "No medicines match this patient handoff.",
  "patientJourney.mobile.patientPharmacy.empty.title": "No pharmacy context",
  "patientJourney.mobile.patientPharmacy.filters.allHistory": "All history",
  "patientJourney.mobile.patientPharmacy.filters.recent": "Last 30 days",
  "patientJourney.mobile.patientPharmacy.handoff.activeCount": "{{count}} active",
  "patientJourney.mobile.patientPharmacy.handoff.dispenseDescription":
    "Selected order is linked from the patient journey for dispensing.",
  "patientJourney.mobile.patientPharmacy.handoff.dispenseTitle": "Dispense handoff",
  "patientJourney.mobile.patientPharmacy.handoff.pharmacyTitle": "Patient pharmacy",
  "patientJourney.mobile.patientPharmacy.handoff.queueDescription":
    "Selected prescription is waiting in pharmacy review before billing and dispense.",
  "patientJourney.mobile.patientPharmacy.handoff.reviewDescription":
    "Review active and recent medicines before pharmacy fulfilment.",
  "patientJourney.mobile.patientPharmacy.loading.context": "Loading pharmacy context...",
  "patientJourney.mobile.patientPharmacy.medication.itemCountPlural": "{{count}} items",
  "patientJourney.mobile.patientPharmacy.medication.itemCountSingular": "{{count}} item",
  "patientJourney.mobile.patientPharmacy.medication.prescriberFallback": "Prescriber",
  "patientJourney.mobile.patientPharmacy.medication.selectedOrder": "Selected order",
  "patientJourney.mobile.patientPharmacy.search.placeholder": "Search medicine, dosage, or doctor",
  "patientJourney.mobile.patientPharmacy.status.active": "Active",
  "patientJourney.mobile.patientPharmacy.status.changed": "Changed",
  "patientJourney.mobile.patientPharmacy.status.discontinued": "Discontinued",
  "patientJourney.mobile.patientPharmacy.status.unknown": "Unknown",
  "patientJourney.mobile.consultationNotes.actions.completeSign": "Complete & Sign",
  "patientJourney.mobile.consultationNotes.actions.save": "Save Notes",
  "patientJourney.mobile.consultationNotes.diagnoses.active": "Active Diagnoses",
  "patientJourney.mobile.consultationNotes.errors.failedToSave": "Failed to save notes",
  "patientJourney.mobile.consultationNotes.progress.soap": "SOAP Note Progress",
  "patientJourney.mobile.consultationNotes.sections.assessment": "Assessment",
  "patientJourney.mobile.consultationNotes.sections.assessmentShort": "A",
  "patientJourney.mobile.consultationNotes.sections.objective": "Objective",
  "patientJourney.mobile.consultationNotes.sections.objectiveShort": "O",
  "patientJourney.mobile.consultationNotes.sections.plan": "Plan",
  "patientJourney.mobile.consultationNotes.sections.planShort": "P",
  "patientJourney.mobile.consultationNotes.sections.subjective": "Subjective",
  "patientJourney.mobile.consultationNotes.sections.subjectiveShort": "S",
  "patientJourney.mobile.consultationNotes.placeholders.assessment":
    "Diagnosis, differential diagnosis, clinical impression...",
  "patientJourney.mobile.consultationNotes.placeholders.objective":
    "Physical examination findings, vital signs, lab results...",
  "patientJourney.mobile.consultationNotes.placeholders.plan":
    "Treatment plan, medications, follow-up, referrals...",
  "patientJourney.mobile.consultationNotes.placeholders.subjective":
    "Patient's symptoms, complaints, and history in their own words...",
  "patientJourney.mobile.consultationNotes.status.saved": "Notes saved successfully",
  "patientJourney.mobile.consultationNotes.templates.complainsOf": "Complains of",
  "patientJourney.mobile.consultationNotes.templates.complainsOfSnippet": "Patient complains of",
  "patientJourney.mobile.consultationNotes.templates.continueMeds": "Continue meds",
  "patientJourney.mobile.consultationNotes.templates.continueMedsSnippet":
    "Continue current medications.",
  "patientJourney.mobile.consultationNotes.templates.diagnosis": "Dx",
  "patientJourney.mobile.consultationNotes.templates.diagnosisSnippet": "Primary diagnosis:",
  "patientJourney.mobile.consultationNotes.templates.historyOf": "H/O",
  "patientJourney.mobile.consultationNotes.templates.historyOfSnippet": "History of",
  "patientJourney.mobile.consultationNotes.templates.noAbnormality": "NAD",
  "patientJourney.mobile.consultationNotes.templates.noAbnormalitySnippet":
    "No abnormality detected.",
  "patientJourney.mobile.consultationNotes.templates.noKnownAllergies": "NKA",
  "patientJourney.mobile.consultationNotes.templates.noKnownAllergiesSnippet":
    "No known allergies.",
  "patientJourney.mobile.consultationNotes.templates.onExamination": "O/E",
  "patientJourney.mobile.consultationNotes.templates.onExaminationSnippet": "On examination:",
  "patientJourney.mobile.consultationNotes.templates.quickPhrases": "Quick phrases:",
  "patientJourney.mobile.consultationNotes.templates.restAdvised": "Rest advised",
  "patientJourney.mobile.consultationNotes.templates.restAdvisedSnippet":
    "Advised rest and hydration.",
  "patientJourney.mobile.consultationNotes.templates.reviewOneWeek": "Review 1w",
  "patientJourney.mobile.consultationNotes.templates.reviewOneWeekSnippet": "Review after 1 week.",
  "patientJourney.mobile.consultationNotes.templates.ruleOut": "R/O",
  "patientJourney.mobile.consultationNotes.templates.ruleOutSnippet": "Rule out",
  "patientJourney.mobile.consultationNotes.templates.stableCondition": "Stable",
  "patientJourney.mobile.consultationNotes.templates.stableConditionSnippet": "Stable condition.",
  "patientJourney.mobile.consultationNotes.templates.vitalsStable": "Vitals stable",
  "patientJourney.mobile.consultationNotes.templates.vitalsStableSnippet": "Vitals stable.",
  "patientJourney.mobile.labOrder.actions.addTest": "Add test",
  "patientJourney.mobile.labOrder.actions.placePlural": "Place Lab Order ({{count}} tests)",
  "patientJourney.mobile.labOrder.actions.placeSingular": "Place Lab Order ({{count}} test)",
  "patientJourney.mobile.labOrder.categories.biochemistry": "Biochemistry",
  "patientJourney.mobile.labOrder.categories.cardiology": "Cardiology",
  "patientJourney.mobile.labOrder.categories.clinicalPathology": "Clinical Pathology",
  "patientJourney.mobile.labOrder.categories.diabetes": "Diabetes",
  "patientJourney.mobile.labOrder.categories.general": "General",
  "patientJourney.mobile.labOrder.categories.hematology": "Hematology",
  "patientJourney.mobile.labOrder.categories.hormones": "Hormones",
  "patientJourney.mobile.labOrder.commonTests.cbc": "Complete Blood Count",
  "patientJourney.mobile.labOrder.commonTests.ecg": "ECG",
  "patientJourney.mobile.labOrder.commonTests.hba1c": "HbA1c",
  "patientJourney.mobile.labOrder.commonTests.lft": "Liver Function Test",
  "patientJourney.mobile.labOrder.commonTests.lipid": "Lipid Profile",
  "patientJourney.mobile.labOrder.commonTests.rft": "Renal Function Test",
  "patientJourney.mobile.labOrder.commonTests.thyroid": "Thyroid Profile",
  "patientJourney.mobile.labOrder.commonTests.urine": "Urine Routine",
  "patientJourney.mobile.labOrder.empty.hint": "Search or tap common tests to add",
  "patientJourney.mobile.labOrder.empty.noResults": "No tests found",
  "patientJourney.mobile.labOrder.empty.title": "No tests selected",
  "patientJourney.mobile.labOrder.errors.failedToCreate": "Failed to create lab order",
  "patientJourney.mobile.labOrder.errors.noTestsSelected": "No tests selected",
  "patientJourney.mobile.labOrder.priority.routine": "Routine",
  "patientJourney.mobile.labOrder.priority.stat": "STAT",
  "patientJourney.mobile.labOrder.priority.urgent": "Urgent",
  "patientJourney.mobile.labOrder.recent.description": "{{status}} • {{date}}",
  "patientJourney.mobile.labOrder.recent.orderTitle": "Lab Order",
  "patientJourney.mobile.labOrder.recent.title": "Recent Lab Orders",
  "patientJourney.mobile.labOrder.search.placeholder": "Search tests...",
  "patientJourney.mobile.labOrder.search.resultDescription": "{{code}} • {{sample}}",
  "patientJourney.mobile.labOrder.sections.commonTests": "Common Tests",
  "patientJourney.mobile.labOrder.sections.priority": "Priority",
  "patientJourney.mobile.labOrder.sections.selectedTests": "Selected Tests",
  "patientJourney.mobile.labOrder.status.cancelled": "Cancelled",
  "patientJourney.mobile.labOrder.status.completed": "Completed",
  "patientJourney.mobile.labOrder.status.created": "Lab order(s) created successfully",
  "patientJourney.mobile.labOrder.status.ordered": "Ordered",
  "patientJourney.mobile.labOrder.status.processing": "Processing",
  "patientJourney.mobile.labOrder.status.sampleCollected": "Sample collected",
  "patientJourney.mobile.labOrder.status.verified": "Verified",
  "patientJourney.mobile.labOrder.tests.tatHours": "{{hours}}h TAT",
  "patientJourney.mobile.labOrder.tests.total": "Total",
  "patientJourney.mobile.radiologyOrder.actions.place": "Place Imaging Order",
  "patientJourney.mobile.radiologyOrder.context.encounterLinked": "Encounter linked",
  "patientJourney.mobile.radiologyOrder.context.noEncounter": "No encounter",
  "patientJourney.mobile.radiologyOrder.context.patientLinked": "Patient linked",
  "patientJourney.mobile.radiologyOrder.context.patientRequired": "Patient required",
  "patientJourney.mobile.radiologyOrder.context.subtitle":
    "Radiology handoff linked to the active OPD or IPD encounter.",
  "patientJourney.mobile.radiologyOrder.context.title": "Imaging order",
  "patientJourney.mobile.radiologyOrder.empty.noActiveModalities":
    "No active radiology modalities are available.",
  "patientJourney.mobile.radiologyOrder.errors.failedToCreate": "Failed to create imaging order",
  "patientJourney.mobile.radiologyOrder.errors.modalityRequired": "Modality is required",
  "patientJourney.mobile.radiologyOrder.errors.patientRequired": "Patient is required",
  "patientJourney.mobile.radiologyOrder.fields.bodyPart": "Body part",
  "patientJourney.mobile.radiologyOrder.fields.clinicalIndication": "Clinical indication",
  "patientJourney.mobile.radiologyOrder.fields.modality": "Modality",
  "patientJourney.mobile.radiologyOrder.fields.notes": "Notes",
  "patientJourney.mobile.radiologyOrder.fields.patientId": "Patient ID",
  "patientJourney.mobile.radiologyOrder.fields.selectedModality": "Selected: {{modality}}",
  "patientJourney.mobile.radiologyOrder.placeholders.bodyPart": "e.g. Chest, abdomen, left knee",
  "patientJourney.mobile.radiologyOrder.placeholders.clinicalIndication": "Reason for imaging",
  "patientJourney.mobile.radiologyOrder.placeholders.notes":
    "Preparation, transport or scheduling notes",
  "patientJourney.mobile.radiologyOrder.priority.routine": "Routine",
  "patientJourney.mobile.radiologyOrder.priority.stat": "STAT",
  "patientJourney.mobile.radiologyOrder.priority.urgent": "Urgent",
  "patientJourney.mobile.radiologyOrder.recent.description": "{{status}} - {{date}}",
  "patientJourney.mobile.radiologyOrder.recent.fallbackTitle": "Radiology order",
  "patientJourney.mobile.radiologyOrder.recent.title": "Recent imaging orders",
  "patientJourney.mobile.radiologyOrder.restricted.message":
    "Creating mobile imaging orders requires radiology order create permission and modality list access.",
  "patientJourney.mobile.radiologyOrder.restricted.title": "Radiology order access restricted",
  "patientJourney.mobile.radiologyOrder.safety.allergyDescription":
    "Highlights allergy or renal/contrast risk for radiology",
  "patientJourney.mobile.radiologyOrder.safety.allergyTitle": "Allergy or contrast risk flagged",
  "patientJourney.mobile.radiologyOrder.safety.contrastDescription":
    "Mark before sending patient to contrast workflow",
  "patientJourney.mobile.radiologyOrder.safety.contrastTitle": "Contrast required",
  "patientJourney.mobile.radiologyOrder.safety.pregnancyDescription":
    "Required safety check where applicable",
  "patientJourney.mobile.radiologyOrder.safety.pregnancyTitle": "Pregnancy status checked",
  "patientJourney.mobile.radiologyOrder.sections.clinicalDetails": "Clinical details",
  "patientJourney.mobile.radiologyOrder.sections.patientModality": "Patient and modality",
  "patientJourney.mobile.radiologyOrder.sections.prioritySafety": "Priority and safety",
  "patientJourney.mobile.radiologyOrder.status.cancelled": "Cancelled",
  "patientJourney.mobile.radiologyOrder.status.completed": "Completed",
  "patientJourney.mobile.radiologyOrder.status.created": "Imaging order {{orderId}} created",
  "patientJourney.mobile.radiologyOrder.status.inProgress": "In progress",
  "patientJourney.mobile.radiologyOrder.status.ordered": "Ordered",
  "patientJourney.mobile.radiologyOrder.status.reported": "Reported",
  "patientJourney.mobile.radiologyOrder.status.scheduled": "Scheduled",
  "patientJourney.mobile.radiologyOrder.status.verified": "Verified",
  "patientJourney.mobile.prescription.actions.add": "Add",
  "patientJourney.mobile.prescription.actions.addDrug": "Add Drug",
  "patientJourney.mobile.prescription.actions.cancel": "Cancel",
  "patientJourney.mobile.prescription.actions.copyPrevious": "Copy previous prescription",
  "patientJourney.mobile.prescription.actions.savePlural": "Save Prescription ({{count}} items)",
  "patientJourney.mobile.prescription.actions.saveSingular": "Save Prescription ({{count}} item)",
  "patientJourney.mobile.prescription.dialog.addMedication": "Add Medication",
  "patientJourney.mobile.prescription.dialog.dosage": "Dosage (e.g., 500 mg)",
  "patientJourney.mobile.prescription.dialog.drugName": "Drug Name",
  "patientJourney.mobile.prescription.dialog.duration": "Duration",
  "patientJourney.mobile.prescription.dialog.frequency": "Frequency",
  "patientJourney.mobile.prescription.dialog.instructions": "Special Instructions (optional)",
  "patientJourney.mobile.prescription.dialog.route": "Route",
  "patientJourney.mobile.prescription.dialog.searchPlaceholder": "Search drug...",
  "patientJourney.mobile.prescription.durations.continuous": "Continuous",
  "patientJourney.mobile.prescription.durations.fiveDays": "5 days",
  "patientJourney.mobile.prescription.durations.fourteenDays": "14 days",
  "patientJourney.mobile.prescription.durations.oneMonth": "1 month",
  "patientJourney.mobile.prescription.durations.sevenDays": "7 days",
  "patientJourney.mobile.prescription.durations.tenDays": "10 days",
  "patientJourney.mobile.prescription.durations.threeDays": "3 days",
  "patientJourney.mobile.prescription.durations.threeMonths": "3 months",
  "patientJourney.mobile.prescription.empty.hint": "Tap + to add medications",
  "patientJourney.mobile.prescription.empty.title": "No medications added yet",
  "patientJourney.mobile.prescription.errors.dosageRequired": "Dosage is required",
  "patientJourney.mobile.prescription.errors.drugNameRequired": "Drug name is required",
  "patientJourney.mobile.prescription.errors.durationRequired": "Duration is required",
  "patientJourney.mobile.prescription.errors.failedToSave": "Failed to save prescription",
  "patientJourney.mobile.prescription.errors.frequencyRequired": "Frequency is required",
  "patientJourney.mobile.prescription.errors.noItems": "No items to save",
  "patientJourney.mobile.prescription.errors.routeRequired": "Route is required",
  "patientJourney.mobile.prescription.errors.tooLong": "Must be at most 255 characters",
  "patientJourney.mobile.prescription.frequencies.afterMeals": "After meals",
  "patientJourney.mobile.prescription.frequencies.asNeeded": "As needed",
  "patientJourney.mobile.prescription.frequencies.atBedtime": "At bedtime",
  "patientJourney.mobile.prescription.frequencies.beforeMeals": "Before meals",
  "patientJourney.mobile.prescription.frequencies.fourTimesDaily": "Four times daily",
  "patientJourney.mobile.prescription.frequencies.onceDaily": "Once daily",
  "patientJourney.mobile.prescription.frequencies.threeTimesDaily": "Three times daily",
  "patientJourney.mobile.prescription.frequencies.twiceDaily": "Twice daily",
  "patientJourney.mobile.prescription.routes.im": "IM",
  "patientJourney.mobile.prescription.routes.inhalation": "Inhalation",
  "patientJourney.mobile.prescription.routes.iv": "IV",
  "patientJourney.mobile.prescription.routes.oral": "Oral",
  "patientJourney.mobile.prescription.routes.rectal": "Rectal",
  "patientJourney.mobile.prescription.routes.sc": "SC",
  "patientJourney.mobile.prescription.routes.sublingual": "Sublingual",
  "patientJourney.mobile.prescription.routes.topical": "Topical",
  "patientJourney.mobile.prescription.sections.current": "Current Prescription",
  "patientJourney.mobile.prescription.sections.previous": "Previous Prescriptions",
  "patientJourney.mobile.prescription.status.copiedPrevious":
    "Added items from previous prescription",
  "patientJourney.mobile.prescription.status.saved": "Prescription saved successfully",
  "patientJourney.mobile.prescription.summary.itemCountPlural": "{{count}} medications",
  "patientJourney.mobile.prescription.summary.itemCountSingular": "{{count}} medication",
  "patientJourney.mobile.prescription.summary.note": "Note: {{instructions}}",
  "patientJourney.mobile.staffDashboard.common.greeting": "Good Morning,",
  "patientJourney.mobile.staffDashboard.common.staffFallback": "Staff",
  "patientJourney.mobile.staffDashboard.common.staffInitials": "ST",
  "patientJourney.mobile.staffDashboard.flow.boards": "Boards",
  "patientJourney.mobile.staffDashboard.flow.empty":
    "No mobile workflow actions are enabled for this role.",
  "patientJourney.mobile.staffDashboard.flow.imaging": "Imaging",
  "patientJourney.mobile.staffDashboard.flow.orders": "Orders",
  "patientJourney.mobile.staffDashboard.flow.patient": "Patient",
  "patientJourney.mobile.staffDashboard.flow.queue": "Queue",
  "patientJourney.mobile.staffDashboard.flow.results": "Results",
  "patientJourney.mobile.staffDashboard.flow.title": "Enabled mobile flow",
  "patientJourney.mobile.staffDashboard.flow.vitals": "Vitals",
  "patientJourney.mobile.staffDashboard.overview.active": "Active",
  "patientJourney.mobile.staffDashboard.overview.completed": "Completed",
  "patientJourney.mobile.staffDashboard.overview.openBillingDesk": "Open billing desk",
  "patientJourney.mobile.staffDashboard.overview.openLabWorklist": "Open lab worklist",
  "patientJourney.mobile.staffDashboard.overview.openOpdQueue": "Open OPD queue",
  "patientJourney.mobile.staffDashboard.overview.openPatientSearch": "Find patient",
  "patientJourney.mobile.staffDashboard.overview.title": "Today's Overview",
  "patientJourney.mobile.staffDashboard.overview.tokensToday": "Tokens Today",
  "patientJourney.mobile.staffDashboard.overview.waiting": "Waiting",
  "patientJourney.mobile.staffDashboard.queue.currentQueue": "Current Queue",
  "patientJourney.mobile.staffDashboard.queue.emptyMessage":
    "Checked-in patients will appear here from the shared OPD queue.",
  "patientJourney.mobile.staffDashboard.queue.emptyTitle": "No active queue tokens",
  "patientJourney.mobile.staffDashboard.queue.loading": "Loading live queue...",
  "patientJourney.mobile.staffDashboard.queue.restrictedMessage":
    "OPD queue visibility is controlled by your permission matrix.",
  "patientJourney.mobile.staffDashboard.queue.restrictedTitle": "Queue restricted",
  "patientJourney.mobile.staffDashboard.queue.retry": "Retry",
  "patientJourney.mobile.staffDashboard.queue.unavailableMessage":
    "Pull from the queue screen or retry when network is stable.",
  "patientJourney.mobile.staffDashboard.queue.unavailableTitle": "Queue unavailable",
  "patientJourney.mobile.staffDashboard.quickActions.emptyMessage":
    "Your role has no mobile workflow actions enabled.",
  "patientJourney.mobile.staffDashboard.quickActions.emptyTitle": "No enabled shortcuts",
  "patientJourney.mobile.staffDashboard.quickActions.fabFind": "Find",
  "patientJourney.mobile.staffDashboard.quickActions.findPatient": "Find Patient",
  "patientJourney.mobile.staffDashboard.quickActions.fullQueue": "Full Queue",
  "patientJourney.mobile.staffDashboard.quickActions.imaging": "Imaging",
  "patientJourney.mobile.staffDashboard.quickActions.labOrder": "Lab Order",
  "patientJourney.mobile.staffDashboard.quickActions.labResults": "Lab Results",
  "patientJourney.mobile.staffDashboard.quickActions.title": "Quick Actions",
  "patientJourney.mobile.staffDashboard.quickActions.tokenBoards": "Token Boards",
  "patientJourney.mobile.staffDashboard.quickActions.vitals": "Vitals",
  "patientJourney.mobile.staffDashboard.quickActions.writeRx": "Write Rx",
  "patientJourney.mobile.vitals.actions.save": "Save Vitals",
  "patientJourney.mobile.vitals.bmi.calculated": "Calculated BMI",
  "patientJourney.mobile.vitals.errors.invalidDiastolic": "Enter a valid diastolic BP",
  "patientJourney.mobile.vitals.errors.invalidHeight": "Enter a valid height",
  "patientJourney.mobile.vitals.errors.invalidPulse": "Enter a valid pulse",
  "patientJourney.mobile.vitals.errors.invalidRespiration": "Enter a valid respiratory rate",
  "patientJourney.mobile.vitals.errors.invalidSpo2": "Enter a valid SpO2",
  "patientJourney.mobile.vitals.errors.invalidSystolic": "Enter a valid systolic BP",
  "patientJourney.mobile.vitals.errors.invalidTemperature": "Enter a valid temperature",
  "patientJourney.mobile.vitals.errors.invalidWeight": "Enter a valid weight",
  "patientJourney.mobile.vitals.errors.noEncounterId": "No encounter ID",
  "patientJourney.mobile.vitals.errors.saveFailed": "Failed to save vitals",
  "patientJourney.mobile.vitals.fields.diastolic": "Diastolic BP",
  "patientJourney.mobile.vitals.fields.height": "Height",
  "patientJourney.mobile.vitals.fields.normalRange": "Normal",
  "patientJourney.mobile.vitals.fields.pulse": "Pulse Rate",
  "patientJourney.mobile.vitals.fields.respiration": "Respiration Rate",
  "patientJourney.mobile.vitals.fields.spo2": "SpO2",
  "patientJourney.mobile.vitals.fields.systolic": "Systolic BP",
  "patientJourney.mobile.vitals.fields.temperature": "Temperature",
  "patientJourney.mobile.vitals.fields.weight": "Weight",
  "patientJourney.mobile.vitals.sections.anthropometry": "Anthropometry",
  "patientJourney.mobile.vitals.sections.previousVitals": "Previous Vitals",
  "patientJourney.mobile.vitals.sections.vitalSigns": "Vital Signs",
  "patientJourney.mobile.vitals.status.saved": "Vitals saved successfully",
  "patientJourney.mobile.vitals.summary.bp": "BP: {{systolic}}/{{diastolic}} mmHg",
  "patientJourney.mobile.vitals.summary.pulse": "Pulse: {{value}} bpm",
  "patientJourney.mobile.vitals.summary.recorded": "Vitals recorded",
  "patientJourney.mobile.vitals.summary.spo2": "SpO2: {{value}}%",
  "patientJourney.mobile.vitals.summary.temperature": "Temp: {{value}}°F",
  "patientJourney.status.available": "Available",
  "patientJourney.status.afterEvents": "After {{events}}",
};

function interpolate(
  template: string,
  values?: ClinicalJourneyMessageValues | Record<string, string | number | boolean>,
): string {
  if (!values) return template;

  return template.replace(/\{\{(\w+)\}\}/g, (placeholder, name) =>
    name in values ? String(values[name]) : placeholder,
  );
}

export const mobilePatientJourneyTranslator: PatientJourneyTranslator = (key, values) => {
  const template = MOBILE_PATIENT_JOURNEY_MESSAGES[key];

  return template ? interpolate(template, values) : key;
};

export function mobilePatientJourneyText(
  key: string,
  values?: ClinicalJourneyMessageValues | Record<string, string | number | boolean>,
): string {
  const translated = mobilePatientJourneyTranslator(key, values);
  return typeof translated === "string" ? translated : key;
}
