import {
  IconActivity,
  IconAlertTriangle,
  IconAmbulance,
  IconBandage,
  IconBed,
  IconBodyScan,
  IconBone,
  IconBrain,
  IconBuildingHospital,
  IconCalendar,
  IconCapsule,
  IconClipboard,
  IconClock,
  IconCreditCard,
  IconCrutches,
  IconCurrencyDollar,
  IconCurrencyRupee,
  IconDental,
  IconDna,
  IconDroplet,
  IconEar,
  IconEmergencyBed,
  IconEye,
  IconFaceMask,
  IconFileText,
  IconFingerprint,
  IconHealthRecognition,
  IconHeart,
  IconHeartRateMonitor,
  IconHome,
  IconHospital,
  IconId,
  IconInfoCircle,
  IconListCheck,
  IconLock,
  IconLungs,
  IconMail,
  IconMapPin,
  IconMedicalCross,
  IconMedicineSyrup,
  IconMicroscope,
  IconNotes,
  IconNurse,
  IconPhone,
  IconPhoto,
  IconPill,
  IconReceipt,
  IconReportMedical,
  IconRibbonHealth,
  IconSection,
  IconSettings,
  IconShield,
  IconStethoscope,
  IconTestPipe,
  IconThermometer,
  IconUser,
  IconUsers,
  IconVaccine,
  IconVirus,
  IconWheelchair,
} from "@tabler/icons-react";

// Healthicons-react (outline variants for consistency)
import {
  AccidentAndEmergencyOutline,
  AdmissionsOutline,
  AllergiesOutline,
  AsthmaOutline,
  BiochemistryLaboratoryOutline,
  BloodBagOutline,
  BloodDropOutline,
  BloodPressureMonitorOutline,
  BodyOutline,
  BurnUnitOutline,
  CardiologyOutline,
  CoronaryCareUnitOutline,
  CriticalCareOutline,
  DefibrillatorOutline,
  DentalHygieneOutline,
  DiabetesOutline,
  DoctorOutline,
  EarOutline as HiEarOutline,
  EarsNoseAndThroatOutline,
  EndocrinologyOutline,
  EyeOutline as HiEyeOutline,
  FootOutline,
  GallbladderOutline,
  GastroenterologyOutline,
  GeneralSurgeryOutline,
  GeriatricsOutline,
  GynecologyOutline,
  HeartOrganOutline,
  HematologyOutline,
  HepatologyOutline,
  HospitalOutline as HiHospitalOutline,
  InfusionPumpOutline,
  InpatientOutline,
  IntensiveCareUnitOutline,
  IntestineOutline,
  IntravenousBagOutline,
  JointsOutline,
  KidneysOutline,
  LungsOutline as HiLungsOutline,
  MedicalRecordsOutline,
  MedicineBottleOutline,
  MicroscopeOutline as HiMicroscopeOutline,
  NephrologyOutline,
  NeurologyOutline as HiNeurologyOutline,
  NurseOutline as HiNurseOutline,
  ObstetricsmoniaOutline,
  OncologyOutline,
  OpthalmologyOutline,
  OrthopaedicsOutline,
  OutpatientOutline,
  OutpatientDepartmentOutline,
  OxygenTankOutline,
  PalliativeCareOutline,
  PancreasOutline,
  PediatricsOutline,
  PharmacyOutline,
  PhysicalTherapyOutline,
  PrescriptionDocumentOutline,
  PsychologyOutline,
  PulseOximeterOutline,
  RadiologyOutline,
  RespirologyOutline,
  RheumatologyOutline,
  SkeletonOutline,
  SpineOutline,
  SpleenOutline,
  StethoscopeOutline as HiStethoscopeOutline,
  StomachOutline,
  SyringeOutline,
  TestTubesOutline,
  ThermometerOutline as HiThermometerOutline,
  ThyroidOutline,
  ToothOutline,
  UltrasoundScannerOutline,
  UrologyOutline,
  VascularSurgeryOutline,
  VentilatorOutline,
  WheelchairOutline as HiWheelchairOutline,
  XrayOutline,
} from "healthicons-react";

// ── Tabler icon map (no prefix) ─────────────────────────

const TABLER_ICON_MAP: Record<string, React.ComponentType<{ size?: number }>> = {
  // People
  user: IconUser,
  users: IconUsers,
  nurse: IconNurse,

  // Medical / Clinical
  stethoscope: IconStethoscope,
  "medical-cross": IconMedicalCross,
  heart: IconHeart,
  "heart-rate": IconHeartRateMonitor,
  activity: IconActivity,
  pill: IconPill,
  capsule: IconCapsule,
  "medicine-syrup": IconMedicineSyrup,
  vaccine: IconVaccine,
  thermometer: IconThermometer,
  bandage: IconBandage,
  microscope: IconMicroscope,
  "test-pipe": IconTestPipe,
  dna: IconDna,
  virus: IconVirus,
  droplet: IconDroplet,
  lungs: IconLungs,
  brain: IconBrain,
  bone: IconBone,
  dental: IconDental,
  eye: IconEye,
  ear: IconEar,
  "face-mask": IconFaceMask,
  "body-scan": IconBodyScan,
  "report-medical": IconReportMedical,
  "health-recognition": IconHealthRecognition,
  "ribbon-health": IconRibbonHealth,

  // Facility
  "building-hospital": IconBuildingHospital,
  hospital: IconHospital,
  bed: IconBed,
  "emergency-bed": IconEmergencyBed,
  ambulance: IconAmbulance,
  wheelchair: IconWheelchair,
  crutches: IconCrutches,

  // General
  id: IconId,
  phone: IconPhone,
  mail: IconMail,
  "map-pin": IconMapPin,
  home: IconHome,
  shield: IconShield,
  lock: IconLock,
  "file-text": IconFileText,
  clipboard: IconClipboard,
  calendar: IconCalendar,
  clock: IconClock,
  "currency-dollar": IconCurrencyDollar,
  "currency-rupee": IconCurrencyRupee,
  "credit-card": IconCreditCard,
  receipt: IconReceipt,
  "alert-triangle": IconAlertTriangle,
  "info-circle": IconInfoCircle,
  settings: IconSettings,
  photo: IconPhoto,
  fingerprint: IconFingerprint,
  "list-check": IconListCheck,
  notes: IconNotes,
};

// ── Health icon map (hi- prefix) ─────────────────────────
// These use SVG props (width/height) instead of size

type SvgIconComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>;

const HEALTH_ICON_MAP: Record<string, SvgIconComponent> = {
  // Departments & Specialties
  "hi-cardiology": CardiologyOutline,
  "hi-neurology": HiNeurologyOutline,
  "hi-pediatrics": PediatricsOutline,
  "hi-gynecology": GynecologyOutline,
  "hi-oncology": OncologyOutline,
  "hi-radiology": RadiologyOutline,
  "hi-pharmacy": PharmacyOutline,
  "hi-nephrology": NephrologyOutline,
  "hi-hematology": HematologyOutline,
  "hi-gastroenterology": GastroenterologyOutline,
  "hi-endocrinology": EndocrinologyOutline,
  "hi-hepatology": HepatologyOutline,
  "hi-rheumatology": RheumatologyOutline,
  "hi-urology": UrologyOutline,
  "hi-orthopaedics": OrthopaedicsOutline,
  "hi-ophthalmology": OpthalmologyOutline,
  "hi-general-surgery": GeneralSurgeryOutline,
  "hi-geriatrics": GeriatricsOutline,
  "hi-psychology": PsychologyOutline,
  "hi-respirology": RespirologyOutline,
  "hi-vascular-surgery": VascularSurgeryOutline,
  "hi-obstetrics": ObstetricsmoniaOutline,
  "hi-ent": EarsNoseAndThroatOutline,
  "hi-palliative-care": PalliativeCareOutline,
  "hi-physical-therapy": PhysicalTherapyOutline,
  "hi-biochemistry-lab": BiochemistryLaboratoryOutline,
  "hi-hematology-lab": HematologyOutline,
  "hi-dental-hygiene": DentalHygieneOutline,

  // Units / Areas
  "hi-emergency": AccidentAndEmergencyOutline,
  "hi-admissions": AdmissionsOutline,
  "hi-icu": IntensiveCareUnitOutline,
  "hi-ccu": CoronaryCareUnitOutline,
  "hi-critical-care": CriticalCareOutline,
  "hi-burn-unit": BurnUnitOutline,
  "hi-opd": OutpatientDepartmentOutline,
  "hi-inpatient": InpatientOutline,
  "hi-outpatient": OutpatientOutline,
  "hi-hospital": HiHospitalOutline,

  // Anatomy
  "hi-heart": HeartOrganOutline,
  "hi-lungs": HiLungsOutline,
  "hi-kidneys": KidneysOutline,
  "hi-stomach": StomachOutline,
  "hi-intestine": IntestineOutline,
  "hi-gallbladder": GallbladderOutline,
  "hi-pancreas": PancreasOutline,
  "hi-spleen": SpleenOutline,
  "hi-thyroid": ThyroidOutline,
  "hi-spine": SpineOutline,
  "hi-skeleton": SkeletonOutline,
  "hi-joints": JointsOutline,
  "hi-body": BodyOutline,
  "hi-eye": HiEyeOutline,
  "hi-ear": HiEarOutline,
  "hi-foot": FootOutline,
  "hi-tooth": ToothOutline,

  // Devices & Equipment
  "hi-stethoscope": HiStethoscopeOutline,
  "hi-microscope": HiMicroscopeOutline,
  "hi-syringe": SyringeOutline,
  "hi-thermometer": HiThermometerOutline,
  "hi-bp-monitor": BloodPressureMonitorOutline,
  "hi-defibrillator": DefibrillatorOutline,
  "hi-infusion-pump": InfusionPumpOutline,
  "hi-oxygen-tank": OxygenTankOutline,
  "hi-ventilator": VentilatorOutline,
  "hi-wheelchair": HiWheelchairOutline,
  "hi-xray": XrayOutline,
  "hi-test-tubes": TestTubesOutline,
  "hi-ultrasound": UltrasoundScannerOutline,
  "hi-iv-bag": IntravenousBagOutline,
  "hi-pulse-oximeter": PulseOximeterOutline,

  // Clinical / Conditions
  "hi-allergies": AllergiesOutline,
  "hi-diabetes": DiabetesOutline,
  "hi-asthma": AsthmaOutline,
  "hi-blood-bag": BloodBagOutline,
  "hi-blood-drop": BloodDropOutline,

  // People
  "hi-doctor": DoctorOutline,
  "hi-nurse": HiNurseOutline,

  // Documents / Admin
  "hi-medical-records": MedicalRecordsOutline,
  "hi-prescription": PrescriptionDocumentOutline,
  "hi-medicine-bottle": MedicineBottleOutline,
};

// ── Combined component ──────────────────────────────────

interface SectionIconProps {
  icon: string | null;
  size?: number;
}

export function SectionIcon({ icon, size = 14 }: SectionIconProps) {
  if (!icon) return <IconSection size={size} />;

  // Check health icons first (hi- prefix)
  if (icon.startsWith("hi-")) {
    const HiIcon = HEALTH_ICON_MAP[icon];
    if (HiIcon) return <HiIcon width={size} height={size} />;
    return <IconSection size={size} />;
  }

  // Tabler icons
  const TablerIcon = TABLER_ICON_MAP[icon];
  if (TablerIcon) return <TablerIcon size={size} />;
  return <IconSection size={size} />;
}

export function hasSectionIcon(icon: string | null): boolean {
  if (!icon) return false;
  if (icon.startsWith("hi-")) return icon in HEALTH_ICON_MAP;
  return icon in TABLER_ICON_MAP;
}
